### ISSUE TITLE
Have textual file opening drop-down's root directory be set to the current working file's directory path

### ISSUE THREAD

**Issue by PurpleAzurite** [ahrm/sioyek#100]
When using ctrl-o to navigate to documents it would be very useful to have the list remember the last opened file's path, since re-navigating to the same directory containing multiple files of interest is a hassle in deep directory structures. The system should still be rooted to home directory when using "~/".

**Comment by ahrm** [comment]
Added a new `open_document_embedded_from_current_path` command (which uses `<C-S-o>` keybinding) in 32ee4860e996dfcb4812b513959011d1fc7b13d6.
