### ISSUE TITLE
is there a way to disable mouse scrolling?

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#1008]
As the tittle says, I want to disable mouse scrolling especially in the presentation mode. Sometimes I accidentally/subconsciously  scroll during presentations. So I am in a quest for a proper config or a way to bind mouse scrolling to noop.

**Comment by nikinbaidar** [comment]
anyway to toggle this based on weather I'm presenting or not?

**Comment by ahrm** [comment]
I think something like this should work:
```
toggle_presentation_mode;toggleconfig_ignore_scroll_events <keybind>
```

**Comment by ai4bing** [comment]
`toggleconfig_ignore_scroll_events` in one window will affect the mouse scroll in another window, how can I fix this?

**Comment by ahrm** [comment]
Configs are global, there is no way to set configs per-window.
