### ISSUE TITLE
Warning: invalid command for goto_top_of_page and goto_bottom_of_page

### ISSUE THREAD

**Issue by lorenzohess** [ahrm/sioyek#1009]
After adding `goto_top_of_page H` and `goto_bottom_of_page L` to my `keys.config`, I get the following warnings when pressing those keys:
```
Warning: invalid command (key:H); resetting to root
Warning: invalid command (key:L); resetting to root
```
[keys.config.txt](https://github.com/ahrm/sioyek/files/14661223/keys.config.txt)

**Comment by ahrm** [comment]
Which sioyek version are you using?

**Comment by lorenzohess** [comment]
Version `2.0.0`, thanks.

**Comment by ahrm** [comment]
I am not entirely sure, and I can't check it now, but I think in the old version of sioyek you had to do something like this:
```
goto_bottom_of_page <S-l>
```
or maybe
```
goto_bottom_of_page <S-L>
```

**Comment by lorenzohess** [comment]
Neither `<S-l>` nor `<S-L>` work. I tried building from source (Debian 11) and those keybinds still don't work. I just realized that the `move_left h` keybinding doesn't move left. Instead, this message appears in the echo area: `add_highlight waiting for symbol [ h:a ]`. And the `move_right l` keybind doesn't appear to do anything. Neither the `h` nor `l` keybindings give a warning on the cli.

**Comment by ahrm** [comment]
You are not supposed to edit `keys.config` you should edit `keys_user.config` file. Your configs are being overwritten by sioyek's default keybindings. Your `keys_user.config` file should be something like this:
```
goto_bottom_of_page L
goto_top_of_page H
move_left h
move_right l
```

**Comment by lorenzohess** [comment]
Got it. That works. Thanks.
