### ISSUE TITLE
Sioyek crashes when searching for terms in file.

### ISSUE THREAD

**Issue by jinjiaodawang** [ahrm/sioyek#1010]
Sioyek crashes when searching for terms in file.
OS: macOS 14.4
Version of sioyek: [development branch](https://github.com/ahrm/sioyek/commit/89971cdd9d4f400f37e57468323d5b79807ebc32)
Steps to reproduce:
1. download https://arxiv.org/pdf/1704.00445.
2. Open the file with Sioyek, search for 'theorem 2'
3. If it does not crash, press n for next match.

**Comment by jinjiaodawang** [comment]
There is no popup window showing error msg, but if I run Sioyek from terminal it shows:
```
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: 0:2: extension 'GL_OES_standard_derivatives' is not supported

[1]    24836 segmentation fault  ./sioyek
```

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/93aef98ef7ffe6ada6283b973c622db9610b6677.

**Comment by jinjiaodawang** [comment]
Works perfectly. Thank you.
