### ISSUE TITLE
Compilation issue on non-macos devices

### ISSUE THREAD

**Issue by hrdl-github** [ahrm/sioyek#1017]
https://github.com/ahrm/sioyek/commit/651e57aaeae9b60f16b255cb6fa260ef11bd124c introduces what I believe are two typos:

https://github.com/ahrm/sioyek/commit/651e57aaeae9b60f16b255cb6fa260ef11bd124c#diff-8b278701fc8d5f6a9c26385012a8443b0cb89f2ea2e24f3aff6571db574ffc68R3582 and https://github.com/ahrm/sioyek/commit/651e57aaeae9b60f16b255cb6fa260ef11bd124c#diff-8b278701fc8d5f6a9c26385012a8443b0cb89f2ea2e24f3aff6571db574ffc68R3592 , which I believe should be `#ifndef` instead of `#ifdef`.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/b48e66ce2b292949e9531c4b7ee8ff47bb1cebe5.
