### ISSUE TITLE
Navigating the TOC

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#1025]
I notice that in the TOC menu I can only move up and down with the arrow keys. I tried tracing the functions bound to these in the keys.conf but it wasn't there. I want to bind <C-j> and <C-k> to move up/down in this TOC/bookmarks lists. How can I map a key in this context?

**Comment by ahrm** [comment]
Using something like this:
```
[m]control_menu(down) <C-j>
```

**Comment by nikinbaidar** [comment]
> Using something like this:
> 
> ```
> [m]control_menu(down) <C-j>
> ```

Exactly what I want. Are there any more docs on these?

**Comment by ahrm** [comment]
See this comment: https://github.com/ahrm/sioyek/issues/921#issuecomment-1913541205.

**Comment by nikinbaidar** [comment]
Thank you!
