### ISSUE TITLE
embed annotations to current file

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#1026]
I'm trying to change the EmbedAnnoationsCommand in the dev branch to use the file that is open right now.

Previously I could just use
` std::wstring embedded_pdf_file_name = widget->doc()->get_path();`
As the path, now after a few months it seems there have been a lot of changes in the code base. 

I see 

```
    virtual void set_file_requirement(std::wstring value) {
        file_path = value;
    }

    std::optional<Requirement> next_requirement(MainWidget* widget) {
        if (!file_path.has_value()) {
            Requirement req = { RequirementType::File, "File Path" };
            return req;
        }
        return {};
    }

```

(I think) I want to remove the `next_requirement` and just pass the curren't files path to `file_path`. How may I achieve this?

**Comment by ahrm** [comment]
You can return `{}` for the next requirement and just use the file path in `perform`. However, overwriting the current opened file in sioyek is really not really supported and even if it is working, it is accidental.

**Comment by nikinbaidar** [comment]
> You can return `{}` for the next requirement and just use the file path in `perform`. However, overwriting the current opened file in sioyek is really not really supported and even if it is working, it is accidental.

Actually I found this 
https://github.com/ahrm/sioyek/issues/973#issuecomment-1939283882

This does what I want to do. But I'm having issues with binding it to `sioyek_async` instead of just `sioyek`.
Did you remove support for `sioyek_async`?

**Comment by ahrm** [comment]
There is no need to specify `_async` anymore, we now automatically use the correct async api when the command is defined to be an async command.

**Comment by nikinbaidar** [comment]
> we now automatically use the correct async api when the command is defined to be an async command.

Are you saying we can use native JS delay functions?I tried asyncio's await but that does seemt to work. I also tires setTimeout.

So I have this. 

```
sioyek._extract_highlights();
sioyek.embed_annotations(path);

sioyek.clear_all_current_document_highlights();
```
The `_extract_highlights` part does not seem to run if I have `clear_all_current_document_highlights`. I suspect the highlights are being deleted faster than they can be extracted so I want a delay between them.

**Comment by ahrm** [comment]
No our javascript engine doesn't support `async`, `await`. The async used in defining the commands refers to how sioyek executes the command not the javascript `async-await`. We do have a `wait` command in sioyek, however, I don't think that is your issue, the problem is that we don't support custom commands in js engine.

**Comment by nikinbaidar** [comment]
> We do have a `wait` command in sioyek, 

Actually, in one of my forks of the repo I was achieve this with a 1 sec delay. However, even with `sioyek.wait(1000)` I can't seem to get this to work. 

> I don't think that is your issue, the problem is that we don't support custom commands in js engine.

But if I remove `clear_all_document_highlights` part for my js file, the `_extract_highlights` is working properly.
