### ISSUE TITLE
Cannot scroll when a preview is open

### ISSUE THREAD

**Issue by cnut1648** [ahrm/sioyek#1028]
Hi, this is the best pdf viewer I've ever used! Thank you for the effort!

I have a question regarding preview. When I open the preview on an equation/citation via right click, the preview will open and if I move the cursor to the preview window I can scroll the preview freely.
But I cannot scroll the main pdf, which stays fixed until I close the preview. In older version it was possible to scroll both. I wonder if there should be a flag in `prefs.config` that controls this behavior.

I am using the latest `v2.0.0`, and I do not have any user prefs.config set.

Thanks!

**Comment by ahrm** [comment]
Yes, this is intentional. We now use mouse scroll when outside the preview window to move to the next possible preview (when available) which of-course does nothing when only one preview is available. Why would you even want to scroll the original document while the preview is opened?

**Comment by cnut1648** [comment]
Hi @ahrm thanks for info. What do you mean by the next possible preview? When I scroll outside of the preview/overview window it does nothing, even if there exist multiple references.
A use case for scrolling the original doc is that, when I am looking at some math doc,
as an example, these are very long equations
![image](https://github.com/ahrm/sioyek/assets/37067883/36ceeec0-7866-4466-a19d-1745a18a8388)
one of the equations near the end needs Equation 37 but if I open the overview for Equation 37 the original doc stays fixed and my screen is not large enough to hold all these long equations. 
![image](https://github.com/ahrm/sioyek/assets/37067883/36f08fe4-f636-4548-a71d-bf80abb0de2f)
If I can open the overview and then freely scroll to scan the entire equations that would be helpful!

**Comment by ahrm** [comment]
> What do you mean by the next possible preview?

Sometimes there are more than one possible match for a reference, in such situations you can use the scroll wheel outside the overview window to switch between possible references.

I added a `allow_main_view_scroll_while_in_overview` config option in https://github.com/ahrm/sioyek/commit/3ec06fc2015e3838877de995f54854b678ad8f45 to restore the old behaviour.

**Comment by cnut1648** [comment]
Hi @ahrm , thanks for the commit! I tried building from the source and setting the following in `prefs_user.config`:
```
allow_main_view_scroll_while_in_overview 1
```
It does allow scrolling but I notice that whenever I scroll it only goes up. I wonder what could be the issues?

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/bdd14c384e4a04edb5ac0e9e15b7b439a21e9f35.

**Comment by cnut1648** [comment]
Great @ahrm thanks a lot! This completely solves the issue!

**Comment by duguyipiao** [comment]
I encountered the `Error: allow_main_view_scroll_while_in_overview is not a valid configuration name` with the latest development branch. I didn't notice from when, maybe because of de9659d6e915c12a6fa13fcfea46fe3a651c2281?

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/ee81df77ec15014e572f9dbc1601792adba9e47b.

**Comment by duguyipiao** [comment]
Thanks for the quick fix, but the Error is still there.

**Comment by duguyipiao** [comment]
Maybe due to the extra space in ` L"allow_main_view_scroll_while_in_overview "`?

**Comment by ahrm** [comment]
Yeah, sorry about that, I only tested it with the command menu and it works there. It should be fixed now.
