### ISSUE TITLE
[development] meta files cluttering the current directory

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#1030]
The freehand drawings and scratchpads amongst things are saved in a separate file in the directory of the pdf file. This seems to clutter the directory, so is there any way to provide a specific path where sioyek can look for these meta files so that they do not get created everywhere.

**Comment by ahrm** [comment]
Added an `annotations_directory` config option in https://github.com/ahrm/sioyek/commit/575e8529810058f4a483d5f4b55ea996c9a0e6cf.

**Comment by nikinbaidar** [comment]
> Added an `annotations_directory` config option in https://github.com/ahrm/sioyek/commit/575e8529810058f4a483d5f4b55ea996c9a0e6cf.

Man this just makes the dev branch so much more usable. Can't wait for the actual release.
