### ISSUE TITLE
Build with CMake

### ISSUE THREAD

**Issue by lgbaldoni** [ahrm/sioyek#104]
Any plans to switch from qmake to cmake? I packaged sioyek for openSUSE (haven't submitted it yet) and handling dependencies is a bit more complicated with qmake, especially if one wants to link to system libraries.

meson would also be an option.

What do you think?

**Comment by Endle** [comment]
Hi

Please let me ask a silly question: How does CMake help link system dependencies? I think using Qmake and CMake should be very similar.

Besides, would you like to share your `sioyek.spec`?

**Comment by lgbaldoni** [comment]
> Please let me ask a silly question: How does CMake help link system dependencies? I think using Qmake and CMake should be very similar.

It's also doable on qmake, but detection is less automated in the former and passing flags, includedirs and libs is all manual.

> Besides, would you like to share your `sioyek.spec`?

My sioyek.spek is quite plain (`qmake`, `make`, `make install`), but I had to add [this](https://github.com/ahrm/sioyek/files/7527386/sioyek-use_system_libraries.patch.gz). Or perhaps you need specific commits of mupdf and/or zlib?

**Comment by Endle** [comment]
> Or perhaps you need specific commits of mupdf and/or zlib?

I think it's packager's job to set `LIBS`

Here is my spec: <https://copr-dist-git.fedorainfracloud.org/cgit/endle/sioyek/sioyek.git/tree/sioyek.spec?id=7e27433f72ea74513a87dd38cede5ad1d989152f>

I also need to do a modification in the `pdf_viewer_build_config.pro`, but I think it should be easy if we figure out which dependencies are really needed (well, I had spent hours to figure it out in Fedora)

`sed -i 's/-lmupdf-third -lmupdf-threads -lharfbuzz/-lmupdf-third -lharfbuzz -lfreetype -lgumbo -ljbig2dec -lopenjp2 -ljpeg/' pdf_viewer_build_config.pro`

Finally, is this part of openSUSE guideline that, when packing an app, we should remove the dependencies included in the package, and use system library if possible? I noticed that you removed sqlite3. I guess there is a similar guideline in Fedora, but I don't have time to push sioyek from COPR to official recently.

**Comment by lgbaldoni** [comment]
> I think it's packager's job to set `LIBS`

I disagree. Chasing unresolved symbols is not the way most people have funny afternoons :smile:, so that's probably better handled upstream.

> I also need to do a modification in the `pdf_viewer_build_config.pro`, but I think it should be easy if we figure out which dependencies are really needed (well, I had spent hours to figure it out in Fedora)
> 
> `sed -i 's/-lmupdf-third -lmupdf-threads -lharfbuzz/-lmupdf-third -lharfbuzz -lfreetype -lgumbo -ljbig2dec -lopenjp2 -ljpeg/' pdf_viewer_build_config.pro`

That regex is going to potentially fail silently at each update if the LIBS line changes even by a space.

> Finally, is this part of openSUSE guideline that, when packing an app, we should remove the dependencies included in the package, and use system library if possible?

Yes, [it is](https://en.opensuse.org/openSUSE:Packaging_guidelines#Duplication_of_system_libraries).

P.S: If you don't feel doing it I can try and create something, but Windows and OSX testing might be delayed.

**Comment by Endle** [comment]
> > Finally, is this part of openSUSE guideline that, when packing an app, we should remove the dependencies included in the package, and use system library if possible?
> 
> Yes, [it is](https://en.opensuse.org/openSUSE:Packaging_guidelines#Duplication_of_system_libraries).
> 

Thank you for sharing it!

> P.S: If you don't feel doing it I can try and create something, but Windows and OSX testing might be delayed.

I'm not sure if the author @ahrm would like this idea. For me, I'm not sure if building with CMake can reduce my work - I'm not experienced with the building system, and I'm afraid if CMake would introduce more complexity.

Please let me invite one more person in this discussion @randomn4me : How do you think about it, as an Arch packager?

**Comment by ahrm** [comment]
I think with `sioyek` mainly being a Qt application, using `qmake` makes more sense. Also featurewise, CMake and qmake are pretty much equivalent so anything possible with one should also be possible with the other. For these reasons I think I will stick with `qmake` (unless there is a really, really good reason to switch).

However, if you mention the specific problems that you have with the current build system, maybe I could fix it within the current `qmake` framework? Or maybe I could add I could add a flag to do things differently when building for packages?

**Comment by lgbaldoni** [comment]
> I think with `sioyek` mainly being a Qt application, using `qmake` makes more sense. Also featurewise, CMake and qmake are pretty much equivalent so anything possible with one should also be possible with the other. For these reasons I think I will stick with `qmake` (unless there is a really, really good reason to switch).

From what I [understand](https://www.qt.io/blog/qt-6-build-system) CMake is the default on Qt6, but of course qmake will be available for a long time.

> However, if you mention the specific problems that you have with the current build system, maybe I could fix it within the current `qmake` framework? Or maybe I could add I could add a flag to do things differently when building for packages?

If possible, it would be useful to have flags like `USE_SYSTEM_MUPDF` for `mupdf`, `utf8cpp`, `zlib` and `sqlite3`.

**Comment by ahrm** [comment]
> If possible, it would be useful to have flags like `USE_SYSTEM_MUPDF` for `mupdf`, `utf8cpp`, `zlib` and `sqlite3`.

`utf8cpp` is a header-only library. How (and why) would I use the system version of that? Also I think we already use the system's `zlib`.
I will try to add options for `mupdf` and `sqlite3` though.

**Comment by ahrm** [comment]
I made a prototype build config file. Does this work for you? (I had to rename it to txt so that I could upload it here)
[pdf_viewer_build_config.txt](https://github.com/ahrm/sioyek/files/7531867/pdf_viewer_build_config.txt)
