### ISSUE TITLE
[Bug] `sioyek --new-window` doesn't follow `prefs_user.config`

### ISSUE THREAD

**Issue by Aman9das** [ahrm/sioyek#1043]
How to reproduce:

enable dark mode by `default_dark_mode 1` in `prefs_user.config`

- open a pdf file. it's going to open in dark mode.
- open another in another windpw. It doesn't open in dark mode.

System: Fedora, flatpak & appimage tested.

**Comment by ahrm** [comment]
This is already fixed in the development branch.

**Comment by Aman9das** [comment]
I apologise for reviving this issue, but i built the latest commit from development version here https://github.com/Aman9das/com.github.ahrm.sioyek/actions/runs/8637196312

And it has the same issue.. It could be very well an issue in the build script at our end.. but still kindly check if there's been a regression
