### ISSUE TITLE
Ubuntu 22.04.4 on a Thinkpad X200s the viewer only shows an empty page

### ISSUE THREAD

**Issue by ouboub** [ahrm/sioyek#1044]
Hi
While I can run sioney on my MacBook running Big Sur, I 

1. installed [Ubuntu 22.04.4](https://releases.ubuntu.com/jammy) on my old Thinkpad X200s together with fuse2 
2. I downloaded either sioyek-release-linux-portable.zip or
3. sioyek-release-linux.zip

however, when I tried to run either of these, I just obtained an empty screen I opened another pdf file
but again the sioyek screen was empty (I attach a screenshot)
What do I miss here
regards

Uwe Brauer

![Sioney](https://github.com/ahrm/sioyek/assets/5957203/03116531-9afa-4145-986f-dc796a3f26c2)

**Comment by ahrm** [comment]
Probably it is an opengl issue? Install opengl drivers or use mesa software opengl.

**Comment by ouboub** [comment]
I installed:
```
sudo apt-get install mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev
sudo apt-get install libglew-dev libglfw3-dev libglm-dev
sudo apt-get install libao-dev libmpg123-dev
```
restarted the X server but it did not help.

**Comment by ahrm** [comment]
Maybe this helps: https://github.com/ahrm/sioyek/issues/266#issuecomment-1530824292 ?

**Comment by ahrm** [comment]
1. No need for a new issue, this issue is basically that
2. You should be using the command in comment 266 regardless of your mesa version (the version in the comment is referring to the version of the emulated OpenGL not the mesa version).

**Comment by ouboub** [comment]
> 1. No need for a new issue, this issue is basically that
> 2. You should be using the command in comment 266 regardless of your mesa version (the version in the comment is referring to the version of the emulated OpenGL not the mesa version).

ok, then I have to report that even then, with the command in comment 266  sioney (either compiled or the precompiled version) just displays an empty page, independent of the pdf file

**Comment by ouboub** [comment]
> 1. No need for a new issue, this issue is basically that
> 2. You should be using the command in comment 266 regardless of your mesa version (the version in the comment is referring to the version of the emulated OpenGL not the mesa version).

since all this did not work, do you know how I could contact [@viccie30](https://github.com/viccie30)
who maintains the Ubuntu packages for distributions 23.04 and 23.10.
Maybe he knows what my problem is

**Comment by ahrm** [comment]
Sorry, I am not in direct contact with him, I assume he will be pinged since you tagged him.

**Comment by viccie30** [comment]
I read the issue, but I have not built more recent versions than the release that's currently in Ubuntu. I'll have some time in a few weeks, then I can look into it.

**Comment by ouboub** [comment]
> I read the issue, but I have not built more recent versions than the release that's currently in Ubuntu. I'll have some time in a few weeks, then I can look into it.

thanks!
since I prefer to use LTS versions, I did not try out 23.
the strange thing is either the compiled version or the pre-compiled show only an empty screen
that is why I thought I forgot to install  package needed for the display.
I will try a bit more and then switch to Ubuntu 23

**Comment by ouboub** [comment]
> Maybe this helps: [#266 (comment)](https://github.com/ahrm/sioyek/issues/266#issuecomment-1530824292) ?

I also installed libguumbo1 and libgumbo-dev
then indeed 
```
 MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 ./sioyek
```
for the version I compiled or 
```
 MESA_GL_VERSION_OVERRIDE=3.3 MESA_GLSL_VERSION_OVERRIDE=330 ./Sioyek-x86_64.AppImage
```
works!
Great, Issue solved, maybe that should be added to the manual or the install instructions?

**Comment by viccie30** [comment]
Instead of showing a blank screen, would it be possible for sioyek to check the available OpenGL version and show an error message? That way users know why the screen is blank.
