### ISSUE TITLE
ETA for the next release

### ISSUE THREAD

**Issue by nickel8448** [ahrm/sioyek#1045]
Hello,

Thank you so much for all your great work. I have noticed that a lot of features are being added to Sioyek for the next release, I was wondering if there is an ETA of when the next release will be available.

Thank you

**Comment by nickel8448** [comment]
I didn't know where else I could have asked a question about it. Hence added it as an issue here.

**Comment by ahrm** [comment]
Unfortunately I don't have an ETA in mind, hopefully sooner rather than later though :)
