### ISSUE TITLE
Does Not Work in Macbook Pro M1 

### ISSUE THREAD

**Issue by mbennette68** [ahrm/sioyek#105]
Hi,

After dragging the app from the build folder into the applications folder and running it, it runs one time bringing up 
the help file in default theme. If I quit the app, it will open one more time but nothing is displayed and just hangs there displaying a black background. I have to force quit to exit the app since it does not respond otherwise.

This has occurred with all versions of the software since the initial release until the v1.0.0 version.

Thank you

**Comment by Endle** [comment]
I hit the same problem today, on a Macbook Pro M1

It's a bit interesting to me: If I open sioyek from the zip file directly, it looks good.

However, after dragging it to Application, then double-click to launch, sioyek will remain black, then I have to force-quit (kill) sioyek

**Comment by ahrm** [comment]
Is this issue fixed? (I can't check it myself)

**Comment by undefdev** [comment]
> Is this issue fixed? (I can't check it myself)

I haven't encountered this problem after a week of use. I suspect it is fixed, or at least not generally occuring on M1 macbooks.

**Comment by ahrm** [comment]
Great, I will close the issue for now, feel free to reopen if the issue persists.
