### ISSUE TITLE
clicking toc contents always makes the doc move rightwards

### ISSUE THREAD

**Issue by PalaceTony** [ahrm/sioyek#1051]
This doesn't happen if i set the page to fit to the width. If otherwise, for example, I set it to the predefined fit_to_page_width_ratio, then click toc items to navigate there, the ratio changes. I'm using mac m1. Thansk for your great work:)

Before:
![Snipaste_2024-04-12_00-27-08](https://github.com/ahrm/sioyek/assets/150102585/1712b8cd-0dea-471b-be27-ccdb8ce73806)

After:
![Snipaste_2024-04-12_00-27-08](https://github.com/ahrm/sioyek/assets/150102585/fe979023-d2db-4f30-a1b5-b48b0369db4f)

**Comment by PalaceTony** [comment]
Sorry the after pic should be as below

![Snipaste_2024-04-12_00-26-59](https://github.com/ahrm/sioyek/assets/150102585/4f64791c-f438-4188-a8fa-d2283387f9f2)

**Comment by ahrm** [comment]
I think this is already fixed in the development branch.

**Comment by PalaceTony** [comment]
Great thanks! I've tried the dev and it's fantastic!
