### ISSUE TITLE
[Command Request/Help] `move_visual_mark_up_smooth` and `move_visual_mark_down_smooth`

### ISSUE THREAD

**Issue by Aman9das** [ahrm/sioyek#1055]
`move_visual_mark_up_smooth`:
- same as `move_up_smooth` generally
- same as `move_visual_mark_up` in visual mark mode [smooth doesn't make sense in visual mark mode]

Similar for `move_visual_mark_down_smooth`

Alternative:
- ability to set mode-specific keymaps

**Comment by ahrm** [comment]
Changed `move_*_smooth` commands to move the visual mark when we are in visual mark mode in https://github.com/ahrm/sioyek/commit/88fd49550af384568d185ee8f1686cc0b54d4fa2.

**Comment by Aman9das** [comment]
Works like a charm! Thanks a LOT!

**Comment by Aman9das** [comment]
This seriously could be the default keymap.. improves the experience by a lot imo
