### ISSUE TITLE
Forward Search with multiple files

### ISSUE THREAD

**Issue by 00sapo** [ahrm/sioyek#106]
When a document has multiple files, the forward search option only works on the main file. In other words, using configurations suggested in the documentation, if you are editing a file that is included in the compiled file and starts the forward search, it doesn't work. If instead it is started from the main file, it works.

**Comment by ahrm** [comment]
Which text editor are you using?
Also could you explain this:
> file that is included in the compiled file and starts the forward search, it doesn't work

more clearly?

**Comment by 00sapo** [comment]
I have prepared a little example. It turned out that if the included files are in the same directory as the main file, it works: [sioyek_test.zip](https://github.com/ahrm/sioyek/files/7562498/sioyek_test.zip).

Just download the zip, uncompress, and try forward search from `src/included.tex`.

I'm using neovim with the following configuration (it works with okular):

```vim

        let g:vimtex_view_general_viewer = '/opt/sioyek-release-linux-portable-gcc8/Sioyek-x86_64.AppImage'
        let g:vimtex_view_general_options = '@pdf --reuse-instance --forward-search-file @tex --forward-search-line @line --inverse-search "nvr --remote-silent +\":call cursor(%2, 0)\" %1"'
        let g:vimtex_view_general_options_latexmk = '--reuse-instance'
```

**Comment by ahrm** [comment]
First of all I had to replace these lines:
```
\include{src/included.tex}
\include{included_same_dir.tex}
```

with these:

```
\include{src/included}
\include{included_same_dir}
```

Otherwise the other file contents would not show up in the document. But after fixing that, forward search worked on my setup (though I use VSCode latex plugin rather than vimtex).

Also note that the VimTex configuration was recently changed in 1a5033159994c4322a4273da6564804b89fe9791. (see https://github.com/ahrm/sioyek/issues/8#issuecomment-968084341). Maybe updating the configuration helps?

**Comment by 00sapo** [comment]
I've just tried vscode and it works with the default settings. If you compile in a subdir (e.g. `%DIR%/build`) the same thing happens. When I try to use the vscode forward search on the pdf obtained from vimtex, it still doesn't work.

I think it's all about the compilation command and how aux files are referenced, but I don't really know a lot about latex compilation :(
