### ISSUE TITLE
Weird dragging on text selection after switching to QMainWindow

### ISSUE THREAD

**Issue by iamkroot** [ahrm/sioyek#1075]
After https://github.com/ahrm/sioyek/commit/f7727a8e4e6af18ae631d5a2bfa4db1f1b4d3b39, I'm seeing extremely annoying behavior when selecting text. Essentially, if we drag on the empty portions of the page, instead of snapping the selection to text, it starts dragging the window.

See gif for before/after.

![output](https://github.com/ahrm/sioyek/assets/29517049/46b2cddb-416f-43d5-a483-b11d8e849ba1) ([higher quality video link](
https://github.com/ahrm/sioyek/assets/29517049/0d8971dd-e4bd-45c3-b62a-b9d7af9b59d8))

In the beginning, sioyek is on an old version. I switch to the build from bad commit at around 8 seconds.

Maybe there's a way to opt out of this dragging behavior at the Qt level?

**Comment by ahrm** [comment]
I think this maybe an interaction of QMainWindow with your window manager because I can't reproduce it on my machines. What window manager are you using here?

**Comment by iamkroot** [comment]
Hmm I'm using KWin on X11 (will report on Wayland in a bit).

Other than that, I'm also running Kvantum. That has a setting called "Drag from:" with the options "Titlebar", "Menubar", "Menubar and primary toolbar", and "Anywhere". I've set it to "Menubar and primary toolbar".

Will check if it is something to do with Kvantum.

**Comment by iamkroot** [comment]
Seems to have been fixed after the Plasma 6.2 update. I'm going to chalk this up to a Qt issue.
