### ISSUE TITLE
Fail rendering text 

### ISSUE THREAD

**Issue by enfmarinho** [ahrm/sioyek#1084]
I'm having a very weird problem, for some reasons sometimes the "A" letter is not being rendered as you can see in the photo, only uppercase and bold "A". I Have open the same file in other pdf viewers and things are alright. That does not happen only on this file but in all papers that i try to read, does someone has some suggestion? 
<img width="1440" alt="Screenshot 2024-05-12 at 23 52 31" src="https://github.com/ahrm/sioyek/assets/120424205/ec539751-60fa-4675-8b02-5bbffee80db5">
The messages that the sioyek prints on entry is: (excluding the unhelpful first messages that only prints the paths)
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

warning: freetype could not find any cmaps
2024-05-12 23:55:03.578 sioyek[16482:7079333] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
warning: freetype could not find any cmaps
warning: freetype could not find any cmaps
warning: freetype could not find any cmaps
warning: ... repeated 6 times...

**Comment by ahrm** [comment]
That is, indeed, weird. I can't reproduce the issue on my machines with the same paper (assuming it was downloaded from arxiv).  Either way, we don't do anything character-specific in sioyek, we just use mupdf to render the page, so if there is a bug, I think it is a mupdf bug.

**Comment by enfmarinho** [comment]
Thank you for your time, gonna give a look on mupdf and see if i can figure it out.

**Comment by enfmarinho** [comment]
Closed it since i think it's not a problem with sioyek itself.
