### ISSUE TITLE
[Feature Request] A draggable popup to preview link destination.

### ISSUE THREAD

**Issue by Creling** [ahrm/sioyek#109]
Hi,

This is a fantastic work and helps me a lot. Thank you!

I wonder, if it is possible to make current overview windows trigged by right click draggable? Now, it appears in the center of the document and covers the context of link.

It will be great to make the overview window works like a popup so we could resize it or move it to the margin.

Creling

**Comment by ahrm** [comment]
Added in a620853bd03ce4d1707cd44948f3b15e4ec9100f.

https://user-images.githubusercontent.com/6392321/143779777-52e1cf0d-3237-476f-b8f6-0bc1b6b0d0e5.mp4

**Comment by Creling** [comment]
it's amazing!
