### ISSUE TITLE
segfault with `overview_link` but not with right click or `keyboard_overview`

### ISSUE THREAD

**Issue by OmegaLambda1998** [ahrm/sioyek#1093]
Using the arch aur `sioyek-git` package on a wayland-native system.

Before running, I renamed my user config files to ensure there wasn't something weird in there causing the issue. I testing this on a few different papers with exactly the same result. If I right-click, or use `keyboard_overview` to overview a citation, everything works as expected, however if I use `overview_link`, sioyek will segfault after selecting the citation.

Output of `sioyek --verbose`:

```
default_config_path: /etc/sioyek/prefs.config
default_keys_path: /etc/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/_/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/_/.config/sioyek/keys_user.config
database_file_path: /home/_/.local/share/sioyek/test.db
local_database_file_path: /home/_/.local/share/sioyek/local.db
global_database_file_path: /home/_/.local/share/sioyek/shared.db
tutorial_path: /usr/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/_/.local/share/sioyek/last_document_path.txt
shader_path: /usr/share/sioyek/shaders
warning: found duplicate fz_icc_link in the store
# I can start interacting with sioyek here
# First I right click the citation, see the overview, then press <esc> to close the overview
Warning: invalid command (key: resetting to root
# Next I run `keyboard_overview`, select the citation, see the overview, then press <esc> to close the overview
Warning: invalid command (key: resetting to root
# Finally I run `overview_link`, select the citation, sioyek freezes, then segfaults
zsh: segmentation fault (core dumped)  sioyek --verbose
```

Happy to provide whatever information is needed to help debug this.

As an aside, any idea what the `warning: found duplicate fz_icc_link in the store` and `Warning: invalid command (key: resetting to root` warnings mean, and whether they could be contributing?

**Comment by OmegaLambda1998** [comment]
As a quick note, it seems that the `sioyek` (not `sioyek-git`) package doesn't even have `overview_link` as a command, so I wasn't able to test whether this is unique to the git package or not

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/372669f61c13f87e00fcbf72082e8c7497a60e30.

**Comment by OmegaLambda1998** [comment]
Confirmed it seems to be working now
