### ISSUE TITLE
Memory leak when highlighting text

### ISSUE THREAD

**Issue by btrkeks** [ahrm/sioyek#1094]
I think this video demonstrates it quite well:

https://github.com/ahrm/sioyek/assets/50422430/73cb17e0-7f87-4a7b-8868-cec6892766e4

I have to regularly restart sioyek because of this.

I use the AUR package of sioyek. I haven't tried the Appimage, but I would assume it's similar there.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/a3aeca4864976a0d09572c58f61da0b2b9896481.

**Comment by btrkeks** [comment]
Seems to work. Thanks!
