### ISSUE TITLE
Command menu ':' not working "invalid command (key::); resetting to root"

### ISSUE THREAD

**Issue by fofusa** [ahrm/sioyek#110]
Hello,
Siojek does not seem to work properly on pop_os 20.04.
In particular many key bindings are failing, most annoyingly the command menu (":") that cannot be opened.
Whenever typing ':', nothing happens, but this is shown in the terminal where Siojek was launched from:

`invalid command (key::); resetting to root`

**Comment by ahrm** [comment]
How did you install sioyek? (from source or prebuilt binaries or a package manager?)

**Comment by mpauper** [comment]
Hello,

I am having the same issue, on Pop_os 21.04, basically ubuntu. Built from source, initially with some error, but after installing some extra packages that I found in another issue here, it worked.

Now opening sioyek only gives an empty page, window title is `<path>/tutorial.pdf` but unable to interact with anything. Terminal reveals that anything I press is `Invalid command; resetting to root`.

**Comment by ahrm** [comment]
Which sioyek executable are you running? (you should be running the one in the build folder)

**Comment by mpauper** [comment]
Oh boy, that's embarrassing! I was using the one in the main folder. It works with the one in the build folder. Thanks!

**Comment by ahrm** [comment]
> Oh boy, that's embarrassing! I was using the one in the main folder. It works with the one in the build folder. Thanks!

You're welcome. I assume the original problem was this too so I close the issue. Please reopen if it is a different issue.
