### ISSUE TITLE
Background Colour (NOT PDF page color) defaults to [0 0 0] when toggle_custom_color is on. 

### ISSUE THREAD

**Issue by lucascarrr** [ahrm/sioyek#1100]
You're able to change this property for Dark Mode, or Light Mode. But neither of these settings apply to when custom_color is enabled. 
This is on the development branch, it works as expected on the main branch.

**Comment by ahrm** [comment]
We have a `custom_color_mode_empty_background_color` config for that now.

**Comment by lucascarrr** [comment]
Ah thanks, couldn't find it in the docs.
