### ISSUE TITLE
C-n and C-p not working in menus

### ISSUE THREAD

**Issue by jingchengx** [ahrm/sioyek#1104]
I moved from 2.0.0 to the main branch and noticed that `<C-n>` and `<C-p>` keybinds are no longer working as up/down for menu selection. 

 [Earlier discussion I posted](https://github.com/ahrm/sioyek/discussions/1103)

**Comment by ahrm** [comment]
This is already fixed in the development branch and therefore will be fixed when development branch is merged into the main branch.

**Comment by jingchengx** [comment]
Great! Thanks!
