### ISSUE TITLE
Build on arch - Xinput No such file or directory

### ISSUE THREAD

**Issue by enrico223** [ahrm/sioyek#1106]
I got all  the dependencies needed, but can't  compile. This is the error:
```
In file included from thirdparty/freeglut/src/fg_internal.h:192,
                 from thirdparty/freeglut/src/fg_callbacks.c:29:
thirdparty/freeglut/src/x11/fg_internal_x11.h:42:10: fatal error: X11/extensions/XInput.h: No such file or directory
   42 | #include <X11/extensions/XInput.h>
```
How do I fix it?

**Comment by ahrm** [comment]
You need to install the xinput library.

**Comment by enrico223** [comment]
I have the `xorg-xinput` package installed, isn't it the one needed?

**Comment by ahrm** [comment]
I don't know, it might be called `libxi` or something. The package names are different for each distribution.

**Comment by enrico223** [comment]
The package is, in fact, called `libxi`, but I had to reinstall it, same goes for `xrender`.
