### ISSUE TITLE
chained commands in keybinding not working?

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#1114]
I'm running a build of the development branch and noticed that chained commands for keybindings have stopped working. For example

```
goto_begining;goto_top_of_page gg
```

only executes the first command.

It used to work on the main branch.

**Comment by ahrm** [comment]
Chained command keybindings still work. The issue is that we removed the typo command `goto_begining`. Now `goto_beginning;goto_top_of_page gg` should work.

**Comment by gokberkgunes** [comment]
@ahrm Just like mil-ad, I am running the development branch. Unlike mil-ad, my `goto_beginning` command fails to run when I feed it with page number if it is chained to another command. The command just ignored the page number but calls the other commands properly

For example, with below setting if I try `10gg`, my sioyek build just jumps to 1st page. Before I was able to go to 10th page and turn on and off the presentation mode. 
```
goto_beginning;toggle_presentation_mode;toggle_presentation_mode  gg
```

I have also tried below. It doesn't work in my build.
```
goto_beginning;fit_to_page_smart  gg
```

By the way, I do the presentation mode toggle to make page to fit both width and height, please let me know if there is something does this. Intuitively I tried `fit_to_page`, but I doubt there is such a keybinding option.

**Comment by ahrm** [comment]
@gokberkgunes Added the ability to handle number commands in macro commands in https://github.com/ahrm/sioyek/commit/e617f531ef6a332b1bbab2b9c04e8f20b3ad1e87. Of course when there are multiple commands, it is ambiguous which command should receive the number, we simply pass it to the first command, so `goto_beginning` has to be the first command in the macro.

```
goto_beginning;fit_to_page_smart  gg
```

This works for me.
