### ISSUE TITLE
Feature Request: Smooth Scrolling for Keys

### ISSUE THREAD

**Issue by borankurut** [ahrm/sioyek#1124]
It would enhance the user experience if smooth scrolling could be implemented for the 'j' and 'k' keys. Currently, pressing 'j' to scroll down or 'k' to scroll up results in immediate movement, which can make it difficult to visually track the text. Implementing smooth scrolling for these keys would make the text movement more fluid and easier to follow.

**Comment by ahrm** [comment]
This is already implemented in the development branch (`move_down_smooth` and `move_up_smooth` commands).
