### ISSUE TITLE
[Feature Request] - Highlight with a comment, in a tree like table of contents

### ISSUE THREAD

**Issue by mostafatouny** [ahrm/sioyek#1130]
Hello,

Thank you for the supremely beautiful reader.

I saw the extension `add_text` and users request of "comment box" like Adobe. Those do not feel keyboard-centric though.

I suggest allowing to attach comments to a highlight through a command text. Similar to how subsections are displayed beneath sections in the "table of contents", Comments get displayed beneath its corresponding highlights in a tree.

When the cursor is on a highlight, A keyboard shortcut to show its comments in that tree would be useful.

I hope to it is not difficulut to code, especially that you already have "table of contents" implemented.

You Rock!

**Comment by mostafatouny** [comment]
A workaround given the current status is to a highlight text, e.g "Moments Generating Functions", Then add bookmarks:
- # Moments Generating Functions: My first comment
- # Moments Generating Functions: My second comment

**Comment by ahrm** [comment]
We already have support for highlight comments in the development branch.

**Comment by mostafatouny** [comment]
I have just checked the dev release and it works! Thanks for your efforts

P.S. Highlights in dev are not nicely looking as in release.

**Comment by ahrm** [comment]
We now have an `adjust_annotation_colors_for_dark_mode` config option (on by default), you may want to turn it off if you don't like the adjusted colors.

**Comment by mostafatouny** [comment]
Thank you for everything. I hope to contribute someday to this wonderful pdf reader.
