### ISSUE TITLE
[Feature Request] snap to whole page with next_page / previous_page

### ISSUE THREAD

**Issue by Uroc327** [ahrm/sioyek#1136]
Is there a possibility to have a variant of `next_page` and `previous_page` that snaps to whole pages? I guess this is only possible when the whole page fits (either width or height, depending on aspect ratios). If more than one page is shown, I would want the next/previous command snap the top of the next page to the top of the window.

Related: I would like to disable scrolling by half a page when issuing `next_page` or `previous_page` when I am already at the beginning or end of the document.

This is the behavior of the arrow keys of many other readers (chrome, evince, okular) when at least one whole page fits.

**Comment by ahrm** [comment]
You mean something like this (in prefs_user.config): ?
```
next_page;goto_top_of_page <keybinding>
```

**Comment by Uroc327** [comment]
Thank you very much :) Works nicely.

Is there any way to do this conditionally? I.e., have `next_page;goto_top_of_page` as a command when whole pages are visible and `move_visual_mark_down` when zoomed in for the same keybining?

**Comment by ahrm** [comment]
Not in the release build of the sioyek, but in the development branch we have some experimental javascript scripting support, it should be possible to do this using javascript.

**Comment by Uroc327** [comment]
I see, thanks. I'll wait for a stable version of that then :)
