### ISSUE TITLE
How robust/persistent is data in shared.db linked to PDF files?

### ISSUE THREAD

**Issue by johkneisl** [ahrm/sioyek#1138]
My understanding is that sioyek does not change the actual PDF. Instead, annotations, such as highlights, are stored in the shared.db file by default.

My question is, how are PDF files identified or associated to a set of highlights in shared.db? Or more practically: What can I do with an PDF file before highlights are lost? 

Renaming and moving the file seems to work.  Does it somehow store the hash of a file? In that case, I'd assume compressing it or adding permanent annotations with another tool might cause problems? 

thanks.

**Comment by johkneisl** [comment]
Oops, there's actually some information in the documentation

> local database file includes a single table named document_hash which maps file paths to their md5 hash. We later use this hash to reference files. This allows us to keep bookmarks/highlights even when the document is moved to another location or even another machine.

Still, as someone who's not too tech-savvy, the practical question remains: What can I do to a file before this association is lost?

**Comment by ahrm** [comment]
You can move or rename the file and the association is not lost.
If you modify the file contents, then the hash will change, however, if you don't move the file yet, the previous hash value is cached so we don't compute a new hash and the bookmarks are still visible. However, if you now move this modified file then the association is lost.
