### ISSUE TITLE
Displaying incorrectly on Mac OS with multiple Monitors

### ISSUE THREAD

**Issue by BenCzu** [ahrm/sioyek#1145]
Hi, 
This is by far my favourite pdf viewer.

However, I use multiple monitors with a Mac and after sleep, or after disconnecting and reconnecting my monitors, all the pdf's in open sioyek windows do not display correctly anymore.
Only fix is to quit and reopen sioyek.

![image](https://github.com/user-attachments/assets/4a19474a-5d34-4ea9-a012-0e0a9758d4b3)

![image](https://github.com/user-attachments/assets/f3da1b12-960a-4e39-a557-7f8c52734666)

This is even after running "fit_to_page_width". 
The text also becomes very blurry.

Thanks for your help!!

**Comment by ahrm** [comment]
Hi! Which version of sioyek are you using?

**Comment by BenCzu** [comment]
I installed it using homebrew.
Version 2.0.0

**Comment by ahrm** [comment]
I expect this issue to be already solved in the development branch, unfortunately there are no binary releases available right now but you can build it from source if you want.

**Comment by BenCzu** [comment]
Ok Thanks, I will give that a go.

**Comment by BenCzu** [comment]
I am new to building from source. Do I just follow the steps on the development branch readme to install the development branch version?

If so, when installing aqtinstall I get error: 

       `error: externally-managed-environment

       × This environment is externally managed
      ╰─> To install Python packages system-wide, try brew install
      xyz, where xyz is the package you are trying to
      install.
    
    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:
    
    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz
    
    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with
    
    brew install pipx
    
    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.
    
    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.
    
    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.`

The solution homebrew suggests, installing qt via homebrew, is the very thing trying to be avoided I assume?

**Comment by ahrm** [comment]
The build instructions for the development branch are similar to the main branch with the exception that we use qt 6.5+ in the development branch.

Your issue is that you are trying to install a python package using the global python interpreter which I think is not allowed, you need to createe a virtual environment and install it there.

Though installing aqtinstall should be unnecessary because I think there should be a qt6 package available on homebrew directly (I don't have a mac so I can't help you much there).

**Comment by BenCzu** [comment]
Yes development branch successfully installed!! Fixed rendering issues.
Installed qt via homebrew. This gave me version 6.7. And I exported qt's path.

Thank you for your help.
