### ISSUE TITLE
shared.db file location

### ISSUE THREAD

**Issue by PalaceTony** [ahrm/sioyek#1150]
Hi dear author, just want to make sure where the shared file is? It seems that I cannot find it anymore

**Comment by ahrm** [comment]
When running sioyek from console it should print the location.

**Comment by PalaceTony** [comment]
> When running sioyek from console it should print the location.

Hi Dear Author, thanks or replying. May i ask how... sry if this is dumb

**Comment by ahrm** [comment]
Depends on your operating system. It might not work if you are on windows. The default location of shared.db file on windows is in `AppData`, I don't remeber the exact location but probably it is something like `AppData/roaming/sioyek/shared.db`.

**Comment by PalaceTony** [comment]
> Depends on your operating system. It might not work if you are on windows. The default location of shared.db file on windows is in `AppData`, I don't remeber the exact location but probably it is something like `AppData/roaming/sioyek/shared.db`.

Many thanks! Just found it
