### ISSUE TITLE
[feature request] highlight all search occurence

### ISSUE THREAD

**Issue by joihn** [ahrm/sioyek#1152]
I wish searching for a keyword would highlight all occurence in a color,
and another color for the currnently selected color.

Screenshot of the desired behavior as implemented in chrome 
![image](https://github.com/user-attachments/assets/367c0ecc-50b0-4e0e-9483-04212018ecbd)

**Comment by ahrm** [comment]
This is already imlpemented in the development branch (`should_highlight_unselected_search` config)

**Comment by joihn** [comment]
thanks

**Comment by joihn** [comment]
![image](https://github.com/user-attachments/assets/7104d6d9-ab4d-4008-9982-1bd9da3a7f6c)
In chrome, there is an overview of the occurence distribution across the document, it there a way to replicate this in sioyek ?

**Comment by ahrm** [comment]
No.
