### ISSUE TITLE
Unable to Open Certain PDFs

### ISSUE THREAD

**Issue by barrett-ruth** [ahrm/sioyek#1157]
Hi ahrm,

Thanks *SO MUCH* for this PDF reader, I love it.

However, I randomly was unable to open a few PDFs on the latest AUR build from arch (both sioyek and sioyek-git). Please let me know what extra information I can provide.

[This](https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/8a750a72b9b9c29f6a0402866bac34b7_MIT6_006S20_prob1.pdf) is an example PDF that crashes with sioyek. Simply downloading and running sioyek will show you the segfault but here's the output as well:

**_I know just saying "this doesn't work, lol" is completely unhelpful. Please let me know any other information I can provide or ways to circumvent this issue._**

![image](https://github.com/user-attachments/assets/c6bc421c-f636-46fd-9fdc-b985be80fb7f)

**Comment by ahrm** [comment]
Can't reproduce the issue, my guess is that the issue is due to those packages using a newer version of libmupdf which might be incompatible with sioyek (the development branch of sioyek currently uses libmupdf 1.22). You should contact the maintainers of these packages about that.

**Comment by barrett-ruth** [comment]
OK awesome, totally thought that was the case. TYSM!
