### ISSUE TITLE
[Feature Request] Scrollbar on by default

### ISSUE THREAD

**Issue by Nielius** [ahrm/sioyek#1159]
I would like to have a scrollbar available by default when I open a PDF. There is a command `:toggle_scrollbar`, but it is annoying to have to type that when I just want it to be on by default. A looked at `prefs.config`, and also in this repo, and couldn't find any setting to achieve this.

**Comment by ahrm** [comment]
You can do this:
```
startup_commands toggle_scrollbar
```

**Comment by Nielius** [comment]
Nice, thanks!
