### ISSUE TITLE
Animation support?

### ISSUE THREAD

**Issue by A3EKV** [ahrm/sioyek#116]
Hello,

I have a question about animation support in Sioyek. Is it possible that Sioyek support animation in PDF documents or it's not possible because the underlying libraries (MuPDF?)  doesn't support that?

I am asking this, because currently in the GNU/Linux world, there is no single PDF viewer that support animations. For example the following [PDF documents that contain animations](https://texample.net/tikz/examples/tag/animations/) can only viewed properly on MS Windows but can't animated on Linux (I don't know about MacOS).

Thank you

**Comment by ahrm** [comment]
I am not sure if MuPDF supports animations, but even if it does, we probably won't because our architecture assumes that pages don't cache (and thus can be aggressively cached).

**Comment by mibmo** [comment]
@A3EKV did you find any Linux software supporting animations? Neither of the two I use daily (sioyek and zathura) seem to support it. Maybe Okular does?
