### ISSUE TITLE
[bug] page is (horizontally) un-centered after jumps

### ISSUE THREAD

**Issue by tennysontbardwell** [ahrm/sioyek#1161]
## Environment
- MacOS 14.5 (Air M1)
- homebrew installed, version `2.0.0`
- [dotfiles](https://github.com/tennysontbardwell/public/tree/1d59ad6839dc23379dd9b1b0467263512e8d0e08/dotfiles/sioyek/.config/sioyek) (issue persist even with empty dotfiles and shared-database)

## Symptoms
1. Open most pdfs with many (10+ pages?) and a table of contents ([example](https://arxiv.org/pdf/1612.09375))
2. Zoom out such that the page is approximately 50% of screen width
3. Use jump commands such as
    a. Navigate via the table of contents command
    b. Jump via remembered marks
4. The page is now off-center

## Expected Behavior
The page remains centered

## Screenshots
1. <img width="1792" alt="Screenshot 2024-09-08 at 20 03 21" src="https://github.com/user-attachments/assets/8d427e50-d2ab-48b4-834f-a7dc10b090fd">
2. <img width="1792" alt="Screenshot 2024-09-08 at 20 03 32" src="https://github.com/user-attachments/assets/c72ababb-676f-420b-b229-616a331639a6">
3. <img width="1792" alt="Screenshot 2024-09-08 at 20 03 36" src="https://github.com/user-attachments/assets/c9d5c445-44b4-439f-92ae-8e28abbe8527">

**Comment by ahrm** [comment]
I think this issue is already solved in the development branch.

**Comment by javivera** [comment]
same bug here.. im trying to compile dev branch see if it solves it
