### ISSUE TITLE
ui_font option seems  doesn't work

### ISSUE THREAD

**Issue by EssenSea** [ahrm/sioyek#1164]
As title saying, ui_font doesn't work.
status_font works well.

os: arch linux 6.10.9.arch1-2.

here are #prefs_user.config#:
# =============== #
# general
enable_experimental_features 1
should_use_multiple_monitors 1
collapsed_toc 1
move_screen_ratio 0.9
super_fast_search 1

# =============== #
# UI
ui_font CodeNewRoman Nerd Font
font_size 20
status_font CodeNewRoman Nerd Font
status_bar_font_size 20
status_bar_format [%{current_page} / %{num_pages}] %{search_results}%{search_progress}%{link_status}%{waiting_for_symbol}%{indexing}%{preview_index}%{synctex}%{drag}%{presentation}%{visual_scroll}%{locked_scroll}%{highlight}%{freehand_drawing}%{rect_select}%{custom_message}

# =============== #
# UI color
background_color           #272e33
dark_mode_background_color #272e33

text_highlight_color       #d3c6aa

search_highlight_color     #a7c080
link_highlight_color       #a7c080
synctex_highlight_color    #a7c080

custom_background_color    #272e33
custom_text_color          #d3c6aa

status_bar_color           #272e33
status_bar_text_color      #d3c6aa

ui_text_color              #d3c6aa
ui_background_color        #272e32
ui_selected_text_color     #272e33
ui_selected_background_color #d3c6aa

startup_commands toggle_custom_color

# =============== #
# translate
new_command _dual_panelify python -m sioyek.dual_panelify "%{sioyek_path}" "%{file_path}" "%{command_text}"
new_command _translate_selected_text python -m sioyek.translate "%{sioyek_path}" "%{selected_text}"
new_command _translate_current_line_text python -m sioyek.translate "%{sioyek_path}" "%{line_text}"

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ziova** [comment]
Any updates on this?

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/279ffaee70b4fe2695e7a8e8376ded09da1fe821.

**Comment by EssenSea** [comment]
> Should be fixed in [279ffae](https://github.com/ahrm/sioyek/commit/279ffaee70b4fe2695e7a8e8376ded09da1fe821).
Thx! It works.

**Comment by EssenSea** [comment]
> Should be fixed in [279ffae](https://github.com/ahrm/sioyek/commit/279ffaee70b4fe2695e7a8e8376ded09da1fe821).

I'm not sure whether it should works for status_bar, but It seems not. Perhaps it could be a feature request?

**Comment by ahrm** [comment]
There is a separate `status_font` config for that.

**Comment by EssenSea** [comment]
> There is a separate `status_font` config for that.

Tried it, and works perfectly!
