### ISSUE TITLE
`[m]control_menu(up)` and `down` interact badly with ToC heirachies

### ISSUE THREAD

**Issue by tennysontbardwell** [ahrm/sioyek#1165]
## Environment
- MacOS 14.5
- Macbook M1 Air
- The arm version of [sioyek3-alpha0](https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0)
- [Config files](https://github.com/tennysontbardwell/public/tree/1d59ad6839dc23379dd9b1b0467263512e8d0e08/dotfiles/sioyek/.config/sioyek)
  - Specifically:
     ```
     [m]control_menu(up) <C-p>
     [m]control_menu(down) <C-n>
     ```

## Observed behavior
- Opened The Matrix Cookbook ([doc](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf))[1]
- Scroll to page 17
- Typed `t` to open the table of contents
  - behaves as expected
  - <img width="1792" alt="Screenshot 2024-09-12 at 15 08 27" src="https://github.com/user-attachments/assets/e32c8dca-7e12-4e63-9af1-69f7d36a1751">
- Typed `<C-n>` to go down the table of contents
  - Does NOT behave as expected. Menu focuses on the parent heading in the table of contents.
  - <img width="1792" alt="Screenshot 2024-09-12 at 15 08 35" src="https://github.com/user-attachments/assets/e9c18066-ba1c-4b17-85ed-1bc83a202bc5">
- Typed `<C-n>` to go down the table of contents
  - Does NOT behave as expected. Menu focuses on the next top-level-heading in the table of contents.
  - <img width="1792" alt="Screenshot 2024-09-12 at 15 08 39" src="https://github.com/user-attachments/assets/95d7f98f-c1e2-464f-b933-8aa391844099">
- Typed `<C-n> <C-n> <C-n>` to go down the table of contents 3 times
  - Does NOT behave as expected. Each time, menu focuses on the next top-level-heading in the table of contents.
  - <img width="1792" alt="Screenshot 2024-09-12 at 15 08 51" src="https://github.com/user-attachments/assets/0534a63b-9b17-409c-bcc9-772fdfe609f7">
- Typed `tab` to go down the table of contents
  - behaves as expected
  - <img width="1792" alt="Screenshot 2024-09-12 at 15 08 54" src="https://github.com/user-attachments/assets/c5ab4ced-155f-4306-897e-95cc9c3fb751">
- Typed `<C-n>` to go down the table of contents
  - Does NOT behave as expected. Menu focuses on a top-level-heading very far away from the current selection
  - <img width="1792" alt="Screenshot 2024-09-12 at 15 08 58" src="https://github.com/user-attachments/assets/cbfd0a33-92c0-42ec-af64-d9d9ff39a6da">

## Expected Behavior
- `[m]control_menu(up) <C-p>` behaves similar to "shift tab" or `<up>`
- `[m]control_menu(down) <C-n>` behaves similar to `<tab>` or `<down>`

## Other thoughts
It seems as though the current development branch does not have any better item than `[m]control_menu(up)` ([codelink](https://github.com/ahrm/sioyek/blob/2a39368c4656e018264b657c20c6cd5a216e9976/pdf_viewer/main_widget.cpp#L9440-L9444))

[1] md5sum `f26b052726b6dd92907c402c35a92131`, sha256 `93da5e376fbc106ec92fbb9c59174298b6c3be8f6ad0295d805e94b8d5e76667`

**Comment by tennysontbardwell** [comment]
Even if it was desired that `[m]control_menu(up)` works on the top-level ToC items, the final screenshot is (as far as I can tell) a nonsensical result.

Obligatory: thank you for producing and maintaining sioyek.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/d448ea962494cd2295669209320b667665314dc8.

**Comment by tennysontbardwell** [comment]
Thank you very much! I have not gotten a chance to build development, but I will optimistically close this.
