### ISSUE TITLE
feat: jump to page n with colon+n command like in vim

### ISSUE THREAD

**Issue by life00** [ahrm/sioyek#1166]
I am not sure if its a duplicate because its not very searchable, but sorry if it is. 

I would like to make a feature request to add a functionality where you can jump to a specific page by pressing colon and page number (`:123`). This feature exists in vim and it allows to jump to that specific line, except here I want to suggest to jump to a page number.

Thanks for consideration.

**Comment by tennysontbardwell** [comment]
I could have sworn that this used to be a feature (I'm currently on the alpha release). Perhaps it was removed/broken recently? Or perhaps I am hallucinating.

**Comment by ahrm** [comment]
Yes, this was a feature that I seem to have removed, I don't remember why but I will bring it back if it is possible.

**Comment by ahrm** [comment]
I re-added this feature in https://github.com/ahrm/sioyek/commit/25b7440193ff489dce42ea1bb63a4d1c3f123905.
