### ISSUE TITLE
How can i select the default highlight in the prefs_user.config?

### ISSUE THREAD

**Issue by Bluey26** [ahrm/sioyek#1168]
Hello!

I am using the program frequently and i always use the hr (highlight red) keybind.

I was wondering if i could select this color (red) as the default one at startup, so i looked into the docs and i have found:

`set_select_highlight_type` (under https://sioyek-documentation.readthedocs.io/en/latest/usage.html#highlights)

which works properly in the program but i don't know how can i set it this way:

`set_select_highlight_type r` (i tried this without luck)

inside my `prefs_user.config` file so i can just press the **h** key and highlight with red.

This part is properly handled by:

`add_highlight_with_current_type h` inside `keys_user.config`

Thanks in advance

Sioyek version: `sioyek-appimage 2.0.0-2`

**Comment by ahrm** [comment]
You can do this:
```
startup_commands set_select_highlight_type(r)
```
