### ISSUE TITLE
[HEAD build] macOS older version support

### ISSUE THREAD

**Issue by SichangHe** [ahrm/sioyek#1169]
Hi @ahrm, thank you for releasing HEAD builds again. I grabbed one from https://github.com/hexomancer/sioyek/releases/tag/manual_release19 and tried it out on macOS. Unfortunately, it says I need macOS 14 to run this app.

If it this is configurable, could you also support older macOS versions?

Thank you very much!
Steven Hé (Sīchàng)

**Comment by ahrm** [comment]
I am not sure. You could change `QMAKE_MACOS_DEPLOYMENT_TARGET` in pdf_viewer_build_config.pro and rerun the github action to see if it works.

**Comment by SichangHe** [comment]
This seems to be a limitation of Qt6; they only support macOS ARM starting from 14. I tried the "intel" build and it works.

`QMAKE_MACOSX_DEPLOYMENT_TARGET` is already set to 11, so no changes is needed.

Thanks,
Steven Hé (Sīchàng)
