### ISSUE TITLE
Execute command within Sioyek in Linux

### ISSUE THREAD

**Issue by DedZago** [ahrm/sioyek#117]
Hello, first of all thanks for the great software!

I was curious whether it would be possible to execute a linux command on the opened pdf from within sioyek, similarly to "exec _linux-command_ $FILE" from zathura. 

This would greatly benefit my workflow since I usually take notes in a LaTeX document which is created using the above command from the currently open pdf file.

Thanks again.

Edit: if launching commands is not possible, for me it would also suffice to be able to get the path of the currently open document in sioyek.

**Comment by ahrm** [comment]
Added an `execute` command in 87af77b7facda64d28daed74a808c4d075a7fdfd. It is not very robust, you can probably break it using commands with lots of spaces in arguments, etc. but it is OK for quick and dirty jobs. In the command, `%1` expands to the file path and `%2` expands to the file name. Also I have only tested it on windows, I don't know if it works on linux.

By the way if you just want the name of the file, you can already press `ctrl+shift+o` (`open_document_embedded_from_current_path` command) and it opens a file selector with the path of the current file already entered.

**Comment by ahrm** [comment]
> Any examples for binding it in config?

```
execute     <C-u>
```

**Comment by VolkovIlia** [comment]
> > Any examples for binding it in config?
> 
> ```
> execute     <C-u>
> ```

I want to map `notify-send \"Name of file is %1\"`, how to do that?

**Comment by ahrm** [comment]
> > > Any examples for binding it in config?
> > 
> > 
> > ```
> > execute     <C-u>
> > ```
> 
> I want to map `notify-send \"Name of file is %2\"`, how to do that?

Oh you can't currently do that, you have to type the name of the command every time. Adding ability to bind a specific command is a good idea which I may implement.

**Comment by VolkovIlia** [comment]
> 

It works great in `Zathura`, just check it.
