### ISSUE TITLE
Hover Overview text is blurry

### ISSUE THREAD

**Issue by iamkroot** [ahrm/sioyek#118]
The Overview popup that is shown when hovering over a link seems to zoom the contents to fit the screen width. When the underlying page is _not_ at "Fit Width" zoom level, this causes the overview to be blurred due to image resizing artifacts.
For example, open the following image in a new tab to see this in action:
![Screenshot_20220108_124711](https://user-images.githubusercontent.com/29517049/148635563-52e44601-5932-42a3-becd-ab0f3d1c757d.png)

(Original page zoom was made exceptionally small to make the bug easily perceivable)

The fix would be to have the overview window render the page at the new zoom level that matches width of the window.

Extra Info:
Sioyek version: [`main` branch](https://github.com/ahrm/sioyek/commit/d790acab252f26fb5ef385ccc50cfb336811442b)
OS: Linux- Manjaro latest
DE: KDE Plasma 5.23.4

**Comment by ahrm** [comment]
I am aware of this but in my opinion this is worth it because we can reuse the same renders for the preview and for the main view which leads to better performance and less memory consumption.

By the way, in recent versions you can resize the preview window so the blurring is less visible.

**Comment by iamkroot** [comment]
> reuse the same renders for the preview and for the main view

That does sound useful, but probably better to have it as an configurable option? I really don't care about memory in most cases, and having it render twice isn't going to eat up my cpu.

> in recent versions you can resize the preview window

Could you specify how to do this? I tried pressing `-` when the overview is open, but that only resized the underlying page. Is there some config key for this?

I realized that the blurring is less apparent when the page is zoomed _more_ than the overview width. So why not make the overview window width be in terms of the current _page_ width, rather than the window width? This way, the text in overview would always be marginally smaller than the text in page.

**Comment by ahrm** [comment]
> Could you specify how to do this? I tried pressing - when the overview is open, but that only resized the underlying page. Is there some config key for this?

You can resize by dragging mouse on the borders of the overview window. Overview being the size of current page is a possible idea, however I don't think it is an important problem since the overview size is adjustable anyway.
I probably will add an option so that the preview window is rendered at an appropriate resolution (at the cost of time and space).

**Comment by ahrm** [comment]
Added a `rerender_overview` option in 913b77c94a01d07502ef39911f3e95a21df83e73 which instructs sioyek to rerender the overview page at appropriate resolution. You have to add the following to your `prefs_user.config`:

```
rerender_overview	1
```

**Comment by iamkroot** [comment]
> Added a `rerender_overview` option in [913b77c](https://github.com/ahrm/sioyek/commit/913b77c94a01d07502ef39911f3e95a21df83e73) which instructs sioyek to rerender the overview page at appropriate resolution. You have to add the following to your `prefs_user.config`:
> 
> ```
> rerender_overview	1
> ```

Thanks a lot! It seems to be working great :)


> You can resize by dragging mouse on the borders of the overview window

Hmm, I might be missing something, but as soon as I move my mouse when the hover overview is over, it closes the overview window. Is there something to keep it open so I can drag the borders?

> Overview being the size of current page is a possible idea, however I don't think it is an important problem since the overview size is adjustable anyway


Is the overview size remembered across restarts/documents? What happens when different docs have different page sizes?

**Comment by iamkroot** [comment]
> you want to be able to resize you should disable it by adding

I guess that means I can't have hover overview enabled _and_ be able to resize it at the same time (since the size isn't persisted, and we need to restart the app to be able to resize). Maybe a shortcut/command to toggle "hover_overview"?


> I don't think I will add the ability to save it because I want to keep database files as simple as possible.

Yes, that makes sense, no point in storing this kind of info. However, this only strengthens the case for having the overview window's size as relative to the page size.
1. You'd also need to take care that if the page isn't centered on the window, the overview should also _not_ be; ie. overview should be centered on the page.
2. When page is zoomed, overview's dimensions are also changed automatically.

This seems like a good default for all documents, and would cover almost all cases where one would need to resize manually.

**Comment by ahrm** [comment]
We have added the ability to store overview position a while back.
