### ISSUE TITLE
Vertical displacement after jump with table of contents

### ISSUE THREAD

**Issue by SebastianMusic** [ahrm/sioyek#1180]
Hello just i downloaded sioyek through homebrew as an alternative to zathura, and it works way better in general but i found an annoying issue pretty quickly. i dont know if this is a bug or if its a setting i have to change.

When i start sioyek i get a lot of whitespace above my first page. when i then center my screen with "zz" and try to jump to a different page using the "t" for table of contents i do not get placed perfectly on the page. it is always slightly off 

The first image provided is the empty space at the top of my first page when starting sioyek which might contribute to the issue. and the second image is immediatly after a jump using table of contents which places me off center.

<img width="836" alt="Screenshot 2024-10-05 at 16 29 26" src="https://github.com/user-attachments/assets/7f39eaaa-e4d8-484a-96c5-d2662e63e3b3">

<img width="421" alt="Screenshot 2024-10-05 at 16 30 55" src="https://github.com/user-attachments/assets/a1c91643-249b-45ab-bc3a-eb4a17e142df">

**Comment by ahrm** [comment]
Normally we center the table of contents in the screen, there is an option to make it align to the top of the screen in the development branch, see this issue: https://github.com/ahrm/sioyek/issues/630.

**Comment by SebastianMusic** [comment]
Thank you for the speedy reply.  I just tested this with the dev branch and i think i may have miscommunicated myself. I do not want to place the heading of what i am jumping to at the top of my screen. I want to jump to the page where that header is. so i want the *page* to be perfectly centered like when you do "zz" on a page. The way you do in zathura if you have tried that viewer.

Because i have bound J and K to next and previous page. if my page gets uncentered because of a jump then it becomes very disorienting when i do next and previous page.

**Comment by ahrm** [comment]
Does using something like this in the development branch help your case? (keys_user.config) :
```
goto_toc;goto_top_of_page t
```

> So if its either possible to bind J and K to go to next or previous page and center it.

It is possible using a similar method:
```
next_page;goto_top_of_page J
```

**Comment by SebastianMusic** [comment]
```
goto_toc;goto_top_of_page t
```
did not work


but binding
```
next_page;goto_top_of_page J
previous_page;goto_top_of_page K
```
worked great thank you! i did not know i could chain commands with the semicolon :)

**Comment by SebastianMusic** [comment]
Yes, i have not tried it on the stable branch though.

**Comment by ahrm** [comment]
Did you restart sioyek after changing the key config?

**Comment by SebastianMusic** [comment]
Yes, i have tried a bit now and i still cant get it to work. i have shut of and restarted sioyek multiple times.

**Comment by ahrm** [comment]
What if you do something like this:
```
goto_toc;toggle_dark_mode t
```

Does toggle_dark_mode work?

**Comment by SebastianMusic** [comment]
Yes dark mode works and it toggles instantly. i assume the other keybind does not work since it centers me at the same time as it opens the table of contents. that is probably why it does not center me when i confirm which of the index i want to jump to.

**Comment by ahrm** [comment]
That should be the case in the development branch (in the old build there was a bug where the second commadn triggered immediately but it should be fixed in the development branch).

**Comment by SebastianMusic** [comment]
Is there a way to confirm my version sioyek inside of sioyek? As to make sure i am actually on the dev branch? I have switched to the dev branch but i might have previous installations which are being run instead.

**Comment by ahrm** [comment]
Do you have access to some new commands in the command menu (e.g. `add_freetext_bookmark`)?

**Comment by SebastianMusic** [comment]
No i do not. So it is i who have not properly switched over to the dev branch. This is my first time attempting to build anything from source so please pardon me for this mistake. Thank you for your help i will try to properly build the dev version

**Comment by SebastianMusic** [comment]
When building the dev branch am i supposed to run the same command i did for the main branch?

i have tried a bit now and i can not get the dev branch to be compiled. But i can manage to compile the main branch.
I try to compile the dev branch, I navigate into the build directory and there is no sioyek.app file. Whereas when i do so inside of the main branch, and run the same commands there does appear a sioyek.app file in the build directory. Am i meant to run some different command when compiling from the development branch?

here is what i run to try to compile
```
chmod +x build_mac.sh

brew install 'qt@5' freeglut mesa harfbuzz

export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"
#: The above is needed to make =qmake= from =qt= be found.
#: Find the path using =brew info 'qt@5'=.

MAKE_PARALLEL=8 ./build_mac.sh
```

**Comment by ahrm** [comment]
It is pretty much the same but we need qt6 instead of qt5.

**Comment by SebastianMusic** [comment]
i tried running this now 
```
chmod +x build_mac.sh

brew install 'qt@6' freeglut mesa harfbuzz

export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"


MAKE_PARALLEL=8 ./build_mac.sh
```

It gets compiled and ends up in my sioyek directory, but not in the builds folder. Also when i move it to my application folder and try to run it i get that i can't because "it may be damaged or incomplete"


This is the last output i get before i presumbly get some sort of error.
<img width="844" alt="Screenshot 2024-10-05 at 21 21 34" src="https://github.com/user-attachments/assets/166f845a-828e-450a-975d-d683c8ca2cfd">

**Comment by ahrm** [comment]
See this comment thread: https://github.com/ahrm/sioyek/discussions/1156#discussioncomment-10818199

**Comment by SebastianMusic** [comment]
That did not work for me unfortunately. Is the compiled sioyek from the development branch supposed to end up in a builds folder like the main branch? Since if it is then it might indicate some issue with the complation process rather than after it. As i have recompiled the main branch and that works well.

**Comment by ahrm** [comment]
> Is the compiled sioyek from the development branch supposed to end up in a builds folder like the main branch

Yes, unfortunately I don't have a mac machine right now so I can't help you directly, maybe this helps: https://github.com/ahrm/sioyek/issues/887#issuecomment-1935694670. (especially the part about signing).

**Comment by SebastianMusic** [comment]
No worries thank you for all the help i really appreciate it. i will try to get it working tomorrow :)

**Comment by jinjiaodawang** [comment]
@SebastianMusic you may look at
https://github.com/ahrm/sioyek/issues/967#issuecomment-1938197461

**Comment by SebastianMusic** [comment]
Thanks for the tip! @jinjiaodawang but that did not work on my machine unfortunatly. It might have something to do with me being on the latest version of MacOS. Which might have broken something in the dev branch. I will have to tinker some more once i get ahead of my school work. Again thanks for the help :)

**Comment by SebastianMusic** [comment]
i could not for the life of me get it to build from source, but i managed to download [this](https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0) alpha release, and that seems to work very well. i just had to sign it like when you build from source.
