### ISSUE TITLE
Sioyek looks pixelated on hd second monitor

### ISSUE THREAD

**Issue by SebastianMusic** [ahrm/sioyek#1181]
Sioyek seems not to fill in each letter properly. They look pixilated and thin and are hard to read. Here i have sioyek on the left and zathura on the right opening the same pdf.

I was working and i noticed my pdf was quite hard to read, i had the pdf on my second monitor. and when i switched it on my main the issue vanished. So i thought the issue was because my second monitor is full hd, while my main is double. 
But i checked and zathura is able to render the pdf properly so it can't be my screen that is the issue.

I dont know how easy it is to see on the picture but the issue seems to be that sioyek does not "fill in" each charachter completly. The lines become thin and pixelated. I dont know if there is some preference i need to set for it to open pdfs with higher fidelity or if there is some bug.

I am on the main branch, on MacOS Sequioa. 
![image](https://github.com/user-attachments/assets/2ec96fa8-d58e-4ee1-bd06-1eba68f4791c)

**Comment by ahrm** [comment]
This also should be fixed in the development branch.

**Comment by SebastianMusic** [comment]
I managed to fix it buy downloading an alpha version instead of building from source on the development branch. See [this comment](https://github.com/ahrm/sioyek/issues/1180#issuecomment-2397522265) if anyone has similar issues
