### ISSUE TITLE
Jumping to chapter in table of contents does not preserve page position

### ISSUE THREAD

**Issue by alexxue99** [ahrm/sioyek#1188]
Steps to reproduce:
When the page is not fit to width, jumping to a chapter via the table of contents changes the page positioning to be off-center.

**Comment by ahrm** [comment]
Does it happen in the preview release here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0?

**Comment by alexxue99** [comment]
> Does it happen in the preview release here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0?

It works there!
