### ISSUE TITLE
[FR] Make sioyek copy text selected using the mouse

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#1190]
I have
```
keyboard_select;copy v
```
which makes keyboard selections automatically copy the selection. Now I am looking for the same but for mouse selections.

**Comment by ahrm** [comment]
If you are on an operating system that supports selection clipboard (e.g. X11) then we already do this. In other operating systems if you are looking for a way to copy the text without having to use keyboard you can do something like this (works only on the development branch):
```
right_click_context_menu 1
context_menu_items_for_selected_text copy
```

Does this fix your problem?

**Comment by NightMachinery** [comment]
@ahrm On the dev branch on macOS; how do I always copy without using the context menu?

**Comment by ahrm** [comment]
Added `always_copy_selected_text` config option in https://github.com/ahrm/sioyek/commit/8877bf02bb5317e839561c369d043db814c17717.
