### ISSUE TITLE
custom colors in preview release don't work like in the main branch

### ISSUE THREAD

**Issue by dinesh-58** [ahrm/sioyek#1193]
So I tried copying over my configs to the [preview release](https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0) build, which includes this in my `pref_user.config`:
```
custom_background_color 0.102 0.106 0.149
custom_text_color 0.753 0.792 0.961
```
So, let's say I open a pdf with some graphical elements / colors which normally looks like this:
![image](https://github.com/user-attachments/assets/6077e52c-80f2-44a1-bbac-a6ec5c1ab81d)
Custom colors in main branch:
![image](https://github.com/user-attachments/assets/27a3f3f5-eee4-476f-acfb-efd7441fc254)

Custom colors in preview release:
![image](https://github.com/user-attachments/assets/a84d4571-db3e-42d7-93bb-92eab66ee940)
Note how the logo, borders & heading don't get the custom color applied, though the corner graphic seems to apply the color properly. Also, the area outside the pdf remains black instead of using custom_background_color. Let me know if I should send the pdf file here

**Comment by ahrm** [comment]
Yes, we try to better save the original colors when possible. We still use the exact configured color for text and background. I think the new colors look much better.

**Comment by dinesh-58** [comment]
Oh ok. I'll try getting used to this then. Is there a way to set the color for the area outside the pdf?

**Comment by ahrm** [comment]
Yes, using `custom_color_mode_empty_background_color` config.

**Comment by dinesh-58** [comment]
Thanks a lot. Seems this hasn't been documented in prefs.config or the docs site. Let me know if you need me to make a PR.
