### ISSUE TITLE
`<C-n>`, `<C-p>`, `<C-j>`, and `<C-k>` do not work to navigate menus

### ISSUE THREAD

**Issue by pangdaxing23** [ahrm/sioyek#1195]
Using [Release 7181c5a463ed4cbeda7ab4937511bdfc836d6c94](https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0) on M3 Mac.
Can confirm they work in 2.0.0 though.
These menu-navigation commands don't seem to be documented anywhere, but they're of course very natural, and `<C-n>` and `<C-p>` are even present in most search bars in MacOS.

**Comment by pangdaxing23** [comment]
I had not! Thanks!
I still do not see it in the documentation though. I may have missed it, but if it's not there then it should be added.
And I'd also suggest adding these as default keybindings:
```
control_menu(down) <C-n>
control_menu(down) <C-j>
control_menu(up) <C-p>
control_menu(up) <C-k>
```

**Comment by hamdan7m** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
