### ISSUE TITLE
Link to external pdf crashes sioyek

### ISSUE THREAD

**Issue by jrotheneder** [ahrm/sioyek#1199]
Opening a link in a pdf which leads to an external pdf in the same folder leads with the example files below to the error message "could not open /..../leA.pdf" [sic] and a subsequent crash. I'm using the pre-release version of sioyek from Sep. 11. The examples have been generated via LaTeX like in [this](https://tex.stackexchange.com/questions/71307/hyperref-to-external-pdf-that-will-open-at-particular-label) stack exchange post. 

[fileA.pdf](https://github.com/user-attachments/files/17449691/fileA.pdf)
[fileB.pdf](https://github.com/user-attachments/files/17449692/fileB.pdf)

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/07bb5f0da06423b544684fd3f7c136190090a106.

**Comment by jrotheneder** [comment]
That was fast! The linked pdf now opens, but not yet in the correct location. 

With the two files above, clicking the link in fileB should open page 3 of fileA, but currently opens page 1. I've tested with other pdf readers to make sure this is not an issue with the pdfs themselves: Okular on Linux and PDF Expert on Mac display the correct behaviour.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/50b4de8e7d9e18df38d0e4f5b37d067e5f10d117.

**Comment by jrotheneder** [comment]
Can confirm, neat.
