### ISSUE TITLE
Cant found a way to tweak prefs_user in flatpak app 

### ISSUE THREAD

**Issue by barcell1** [ahrm/sioyek#1206]
Would like to set some custom colors, tried setconfig or set_custom_background_color , altough did work when i quit and reopen the colors are note saved, and i dindt found the file on flatpak directory

**Comment by ahrm** [comment]
The paths should be printed when sioyek is executed from the command line. `set_custom_background_color` is temporary and is not supposed to be saved across sessions, for that you need to manually edit `prefs_user.config`.

**Comment by Anshsahu0802** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by barcell1** [comment]
thanks, you can close, already sent issue report to the flatpak variant of this app, the owner noticed that there is a bug  with the paths and will fix in the next release second to him .
