### ISSUE TITLE
Predefined shell commands missing in sioyek3-alpha0 release

### ISSUE THREAD

**Issue by Tonyzhu77** [ahrm/sioyek#1208]
Hi. I love this program and have recently installed the new release of [sioyek3-alpha0](https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0). I found many of the updates really helpful and I really appreciate it.
However, in the new release I cannot find the predefined shell commands `execute_predefined_command`, `execute_command_a` to `_z` or `new_command`. Is it a bug, or intentionally removed, or that something is wrong with the build process? I'm using MacOS ARM version. Thanks in advance.

**Comment by ahrm** [comment]
`execute_predefined_command` and `execute_command_a-z` were removed and replaced with `new_command`. `new_command` should still work:

```
new_command _my_command <some shell command>
```

**Comment by Tonyzhu77** [comment]
It works! Thank you so much.
