### ISSUE TITLE
zoom_inc_factor    does not affect ctrl + scrollwheel 

### ISSUE THREAD

**Issue by joihn** [ahrm/sioyek#1217]
thanks for this tool,

setting :
```
zoom_inc_factor         1.05
```
does affect zoom via `-` / `+` key
however it does not affect zoom via `ctrl + scrollwheel`, the increment step stays the same :cry: 

### env 
- self compiled sioyek, compiled 2 weeks ago from development branch 
- I also have set 
```
wheel_zoom_on_cursor 1
```
which could maybe potentially have an influence
- ubuntu 24.04

**Comment by ahrm** [comment]
We have a separate `scroll_zoom_inc_factor` config for that.
