### ISSUE TITLE
[Development] Visual mark is an underline now?

### ISSUE THREAD

**Issue by panangam** [ahrm/sioyek#1220]
I just pulled the latest development branch commits and found out that the usual shadowbox visual mark became underline now. This seems to also be buggy, as in the light mode the underline is white (most of the time) and barely visible. Is there any setting to turn it back to a shadowbox as before, or which commit should I revert to to get the shadowbox back?

**Comment by ahrm** [comment]
You can enable the old behavior by adding this to your `prefs_user`:
```
ruler_display_mode slit
```

> as in the light mode the underline is white (most of the time) and barely visible

I don't have this issue. Can you post a screenshot?

**Comment by panangam** [comment]
@ahrm Thank you! I took 2 screen recordings for the `underline` and `box` mode. The lines look fine in dark mode, but in light mode the colors seem to shift erratically. 

[Screencast_20241110_210516.webm](https://github.com/user-attachments/assets/4cd303c0-e6af-4670-851b-ff56a2008962)
[Screencast_20241110_210654.webm](https://github.com/user-attachments/assets/6ab1dbd6-5aaa-4394-adc3-e68fabe89e28)

**Comment by ahrm** [comment]
Unfortunately I can't reproduce the issue. What happens when you change the ruler color using `ruler_color` config?

**Comment by panangam** [comment]
I've had issues in my local build that nobody else encounters before, so I wouldn't be surprised if this is something caused by my environment again. 

Here's a video setting the `ruler_color` to red. The red line fades to a lighter shade *sometimes*.

[Screencast_20241110_213346.webm](https://github.com/user-attachments/assets/6aac1a12-7ce6-4c06-aa08-015e46dc448e)

**Comment by ahrm** [comment]
I added some shot in the dark changes in https://github.com/ahrm/sioyek/commit/e7b4c6bd7a1e20ad134b199f4c2ab53a2e99af1c. Do they help the issue?

**Comment by panangam** [comment]
That fixed it 👍👍👍. Closing this now.

**Comment by ShadiZade** [comment]
I almost went crazy looking for this option in the documentation. It wasn’t there.

**Comment by ahrm** [comment]
The documentation is for the main branch not the development branch.
