### ISSUE TITLE
Is there a keybind to collapse all / expand all toc entries?

### ISSUE THREAD

**Issue by ziova** [ahrm/sioyek#1223]
For most documents, I prefer to not have a collapsed toc (`collapsed toc = 0`), but for larger documents, I'd rather collapse everything but I do not want a global configuration for this that works on all documents. I am aware that right and left arrow collapse and expand toc items but is there any way to do this for all entries in the toc (smth like S-<right> or S-<left>)?

**Comment by ahrm** [comment]
Added a `toggle_menu_collapse` command. You can bind it to a keybind like so:
```
[m]toggle_menu_collapse <C-t>
```

**Comment by ziova** [comment]
Yes, this works perfectly as expected. Thank you so much. Closing this issue.

**Comment by hamzamohdzubair** [comment]
i can't find this command: `toggle_menu_collapse` in the docs, and adding it to keys_user.config doesn't do anything

**Comment by ahrm** [comment]
You need to compile the development branch.

**Comment by hamzamohdzubair** [comment]
> You need to compile the development branch.

Thanks for one of the most amazing pdf readers out there, however building from source is turning out to be a challenge on mac. It's going to be 3 years since the last release, any plans of the next release?

**Comment by ahrm** [comment]
There is a preview release here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0 (if you see an issue about sioyek being damagaged, that is a know issue, there are solutions in the repo issues, just search the error), but that is also a year old. Unfortunately I can't give you a timeline but I will make a new release when I have some time.
