### ISSUE TITLE
Suddenly wont open

### ISSUE THREAD

**Issue by jerme42** [ahrm/sioyek#1225]
As the title says. I am not sure what has changed and love this reader but it suddenly just does not open on any of my machines.

**Comment by ahrm** [comment]
What operating system are you using?

**Comment by jerme42** [comment]
windows 11.

**Comment by ahrm** [comment]
Do you use the same database files on your different machines? Do you see any error when launching sioyek?

**Comment by jerme42** [comment]
database files? I just try and open any pdf and it tries to launch and a window blinks in than out of existence before I can see anything.

**Comment by ahrm** [comment]
Hmmm the fact that this is happening simultaneously on more than one machine is very strange. There should be a `shared.db` and `local.db` files in `C:\Users\<username>\AppData\Roaming\sioyek`, can you backup these files and delete them and see if it launches?

**Comment by ahrm** [comment]
Which version of sioyek are you using (where did you download it from?).

**Comment by jerme42** [comment]
the newest version from the website

**Comment by jerme42** [comment]
nope. that one works fine.

**Comment by ahrm** [comment]
I guess whatever the issue was it has been fixed inadvertently.

**Comment by hjm7** [comment]
> I guess whatever the issue was it has been fixed inadvertently.我想无论问题是什么，它都已在无意中得到解决。

I installed sioyek today. 

- When I install it at a path containing space, such as "D:\Program Files\...", it won't work well; I see a preview window when cursor at task bar but can't click to display a window. 
- If I install it at a path not containing space, it works well. 
- Hope document it for Windows users.
