### ISSUE TITLE
[feature request] list recently opened files

### ISSUE THREAD

**Issue by stites** [ahrm/sioyek#1227]
I'm on the dev branch and have increasingly used sioyek for more and more of my workflow, so much so that I do a lot of file navigation in a single sioyek instance. I would love to have a command that lets me see a list of recently opened files (maybe something that I could fuzzily match on).

Thank you for the great software!

**Comment by ahrm** [comment]
We have `goto_prev_doc` and `goto_tab` commands for that.

**Comment by stites** [comment]
:100: Exactly what I was looking for!
