### ISSUE TITLE
Multiple global marks resolving to the same page

### ISSUE THREAD

**Issue by EdvardSire** [ahrm/sioyek#1230]
Hello and thank you for this wonderful tool!

I'm trying to set multiple global marks e.g. `mK` and `mF` two different places in the same document.
When resolving these, `` `K`` and `` `F`` resolve to the last mark set(in a specific document). Is this indented behavior or am I doing it wrong.

Best regards

**Comment by ahrm** [comment]
Which sioyek version are you using?

**Comment by EdvardSire** [comment]
```
sioyek --version
sioyek 2.0.0
```
i don't have the exact commit, this should be representative [nix 24.05](https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=sioyek), [default.nix](https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/applications/misc/sioyek/default.nix#L88).

**Comment by ahrm** [comment]
Can the issue be reproduced in the preview release here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0?

**Comment by EdvardSire** [comment]
I am running nix  on `linux aarch64` so I am unable to run any of the provided AppImages. But I'm trying to build it so i can test:

@xyven1 do you have any insights?

So far i have [default.nix](https://github.com/EdvardSire/nixpkgs/blob/master/pkgs/by-name/si/sioyek/package.nix#L20-L25):
```
  src = fetchFromGitHub {
    owner = "ahrm";
    repo = "sioyek";
    rev = "7181c5a463ed4cbeda7ab4937511bdfc836d6c94"; # <-- the commit ahrm refered to
    hash = "sha256-lHKB9jchsRYjgF7KJdlDTpKVZGP8lq1btmTt3ud67wM=";
  };
```
then i run
```
NIXPKGS=./nixpkgs nix-build $NIXPKGS -A sioyek
```
which crashes. Relevant `nix-store -l /nix/store/AAAAAAA-sioyek-local-testing.drv`:
```
pdf_viewer/utils.cpp: In function 'ParsedUri parse_uri(fz_context*, std::string)':
pdf_viewer/utils.cpp:122:29: error: 'pdf_parse_link_uri' was not declared in this scope; did you mean 'pdf_parse_ind_obj'?
  122 |         fz_link_dest dest = pdf_parse_link_uri(mupdf_context, uri.c_str());
      |                             ^~~~~~~~~~~~~~~~~~
      |                             pdf_parse_ind_obj
```
Relevant issue #804

**Comment by ahrm** [comment]
Are you sure you are building the development branch? This looks like you are trying to build the main branch.

**Comment by EdvardSire** [comment]
Yes that works!
Greatly appreciate the fast response:)
