### ISSUE TITLE
Keybindings to move up and down for list opened by `open_prev_doc`

### ISSUE THREAD

**Issue by jsr-p** [ahrm/sioyek#1231]
Hi

I installed `sioyek` from source at commit `ba481becabbd0c85692c4eeaf7d0dd8284f09c4a`.
However, my keybindings used when going through previous files in `open_prev_doc` suddenly don't work (I used to press `<c-j>` and `<c-k>` to go up and down.
I can't see any command inside the [docs](https://sioyek-documentation.readthedocs.io/en/latest/commands.html#open-prev-doc) that show what I should bind; does anyone know where it can be set?

**Comment by ahrm** [comment]
Does this help? : https://github.com/ahrm/sioyek/issues/1195

**Comment by jsr-p** [comment]
yes, thanks a lot! I searched through old issues by `open_prev_doc` so didn't see that one :s 

however, `<c-k>` for `control_menu(up)` does not work for me for some reason? binding it to `<c-p>` does, though :thinking:

**Comment by ahrm** [comment]
What is your `keys_user.config`?
This works for me in the development branch build:
```
[m]control_menu(up) <C-k>
[m]control_menu(down) <C-j>
```

**Comment by jsr-p** [comment]
nice, that works!
what are the prepended `[m]`'s in yours?
I just wrote
```
control_menu(down) <C-j>
control_menu(up) <C-k>
```
before

**Comment by ahrm** [comment]
`[m]` means that the keybinding is only active in menus. I don't know why `<C-k>` is not working for you, maybe there is another keybinding that is overriding it?

**Comment by jsr-p** [comment]
> `[m]` means that the keybinding is only active in menus. I don't know why `<C-k>` is not working for you, maybe there is another keybinding that is overriding it?

I do indeed have it bound to something else as well; but I tried to remove that part and it stil didn't work.
But now with `[m]` it all works :champagne: 

```
previous_page <C-k>
next_page <C-j>
[m]control_menu(up) <C-k>
[m]control_menu(down) <C-j>
```
