### ISSUE TITLE
Long height of text selection and highlight in Axler's linear algebra 4th ed

### ISSUE THREAD

**Issue by mostafatouny** [ahrm/sioyek#1232]
Sheldon Axler's new edition of linear algebra book is open accessed [HERE](https://link.springer.com/book/10.1007/978-3-031-41026-0).

Unfortunately, Text selection consumes long height, and in turn text highlight does not look nice:

![Screenshot_2024-11-19_08-33-59](https://github.com/user-attachments/assets/f658d25c-996c-46c7-a22a-ba124adbe5a0)

The third edition of the book had no issues at all.

Is this a bug in sioyek or the book itself? any work-around?

version 2.0.0

**Comment by ahrm** [comment]
This is just the height that mupdf returns to us. There is nothing I can do about that, if there is a bug, it should be reported to mupdf devs.

**Comment by mostafatouny** [comment]
I discovered ghostscript fixes the issue also:

`gs -o fixed.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress corrupted.pdf`

For more debugging tools, see [pdftk](https://www.pdflabs.com/docs/) and [qpdf](https://github.com/qpdf/qpdf).
