### ISSUE TITLE
The Portal window does not follow the theme of the main window

### ISSUE THREAD

**Issue by 1andro1** [ahrm/sioyek#1237]
Hello,

many thanks for the exceptional program!

As the title suggests, the new opened windows in a portal does not follow the theme of the main document. I do not know whether that is made intentionally, but for me make sense, if the main document is with a black background, the portal document also to have the same background.

  
<img width="1920" alt="Capture" src="https://github.com/user-attachments/assets/53aee4d2-4831-40b5-8f32-e9399e34b1bd">

Best Regards,
Adriyan

**Comment by ahrm** [comment]
Should be fixed in the latest commits in the development branch.

**Comment by 1andro1** [comment]
Many Thanks! I do not know how to test it, but the idea was to inform you.

Many Thanks once again!!!
