### ISSUE TITLE
One instance per file

### ISSUE THREAD

**Issue by DetectiveBrie** [ahrm/sioyek#124]
Hi,

Is there any setting to have one instance per file? As far as I can tell, the `should_reuse_instance` setting either means that the latest used instance will open the file, or that a new instance will open each time a pdf will be used. The main reason I use this is because when I read papers, I tend to have many papers open at the same time, but also I sometimes forget I already opened a paper and on sumatra, reopening it from zotero would just send the already opened instance to the foreground.

**Comment by Endle** [comment]
I like this feature request. I have similar use cases.

However, one question is poping up in my mind - how could we define "same file"? If a same PDF has many copies, should we consider them as the same file?

**Comment by DetectiveBrie** [comment]
I'm sure there are many ways to answer that but the path of the pdf file would be a simple way for this. When I open a paper from Zotero, it's always the same pdf file opened. When I build from my code editor, it's the same pdf I reopen at each build, etc...

**Comment by ahrm** [comment]
I understand this is a useful feature, however, implementing it is pretty difficult with our current way of handling multiple instances. I may implement it by rewriting the way we handle instances but it probably won't be anytime soon.

**Comment by ahrm** [comment]
We have introduced the `new-window` command line option (instead of `new-instance`) which does support this. Also I consider the `new-instance` command deprecated because `new-window` can do everything that `new-instance` does in a more efficient manner.
