### ISSUE TITLE
How to create a sioyek appimage?

### ISSUE THREAD

**Issue by Bluey26** [ahrm/sioyek#1240]
Hi, i wanted to create a sioyek appimage, both for testing purposes and also to see if i could add to it the qtwayland support.

There is already an appimage for my system, but it does not have qtwayland, so i decided to try to make it myself. This would also help me for future uses and other programs. (See https://github.com/ahrm/sioyek/issues/867)

I almost did everything(i think), but i still end without the .appimage file, but i end without the .appimage, but `sioyek-release` folder instead.

So far, i did the following:

```
git clone --recursive https://github.com/ahrm/sioyek`

cd sioyek
mkdir qtwayland

```

Then,inside, i extracted the contents of: https://github.com/qt/qtwayland/archive/refs/tags/v6.8.0.zip

I added the following to `.gitmodules` (not sure if this is used in this case):

```
[submodule "qtwayland"]
	path = qtwayland
	url = https://github.com/qt/qtwayland/
```

Then, i added the following lines to `build_and_release.sh` (`build_linux.sh` does not contain anything about appimage):

```
# Compile qtwayland
cd qtwayland
cmake -B build -S . -G Ninja \ -DCMAKE_MESSAGE_LOG_LEVEL=STATUS   cmake 
cd ..
```
~~
I installed in my system: `qt5-3d`

I replaced:

`./linuxdeployqt-continuous-x86_64.AppImage ./sioyek-release/usr/share/applications/sioyek.desktop -appimage`

for 

`./linuxdeployqt-continuous-x86_64.AppImage ./sioyek-release/usr/share/applications/sioyek.desktop -appimage -unsupported-bundle-everything -unsupported-allow-new-glibc`

also without `-unsupported-bundle-everything`

`-unsupported-allow-new-glibc` seems to be necesary to continue in my system (to avoid the error `Host system too new` in linuxdeployqt)

Then, i tried to run:

`./build_and_release.sh portable`

After some minutes, everything seems OK and the program is compiled, `sioyek-release` folder is created, and it has something as a .appImage content structure, but i do not see how to create the .AppImage itself.

The binaries seem to be running qtwayland, but i am still not sure about the presence of the qtwayland package in the future .AppImage

Thanks in advance.

**Comment by ahrm** [comment]
`build_and_release.sh` is literally the script that we use to generate the appimages for github actions. If it is not working for you it might be a system-related issue. As far as I know `linuxdeployqt` only supports the oldest supported version of ubuntu, so running it on an incompatible OS might be causing an issue.

**Comment by Bluey26** [comment]
Yes, that might be the issue in my case, i use Archlinux and i've seen that i should use an older system to do this.

I just have been reading this, and decided to try another option:

https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e

Now i tried to do the following:

i copied the whole sioyek-release (created by `build_and_release.sh`) and moved somewhere else for the test. I installed `appimagetool-bin` from the AUR, then i run:

`appimagetool ./sioyek-release/`

This bundled the appimage for me. Yet i am not sure if the appimage is correctly done. The program opens and i see that is running using wayland (xdg-shell), yet the sioyek-release folder has less folders than the original appimage  i downloaded from ehre (and 've been using until now).

Oirignal AppImage
> ls usr/
`bin  etc  lib  plugins  share  translations`

The one created by me, using the described procedure:

>ls usr/
`bin  etc  share`

I yet have to test for bugs, but it seems to work for now
