### ISSUE TITLE
Segfault when opening non existent local external link

### ISSUE THREAD

**Issue by EdvardSire** [ahrm/sioyek#1242]
Left clicking on a "non existent local external link" (see evince image) with Sioyek `e71f7e29dd` segfaults:
```
  sioyek
shader_path: /nix/store/hnc9940ffb2z96jixak1qm7w1bfp1v3p-sioyek-local-testing/share/shaders
SIOYEK
Warning: invalid command (key: resetting to root
Warning: invalid command (key: resetting to root
warning: invalid marked content and clip nesting
Segmentation fault (core dumped)
```
this is the same evince behavior when left clicking on the "none existent local external link":
![image](https://github.com/user-attachments/assets/b44d6240-f7b1-4b79-96a9-d88a31f9f2da)

Guessing this is somewhat related to #1199.

Let me know if you need some more information.

Best regards

**Comment by ahrm** [comment]
Can you email me the pdf?

**Comment by EdvardSire** [comment]
@ahrm sent!

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/c4e38590605df714b380f1159d5c44dfa218d451.

**Comment by EdvardSire** [comment]
Nice! Segfault is fixed.

When left clicking the relevant link i now get: 
![image](https://github.com/user-attachments/assets/a7437c37-a55a-4de1-81a1-bc6bf2b9104e)

The popup window makes a lot of sense, but the sioyek viewer has turned black with red text which reads "Document /home/user/data/pdf/book/sensorfusion.pdf". This doesn't make sense since it's the path where the original pdf was on disk.

**Comment by ahrm** [comment]
You can press backspace to go back to the previous location.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/e30f5b8279444bf4ca5b731a5987fcab88e71598.

**Comment by EdvardSire** [comment]
Now i get:
![image](https://github.com/user-attachments/assets/ac651510-0b61-4145-a9a1-7c7e8132d47e)

Both the popup window and the sioyek viewer "references" the same non existent link.

**Comment by ahrm** [comment]
This is the intended behaviour.

**Comment by EdvardSire** [comment]
I totally agree now, makes sense!
Thank you for the fast responses.
