### ISSUE TITLE
Option for closing tab and circling among opened tabs?

### ISSUE THREAD

**Issue by 1andro1** [ahrm/sioyek#1245]
Hello,

would it be possible to have a command for closing tab and circling among opened tabs?

Best Regards,
Adriyan

**Comment by ahrm** [comment]
You can close a tab by pressing the `delete` key in `goto_tabs` menu. What do you mean by "circling"?

**Comment by 1andro1** [comment]
Something like ctrl+tab in Windows. By pressing a shortcut person can switch between opened documents/tabs. Maybe the word circle is not correct. 

Now, when I gave it a second though, I think using goto_tab is enough.

Many Thanks for your answer!

Best Regards,
Adriyan

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/be1324cae9b466b87b4faff2fad075eedd67397e.

**Comment by 1andro1** [comment]
Many Thanks!

**Comment by michaelfortunato** [comment]
Is it possible to bind another key to remove documents in the `goto_tabs` menu besides `del`?  Thanks!
