### ISSUE TITLE
Stragne behaviour in two page document when moving next/previous page

### ISSUE THREAD

**Issue by 1andro1** [ahrm/sioyek#1250]
Hello,

In case of two page mode and moving next/previous page by keyboard, the change of the pages is sporadically. Please see the attached video for more information. In single page mode everything is ok.

Best Regards

https://github.com/user-attachments/assets/11368c54-ec5b-4738-bd32-1936bb6b5a16

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/6a96f9c31ebdf07e5e67fcdd524dca4165c981bb.
