### ISSUE TITLE
Possible to scroll with different keys (in table of contents for example)?

### ISSUE THREAD

**Issue by KasselMarc** [ahrm/sioyek#1251]
Would it be possible to add the option to scroll up and down in the table of contents using `<C-u>` and `<C-d>` respectively?

**Comment by ahrm** [comment]
It is already possible in the development branch (see https://github.com/ahrm/sioyek/issues/1231).

**Comment by KasselMarc** [comment]
> It is already possible in the development branch (see #1231).

I'm sorry, thanks for the quick response!
