### ISSUE TITLE
[regression] Command fuzzy search broken in v3

### ISSUE THREAD

**Issue by KorigamiK** [ahrm/sioyek#1252]
In the v2 version, you can search for something like this and get a result of a lot of commands that match, but v3 just cant match all those commands

| Old    | New |
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/df8abc12-3614-4ee8-aafa-6288df2ed16f)  | ![image](https://github.com/user-attachments/assets/c2404fce-ef71-4468-bd1e-f274dd081530)    |

**Comment by ahrm** [comment]
Now we don't include `setconfig_` command by default because they pollute the search commands. If you want to search them you need to enter the `setconfig_` prefix or alternatively the `=` shortcut.
