### ISSUE TITLE
no matching function for call to 'invokeMethod'

### ISSUE THREAD

**Issue by hwangy** [ahrm/sioyek#1256]
Hey there, I'm trying to build the Mac app from source, in the development branch. I've run,

```
brew install qt@5 freeglut mesa harfbuzz
brew link qt5 --force
git clone --recursive -b development https://github.com/ahrm/sioyek
cd sioyek
chmod +x build_mac.sh
./build_mac.sh
```

But I'm seeing the error,
```
pdf_viewer/touchui/TouchDrawControls.cpp:149:5: error: no matching function for call to 'invokeMethod'
    QMetaObject::invokeMethod(quick_widget->rootObject(), "on_scratchpad_mode_change", QVariant::fromValue(mode));
    ^~~~~~~~~~~~~~~~~~~~~~~~~
```

Any ideas on why this error is occurring? I'm running this on an M1 mac, on OS 14.4.1.

**Comment by ahrm** [comment]
We need qt6.7+ for the development branch. It does not work with qt5.

**Comment by hwangy** [comment]
Thanks! That error no longer occurs. Now I'm seeing an error like,
```
Undefined symbols for architecture arm64:
  "QArrayData::deallocate(QArrayData*, unsigned long, unsigned long)", referenced from:
      TouchSlider::TouchSlider(int, int, int, QWidget*) in TouchSlider.o
      TouchSlider::TouchSlider(int, int, int, QWidget*) in TouchSlider.o
      TouchSlider::TouchSlider(int, int, int, QWidget*) in TouchSlider.o
      TouchSlider::TouchSlider(int, int, int, QWidget*) in TouchSlider.o
      QString::~QString() in TouchSlider.o
      TouchCheckbox::TouchCheckbox(QString, bool, QWidget*) in TouchCheckbox.o
      TouchCheckbox::TouchCheckbox(QString, bool, QWidget*) in TouchCheckbox.o
      TouchCheckbox::TouchCheckbox(QString, bool, QWidget*) in TouchCheckbox.o
```
From [this website](https://www.qt.io/blog/qt-on-apple-silicon), it seems maybe arm64 needs to be targeted directly (since I'm on Apple Silicon), so I tried adding the argument
``QMAKE_APPLE_DEVICE_ARCHS = arm64``
to pdf_viewer_build_config.pro in the "mac" section. This removed this error and the build seemingly succeeded, except there were several messages like:
```
ERROR: Cannot resolve rpath "@rpath/QtGui.framework/Versions/A/QtGui"
ERROR:  using QList("/Users/yeongwoohwang/Documents/software/sioyek/build/lib")
```
at the end of the build process. It successfully generated a `sioyek-release-mac.zip`, containing a sioyek app and dmg, but both of these crash when I attempt to open the app.

**Comment by ahrm** [comment]
I don't have a mac so I can't help you much, maybe others can help? But the mac version surely can be built for the arm64 architrecture there are experimental builds available here: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0. You can see the github action that is used to build those in the .github folder.

**Comment by hwangy** [comment]
I see. When I try to open the app in the the mac-arm file in the link you provided, I see a popup that says "sioyek is damaged and can't be opened. You should move it to the Trash," so there seems to be something wrong with that version as well.

**Comment by ahrm** [comment]
No, this is a new security feature on mac. See https://github.com/ahrm/sioyek/discussions/1156#discussioncomment-10818199.

**Comment by hwangy** [comment]
That worked! Thanks for your help!
