### ISSUE TITLE
Sorting Highlights in a double column pdf

### ISSUE THREAD

**Issue by usernameduck** [ahrm/sioyek#1258]
Hello, right now i am using a pdf with double column. The highlights (gh) is being rendered by location and this is messing up the order (it is considering parallel lines in 2 columns as same line). 
>> Similar to "sort_bookmarks_by_location 0" is there a "sort_highlights_by_location 0" ? , or is there any other solution for multi column pdf to show highlights in proper order.

**Comment by ahrm** [comment]
I can fix this but it would add drastic performance penalty to sorting the highlights (instead of just comparing two numbers now we would have to load an entire PDF page and detect the ordering based on that). I don't think benefit is worth the performance penalty at all, for that reason I won't fix this.

**Comment by usernameduck** [comment]
Hii @ahrm , why not add a partial solution. As most of the times we add highlight from as we read - 

Simple solution - we just need to use  be sort_highlights_by_time 1. This is by default in (gH), but disabled in individual pdf(gh).

Another solution - applying 2 sorts(might cause performance issue) - "sort_highlights_by_time_and_page 1".  - the first sort shows highlights based on page number, then sort highlights based on time. 

I am reading pdf's with more than 5+ columns in a page, I'd be really grateful if you can give it a thought. I'd understand if it is difficult. Really grateful for the app.

**Comment by ahrm** [comment]
Added a `sort_highlights_by_location` config in https://github.com/ahrm/sioyek/commit/e555b4d14fa0ebbe6feb148caf186535ceb3e7bc. You can disable in like so:

```
sort_highlights_by_location 0
```
