### ISSUE TITLE
Inconsistency in highlight colors in other PDF viewers

### ISSUE THREAD

**Issue by hwangy** [ahrm/sioyek#1259]
There seems to be some weird inconsistency in the highlight colors when I view the embedded pdf in other PDF viewers. For instance, if I highlight something with "Forest" (e.g. ``highlight_color_f	0.00 0.36 0.19'') which corresponds to approximately to hex code #005c30, It shows up instead as #BFFFE0, which has percent values (74.9, 100, 87.8). Visually, this looks like:

In Sioyek:
![image](https://github.com/user-attachments/assets/d9896aba-82af-4b53-a297-6bc69c6ed938)

In (MacOS) Preview, and PDF Expert
![image](https://github.com/user-attachments/assets/52ece7a2-2c97-4d49-8532-f657d399bf15)

Any idea why these might be inconsistent?

**Comment by ahrm** [comment]
Maybe there is a different in how the PDF engines render the highlights. How does it look in another mupdf-based PDF viewer (like mupdf itself)?

**Comment by hwangy** [comment]
Same issue, I think. I'm using the mupdf webviewer at https://casper.mupdf.com/wasm/demo. The area looks like,

![image](https://github.com/user-attachments/assets/31084b74-1d6c-49fe-847f-87416bc6052f)

**Comment by ahrm** [comment]
Can you share the pdf here?

**Comment by hwangy** [comment]
Here you go!

[test page 86.pdf](https://github.com/user-attachments/files/18136149/test.page.86.pdf)

**Comment by hwangy** [comment]
btw, the _reverse_ direction seems fine. If I create a highlight in a different PDF viewer, the color is preserved when I open it in Sioyek.

**Comment by ahrm** [comment]
It looks the same in sioyek vs other PDF viewers for me. Maybe you have a sioyek highlight on top of the embedded highlight in your document?

**Comment by hwangy** [comment]
If I open the PDF I sent in Sioyek, it looks the same (e.g. with an embedded highlight). The problem is that the highlights I create _in_ Sioyek (via some color code in the prefs_user.config) are not representative of the color that shows up after the fact.

**Comment by ahrm** [comment]
Oh that's because sioyek uses a completely different rendering method than the embedded PDF highlights. We do try to make them look as similar as possible but there will always be differences.

**Comment by hwangy** [comment]
That makes sense! Is there someway to map between the RGB percent values set in `prefs_user.config' and the RGB values that will show up in other PDF readers? I'd like to make it consistent with the highlights I create in Zotero (which is how I manage my papers), but currently I can't get the colors to match up.

**Comment by ahrm** [comment]
There is no way to do that. We do lighten the colors before embedding them in the PDF file because otherwise some highlights would look very dark and bad. See this part in code: https://github.com/ahrm/sioyek/blob/a6ec43dfd2a3a75c0d1f7ede7121f06ed5b83451/pdf_viewer/document.cpp#L2258 .

**Comment by hwangy** [comment]
Do you know how lighten_color is implemented? Or what library this call comes from?

**Comment by ahrm** [comment]
It is defined in utils.cpp.

**Comment by ahrm** [comment]
Added a `lighten_colors_when_embedding_annotations` config in https://github.com/ahrm/sioyek/commit/bab683c46f92421427f505377ff853d2a1905200 in the development branch.

**Comment by hwangy** [comment]
This is great, thank you for the addition!
