### ISSUE TITLE
Strange behavior of goto_end

### ISSUE THREAD

**Issue by duguyipiao** [ahrm/sioyek#1260]
Today, I encounter a strange behavior of `goto_end`. I have the custom keybinding
```bash
goto_end;goto_bottom_of_page G
```
It used to work perfectly, but now instead of going to the bottom of **last** page, it goes to the bottom of the **first** page.
The command `goto_end` itself however works normally.

I'm in the latest development branch.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/fd06141450f0ad4cdac353f643e7e2cd535305ca.
