### ISSUE TITLE
Highlights too dark and overly saturate

### ISSUE THREAD

**Issue by Marc0sGabriel** [ahrm/sioyek#1261]
I'm using the default config of catppuccin mocha theme but the colors don't match with their screenshots for some reason.
I am not sure what happened, but everything was working correctly before. I did not modify the prefs_user.conf file after adding the theme. However, after updating Sioyek, the highlights broke. Regardless of the color theme I use, the highlights now appear very dark and overly saturated.

In Sioyek:
<img  src="https://github.com/user-attachments/assets/9ff6a6a2-8105-4588-8d79-c379211c97f3" width="500"/>

In catppuccin screenshot:
<img src="https://github.com/user-attachments/assets/5012e733-602f-4565-b17a-1ad95971acc7" width="400"/>

My current config:
```
# === CATPPUCCIN MOCHA === #
background_color           #1e1e2e

text_highlight_color       #f9e2af
visual_mark_color          #7f849c

search_highlight_color     #f9e2af
link_highlight_color       #89b4fa
synctex_highlight_color    #a6e3a1

highlight_color_a          #f9e2af
highlight_color_b          #a6e3a1
highlight_color_c          #89dceb
highlight_color_d          #eba0ac
highlight_color_e          #cba6f7
highlight_color_f          #f38ba8
highlight_color_g          #f9e2af


custom_background_color    #1e1e2e
custom_text_color          #cdd6f4

ui_text_color                #cdd6f4
ui_background_color          #313244
ui_selected_text_color       #cdd6f4
ui_selected_background_color #585b70
```

**Comment by ahrm** [comment]
We have an `adjust_annotation_colors_for_dark_mode` config now (enabled by default). Does disabling it help?

**Comment by Marc0sGabriel** [comment]
Yeah I tried it right now and that's solved my problem. Sorry for taking a long time to reply.
Thanks so much

<img src="https://github.com/user-attachments/assets/a28bc759-1b08-4135-8032-ce4d75988db0" width="400"/>
