### ISSUE TITLE
Mac os arm alpha version corrupted

### ISSUE THREAD

**Issue by norepository** [ahrm/sioyek#1265]
Have the following error when trying to run the mac os arm alpha version
![Finder_2024-12-27_17-53-53@2x](https://github.com/user-attachments/assets/2713b665-5942-4962-a1c8-af32f46e3862)

**Comment by chris-aeviator** [comment]
same here

**Comment by ahrm** [comment]
See https://github.com/ahrm/sioyek/discussions/1156#discussioncomment-10818199.
