### ISSUE TITLE
[request] smooth scrolling

### ISSUE THREAD

**Issue by KorigamiK** [ahrm/sioyek#1266]
Using j/k or arrow keys or even the scroll wheel is kind of choppy and doesn't smoothly move the page.
Similar to how Okular for example handles the school movement behaviour, 

a smooth scrolling feature would be amazing

**Comment by ahrm** [comment]
This is already added in the development branch (`move_down_smooth` and `move_up_smooth` commands).

**Comment by KorigamiK** [comment]
This is nice! Although is there a way to not focus the sioyek windows when executing the command from the command line interface?

**Comment by ahrm** [comment]
The `--nofocus` command line option.

**Comment by KorigamiK** [comment]
Thanks!

**Comment by Bumblebee00** [comment]
when will this be added to main branch?

**Comment by ahrm** [comment]
I don't know, there are experimental builds of the development branch here if you want to try it out: https://github.com/ahrm/sioyek/releases/tag/sioyek3-alpha0.
