### ISSUE TITLE
Firefox-style highlighting of neurips urls/citations

### ISSUE THREAD

**Issue by stephen-huan** [ahrm/sioyek#1268]
The [neurips style files](http://media.neurips.cc/Conferences/NeurIPS2024/Styles.zip) use `hyperref` / `url` / `natbib`.

```tex
\documentclass{article}
\usepackage{hyperref}
\usepackage{url}
\usepackage{natbib}

\begin{document}

\url{https://sioyek.info/}
\cite{jax2018github}

\bibliographystyle{unsrt}
\bibliography{references}

\end{document}
```

The file `references.bib` is as follows.

```bibtex
@software{jax2018github,
  author = {James Bradbury and Roy Frostig and Peter Hawkins and Matthew James Johnson and Chris Leary and Dougal Maclaurin and George Necula and Adam Paszke and Jake Vander{P}las and Skye Wanderman-{M}ilne and Qiao Zhang},
  title = {{JAX}: composable transformations of {P}ython+{N}um{P}y programs},
  url = {http://github.com/jax-ml/jax},
  version = {0.3.13},
  year = {2018},
}
```

Sioyek renders this as unhighlighted text, but firefox renders the urls with a blue border and the citations with a green border. Could this be supported? (It seems this is a firefox-specific thing, as neither chromium nor zathura do highlights, but in my opinion it makes it easier to read. Also, there has to be some metadata in the pdf for firefox to tell links and citations apart.)

![image](https://github.com/user-attachments/assets/549fd5fa-0241-4cbf-a395-9583d46ec1c9)

![image](https://github.com/user-attachments/assets/479093ca-0ab1-4e03-9bbc-68f2be9c21f4)

**Comment by ahrm** [comment]
This is outside my control, I just use the mupdf library to render PDF files, if there is an issue it should be reported to mupdf devs.

**Comment by stephen-huan** [comment]
I see, thanks!
