### ISSUE TITLE
Binding executable commands

### ISSUE THREAD

**Issue by VolkovIlia** [ahrm/sioyek#127]
> > > Any examples for binding it in config?
> > 
> > 
> > ```
> > execute     <C-u>
> > ```
> 
> I want to map `notify-send \"Name of file is %2\"`, how to do that?

Oh you can't currently do that, you have to type the name of the command every time. Adding ability to bind a specific command is a good idea which I may implement.

_Originally posted by @ahrm in https://github.com/ahrm/sioyek/issues/117#issuecomment-1033954004_

**Comment by ahrm** [comment]
Added in f6248c2c51cc1f8eb3ff54e390decb3a807d84f1. Here is how to configure it:
First, you need to bind a key for `execute_predefine_command` in your `keys_user.config`. For example:
```
execute_predefined_command     <C-e>
```
There can be 26 predefine command (corresponding to letters a-z). In order to define the command you should add the following to your `prefs_user.config`:
```
execute_command_a	some_command %1 %2
execute_command_x	another_command %2
```
This now if you enter `<C-e>a` we execute the first command and if you enter `<C-e>x` we execute the second command.

**Comment by VolkovIlia** [comment]
`execute_command_a "execute \"notify_send %1\""` not working
`execute_command_a execute notify_send %1` not working
`execute_command_a notify_send %1` not working
`execute_command_a $notify_send test` not working
`execute_command_a notify_send %2` not working


`QString::arg: 1 argument(s) missing in %2
QProcess: Destroyed while process ("notify_send") is still running.`

**Comment by VolkovIlia** [comment]
Also It is working idea to bind commands to special command `execute_command` but it is not ergonomic and  hackable. In Zathura I have 4-5 scripts that I suppose working in one key push, there I should to do two key pushines. Also I don't understand how to make scripts with this way

My map to zathura is 
```
map <C-o> feedkeys ":exec zathura-annotate $FILE<Return>"
map <C-b> feedkeys ":exec zathura-add-papers $FILE<Return> q<Return>"
map <C-y> feedkeys ":exec sh -c \"echo $FILE | xclip -i -sel clip\"<Return>"
map <C-Z> feedkeys ":exec zotadd % <Return>"
```

How to do that in `Sioyek`?

**Comment by ahrm** [comment]
This feature is pretty fragile and definitely not as well-developed as zathura's scripting system. If you want to run a script, I recommend first write the script into a `.sh` file and call the script.
Also this

```
execute_command_a notify_send "%1"
```
works for me on windows, I have not yet tested this feature on linux, maybe there is an issue on linux. What happens when you run this? Does it crash?

**Comment by VolkovIlia** [comment]
> This feature is pretty fragile and definitely not as well-developed as zathura's scripting system. If you want to run a script, I recommend first write the script into a `.sh` file and call the script. Also this
> 
> ```
> execute_command_a notify_send "%1"
> ```
> 
> works for me on windows, I have not yet tested this feature on linux, maybe there is an issue on linux. What happens when you run this? Does it crash?

`execute_command_a notify_send "%1"`

Terminal output when I close program:
```
QString::arg: 1 argument(s) missing in "%1"
QString::arg: 1 argument(s) missing in "%1"
QProcess: Destroyed while process ("notify_send") is still running.
```

Just nothing happen... Nothing crush.

**Comment by VolkovIlia** [comment]
Any news?)

**Comment by ahrm** [comment]
> Any news?)

Is it fixed in a71e393bfba242e044f9443c8c5e9de60701bb6b?

**Comment by VolkovIlia** [comment]
Command 
```
execute_command_a notify-send "%1"
```

Now working!) Thx

But still have some messages 

```
QString::arg: 1 argument(s) missing in "%1"
QString::arg: 1 argument(s) missing in "%1"
```

**Comment by ahrm** [comment]
That's not a problem, it simply means we have not used all possible arguments.

**Comment by brian6932** [comment]
Is there a way to have a command run on program startup automatically (without a bind)? I want to open with `fit_to_page_height_smart` by default, and I don't see how to do that in the config documentation currently.
