### ISSUE TITLE
use ascii lables for opening links in documents instead of numbers

### ISSUE THREAD

**Issue by KorigamiK** [ahrm/sioyek#1276]
Typing out numbers is a bit annoying at times, would be better to use the 2 letter labels here as well
![image](https://github.com/user-attachments/assets/3583b355-4869-4b83-821a-db1457294dcd)

**Comment by ahrm** [comment]
We have an `alphabetic_link_tags` config for that.

**Comment by KorigamiK** [comment]
> We have an `alphabetic_link_tags` config for that.

That's great, although I'd suggest making this the default instead
