### ISSUE TITLE
Changing appearance of status bar?

### ISSUE THREAD

**Issue by ma-con** [ahrm/sioyek#129]
Hi, 
I just found your program and it really is super useful, thanks for that!
I was just wondering, if there is an option to change the appearance of the status bar (if that's the correct name?) showing page numbers and so on. I could not find any configuration option for this. 
Mainly changing background and text color would be really useful to make it blend in with custom colored PDFs.
Also, from my testing, the font_size option only influences the command menu but, right?

And last but not least: it seems to me, that sometimes when I change the custom_colors in the config file, they are applied immediately, but other times I need to close and reopen sioyek in order to get it to recognize the changed colors, is there any way to make it it always recognize changed colors, or maybe a command to reload the config?

Thanks!

**Comment by ahrm** [comment]
Added in ce6f424a33fbcdcf9d70d39ca3354f6c985e1262. You can configure the background color, text color and font size of status bar like so:
```
status_bar_color    0 0 0
status_bar_text_color    1 1 1
status_bar_font_size     15
```

> And last but not least: it seems to me, that sometimes when I change the custom_colors in the config file, they are applied immediately, but other times I need to close and reopen sioyek in order to get it to recognize the changed colors, is there any way to make it it always recognize changed colors, or maybe a command to reload the config?

I assume you are using linux. We use `QFileSystemWatcher` to notify file system changes. For some reason on linux sometimes this stops working after the first time a file is changed. I don't exactly know why but I think it is a Qt bug.

**Comment by ma-con** [comment]
Amazing, that was fast! Thanks a lot!

> I assume you are using linux. We use QFileSystemWatcher to notify file system changes. For some reason on linux sometimes this stops working after the first time a file is changed. I don't exactly know why but I think it is a Qt bug.

Correct, this was on Linux. On my MacBook the changes are always applied immediately.

Btw: Do you have any plans to allow to view multiple pages horizontally like for example zathura does (or is this already possible and I missed it)? This would be quite useful on widescreen monitors... I an also open a different issue for that if you prefer.

**Comment by ma-con** [comment]
All right, thanks for the pointer. I searched the issues, but apparently used the wrong terms. I'll close this issue then, as it is implemented, I hope thats ok with you.
Thanks again!

**Comment by ma-con** [comment]
Just a small update regarding changing and live reloading the config file on Linux:
I was curios and googled this problem, and it seems that this is not really a bug in QT but that many editors on Linux don't really change a file when saving but instead delete the original one and replace it with the changed one. Apparently this is not detected by `QFileSystemWatcher`.
You can test this in vim, which on default seems to delete and overwrite files on save, so live reload works only one time. Closing and reopening sioyek and setting `set backupcopy=yes` in vim will make live reloading work all the time.

(I found the solution in this thread https://stackoverflow.com/questions/18300376/qt-qfilesystemwatcher-signal-filechanged-gets-emited-only-once and it seems that there is also a workaround to make live reloading work on deleting and replacing config files.)

**Comment by ahrm** [comment]
Thanks for the info. I added a fix in b89797614e76eead869b15b2fa0a93d9aad00fe2. I haven't tested it on a linux system though.

**Comment by ma-con** [comment]
From my (admittedly limited) testing on linux, this seems to complete fix the issue! Thanks!

**Comment by yuuuxt** [comment]
It would be good to also have the font family customizable. 
The default font on Windows doesn't look nice (also the font of status bar and the font of  `:` menu are not consistent), but haven't found a way to adjust them.
