### ISSUE TITLE
How to open two or more documents in different sioyek windows

### ISSUE THREAD

**Issue by VolkovIlia** [ahrm/sioyek#130]
I am trying to open some file with command `sioyek file1.pdf`
After that I opened the second one with command `sioyek file2.pdf` but it replace the `file1.pdf` in `sioyek` window. 

How to open more then one form terminal?

**Comment by ahrm** [comment]
Use `sioyek file2.pdf --new-instance`.

**Comment by VolkovIlia** [comment]
Thank you!
