### ISSUE TITLE
Remembering windows sizes and positions

### ISSUE THREAD

**Issue by Talinf** [ahrm/sioyek#133]
Hi, very good program.
I'm using Windows 8.1
I have two monitors, main one is on the left. When opening a portal, second window is not visible if multi monitor option is not set. I have to use the move windows function to reposition it.
If I enabled multi-monitor support, the portal window is under the main document window. If I use the resize window button, the window disappear and I need to use the move windows function again.
I can move my main window to the left screen and keep the portal window on the right. But if I close the program and reopen it, the window's positions are reset.
Would it be possible to remember the windows size and position so that the two windows (main and portal) reopen with the same size and position as the last time they were opened? Maybe with a user option?
Thanks

**Comment by ahrm** [comment]
Added the ability to customize the position and size of windows in df3996502ca4fd1d5928a4586438138b68ed47f8. You have to add something like this to your `prefs_user.config`:
```
main_window_size    867 913
main_window_move     109 68
helper_window_size    644 704
helper_window_move     1114 202
```

You can execute the `copy_window_size_config` command (by pressing `:` and typing `copy_window_size_config`) which copies the config corresponding to your current window arrangement. But you have to manually paste it to your `prefs_user.config`.

**Comment by Talinf** [comment]
Thanks for your prompt answer. I will try to setup a VM to build a version with the modifications.

**Comment by ahrm** [comment]
There is an experimental build of this version here:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.137

**Comment by efficacy** [comment]
Does this work in the current version (April 3, 2022)? I just followed the instructions above but when I restarted Sioyek it was full-screen again.
I am getting really sick of having to resize the huge Sioyek window every time so I can see the app ( https://github.com/Zettlr/Zettlr ) that I use to manage my notes. Almost every other app I use remembers its window size and location between runs.
Please consider a setting for this!
I'm using WIndows 10 with a single monitor, if that helps.

**Comment by ahrm** [comment]
> Does this work in the current version (April 3, 2022)? I just followed the instructions above but when I restarted Sioyek it was full-screen again. I am getting really sick of having to resize the huge Sioyek window every time so I can see the app ( https://github.com/Zettlr/Zettlr ) that I use to manage my notes. Almost every other app I use remembers its window size and location between runs. Please consider a setting for this! I'm using WIndows 10 with a single monitor, if that helps.

If you are using a single window (rather than two monitor setup), there is a separate config like this:
```
single_main_window_size    500 500
single_main_window_move     0 0

```

**Comment by efficacy** [comment]
Thanks for that. It now does what I want 😄 
Would it be possible to also include those values when doing a `copy_window_size_config`? Should that be a separate issue?

**Comment by ahrm** [comment]
> Thanks for that. It now does what I want 😄 Would it be possible to also include those values when doing a `copy_window_size_config`? Should that be a separate issue?

Yeah I wanted to implement that but I forgot about it. Please add an issue so I don't forget again :D .
