### ISSUE TITLE
Build fails MacOS 12.2.1 (Monterey)

### ISSUE THREAD

**Issue by ns740** [ahrm/sioyek#134]
MacOS `12.2.1`
Qt: `qt@5: stable 5.15.2`
XCode: `Xcode 13.2.1  Build version 13C100`
cloned commit `22c256186cc`
`./build_mac_sh` fails with 
```
Info: creating stash file /Users/ns/sioyek/.qmake.stash
Project ERROR: Unknown module(s) in QT: openglextensions
make: *** No targets specified and no makefile found.  Stop.
mv: rename sioyek.app to build/sioyek.app: No such file or directory
```
is `openglextensions` something i need to install or configure for the build to work?

[edit] the 1.1.0 release version installed from .zip seems to work :-)

**Comment by ahrm** [comment]
See https://github.com/ahrm/sioyek/issues/41.

**Comment by ns740** [comment]
> See #41.
yes that fixed it - thanks 
this looks to be a great replacement for zathura/skim for previewing LaTex documents in vimtex.
