### ISSUE TITLE
User keyboard shortcuts with Control key don't work on MacOS

### ISSUE THREAD

**Issue by hovnatan** [ahrm/sioyek#135]
User keyboard shortcuts with Control key don't work on MacOS. For example, <C-h> is not recognized in Mac OS Monterey.

**Comment by ahrm** [comment]
I think you have to use command key instead of control key. Don't they work with command key?

**Comment by hovnatan** [comment]
No it doesn't work with Command key -- `<C-j>` is not recognized.

**Comment by ahrm** [comment]
Maybe a2371b43dd0915ffd8c549383fe589c4c2021bd5 helps? I don't have access to a Mac machine so I have not been able to test it myself.

**Comment by hovnatan** [comment]
You are right, Command key is recognized in `<C-j>` type of shortcuts. Is there a way to use Ctrl key in Mac?

**Comment by hovnatan** [comment]
I just build using using git clone and now Ctrl shortcuts work on Mac OS. Before I was using latest release on Github.
