### ISSUE TITLE
Scrolling with touchpad on MacBook Pro extremely fast

### ISSUE THREAD

**Issue by hovnatan** [ahrm/sioyek#136]
Scrolling with touchpad on MacBook Pro extremely fast. Small touches with two fingers on MacBook Pro 14 (Monterey) result in huge changes in position.

**Comment by jonnyyu** [comment]
same with magic mouse.

**Comment by ahrm** [comment]
You can set `vertical_move_amount` in your `prefs.config` to a lower value.

**Comment by hovnatan** [comment]
But that will affect other `move_` commands, which are fine. The touchpad scrolling is too fast.

**Comment by ahrm** [comment]
Added a `touchpad_sensitivity` option in 0f8ecc6bf15fe1b2677d47b02ea28c5e0e90f68c which allows you to customize touchpad (and scroll wheel) sensitivity.
```
touchpad_sensitivity  0.1
```

**Comment by fnune** [comment]
https://user-images.githubusercontent.com/16181067/155016328-3dfde958-8ce2-4ab7-897d-19b696a16a63.mp4

Does `touchpad_sensitivity` also affect the speed of zooming in and out? It's too fast for me (see the video where I'm trying to get the text to match the size of the screen).

**Comment by hovnatan** [comment]
Ok thanks, it works!

**Comment by nickdvlpr** [comment]
Is there a way to set the scrolling behavior to be the default on MacOS? For example, when scrolling a website in a browser or a PDF in Preview, the touchpad allows for subtle, slow movements and faster flicks with corresponding scroll speeds. Right now, sioyek essentially can only scroll at a single speed and it is noticeably jarring.
