### ISSUE TITLE
Page separator

### ISSUE THREAD

**Issue by dervist** [ahrm/sioyek#137]
Is it possible to set page separation, so that we can see where one page ends and the next one begins? If yes, how is it done, and if no, please consider this a feature request. 

Currently, the program shows an endless canvas without any visual indication where a page ends – basically, the bottom margin of current page is invisibly glued to the top margin of the following page. An option to add a horizontal line between two pages as a means to separate them visually would be most welcome.

Version: Sioyek 1.1.0 for LInux

**Comment by ahrm** [comment]
Added a page separator option in 5a10bcdfaf64660f416cae77edbe30f714794bb7:

```
page_separator_width     1
page_separator_color	0.9 0.9 0.9
```

**Comment by AlexMV12** [comment]
I'd like to add something to this.

It looks like `page_separator_width` does NOT separate the pages; instead, it just draw ON the pages.
For instance, in the following, `page_separator_width` has been set to `1`:
![immagine](https://user-images.githubusercontent.com/36054651/196180897-fd96af71-755a-4cae-94ae-4f76a520e6a2.png)

Instead, in the following, `page_separator_width` has been set to `150`:
![immagine](https://user-images.githubusercontent.com/36054651/196181062-b4771305-8716-42b9-8afb-c11342adc5bc.png)

You can see that a part of the paper's pages has been hidden.

In some circustamances, this can be annoying (e.g., LaTeX beamers - where part of the footer gets hidden).
