### ISSUE TITLE
Interest to package this as Flatpak?

### ISSUE THREAD

**Issue by kevinsmia1939** [ahrm/sioyek#14]
Hi,

Would you be interest in Sioyek package as Flatpak.
I am trying to build it as Flatpak, but got the error
```
make: g++-9: No such file or directory
make: *** [Makefile:1037: book.o] Error 127
Error: module Sioyek: Child process exited with code 2
```

I think this is because flatpak use gcc 10.2.

**Comment by ahrm** [comment]
> Hi,
> 
> Would you be interest in Sioyek package as Flatpak.
> I am trying to build it as Flatpak, but got the error
> 
> ```
> make: g++-9: No such file or directory
> make: *** [Makefile:1037: book.o] Error 127
> Error: module Sioyek: Child process exited with code 2
> ```
> 
> I think this is because flatpak use gcc 10.2.

You can remove these lines from `pdf_viewer_build_config.pro`:

```
    QMAKE_CC = gcc-9
    QMAKE_CXX = g++-9
```

**Comment by kevinsmia1939** [comment]
I am trying to put the compiled file into there file system hierarchy. I know that I need to put sioyek to /bin, but what about the *.o files and *.config?

**Comment by ahrm** [comment]
> I am trying to put the compiled files into their file system hierarchy. I know that I need to put sioyek to /bin, but what about the *.o files and *.config?

*.o files are temporary and should not be placed anywhere. `prefs.config`, `keys.config` and the `shaders` folder should be placed next to the executable in `bin`. I don't know anything about flatpaks so I can't help you much, but another user managed to get a flatpak working. Maybe their post can help you : https://github.com/ahrm/sioyek/issues/1#issuecomment-888259726 .

**Comment by ahrm** [comment]
A flatpak is available thanks to @nbenitez. https://flathub.org/apps/details/com.github.ahrm.sioyek .
