### ISSUE TITLE
Tabbed mode

### ISSUE THREAD

**Issue by hovnatan** [ahrm/sioyek#140]
Is it possible to add tabbed mode for multiple file viewing to easily switch between files, like with `<C-Tab>?

**Comment by ahrm** [comment]
I tend to think of the recent documents menu (`<S-o>`) as a searchable list of tabs. What functionality do you want from tabs that `<S-o>` doesn't provide?

**Comment by hovnatan** [comment]
Kind of like `<Alt-Tab>` of Windows or Mac OS window manager, where you go the recent windows easily by a single keyboard  shortcut.

**Comment by ahrm** [comment]
Added a `open_last_document` command in 1f89bdd2b4c0f643cb1dc483f24fdaa70f5548ba which allows you to quickly toggle between two documents which I think is the main use case for tabs. For more than two documents I think the current `<S-o>` menu is good enough. You can configure the new setting like so:
```
open_last_document <tab>
```

**Comment by hovnatan** [comment]
Thank you! Two more questions. Is there way configure `<S-o>` menu keyboard shortcuts, like arrows move around it. Is there a way to open 2 windows of Sioyek on Mac OS so that I can view 2 pdf on 2 different monitors?

**Comment by ahrm** [comment]
> Thank you! Two more questions. Is there way configure `<S-o>` menu keyboard shortcuts, like arrows move around it. Is there a way to open 2 windows of Sioyek on Mac OS so that I can view 2 pdf on 2 different monitors?

* Arrows should already work in the menu. Also `tab` and `shift+tab` should work in this menu.
* You can use `--new-instance` command line option to open a new instance of sioyek

**Comment by ahrm** [comment]
> No I meant using (as is customary in vim) `<C-n>` and `<C-p>` in the `<S-o>` menu to navigate around. Is that possible?

Added in d715cc0934104ed7e6d78d8a1fa94e63104ffe97.

**Comment by hovnatan** [comment]
Thanks!
