### ISSUE TITLE
Make window title the paper title

### ISSUE THREAD

**Issue by skjerns** [ahrm/sioyek#144]
Currently the window title is simply the full path of the PDF that is open, which will most likely be truncated to `c:/users/username/do[...]`, ie is not very informative, and not searchable with window name search with other programs (e.g. Wox.Launcher). 

![image](https://user-images.githubusercontent.com/14980558/155583319-022ec265-6476-45c6-9908-7496c5af284d.png)

Do you think it would be possible to display either the PDF title or something more recognizeable?

**Comment by ahrm** [comment]
Done in 4b253e9c1bc0176f2267f611352699e8f8a4f1c9.

**Comment by skjerns** [comment]
very cool, thanks!
