### ISSUE TITLE
Does Sioyek support this feature?🙏

### ISSUE THREAD

**Issue by ahmedfarrag17** [ahrm/sioyek#146]
Hello!
I am looking for a pdf viewer that shows internal hyperlinks in a second window in split view, and not the same opened one.

Example:
I have a large pdf file (textbook), on Page 1 there is an internal link that sends me to a specific page view (a specific portion of Page 100 let's say). But I want to keep Page 1 still opened while reading the content of the hyperlink (page 100). So is it possible that once I click on the link on page 1, the result (page 100) is shown in a new window in Split view? (So I can keep page 1 and 100 side by side to read them both). And after that I continue to read on the left side and when I find another link 🔗 I click on it and it is shown on the right side/window. Etc. Etc.

Is this possible? (If Yes, how?).
(If not, I am sorry for asking it, but do you know any available pdf viewer on Earth that does this?😭 i need it so so much!).

Thank you!

**Comment by Elaws** [comment]
Yes ! You may find what you want in portals or overview. Please read the official documentation about them :

- [portals](https://sioyek-documentation.readthedocs.io/en/latest/usage.html?highlight=portal#portals)
- [hover overview](https://sioyek-documentation.readthedocs.io/en/latest/usage.html?highlight=hover%20overview#overview-and-smartjump)
