### ISSUE TITLE
Idea: Total keyboard driven mode

### ISSUE THREAD

**Issue by VolkovIlia** [ahrm/sioyek#147]
Thanks for awesome soft, I switched to it from `zathura` and it is amazing. 

But can you add features for total keyboard driven functionality (or mouse free). 
Now key board driven features: link picking (`f`) and navigation, but can you add other stuff: smart jump, portals, highlights and select text for copy (visual-caret mode like in vim), etc?

**Comment by ahrm** [comment]
Unfortunately this is not possible. For example smart jump is not as "smart" as it sounds. It can have a lot of false positives and the reason it works is that the user does some of the work by clicking on something that is probably a reference (rather than a random piece of text or numbers).

Portals already can be made without mouse though (still needs mouse if you want to create it using a smart jump).

**Comment by VolkovIlia** [comment]
> Unfortunately this is not possible. For example smart jump is not as "smart" as it sounds. It can have a lot of false positives and the reason it works is that the user does some of the work by clicking on something that is probably a reference (rather than a random piece of text or numbers).
> 
> Portals already can be made without mouse though (still needs mouse if you want to create it using a smart jump).

I use smart jumps about 5% of my workflow... But 95 % of workflow is selecting text and highlighting it, is it also not possible?

**Comment by ahrm** [comment]
That is probably possible (not for scanned documents though). I may add it once I have some free time.

**Comment by ahrm** [comment]
I added it in 6f08fcd07d737be524a18c6387d146d4ee9f112c. It looks like this:

https://user-images.githubusercontent.com/6392321/161816240-0020b9ac-5955-44d0-a97f-17060cf68abc.mp4

The relevant commands are:
```
keyboard_select
keyboard_smart_jump
keyboard_overview
```

**Comment by ryanwwest** [comment]
This is really awesome and I use it frequently to be totally mouse-free. However, I still think a more vim-like visual mode could be better for some people. A few reasons:

1. The yellow letterboxes used to select a first (and possibly last) word cover up a lot of each word, decreasing visibility when rereading text to select. 
2. It also seems a bit unnecessary to need to look up two three-letter combinations when you already know the text you want to select. Many vim users (who seem to be a major audience for sioyek) are already familiar with navigation using vim's cursor by pressing `v` to enter visual mode then using keys like w/W/b/B/e/E/f/F etc. to quickly jump between the text and actively alter the selected portion of the text (before doing something with it like highlighting). Or something like `vi[` to select text within brackets. I don't think quick adjustments of the selected portion of text are possible without restarting `keyboard_select`.

Of course, this would probably require a lot of work and I think the current solution is a good option to have. But when I use the visual mark in the ruler mode that focuses on a specific line, I constantly think about how it's so close to being a single caret/character cursor that vim has and I can _almost_ navigate and select text similar to how I can with the Vimium Chrome Extension's 'caret' mode.

With a single-character cursor in the document, I could also see it being easier to jump to links (even when there are multiple on the same line) and likely for other commands too.

**Comment by agenbite** [comment]
Thanks for sioyek, it is my new pdf viewer of choice! :) I totally agree with @ryanwwest that a visual mode à la vim would be absolutely great.

Also, the video up there is apparently not working anymore and it took me a while to figure out how to use keyboard select.  Anyway, thanks!

**Comment by ahrm** [comment]
> Also, the video up there is apparently not working anymore and it took me a while to figure out how to use keyboard select. Anyway, thanks!

How do you mean? It should still work like the video above.

**Comment by agenbite** [comment]
> How do you mean? It should still work like the video above.

Hm, it might be me, but I tried in a couple browsers and devices and the video doesn't play...

**Comment by ahrm** [comment]
> Hm, it might be me, but I tried in a couple browsers and devices and the video doesn't play...

Aaah, I though you meant sioyek is not working like the video anymore.

**Comment by agenbite** [comment]
Sorry, I should have been clearer. :) Thanks again!

**Comment by BhargavManohar** [comment]
> That is probably possible (not for scanned documents though). I may add it once I have some free time.

Is it possible to highlight a scanned document with a rectangular select or something of the sort?

**Comment by ahrm** [comment]
Yes (in the development branch only). See this: https://github.com/ahrm/sioyek/issues/941#issuecomment-1912329714.

**Comment by rtviii** [comment]
+1 for @ryanwwest. visual caret mode would be a game changer.

**Comment by Kr1ngl3** [comment]
+1 for @ryanwwest
