### ISSUE TITLE
Sioyek Keeps crashing

### ISSUE THREAD

**Issue by Syenta** [ahrm/sioyek#148]
HI,

I downloaded the latest Windows portable version and it opened great, I ran through the tutorial and had a play with it.

Since that day Sioyek keeps crashing on opening.  I get either:

1. A black screen and then it closes down.
2. A black screen then white screen then it closes down
3. It open the last file opened then closes down.
4. It open the last file but on pressing any key it closes down.

I check the Task Manager and found multiple instances of PostGreSQL

My system has an Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz CPU, with 32GB of memory so not a slow system and the graphics card is a NVidea 2080. I would not expect an issue running Sioyek with this system.

I deleted the folder I had and downloaded a second copy, it opened fine but the second I press a button on my keyboard Sioyek crashes.

Hope this helps.

**Comment by ahrm** [comment]
Hmmm from this log it appears that sioyek was closed properly (becasue `closeEvent` is called). Are you sure this log corresponds to a run wich crashed?

**Comment by 1JunGu** [comment]
> Hmmm from this log it appears that sioyek was closed properly (becasue `closeEvent` is called). Are you sure this log corresponds to a run wich crashed?
 But the `sioyek.exe` installed from https://github.com/ahrm/sioyek/releases/tag/v1.1.0 couldn't open PDF file. But the app downloaded from  https://github.com/hexomancer/sioyek/releases/tag/v0.31.141 is ok. The attachment is open fault with `sioyek.exe`. And thanks lot for your reply and this amazing app.
![屏幕截图 2022-02-27 221026](https://user-images.githubusercontent.com/50906079/155885927-f2fdb340-7ec3-492f-b969-d20556a5ff3a.png)
.

**Comment by ahrm** [comment]
This is not a crash but it means that sioyek was not able to open its shaders folder. Another user had the same problem and it turned out it was because sioyek was installed in a location with non-ascii path (which appears to be your case too).

**Comment by 1JunGu** [comment]
> This is not a crash but it means that sioyek was not able to open its shaders folder. Another user had the same problem and it turned out it was because sioyek was installed in a location with non-ascii path (which appears to be your case too).

Ohhhhh! It worked! I installed the app in a proper location with non-ascii path. Thanks a lot!!
