### ISSUE TITLE
[Feature Request] snapshots with backlinks

### ISSUE THREAD

**Issue by aalexei** [ahrm/sioyek#151]
This is a really interesting project, thanks for developing it. A great feature I would like to see is being able to take a snapshot of a region on a page and have the clipboard hold an image of that region (at good resolution) together with metadata for the filename, page and location of the snapshot. 

This would let other devs write code to embed that image with a backlink to the pdf file and location. That would be awesome for a research notebook where you could clip snippets of research papers and have automatic links back to the original source for each snippet.

One encoding that could be used easily, or repurposed, would be a url like file:///path-to-file/filename?page=page-no&rect=10,78,40,10

where the rect is x,y,width,height as percentages of page size, or some other coordinate system.

**Comment by ahrm** [comment]
This can be added to the latest versions of sioyek as an extension: https://sioyek-documentation.readthedocs.io/en/latest/scripting.html
