### ISSUE TITLE
[Bug] Helper window's : Position not recovered after it has been snapped to the edge of screen (Proposed workaround)

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#152]
# Environment

Windows 10 (21H2)
Sioyek v1.1.0

# Description

I've just stumbled upon a weird behavior where the helper window will not go back to its original position after it was snapped to the edge of the screen (we need to snap it twice to the edge of screen for the issue to appear, as shown below).

Please see below an example :

![demoSioyek](https://user-images.githubusercontent.com/52013479/155856851-36de4553-564f-4267-b3cf-b00f834641ba.gif)

If on future versions of Sioyek we want to save windows positions (without the need to restart the app), this issue currently prevents it : when the user will snap the helper window to the edge of the screen, its position will not properly be recovered.

I will continue to investigate this issue, but your help will be greatly appreciated !

Thanks

**Comment by Elaws** [comment]
Mmm.. something very interesting that may help :

From the following observation :

1. *Helper window* will not recover its position after it has been snapped to the edge of a screen.
2. *Main window* is not concerned by that problem.
3. The difference between *Helper* and *Main* window is that *Helper* is the only window that get hidden.

So I made a little experiment, and noticed that when I prevent *Helper* window from being hidden, it can be successfully snapped and its position is recovered properly.

That's not a solution yet, but maybe it helps !

**Comment by Elaws** [comment]
I've finally found a workaround.

For a reason I don't know yet (bug in Qt ?), if a window is hidden (`hide()`) after being snapped to the edge of the screen, it won't recover its original position when using `show()`.

It seems we can circumvent this problem by moving and resizing the window a tiny bit before applying the real `move()` and `resize()`.

That is, by replacing in `MainWidget::apply_window_params_for_two_window_mode` (*l.2915* of *main_widget.cpp* as of bb571d01878b33bf53bf72b55b0b9dce394627c9) this (*l.2937*)  :

```c++
helper_window->move(helper_window_move[0], helper_window_move[1]);
helper_window->resize(helper_window_size[0], helper_window_size[1]);
helper_window->show();
```

by this :

```c++

// Without the 2 following lines, the move() and resize() after show() have no effect on Widget position if it was snapped before being hidden.
helper_window->move(helper_window_move[0]+1, helper_window_move[1]+1); 
helper_window->resize(helper_window_size[0]+1, helper_window_size[1]+1);

helper_window->show();

helper_window->move(helper_window_move[0], helper_window_move[1]);
helper_window->resize(helper_window_size[0], helper_window_size[1]);
```

**Comment by ahrm** [comment]
Should be fixed in 0d4a069dbc6aa9e5011ac95d5e0e63eacec29fcf.
I basically deleted all logic from `toggle_one_window` command and made it so that it just hides/shows the helper window. (Now `toggle_window_configuration` is responsible for possibly complex reconfigurations). I added to following code to handle `toggle_one_window` command which seems to work around the issue:
```
QPoint pos = helper_opengl_widget->pos();
QSize size = helper_opengl_widget->size();
helper_window->show();
helper_window->resize(size);
helper_window->move(pos);

```

**Comment by Elaws** [comment]
Hello @ahrm,

I can still reproduce the issue with 0d4a069dbc6aa9e5011ac95d5e0e63eacec29f . For now, I've only been able to solve it using the workaround described [above ](https://github.com/ahrm/sioyek/issues/152#issuecomment-1053089539).

It seems the following sequence is important.

1. Window is hidden.
2. Move and resize window a little (should be different from the final position/size I think, but maybe I'm wrong).
3. `show()`
4. Move and resize to final position/size.

**Comment by ahrm** [comment]
I think this issue should be fixed in the latest commits. Moreover, we now automatically save the last window configuration and restore it next time, so there is no need to manually configure window sizes.
