### ISSUE TITLE
[Bug] Dark mode and custom color scheme not applied to helper window (Proposed solution)

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#154]
# Description

When pressing "f8" to toggle dark mode (or custom shortcut to toggle custom color scheme), the modifications are not applied to helper window.

# Proposed solution

At *l.2356* and *l.2359* of *main_widget.cpp* (line numbers as of bb571d01878b33bf53bf72b55b0b9dce394627c9), adding :

```c++
this->helper_opengl_widget->toggle_dark_mode();
```

and, respectively :

```c++
this->helper_opengl_widget->toggle_custom_color_mode();
```

seems to solve the issue.

**Comment by ahrm** [comment]
Added in a50c871540bda2fa73c21d9d328014cfa222f159. Thanks for your work.
