### ISSUE TITLE
[Feature Request] Search coommands via fuzzy search

### ISSUE THREAD

**Issue by jdbrice** [ahrm/sioyek#155]
Currently the command search is rather unforgiving. For instance, typing "dark" gives no results - instead one must know to type "toggle" since the command is "toggle_dark_mode". Right now there are not too many commands so it isnt bad, but as more commands become available this becomes more problematic.

One could consider a 'fuzzy' search against the command names when populating the list.

**Comment by Elaws** [comment]
Hello,

Please read [this](https://github.com/ahrm/sioyek/issues/145#issuecomment-1051929938). Fuzzy search has been added to a recent commit (bb571d01878b33bf53bf72b55b0b9dce394627c9).

**Comment by jdbrice** [comment]
awesome :)
