### ISSUE TITLE
[Question] or [Feature Request] Export highlights as JSON or plain text

### ISSUE THREAD

**Issue by jdbrice** [ahrm/sioyek#158]
Ability to export highlighted text as plaintext (Markdown?)  or JSON (maybe provide a little more context like source, page number, etc.).
I use Obsidian for notes, and I'd like to read/highlight in sioyek, then afterwards dump all my highlights (not the PDF) into my notes for each PDF that I've reviewed.

I looked at the output of the `export` command, and unless I am missing something, it doesnt seem to include this info. 

I might even be able/willing to contribute this as a PR with a little guidance.
PS. sorry if this is already possible or in another issue (I didnt see it)

**Comment by Elaws** [comment]
Hello @jdbrice,

I'm using Obsidian too and that feature would be amazing ! Obsidian + Sioyek is a really great combo...

To make a little test, I've added a highlight and a bookmark comment to a pdf, and `export` gives : 

```json
{
    "documents": [
        {
            "bookmarks": [
                {
                    "description": "This is a bookmark test.",
                    "y_offset": 3468.530029296875
                }
            ],
            "checksum": "78e95e3edf0676e500ab39a033181ee3",
            "highlights": [
                {
                    "description": "config files are located in the same place where sioyek executable file is located. In non-portable builds, their location",
                    "selection_begin_x": -102.63800048828125,
                    "selection_begin_y": 3274.429931640625,
                    "selection_end_x": -24.543800354003906,
                    "selection_end_y": 3285.909912109375,
                    "type": 97
                }
            ],
            "marks": [
                {
                    "symbol": 48,
                    "y_offset": 3740
                }
            ],
            "offset_x": 0,
            "offset_y": 3323.530029296875,
            "path": "D:/Software/sioyek-release-windows/tutorial.pdf",
            "portals": [
            ],
            "zoom_level": 3.1372499465942383
        }
    ]
}
```

Do you get something similar ? All data seems here, but it would be nice if it was in the following markdown format (or a format specified by a template, as most web clippers do like [Memex](https://www.notion.so/Text-Export-Templates-bb1794c15dea4e588a59b52d37ca0070)) :

```md
[page_number](URI_to_highlight)
highlight
```

Also, it would be so useful if this also worked with simply copy/pasting.

I've forked the repo and managed to build/debug on my computer using VSCode (on Windows), so I'm also possibly interested to contribute  ! I'm not very experimented with C++ or development best practices though, and discovering `git` at the same time, thus I'll probably need a little guidance ^^

**Comment by ahrm** [comment]
As @Elaws mentioned, we already have the data required, however it is maybe not in the format that you expect. I don't think that I will change the export format for sioyek (because I want to keep it simple and fast, computing the page number from page location of a large number of documents can take a few seconds) but maybe we can create a python script to convert the exported data into the format that you expect?

**Comment by jdbrice** [comment]
I see it now, for some reason I didnt see these in the export last time. Thank you!
I'll write a python script to export JSON -> Markdown and share it once i've made it.

Thanks!

**Comment by kofm** [comment]
You can export your highlights on a per file basis using this jq oneliner

`jq '.documents[] | select(.path | contains("YOURFILENAME")) | .highlights[].description' sioyek_export.json`

Hope this helps someone
