### ISSUE TITLE
[Feature request] Open a PDF at specific page ?

### ISSUE THREAD

**Issue by Elaws** [ahrm/sioyek#159]
Hello,

I was wondering if it is currently possible to open a pdf at a specified page (with links such as `.../myBook.pdf#page=3`) ?

Often, notes taken on a pdf look like that :

```md
[page 3](.../myBook.pdf#page=3)
highlight1

[page 17](.../myBook.pdf#page=17)
highlight2
```

It would be so useful to open pdf directly at specified page.

If currently not possible, what would be a way to pass `page=x` argument to Sioyek ?

Thanks

**Comment by ahrm** [comment]
We already have a `--page` option:
```
sioyek filename.pdf --page 10
```

**Comment by Elaws** [comment]
Thank you. 

Oh this is nice : is that option documented somewhere ? What are the other existing command line options ?

**Comment by ahrm** [comment]
I think I forgot to document command line options. I will add it soon. Here are the current command line options:

```
reuse-instance: When opening a new file, reuse the previous instance of sioyek instead of opening a new window.
new-instance: When opening a new file, create a new instance of sioyek.
page: Which page to open.
inverse-search: The command to execute when performing inverse search. In <command>, %1 is filled with the file name and %2 is filled with the line number.
forward-search-file: Perform forward search on file <file> must also include --forward-search-line to specify the line.
forward-search-line: Perform forward search on line <line> must also include --forward-search-file to specify the file
zoom: Set zoom level to <zoom>.
xloc: Set x position within page to <xloc>.
yloc: Set y position within page to <yloc>.
shared-database-path: Specify which file to use for shared data (bookmarks, highlights, etc.)
```

**Comment by Elaws** [comment]
Thank you !

I noticed using `--page i` open the pdf with the page off-centered (like below) : is this the expected behavior ?

![image](https://user-images.githubusercontent.com/52013479/156558884-653b4f46-0c4b-44d6-b2c3-2874725d4c22.png)

**Comment by ahrm** [comment]
Yes, top of the page is in the middle of the page.

**Comment by Elaws** [comment]
I noticed an issue where if you open the last page of a pdf using the command line (`--page i`), it opens the first page of the pdf instead.

Do you prefer I open a new issue for that ?

**Comment by ahrm** [comment]
Changed page indexing to be one-based in 1a21f7b9b482cfca46cb457133eca4b2d5fd2df3. Should probably fix your issue.

**Comment by Elaws** [comment]
Perfect, it solves the issue of opening last page with command line.
