### ISSUE TITLE
Asking permission to publish sioyek on flathub

### ISSUE THREAD

**Issue by nbenitez** [ahrm/sioyek#163]
Hi @ahrm ,

[Flathub](https://flathub.org/) is a build and distribution platform for Linux apps, packaged in
a way that makes them portable and running on all major distributions.
Anyone can submit an app (we're not doing it for profit), but one of the
requirements is to reach out to the application's authors if they would
like to help with maintenance and thus making that distribution channel
considered official.

I'm volunteering to make a flatpak for _sioyek_ to be published in https://flathub.org/.

The usual maintenance for new releases is just changing version string and
the file checksum. The rest is done by flathub's build infraestructure.

It's understandable if you can't commit to maintaining it, I can do the new
version updates as I'm the original packager and interested in having
_sioyek_ on flathub, but we'd like to know **if you are not against
distributing it on Flathub in general**.

Thank you,
Nelson

**Comment by ahrm** [comment]
Yes, you can absolutely distribute it on flathub. And thanks for your work.

**Comment by nbenitez** [comment]
Thanks!, it's now published:
https://flathub.org/apps/details/com.github.ahrm.sioyek

so now it's easier to try sioyek in Linux no matter the distribution.

**Comment by ahrm** [comment]
Fantastic! Added a link in README page.
