### ISSUE TITLE
[Feature Request] Perform fuzzy search against filenames in the embedded file system browser

### ISSUE THREAD

**Issue by wongsingfo** [ahrm/sioyek#164]
Sioyek is an amazing PDF viewer! I really enjoy the features such as overview, external search, and the vim-like keybindings.

I'm wondering if Sioyek can perform fuzzy search against filenames in the embedded file system browser, similar to #150 and #155. To be specific, one can press `<C-S-o>` to open an embedded file system browser rooted in the current document folder, type in a keyword in the filename, and select the desired file to open.

This feature is quite useful when searching for a paper in a folder containing hundreds of files.

**Comment by ahrm** [comment]
Added in 185fba36713124459f0f4fc795995d81c29d7bf6.
