### ISSUE TITLE
Crashing with frequent overwriting of the PDF

### ISSUE THREAD

**Issue by frabjous** [ahrm/sioyek#166]
As you know from [the previous issue](https://github.com/ahrm/sioyek/issues/165) I posted, and you quickly fixed (thanks again!), I like to have a live-updating PDF preview as I type a markdown or LaTeX document. To get the live updating, of course, the file is constantly overwritten again and again. Sioyek has the unenviable task of constantly reloading the file every time it changes. Unfortunately, it seems it is not always up to the task.

This was working fine for me with markdown files converted to PDF via pandoc, both with its weasyprint backend and with its pdflatex/xelatex backend.

However, today I tested this on a LaTeX file, updating it by running pdflatex directly over and over again. I notice that if try that, Sioyek will randomly crash/quit as I edit. There doesn't seem to be a definite pattern to the crashes; sometimes it crashes right away when I start this process, sometimes it chugs along for awhile and then crashes. (Same result with xelatex.)

My guess is that Sioyek is trying to read the file before pdflatex is finished writing it, so that the pdf appears corrupted, or conversely, pdflatex is removing/overwriting the file before Sioyek is finished reading it. (Not sure who's to blame.)

I'm including below some of the output in the terminal a couple times this has happened. The output isn't always the same, but there are patterns. These are a sampling.

```
calling
starting index thread ...
figure indexing finished ... 
error: expected object number
warning: repairing PDF document
error: cannot tell in file
error: cannot parse object (5 0 R)
warning: cannot load object (21 0 R) into cache
error: Page not found: 1
error: aborting process from uncaught error!
```

```
starting index thread ...
figure indexing finished ... 
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot tell in file
Error: could not open document
error: Page not found: 4
Error: could not render page
error: expected object number
warning: repairing PDF document
error: cannot tell in file
error: cannot parse object (5 0 R)
warning: cannot load object (21 0 R) into cache
error: Page not found: 1
error: aborting process from uncaught error!
```

```
starting index thread ...
figure indexing finished ... 
error: cannot find startxref
warning: trying to repair broken xref
warning: repairing PDF document
warning: object missing 'endobj' token
error: Page not found: 3
Error: could not render page
error: cannot recognize version marker
warning: trying to repair broken xref
warning: repairing PDF document
error: cannot tell in file
Error: could not open document
error: Page not found: 3
Error: could not render page
calling
starting index thread ...
figure indexing finished ... 
texture: 7
calling
starting index thread ...
figure indexing finished ... 
texture: 8
calling
starting index thread ...
figure indexing finished ... 
error: expected object number
warning: repairing PDF document
warning: object missing 'endobj' token
error: object is not a stream
warning: cannot load object (24 0 R) into cache
error: Page not found: 1
error: aborting process from uncaught error!
```

If there's a way to enable more verbose logging with the latest version I'd be happy to test with that enabled.

I gave some thought into why this would happen when I'm calling pdflatex directly as opposed to when pandoc uses it. The difference would seem to be that pandoc writes its output to a temporary file first and then moves the temporary file into place when it's done.

So as a workaround, I've now changed my updating script to do likewise. I think it's still crashed once with this version of the script, but I've been unable to reproduce that, and things seem to work more or less OK when I use this workaround. My guess here is that moving the file is of course a much quicker process than pdflatex's compilation, so there's less likely to be a conflict.

The workaround has some costs, however, as the SyncTeX, log, and auxiliary files pdflatex produces are not in the proper directory for everything else to work smoothly. I can probably solve all those issues with some work, but it's not ideal. 

So this might be worth looking in to. I'm not sure how easy it is to fix something like this. However, there are other PDF viewers that auto-reload a PDF on changes that don't seem to crash like this, even with such frequently overwrites. (E.g., okular, zathura, qpdfview.) Somehow they either avoid the conflict or are able to recover from it.

Another possibility that would probably work, at least for my own workflow, is to give an option for turning auto-reloading off (--could just be an optional thing in the config file--), and then trigger a manual reload when a certain signal is sent (SIGHUP for example), or `sioyek --reuse-instace` is run on the same file, etc. That way, my script could be set up to send the signal only after pdflatex has finished its job (and only if pdflatex exits without an error). Regular MuPDF and llpp both work like this.

Thanks again for creating such a (in most ways) excellent product!

**Comment by ahrm** [comment]
Should probably be fixed in f300e4540cad63a94aa503ba80e828766cbbc1f4. I am not entirely sure though. Please notify me if you continue to have issues.

**Comment by frabjous** [comment]
Amazing. I can't believe how fast you are at getting to this stuff.

Been working with it this morning, and so far so good. I'll leave this open another week or so in case I run into trouble down the road, but at the moment, I'm very pleased.

It's a shame you aren't able easily to accept donations. Travel restrictions suck, but if you ever make it to the US, drinks are on me!

**Comment by ahrm** [comment]
I assume this issue is fixed. Please reopen if it is not.
