### ISSUE TITLE
[Flatpak] Default to --new-instance

### ISSUE THREAD

**Issue by ldelossa** [ahrm/sioyek#167]
When installing with flatpak `sioyek` cli is not availble in the traditional $PATH method. 

Instead .desktop file is installed. 

This makes opening two instances of Sioyek difficult. 

I suggest changing the default .desktop file to:

```
[Desktop Entry]
Name=Sioyek
GenericName=PDF Viewer for research papers
Comment=Sioyek is a PDF viewer designed for reading research papers and technical books
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 com.github.ahrm.sioyek --new-instance
Icon=com.github.ahrm.sioyek
Terminal=false
Type=Application
Keywords=pdf;viewer;research;
Categories=Office;Viewer;
MimeType=application/pdf;
StartupNotify=false
X-Desktop-File-Install-Version=0.26
X-Flatpak=com.github.ahrm.sioyek
```

This will provide a typical user experience where opening Sioyek creates a new window and using your DE's app switcher will navigate you to a particular open pdf.

**Comment by ahrm** [comment]
You can achieve this by setting `should_launch_new_instance` in your `prefs_user.config`:

```
should_launch_new_instance 1
```

**Comment by ldelossa** [comment]
My flatpak ran instance does pickup on configs in XDG_CONFIG directory :/

**Comment by ahrm** [comment]
Does it have to be placed in XDG_CONFIG? why don't you use the config file located in `/.var/app/com.github.ahrm.sioyek/config/.local/share/Sioyek/`?

**Comment by ldelossa** [comment]
Can try that

**Comment by ahrm** [comment]
Is this issue fixed?

**Comment by ldelossa** [comment]
Not sure, TBH I gave up on Sioyek. I tried to build it many times in a qt container, but can't seem to avoid issues. I'll close this since its no longer relevant for me.
