### ISSUE TITLE
[Table of contents] Collapse all and open with other chapters collapsed

### ISSUE THREAD

**Issue by ldelossa** [ahrm/sioyek#168]
Hey there. 

Using the ToC is pretty tough for large documents. 

It would be helpful to introduce a "collapse all" nodes in the ToC tree command. 

Additionally, it would be useful to start with all nodes collapse other then the current chapter youre viewing in the document viewer

**Comment by ahrm** [comment]
Added a `collapsed_toc` config option which does this. You can enable it by adding the following to your `prefs_user.config`:

```
collapsed_toc 1
```

**Comment by ldelossa** [comment]
Awesome!

**Comment by ldelossa** [comment]
@ahrm can I access this with latest flatpak? 

```
Sioyek                       com.github.ahrm.sioyek                    1.1.0.fl1  stable flathub system
```
I attempted an update but no update.

**Comment by ahrm** [comment]
> @ahrm can I access this with latest flatpak? 
> 
> ```
> Sioyek                       com.github.ahrm.sioyek                    1.1.0.fl1  stable flathub system
> ```
> I attempted an update but no update.

No, it will be available when the maintainer of the flatpak version updates the package.

**Comment by ahrm** [comment]
By the way this is available in latest releases of sioyek on this page: https://github.com/ahrm/sioyek/releases/tag/v1.2.0

**Comment by joelsleeba** [comment]
Hi, I tried to find the shortcut/command to collapse/expand individual nodes in toc, couldn't find in the config files. How can I configure sioyek to expand and collapse a particular node in toc with keyboard shortcut

**Comment by ahrm** [comment]
You can't configure it, it works with left and right arrow.

**Comment by SuperContraptionGuy** [comment]
This feature is missing in sioyek 2.0.0?

there is no command
`collapsed_toc`
Was this replaced with something else? How can I collapse a large table of contents, preferably automatically expanding the current location in sioyek 2.0.0?

**Comment by ahrm** [comment]
Note that `collapsed_toc` is a config option not a command.
