### ISSUE TITLE
Quit properly ?

### ISSUE THREAD

**Issue by okalm** [ahrm/sioyek#169]
I don't know if I totally miss the option on the tutorial, but it seems that "sioyek" can't exit properly without been killed.
Could it be possible to add a function for it, a shortcut like "Ctrl-q --> Exit " or something like that ?
Other than that there is nothing to say, your application is really good :)
Thank you.

**Comment by ahrm** [comment]
You can use the `quit` command by pressing `:` and then typing `quit` (or just `q`). You can also bind it to your prefered keybinding in your `keys_user.config`:

```
quit   q
```

**Comment by okalm** [comment]
I installed the Flatpak package version of sioyek .
So the right place for the file would be: `~/.var/app/com.github.ahrm.sioyek/config/keys_user.config`
Is this correct ?

**Comment by ahrm** [comment]
No it is `~/.var/app/com.github.ahrm.sioyek/config/.local/share/Sioyek/keys_user.config`.

**Comment by okalm** [comment]
Indeed it works as intended :)
Now if I want it to be `Ctrl-q` instead of `q` , how do I make it happen ? 
I already tried `C-q` , `Ctrl-q` and `^q` but none of them worked.

**Comment by ahrm** [comment]
This should work:
```
quit   <C-q>
```

**Comment by okalm** [comment]
Yeah, It works :)
Thank you for your time @ahrm .

Oh this have nothing to do with this topic but I have to say it the feature "table of content" is a killer one, I love it  :+1: 
Keep up the good work and again, thank you .
