### ISSUE TITLE
[Bug] when switching to dark mode, image colors also get inverted

### ISSUE THREAD

**Issue by dangmoody** [ahrm/sioyek#171]
If I view the following image in light mode:
![image](https://user-images.githubusercontent.com/1485355/160935347-49b04ef3-4557-433e-82ec-7c8e48fb493e.png)

When switching to dark mode, the image displays like this:
![image](https://user-images.githubusercontent.com/1485355/160935421-b875b6cb-0150-4163-8aa6-ae718aa217fe.png)

This specific image is a good test case because the skeleton on the right benefits from being shown in contrast to the background color whereas the image of the monster on the left does not.

In my test case Sioyek boots in light mode by default.

**Comment by ahrm** [comment]
I don't consider this a bug. The alternative would be to automatically detect images and don't invert them. But that would cause a giant white rectangle in the middle of dark mode which I think is pretty undesirable. Or is there any other behavior you have in mind?

**Comment by Twix53791** [comment]
I leave here a comment on this behavior. Personally, I found it annoying. At least an option should be available in the config to choose between the two behavior. The best would be to fill just the white background on the images, but not the other colors, but it is maybe impossible. The problem to invert colors appears critical on some graphics using specific colors, worse, which a legend (if the colors don't match...),  or for example a map again with colors which can become really weird with inverted colors...

**Comment by xulongwu4** [comment]
@Twix53791, maybe you can use the `custom_background_color` and `custom_text_color` options, which in my experiment change the image colors a little bit, but not as dramatic as flipping them.

**Comment by fossimprove** [comment]
Is there any option like to keep hue?
Zathura has this option `set recolor-keephue "true"` which keeps the reversing of colors to some readable level.
If so, i would like to request to try to keep hue !

Thank you again!

**Comment by ahrm** [comment]
> Is there any option like to keep hue? Zathura has this option `set recolor-keephue "true"` which keeps the reversing of colors to some readable level. If so, i would like to request to try to keep hue !
> 
> Thank you again!

Have you tried `toggle_custom_color` and setting `custom_background_color` and `custom_text_color` in your `prefs_user.config`? In that mode we try to somewhat keep the hue.

**Comment by fossimprove** [comment]
I have set `custom_background_color   0.0 0.0 0.0
custom_text_color     1.1 1.1 1.1`

When i toggle the whole pdf gets black white (which is better rather than reversing of color) but no color hue is kept, only black white.

**Comment by ahrm** [comment]
I changed the dark mode algorithm in 8cf94f94fef31f8ddff8e269923ab454b2e052a9 to try to keep the hue. I don't know if it is much better than previous algorithm though because some JPG compression artifacts are *very* visible in this mode.

**Comment by xulongwu4** [comment]
I haven't tried the new algorithm, but the old algorithm for keeping the hues work very well for me. I guess the reason is that I don't use pure white/black as cutom text/background color.

This is my settings (use the famous nord color template):

```
custom_background_color 0.180 0.204 0.251
custom_text_color 0.847 0.871 0.914
```

This is the result after toggling custom color on:
![Screenshot_20220425_095058](https://user-images.githubusercontent.com/16892446/165103508-16ca7d43-95a2-421a-85d1-31a5692385e3.png)

For comparison, this is the original plot with the default background/color settings:
![Screenshot_20220425_095127](https://user-images.githubusercontent.com/16892446/165103669-d982cdfb-5694-4855-9420-fd51f51afd31.png)

The color hue changed a little bit (I kind of like the new color hue in the custom color mode to be honest), but you can still tell one is blu-ish, and the other one is red-ish.

**Comment by fossimprove** [comment]
I tried with xulong's nord custom colors, it worked decently as stated.
Then i updated to new commit, the new algorithm works better than the previous dark mode. In some pictures, colors are maintained as it is.
This is now perfectly readable in dark mode.

Thank you for working on new algorithm!
You are the BEST!!!

**Comment by amzon-ex** [comment]
Hi!

I'm on [Release v0.31.314](https://github.com/hexomancer/sioyek/releases/tag/v0.31.314) and some colours seem to completely vanish when I use dark mode:

---
### Original
![sioyek-white](https://user-images.githubusercontent.com/45428344/166134741-6c30fa28-f225-44f8-bdc2-a1dd68759b9f.png)

---
### Dark
![sioyek-dark](https://user-images.githubusercontent.com/45428344/166134745-ba1e2341-9576-4448-b430-2aa4d3ef3842.png)

---
### Custom colours
![sioyek-custom](https://user-images.githubusercontent.com/45428344/166134746-998f3f8f-d309-4738-9384-bc7d6d4d2349.png)

---
As you can see, when I use "custom" colours, the colours are quite faded, which is an issue, but in dark mode, they completely vanish (such a problem didn't exist on the [stable version](https://github.com/ahrm/sioyek/releases/tag/v1.2.0) from this repo.)

**Comment by ahrm** [comment]
I changed the algorithm again in dc05477023661d034a70df18a6695659785c8866. Should be fixed now.

**Comment by amzon-ex** [comment]
Thanks, @ahrm !

I tried it out, and now it seems like I can see the blue curve, but since it's very dark, there's no contrast against the dark background, hence it's as good as invisible:

![sioyek-dark-2](https://user-images.githubusercontent.com/45428344/166290246-c5eb6a39-0d8a-4e81-b815-902f9b08d81e.png)

(Same with the red dotted curve, but that's comparably better)

**Comment by dangmoody** [comment]
> I don't consider this a bug. The alternative would be to automatically detect images and don't invert them. But that would cause a giant white rectangle in the middle of dark mode which I think is pretty undesirable. Or is there any other behavior you have in mind?

Hey, sorry for the late response.  I've been busy.

After having thought about it I personally would want the image backgrounds to still be light.  I look at graphics papers so it would get confusing to be looking at an figure where the paper is describing the red signal/portions of an image only for dark mode to be inverting the colors and not showing a red signal, for instance.

**Comment by seblj** [comment]
I just tried out sioyek and found it really good, but I also found the colors on pictures with custom colors to be less visible compared to for example zathura with the hue option set.

sioyek:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/5160701/197388638-e8d87a3a-2f50-4f19-96ff-5c73600e304e.png">
<img width="314" alt="image" src="https://user-images.githubusercontent.com/5160701/197388649-bf4f80b4-da1b-45d4-8c1f-cdc0f36a6092.png">

zathura:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/5160701/197388472-c9a501a9-8793-4815-a0a0-64e7ec3a5846.png">
<img width="290" alt="image" src="https://user-images.githubusercontent.com/5160701/197388476-2b914485-81ae-4719-ab1f-47721bba6880.png">

Are there any options that I am missing that could make this more vibrant like in zathura?

**Comment by ahrm** [comment]
No.

**Comment by ahrm** [comment]
This is fixed in the latest version of sioyek.
