### ISSUE TITLE
Enhance fuzzy search of Command 

### ISSUE THREAD

**Issue by fossimprove** [ahrm/sioyek#172]
I noticed the search [searching like," : bookmark" ] only seeks from first word but not like fuzzy finder, where I can search for "bookmark" and get options of 
add_bookmark
delete_bookmark ..... etc

For quick process it would be handy.
Instead of typing "goto" or "add" to get each result. Better to search just "mark"

I hope I conveyed the information and you get what I mean.

Thank you for the pdf reader, Its absolute replacement (for zathura) for me (student) 
I thought it was made primarily for linux, but its for all. Cheers ;-)
It's fantastic, I love the fact it can be keyboard driven, and it's developing great.
From my side, all I'd like is to maintain the minimalism and add simple yet powerful features.

**Comment by fossimprove** [comment]
Idk if this the duplicate of #155 
Im on latest release AppImage, so it might not be updated yet or next update?

You can close it if so, Thank you for such a productive tool

**Comment by ahrm** [comment]
I think this issue has been fixed but maybe there is still no release with the fix.
Here is an experimental appimage of the latest commit: https://github.com/hexomancer/sioyek/releases/tag/v0.31.165

Probably there is no risk I just don't want to take any responsibility for those packages, I am not entirely sure how aur builds packages but I think maintainers are allowed to patch the code.

**Comment by fossimprove** [comment]
This issue can be closed.

Also does ui_font work in linux?
Im not able to obtain the font, size works though.

**Comment by ahrm** [comment]
I have not tested it on linux myself, but it should probably work.
