### ISSUE TITLE
[Enhancement] – Please add the configuration to Map the black font color to other color – Dyslexic

### ISSUE THREAD

**Issue by joaocarvalhoopen** [ahrm/sioyek#176]
Hi,
This feature will be really great for dyslexic people and color blind people!

The majority of PDF like 98% are white background in black letters. For dyslexic and color blind people the color, the contrast and the brightness are really important because it’s the difference between a person reading well a pdf document or not reading well a pdf document and having headaches.
Your full screen modes are really clean and really good for reading and you already have a really good configurable contrast setting for dark mode, so please transform this good program into an incredibly good program for Dyslexic and Daltonic people by adding to the contrast setting, the possibility to map the color black of the 99% of the fonts in all documents to a different color. Like a post processing of some kind.

I really like the dark mode but I would like to change it’s background color and it’s font color and this is really important for Dyslexic people. I have dyslexic people at home.

The systems that we use are Linux Ubuntu 20.04, but of course this would be very useful for all operating systems.

Best regards,
João

**Comment by ahrm** [comment]
You can already do that. https://sioyek-documentation.readthedocs.io/en/latest/configuration.html?highlight=custom_color#custom-background-color-and-custom-text-color.

**Comment by joaocarvalhoopen** [comment]
**It’s oficial, you have the best PDF reader for Dyslexics for Linux Ubuntu!**

Thank you very much!
I will install you software into the computer of two other persons that will really appreciate it because they are Dyslexic, they are students. In my case I’m a life long student and I read a lot of PDF’s papers and books so it will be also really appreciated by me!

The configurations that I have found to be good are:

**prefs_user.config**

```
# The color with which the screen is cleared before rendering the pdf
background_color    1.0 1.0 1.0
dark_mode_background_color    0.0 0.0 0.0

# Showing full white text on black background can be irritating for the eye, we can dim the whites a little bit using the contrast option
dark_mode_contrast      0.6

# Application colors background color and text color.
custom_background_color  0.01 0.01 0.01
custom_text_color        0.3 0.5 0.1

# Commands that run at startup.
startup_commands      toggle_custom_color;toggle_visual_scroll

# Highlight color when text is selected using mouse
text_highlight_color    1.0 1.0 0.0

# The color of highlight bar which is displayed when right click is pressed
vertical_line_color    0.0 0.0 0.0 0.4

# Use dark mode by default
default_dark_mode	1
```

Best regards,
João

**Comment by ahrm** [comment]
Awesome, and thanks for the kind words!
