### ISSUE TITLE
[Enhancement] – Please add drag and drop to open a file – Linux

### ISSUE THREAD

**Issue by joaocarvalhoopen** [ahrm/sioyek#177]
Hello,

Thank you Ahrm for your rapid replies to my two previous bug and enhancement that Sioyek already did correctly.
I have written about Sioyek in foruns because I think it’s really also really good for Dyslexic people.
Currently the on only thing that I’m missing is the **drag and drop to open a PDF file** from a file manager, **this is specially useful if you have to read several different file and open them in a fast way, without having  previously opened that file**. In this last case one can use the ```Shift+O``` shortcut. The normal Open file is not optimal to open **PDF files organized in different directories**.
I’m using Linux Ubuntu 20.04.

Thank youi,

Best regards,
João

**Comment by ahrm** [comment]
Added in e5fa57b300e5e0b207a05afba449717423cbdf1c. By the way you can press `Control+Shift+O` or `Control+O` to open an embedded file explorer inside sioyek.

**Comment by joaocarvalhoopen** [comment]
Thank you so much Ahrm,

You are making really a ground breaking software! 
The Crtl+ Shift+O and Ctrl+O are also really really nice!

I have made a forum post in a Portuguese forum about your incredible PDF and Epub Reader, Sioyek.

Sioyek - One of the best PDF readers, for papers and technical books, also good for Dyslexic and Daltonic
[https://lusorobotica.com/index.php?topic=9921.0](https://lusorobotica.com/index.php?topic=9921.0)

Thank you again.

The very best regards,
João
