### ISSUE TITLE
[Enhancement] - Read a PDF from the standard input.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [ahrm/sioyek#188]
Hello Ahrm,

Read a PDF from the standard input so that you can auto-generate documentation from a program to not blowup the size of a user GitHub repository with constant documentation in a project.

Thank you

The very best regards,
João

**Comment by ahrm** [comment]
Unfortunately it is a built in assumption in sioyek that files have paths and changing it would require a lot of work, so I don't think I will implement this feature.
