### ISSUE TITLE
[Enhancement] - Live update a PDF view of a file if it is changed in the hard disc.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [ahrm/sioyek#189]
Hello Ahrm,

This is very good for a fast process of document creation.

Thank you,

The very best regards,
João

**Comment by ahrm** [comment]
We already have this feature.

**Comment by joaocarvalhoopen** [comment]
Hello Ahrm,

very nice!

Thank you,

I have found that those features where important while seeing what Sioyek could do, and that I think-ed it didn’t while comparing to Zathura.

Like I said you are making an incredible peace of Open Software.
A very complete and feature rich software suit for PDF and EPUB.

The very best regards,
João
