### ISSUE TITLE
Links are being confused when there are tables, algorithms, figures and equations.

### ISSUE THREAD

**Issue by DhruvPatel01** [ahrm/sioyek#19]
When I middle-click on ... table x.y ..., ideally I should be redirected to the table x.y. But some books have both table x.y and figure x.y. The behavior currently looks arbitrary. Upon clicking a table, I was redirected to a figure with the same number.

Also, when I clicked on 3.4 (I was in chapter 13), I was redirected to 13.4. 

I understand that you might be using heuristics when links are not provided, and they are prone to failures. Can you point me to relevant code files (or function)? I want to understand the logic and see what can be done to alleviate this kind of behavior. (Sorry, I was planning to peruse the whole code, but it seems daunting :) ).

**Comment by ahrm** [comment]
Yes you are right, we currently use pretty simple heuristics for figure links. Adding tables, algorithms etc. are in my roadmap. There are two approaches to do this:
1- Add additional heuristics for each new type of item
2- Use some sort of AI-based algorithm to automatically detect the items

Currently I am exploring the second option, but if it doesn't work I will add additional heuristics for different items.

The relevant code are:
* First we index all the figures/references/equations when the document is first opened in here: https://github.com/ahrm/sioyek/blob/3a79668cf429b146632508dd17c4cd58aa764d8e/pdf_viewer/document.cpp#L695
* Then when the user middle clicks on a text, first we detect the type of the item which is under the cursor and if it is in the index, we jump to the location: https://github.com/ahrm/sioyek/blob/3a79668cf429b146632508dd17c4cd58aa764d8e/pdf_viewer/main_widget.cpp#L1187

The code is ugly and requires a lot of refactoring, but as I said I am exploring the AI option first before putting a lot of effort in the current system.

**Comment by ahrm** [comment]
I have added the ability to index and reference generic items (for example Figure, Algorithm, Theorem, etc.) in 445c623d1c6f3762badd21186c1643636c45383e. It is still a pretty simple heuristic and sometimes it gets references wrong, but it should work on many more items.

**Comment by DhruvPatel01** [comment]
Thanks for fixing this quickly! I tried the changes, and seems to be working. Great work.
