### ISSUE TITLE
Why can I scroll horizontally?

### ISSUE THREAD

**Issue by qazip** [ahrm/sioyek#192]
Even when the page is fit to the screen size (or when it is zoomed out), sioyek allows to zoom horizontally, which is quite annoying for those of us who use a touchpad.

Is this something that can be configured? One should not be able to scroll horizontally if page is fit to the screen or if zoomed out!

**Comment by ahrm** [comment]
We have a `toggle_horizontal_scroll_lock` command which disables horizontal scroll.

**Comment by ahrm** [comment]
Also added better handling of `move_left` and `move_right` in 8356e47754b8e7b6cac60d53c01ffc1c542449c8. Now you are not able to leave the document using these commands (which means that they are disabled when the document is fit to screen width).
