### ISSUE TITLE
No figure preview generated

### ISSUE THREAD

**Issue by amzon-ex** [ahrm/sioyek#193]
In a certain book I was reading, right-clicking on figure references does not generate a preview. In this book, the figures are labelled as *Figure x.y* but the reference to the figure is like *Fig. x.y*, which I believe could be the reason why it does not work. 
In the same PDF, it works with equations, and in another book I checked in, figure previews are also generated. In that book, text references to figure are as *Figure x.y*, which is why I suspected the above.

Any insight?

**Comment by amzon-ex** [comment]
I think: since the textual reference to figures should be constant throughout the book *and* the user can easily notice what the reference style used is, if `sioyek` fails to build associations for such reasons, it can prompt the user to input the right kind of reference. This only needs to be done once and instantly should make the book workable with this super-useful feature - as a workaround, I mean.

**Comment by ahrm** [comment]
The algorithm we use is a little more complicated than that, so we can not simply prompt the user for a pattern. Maybe if your file is not private you could share it here so I can see if we can fix our algorithm for this file. (no promises though)

**Comment by amzon-ex** [comment]
@ahrm It's not really private, but it would be nice if I could share it via email or something (and not publicly here), since it's a libgen-obtained pdf.

**Comment by ahrm** [comment]
> @ahrm It's not really private, but it would be nice if I could share it via email or something (and not publicly here), since it's a libgen-obtained pdf.

Of course. My email is: [a.hr.mostafavi@gmail.com](mailto:a.hr.mostafavi@gmail.com).

**Comment by amzon-ex** [comment]
Just curious - is this a separately maintained fork?

**Comment by ahrm** [comment]
No, I just create experimental builds there so as not to spam people who have watched this repository with notifications.

**Comment by amzon-ex** [comment]
@ahrm When I reopened the pdf after closing sioyek, it worked somehow. The first time I tried it, it was unresponsive. I have no idea why...
