### ISSUE TITLE
Default data path when using appimage

### ISSUE THREAD

**Issue by xulongwu4** [ahrm/sioyek#198]
I use sioyek's appimage on linux. In the meantime I defined `XDG_CONFIG_HOME` to be $HOME/.config. All my use data goes to the folder $HOME/.config/.local/share/Sioyek. This path is not standard for linux applications for its data. I think it is okay if the data goes to $HOME/.config or $HOME/.local/share, but not their combinations.

When I look into the source code, I see that we don't define `LINUX_STANDARD_PATHS` when building the sioyek appimage. My question is, why is that the case? I suppose the appimage is supposed to be run on linux, and the path under `LINUX_STANDARD_PATHS` flag seems very reasonable on any modern linux distributions.

**Comment by ahrm** [comment]
You are right, I will probably fix it at the next release of sioyek.
