### ISSUE TITLE
Allow `enter` key in `keys.config`

### ISSUE THREAD

**Issue by Standecco** [ahrm/sioyek#199]
Just installed the software, and currently trying to map `enter` to `next_item` and `<S-enter>` to `previous_item`.

Having tried all possible combinations of lowercase and uppercase names for the return key, I went to the source and found https://github.com/ahrm/sioyek/blob/main/pdf_viewer/input.cpp#L209-L221.

Am I right in thinking that `enter` is not handled at all, and that there is no way to bind it to anything?
If so, could it be added? My aim was to get the search-in-text keybindings I'm familiar with, from VSCode and web browsers.

**Comment by Standecco** [comment]
Also tried binding `tab` to the command (which in theory should be handled), but that didn't work either. Am I missing something and binding "non-regular" keys can't be done at all, or is this a separate issue?

**Comment by ahrm** [comment]
Added ability to map enter in 689e07c6c6908debb60a323b03da18d061535ccd. Tab should work already, I just tested it. The syntax is something like this:
```
zoom_in <tab>
zoom_in <return>
```

**Comment by Standecco** [comment]
Works like a charm! Thanks a lot, that was insanely fast!
