### ISSUE TITLE
C++ error on Ubuntu installation

### ISSUE THREAD

**Issue by bernsm3** [ahrm/sioyek#20]
Hi,

I am trying to install from source on Ubuntu 20.04 and getting the following C++ error in during compilation. Probably I am just missing some C++ library, or a compiler flag to conform to a recent standard is not being set in `pdf_viewer_build_config.pro`, but my Googling is not strong enough to figure out what it is.

```bash
$ cd sioyek
$ git pull --recurse-submodules
$ ./build_linux.sh
make: Nothing to be done for 'default'.
g++ -c -pipe -std=c++17 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQAPPLICATION_CLASS=QApplication -DQT_3DCORE_LIB -DQT_3DANIMATION_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DRENDER_LIB -DQT_OPENGL_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_QUICKWIDGETS_LIB -DQT_SQL_LIB -DQT_WIDGETS_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_QUICKWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_QUICK_LIB -DQT_3DANIMATION_LIB -DQT_3DEXTRAS_LIB -DQT_3DRENDER_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DCORE_LIB -DQT_GAMEPAD_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -Ipdf_viewer/SingleApplication -Ipdf_viewer -Imupdf/include -Izlib -I../anaconda3/include/qt -I../anaconda3/include/qt/QtOpenGL -I../anaconda3/include/qt/QtQuickWidgets -I../anaconda3/include/qt/QtWidgets -I../anaconda3/include/qt/QtQuick -I../anaconda3/include/qt/Qt3DAnimation -I../anaconda3/include/qt/Qt3DExtras -I../anaconda3/include/qt/Qt3DRender -I../anaconda3/include/qt/Qt3DInput -I../anaconda3/include/qt/Qt3DLogic -I../anaconda3/include/qt/Qt3DCore -I../anaconda3/include/qt/QtGamepad -I../anaconda3/include/qt/QtOpenGLExtensions -I../anaconda3/include/qt/QtGui -I../anaconda3/include/qt/QtQml -I../anaconda3/include/qt/QtNetwork -I../anaconda3/include/qt/QtSql -I../anaconda3/include/qt/QtCore -I. -I../anaconda3/mkspecs/linux-g++ -o config.o pdf_viewer/config.cpp
In file included from mupdf/include/mupdf/fitz.h:11,
                 from pdf_viewer/utils.h:15,
                 from pdf_viewer/config.cpp:2:
mupdf/include/mupdf/fitz/context.h: In function ‘void* fz_keep_imp_locked(fz_context*, void*, int*)’:
mupdf/include/mupdf/fitz/context.h:633:32: warning: unused parameter ‘ctx’ [-Wunused-parameter]
  633 | fz_keep_imp_locked(fz_context *ctx, void *p, int *refs)
      |                    ~~~~~~~~~~~~^~~
pdf_viewer/config.cpp: In constructor ‘ConfigManager::ConfigManager(const wstring&, const wstring&)’:
pdf_viewer/config.cpp:102:113: error: no matching function for call to ‘std::vector<Config>::push_back(<brace-enclosed initializer list>)’
  102 |  configs.push_back({ L"text_highlight_color", DEFAULT_TEXT_HIGHLIGHT_COLOR, vec3_serializer, vec3_deserializer });
      |                      
```

This is repeated for several lines in the source file; I'll provide the complete output on request (didn't want to clutter up the issue)

My system info:
```bash
$ uname -a
Linux xxxx 5.11.0-25-lowlatency #27~20.04.1-Ubuntu SMP PREEMPT Tue Jul 13 18:53:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by iamkroot** [comment]
`g++ -c -pipe -std=c++17 -O2 -std=gnu++11 ...` this seems to be the culprit. The `gnu++11` overrides `c++17`.

**Comment by ahrm** [comment]
Yes, as @iamkroot said, the issue is `-std=gnu++11`. I think it should be fixed in the latest commit here d2608303e95081d88fad19dfbb796a484bb43eb5. Please try it on the latest commit and notify me if the issue persists.

**Comment by bernsm3** [comment]
Thank, you I'm able to build it now!

When I run the executable, it shows up as a blank white screen exactly like the first screenshot here: https://github.com/ahrm/sioyek/issues/13

startup trace (nothing seems unusual?):
```bash
$ ./sioyek 
default_config_path: /home/matt/sioyek/prefs.config
default_keys_path: /home/matt/sioyek/keys.config
user_config_path: /home/matt/.local/share/Sioyek/prefs_user.config
user_keys_path: /home/matt/.local/share/Sioyek/keys_user.config
database_file_path: /home/matt/.local/share/Sioyek/test.db
tutorial_path: /home/matt/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path/home/matt/.local/share/Sioyek/last_document_path.txt
shader_path/home/matt/sioyek/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
inotify_add_watch("/home/matt/sioyek/prefs.config") failed: "No such file or directory"
inotify_add_watch("/home/matt/sioyek/keys.config") failed: "No such file or directory"
config file change listener constructor called1starting index thread ...
figure indexing finished ... 
texture: 4
getting links .... for 0
invalid command; resetting to root
```

The last line `invalid command; resetting to root` shows up whenever I hit one of the hotkeys mentioned in the tutorial, and the page number does not change.

Not sure if this is still a build problem, if not this issue can be closed

**Comment by ahrm** [comment]
> Thank, you I'm able to build it now!
> 
> When I run the executable, it shows up as a blank white screen exactly like the first screenshot here: #13
> 
> startup trace (nothing seems unusual?):
> 
> ```shell
> $ ./sioyek 
> default_config_path: /home/matt/sioyek/prefs.config
> default_keys_path: /home/matt/sioyek/keys.config
> user_config_path: /home/matt/.local/share/Sioyek/prefs_user.config
> user_keys_path: /home/matt/.local/share/Sioyek/keys_user.config
> database_file_path: /home/matt/.local/share/Sioyek/test.db
> tutorial_path: /home/matt/.local/share/Sioyek/tutorial.pdf
> last_opened_file_address_path/home/matt/.local/share/Sioyek/last_document_path.txt
> shader_path/home/matt/sioyek/shaders
> Creating shared memory block...
> Shared memory created: this is the primary application.
> Starting IPC server...
> IPC server started.
> inotify_add_watch("/home/matt/sioyek/prefs.config") failed: "No such file or directory"
> inotify_add_watch("/home/matt/sioyek/keys.config") failed: "No such file or directory"
> config file change listener constructor called1starting index thread ...
> figure indexing finished ... 
> texture: 4
> getting links .... for 0
> invalid command; resetting to root
> ```
> 
> The last line `invalid command; resetting to root` shows up whenever I hit one of the hotkeys mentioned in the tutorial, and the page number does not change.
> 
> Not sure if this is still a build problem, if not this issue can be closed

Which sioyek executable are you running? You should run the one in the `build` folder.

**Comment by bernsm3** [comment]
Oh, yup, that was the problem. I was running the executable in the root.
Thanks for your help!
