### ISSUE TITLE
[Enhancement] – Really crazy feature – Full Screen mode with vertical split half Sioyek half other program.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [ahrm/sioyek#201]
Hello Ahrm,

**This is really crazy stuff but I think it is still possible to do.**

**The problem and the feature:**

When you work with Dyslexic mode you need custom_colors without high contrast white text and bright  icons on the screen so you need F11- Full Screen mode, but it’s really nice to real a book or a paper and have the screen half with Sioyek and half with Zettlr with custom CSS for dyslexic that also has a full screen mode.
But only one program can be in full screen mode at the same time, so it would be really nice, but I know that this is really crazy stuff, that sioyek could be configured to take a open window and blend inside it’s Sioyek app fullscreen mode the function screen. Mouse and keys of the window of other program and it would only process the keys and the mouse in that half ex: left half was selected, Sioyek has the focus. The selection could be a sortkey toogle. The other half, right half would route out the graphics from the windows to the screen of Sioyek fullscreen and route in  the key presses and the mouse clicks.

This would be really useful for note taking while reading books or papers in any note program that the user uses.

It would remove bright colors and high contrasts from any screen and it would maximize the screen area and give other programs that can work as a pair program to Sioyek the clean mode of Sioyek Fullscreen.

Note: I’m note expecting that you will implement this feature, I’m just bouncing this good, useful but crazy idea with you! 

```
Without any division line or border.

|*************|***********|
|             |           |
|             |           |
|             |           |
|   Sioyek    |   Other   |
|             |  Program  |
|             |           |
|             |           |
|*************|***********|

```

Thank you Ahrm,

The very best regards,
João

**Comment by joaocarvalhoopen** [comment]
Hello Ahrm,

I showed my description of my crazy idea to my daughter and she gave me a really cool idea, a different way to obtain almost what I asked you with this Enhancement without any development.

The steps are:

1. You open **Sioyek** with the paper or book you are reading and send it to the left half of the screen, Windows-Key  + Arrow Left, remember Linux Ubuntu 20.04 with the start icon bar on the left, and a bar above, and the sioyek with the title of the document above.

2. You open **Zettlr** or other program and open your note for the book or paper, and close the file tree, only text is on the screen, and you have a Custom CSS for dyslexic people.

3. Hit F11 on the Sioyek, make it full screen and with the Zoom In and Zoom Out keys or with Ctrl + mouse wheel and pointer size the PDF viewable text to only the left screen.

4. Alt + Tab to switch windows and make The Zettler window above the Sioyek fullscreen mode.

5. Then alt tab it has you need it and use the keys.

**Problems**: The only problem is that **you loose the capacity to go down and up the attention visual line in this mode**. Maybe there is a possibility for a work around with a general key binding that doesn’t depend on the Sioyek having the focus of the screen. 

Thank you Ahrm,

The very best regards,
João

**Comment by ahrm** [comment]
As you mentioned, this *is* a crazy feature :) . I think this is the job of the window manager and maybe it can be arranged with some window managers in linux like i3 but I don't think implementing this in a PDF reader is reasonable.
