### ISSUE TITLE
DBus support?

### ISSUE THREAD

**Issue by OpenFoam-User** [ahrm/sioyek#203]
Hello,
Zathura has a very neat DBus API to query some important data (open a document at specifc page, get number of pages, get current page number, ... etc.).

Is there a plan to create a DBus API?

Thanks

**Comment by ahrm** [comment]
There is currently no plan to do that. Mainly because I try to keep sioyek as cross-platform as possible and dbus is mainly a linux thing (I know it is technically cross-platform but it really isn't). If there is a cross-platform alternative I may do that.

**Comment by dkwo** [comment]
I really like that you keep it cros-platform, and do not require dbus.
Does synctex work without dbus as well? that would be nice.

**Comment by ahrm** [comment]
Yes, synctex should work without dbus (you need to configure sioyek and your editor though, here is more information: https://sioyek-documentation.readthedocs.io/en/latest/usage.html#synctex).

**Comment by ahrm** [comment]
We include the source code for synctex in the repository. It doesn't do IPC, it just runs shell commands which are configurable.
