### ISSUE TITLE
[Enhancement] – Please add a temporarily key up and key down on the text color of the RGB Brightness of Custom_Color text.

### ISSUE THREAD

**Issue by joaocarvalhoopen** [ahrm/sioyek#206]
Hello Ahrm,

I think that this case is some what common. The case in question is this:

If the original PDF is black text on white paper, you have nailed it the custom_color  settings in my Dyslexic configuration is really the best PDF Reader for Dyslexic people that I have found.

But if the text has in between block in a different color like light gray in the original white background and black text, before applying the Custom_color, this ones will not be easily seen in my custom color mode settings. I can up the brightness of my text color but then the rest of the text will have to much brightness to be good for Dyslexic people.

So what would be nice is for a temporarily up of the brightness of custom_color_text in a way that one could easily read the gray text and then come down for the rest when the text is the normal black text, the majority of the cases is black text, but in dark text just temporarily up the brightness of the text and then after the block is finished go down on the brightness again to the default Custom_color_text.

And what I ask is a way to temporarily not saved, when I am in the middle of a block of a text and this blocks of text show up I can press a key UP Brightness to temporarily up my brightness of the color of the text and then do the key down to go to the normal text color that is configured on my prefs_user, custom_color.

Thank you,

The very best regards,
João

**Comment by ahrm** [comment]
I think this is best handled with an external script. You can have two versions of prefs_user.config 
 with different values for custom color and configure your system to swap these files when you press a hotkey. We live-reload the changes so they immediately take effect.

**Comment by joaocarvalhoopen** [comment]
Thank you, you are right, I hadn’t think of that, but Sioyek auto reloads it’s settings files so a toogle script is really a simple solution.

I will tell you the following, **Sioyek and Zettlr combination has been a revolution in my daily processes of studying**, and I’m contributing to both projects not yet with code, but with my time and my writing, be it on bug reports, on testing or on enhancements, on posts about them and on there respective discussion forums.

**I have being so impressed by Sioyek clean look and feel for dyslexic people, and having feedback on more people on it**, that I’m thinking of making a small editor experiment to have a very simplified kind of Zettlr text editor but with an interface an clean look of Sioyek. The idea is if one could see the words in the edit text in the screen without anything else in a full screen mode and that somehow it would work to divide the screen in half and have a PDF paper or a book open on the left of the screen with my custom_colors with Sioyek and the DisEditor open in the right of the screen to make the paper or book notes.

The other use case is to put you notes on a .md file with minimal distraction from everything else, but with custom colors, custom CSS and have a second pass (editing pass) by the text to have the possibility to make spell checking with hunspell for different languages like English and Portuguese for example.

I would also like to ask you what font are you using in Sioyek because it is specially good for legibility. Or is it the font from the PDF itself?

This will be just a simple experiment but a nice one, and I will have to learn a bunch of new technologies, like for example Tauri and CodeMirror 6, Vue.js .

**DisEditor - A low noise text editor @;-)**
https://github.com/joaocarvalhoopen/DisEditor---A-low-noise-text-editor

Best regards,
João

**Comment by ahrm** [comment]
Thanks for the kind words and good luck on your project :) .

> I would also like to ask you what font are you using in Sioyek because it is specially good for legibility. Or is it the font from the PDF itself?

It is the font in PDF itself.
