### ISSUE TITLE
Vim-style keybindings / `gg` & `G`

### ISSUE THREAD

**Issue by st--** [ahrm/sioyek#209]
I love the vim-style keybindings you've gone for! One thing that's really going against my finger habits though is using `<num>gg` to jump to a page (line in Vim) which sioyek uses, whereas Vim (also) supports `<num>G` (number & shift+G) to jump to a line. Would you be able to also support `<num>G` to jump to a page? (It doesn't seem to be directly configurable using keys.config as it seems to be a property of the goto_beginning command which goto_end doesn't have?)

**Comment by ahrm** [comment]
Added in 29e121542a0dd73fc3e16e2ea8cd780e7d07e28c.

**Comment by st--** [comment]
awesome, thanks for the quick response! should we close this issue then?:)
