### ISSUE TITLE
Request: add homebrew formula install from HEAD

### ISSUE THREAD

**Issue by SichangHe** [ahrm/sioyek#210]
# add homebrew formula install from HEAD
Please provide a homebrew formula to install from HEAD, that is, from the latest experimental build.
Alternatively, a homebrew formula to build automatically is also welcomed (if that is possible).

**Comment by ahrm** [comment]
I am not familiar with homebrew, but we do have a github action that builds sioyek on macos here:
https://github.com/ahrm/sioyek/blob/main/.github/workflows/build_and_release.yml . Maybe someone can port it into a homebrew formula.

**Comment by SichangHe** [comment]
Alternatively, can we just have a developer version build that is up-to-date?

**Comment by SichangHe** [comment]
sioyek does have a homebrew formula [here](https://github.com/Homebrew/homebrew-cask/pull/122650)
However, I recommend doing a [brew tap](https://docs.brew.sh/Taps) and keep it in a repo under your user like [what yabai does](https://github.com/koekeishiya/homebrew-formulae). yabai has instruction on [how to install from HEAD using homebrew](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(from-HEAD)). I suggest we may modify it and make the ruby script work.

**Comment by ahrm** [comment]
I frequently build the latest version of sioyek in this repository:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.314

I am not at all familiar with homebrew and it's associated tooling, therefore I am not comfortable hosting a tap (at least not in near future). But if someone else wants to do it they are of course welcome to do so.
