### ISSUE TITLE
Allow `tab` key

### ISSUE THREAD

**Issue by TornaxO7** [ahrm/sioyek#213]
Is it possible to map a command to the `<Tab>` key?

**Comment by ahrm** [comment]
Yes. For example:
```
next_page <tab>
```

**Comment by TornaxO7** [comment]
Oh god... I used `<Tab>`... I didn't knew that it should be `<tab>`.... thank you! I just found this PDF viewer and I love its performance. I'm reading CPU manuals like those from intel with more then 5.000 Pages and holy cow this pdf-viewer is fast as hell and I love it! Thank you for this PDF-Viewer!

**Comment by davidsircoin** [comment]
I have `goto_toc <tab>` in my config file but it is not working on linux :(
