### ISSUE TITLE
Support for copy to clipboard [MacOS]

### ISSUE THREAD

**Issue by orsic** [ahrm/sioyek#214]
Does sioyek support copying to clipboard?

If no, can we get this feature?

**Comment by mark2185** [comment]
Have you tried what [the documentation](https://sioyek-documentation.readthedocs.io/en/latest/usage.html#miscellaneous) suggests?
```
Copy text by first selecting it and pressing <Ctrl c>. (copy command)
```

**Comment by orsic** [comment]
Yes, Cmd+C actually works as expected. Closing issue
