### ISSUE TITLE
[Touch support] scrolling

### ISSUE THREAD

**Issue by TornaxO7** [ahrm/sioyek#215]
Hello, I'm trying to scroll with my fingers on the screen but the text gets highlighted instead. Do you have an idea how I can fix that?

**Comment by ahrm** [comment]
We have a `toggle_mouse_drag_mode` command that does that.

**Comment by TornaxO7** [comment]
yeet, it works! Thank you!

**Comment by TornaxO7** [comment]
@ahrm is it possible to make it the default behaviour of sioyek to set `toggle_mouse_drag_mode`?

I put the following into `~/.config/sioyek/prefs_user.config`:
```
toggle_mouse_drag_mode 1
```
but it doesn't seem to work.

**Comment by ahrm** [comment]
> @ahrm is it possible to make it the default behaviour of sioyek to set `toggle_mouse_drag_mode`?
> 
> I put the following into `~/.config/sioyek/prefs_user.config`:
> 
> ```
> toggle_mouse_drag_mode 1
> ```
> 
> but it doesn't seem to work.

You need to add this to your `prefs_user.config`:

```
startup_commands toggle_mouse_drag_mode
```
