### ISSUE TITLE
Multiple instances of sioyek or display multiple documents

### ISSUE THREAD

**Issue by TornaxO7** [ahrm/sioyek#217]
Is it possible to run multiple instances of sioyek? Because I have two documents which I want to look at: On the one pdf my exercises and on the other one my lecture.

**Comment by ahrm** [comment]
Yes. If you are using command line you can pass `--new-instance` to sioyek and it launches a  new instance.
Alternatively you can add this to your `prefs_user.config` which makes this the default behaviour:
```
should_launch_new_instance 1
```

**Comment by TornaxO7** [comment]
Thank you!
