### ISSUE TITLE
[Feature Request] Fit to page height smart

### ISSUE THREAD

**Issue by mrro22** [ahrm/sioyek#220]
Would it be possible to implement a smart zoom feature that fits to content height instead of width? I believe Zathura has something like this.

(The current fit_to_page_width_smart is excellent by the way). Thanks!

**Comment by ahrm** [comment]
Added `fit_to_page_height_smart` option in 09702de8dbb18ca6311fab67dd45e16ff70aacf1.

**Comment by mrro22** [comment]
Works really well for the first page. But when you scroll to the next page, it seems to zoom based on fit_to_page_width_smart. This is a great feature of the smart width zoom because the automatic dynamic zoom handles pages of different width and centering very well. Would be great if the height_smart option could do the same, re-zooming and re-centering dynamically for each new page.

Thank you! Gonna go donate to this lovely project.

**Comment by ahrm** [comment]
Isn't that the same thing as presentation mode (`toggle_presentation_mode` command)?

**Comment by mrro22** [comment]
I confess I didn't know about toggle_presentation_mode... It's a pretty good substitute and definitely usable for my purposes. I'd say the advantages of what I'm proposing are 1. fit_to_page_height_smart is whitespace-aware and 2. fit_to_page_height_smart would respond to moving the visual mark around in a way that presentation mode doesn't quite work great with yet. But point taken, it's presentation mode is definitely usable for these purposes.

**Comment by ahrm** [comment]
Added a config option in 08d11e3757a4244a18516070f74202c788857a7b which allows you to ignore whitespaces in presentation mode:
```
ignore_whitespace_in_presentation_mode 1
```
Also in 50c078472f85dad3f615dfd79195bb6db92ac7d9 fixed the bug where we would move to the next page too soon when presentation mode and visual mark mode were activated (which I assume is the issue you were having with visual mark in presentation mode).

**Comment by mrro22** [comment]
Works great. You're the best, ahrm!!
