### ISSUE TITLE
Change default browser for external searches

### ISSUE THREAD

**Issue by bertulli** [ahrm/sioyek#222]
Hi!
First of all, thank you very much for your work.

I want to change the default browser used to perform external searches. I use Firefox for my usual needs, but the proxy of my University is currently set up on Chrome, which is the browser I use when I have to access papers in online databases (ArXiv, IEEE, ACM and the like). External search works great, but by defaults it searches Google Scholar on Firefox (I suppose it retrieves my default browser).

How can I tell Sioyek to use a different browser, let's say when I press <kbd>s s</kbd>?

Thank you!

**Comment by ahrm** [comment]
We don't choose the browser, we just open the URL and the operating system decides which browser to choose. So the only way would be to change the default browser on operating system. One thing you could do is to use the execute commands, in newer builds of sioyek `%3` expands to selected text, so you can write a script to get the selected text and use your preferred browser to open it. Unfortunately I have not added the documentation for these commands to the documentation but this post explains it:
https://github.com/ahrm/sioyek/issues/127#issuecomment-1034014397

**Comment by bertulli** [comment]
Thank you! I'll investigate it and if I succeed I report the solution here, so it can be integrated in the docs

**Comment by ahrm** [comment]
Good luck! Just be warned that the code that parses commands is very bad :/ . So it can't parse complicated commands like `command1 %1; command2` or commands that have space in them etc. If you want to execute a complicated command, I recommend first putting all your commands in a script and then executing your script like `/path/to/script.sh %1 %2 %3`.

**Comment by bertulli** [comment]
Ok, I have a working solution:

- `~/.config/sioyek/keys_user.config`:
```config
execute_predefined_command     <C-e>
execute_command_s      s
```
- `~/.config/sioyek/prefs_user.config`:
```config
execute_command_s	chromium https://scholar.google.com/scholar?q=%3
```

Now **I can search** with `<C-e> s`.

While this is ok, I tried to completely replace `ss`, and I can't. What I mean is, even if I manually change file `/etc/sioyek/keys.config`, commenting out `#external_search		s`, and having in `~/.config/keys_user.config`:
```config
execute_predefined_command     q
execute_command_s      s
```
works when pressing `q s`, But
```config
execute_predefined_command     q
execute_command_s      s
```
does **not** work when pressing `s s`. In fact, when pressing the first `s`, nothing shows up in the bottom part of the window, and the attached terminal window (which I used for monitoring) stays silent (it doesn't report an `invalid command (key:s)`).

Is the key <kbd>s</kbd> somehow hardcoded, so that it cannot be remapped?
Thanks

**Comment by ahrm** [comment]
Is the second snippet correct? Why would 
```
execute_predefined_command     q
execute_command_s      s
```
work when pressing ss?

**Comment by bertulli** [comment]
You're completely right, I copy-pasted twice the same file, sorry. I edited the message. My bad! :-)

**Comment by ahrm** [comment]
I tested it and it works for me. Are you using the correct files? Note that this:
```
execute_predefined_command     s
```
should be in `keys_user.config` and this:
```
execute_command_s	chromium https://scholar.google.com/scholar?q=%3
```
should be in your `prefs_user.config`.
This setting:
```
execute_command_s      s

``` is wrong and should be removed.

**Comment by bertulli** [comment]
Thanks, you're right! I put that because I thought I needed to **also** indicate the key of the actual command, where instead it is set by the command itself. I didn't read the documentation completely, sorry.

Anyway, **now it works**! And by the way, even restoring the default file `/etc/sioyek/keys.config`, the `*_user.config` ones correctly take precedence, so this setting should be update-resilient. Thank you very much for your kind and quick help! This thread can be marked as solved for me.
