### ISSUE TITLE
How to clear recently opened documents list?

### ISSUE THREAD

**Issue by haitrungle** [ahrm/sioyek#223]
I want to clear the list of recently opened documents to make it less cluttered. Is there any way to do this?

Being able to remove individual entries from the list would be even better.

**Comment by ahrm** [comment]
You can press the delete key in recent documents menu to delete the selected document.

**Comment by haitrungle** [comment]
Thank you, exactly what I wanted

**Comment by NightMachinery** [comment]
https://github.com/ahrm/sioyek/issues/904
