### ISSUE TITLE
The `tutorial.pdf` file as a case has no TOC, and I don't know how to automate table of content generation for it.

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#224]
prefs_user_config:
```
create_table_of_contents_if_not_exists  1
max_created_toc_size 5000
```

**Comment by ahrm** [comment]
Yes. The table of content generation is a heuristic and doesn't work for all documents. Ironically it doesn't work for sioyek tutorial itself! It does work for most documents that I care about though.
