### ISSUE TITLE
Language without spaces like Chinese, it is difficult to highlight the area that you really want to.

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#225]
Thanks for this great tool.
I can understand your design for autocompletion of words in highlighted areas. But for a language without spaces like Chinese, it is difficult to highlight the area that you really want to. Is it possible to provide a setting option to turn off automatic word selection? Thanks again for your great work.

![highlighted issue](https://s2.loli.net/2022/05/11/AZ9ioKrQO8fxJL2.jpg)

**Comment by ahrm** [comment]
The automatic word selection should only be applied when you double click and then select. If you single click there should be no word selection. Is it not working for you?

**Comment by wenbopeng** [comment]
> The automatic word selection should only be applied when you double click and then select. If you single click there should be no word selection. Is it not working for you?

Yes I think I understand what you're saying. It's valid for English. After double click it, I select the entire line. After one click, I can really select the part I want (as shown in the figure √). But after using the highlight command `hy`, the highlighted part is not the real part I selected, sioyek will automatically highlight the beginning and end of the line together (as shown in the figure ×),

**Comment by ahrm** [comment]
Added an option in e096c90e91d9b8e1bb7708a363af00a795ab5d8e to enable exact highlighting. You can enable it in your `prefs_user.config` by adding the following:
```
exact_highlight_select 1
```

**Comment by wenbopeng** [comment]
> Added an option in [e096c90](https://github.com/ahrm/sioyek/commit/e096c90e91d9b8e1bb7708a363af00a795ab5d8e) to enable exact highlighting. You can enable it in your `prefs_user.config` by adding the following:
> 
> ```
> exact_highlight_select 1
> ```

Moved to cry😀. Your development speed is incredible！
