### ISSUE TITLE
[bug] keyboard_select not work

### ISSUE THREAD

**Issue by bommbo** [ahrm/sioyek#226]
Thanks for awesome soft. I like this soft. I am a vimer.
I want to know how to use "keyboard_select", when I typed "v" key. nothing happened.

**Comment by ahrm** [comment]
Which version of sioyek are you using (are you using builds in release page or are you building it yourself?). I recently updated the documentation and it is actually more recent than the builds so there are some features in the documentation that is missing from the builds. I will release a new build soon.

**Comment by bommbo** [comment]
It's AUR -- sioyek-git.

**Comment by ahrm** [comment]
Yeah, that's probably an old build of sioyek. If you want to test the latest features I have an experimental build here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.322

**Comment by bommbo** [comment]
I can see hint when type "v" key. But next? The prompt doesn't disappear. I can't type "l" or right arrow to choose text.

**Comment by ahrm** [comment]
No the way you select is by typing the symbols corresponding to beginning and the end of selection. For example: 'af hg'.

**Comment by bommbo** [comment]
Thank you. I misunderstand.
