### ISSUE TITLE
Hope to optimize the text selection

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#227]
Hope to add text selection: click at the beginning of the text, hold `shift` and click the end of the text to select and then further highlight.

It`s more efficient than using the mouse to swipe.

**Comment by ahrm** [comment]
I understand this is can be a useful feature but I think it is pretty niche and I would like to keep shift+click shortcut available in case it could be used for a more useful feature (for example it could be used to directly open a portal to destination). For these reasons I don't think I will implement this.
