### ISSUE TITLE
Hotkey to follow pdf links

### ISSUE THREAD

**Issue by Weznon** [ahrm/sioyek#23]
One feature of Zathura which I use a lot is the ability to follow links from a hotkey - the way it works is you press a hotkey and visible pdf links are highlighted and given a number. Typing the corresponding number to a link then makes the viewer follow it.

Would it be possible to get functionality similar to this in Sioyek?

**Comment by ahrm** [comment]
Added in 0d2fab3af8c1500cec15aaf3873f63517430cdfd.


https://user-images.githubusercontent.com/6392321/131333870-d3a190c5-0579-4cd5-b425-2c3bf6c02a79.mp4
