### ISSUE TITLE
Suggestion：a command that outputs the current filename and page number

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#230]
I use Obsidian, using `[[filename.pdf#page=10]]` can preview the file and jump to the corresponding page number 10. Hope sioyek to provide a command to get the file name and current page number.
Thank you very much.

**Comment by ahrm** [comment]
We already had the ability to use current file name. In db83becfc2232eece486c0cabb7fbbe604051996 I added the ability to use page numbers as well using external commands. You can see this thread for how to use this feature: https://github.com/ahrm/sioyek/issues/222. Now `%4` expands the the current page number.

**Comment by wenbopeng** [comment]
thanks a lot
I want to copy the filename and page number to the clipboard, can `execute_predefined_command_a` do?

**Comment by ahrm** [comment]
Yes, you can use write a script that uses `xclip` to copy its arguments to clipboard and then run the script using `execute_predefined_command_a `.

**Comment by wenbopeng** [comment]
> Yes, you can use write a script that uses `xclip` to copy its arguments to clipboard and then run the script using `execute_predefined_command_a `.

`xclip` may be a linux command, I use windows and I don't know how should I copy the filename and page number to the clipboard

**Comment by ahrm** [comment]
Here is a script I wrote for windows:

First write this script into a batchfile (with '.bat' extension):

```
set /A PAGE=%2
set /A PAGE=PAGE+1
echo [[%1#page=%PAGE%]] | clip
```

And add the following to your `prefs_user.config`:

```
execute_command_d D:\sioyek-scripts\copy.bat "%2" %4
```
(you need to replace the path with the path of your script). Now you can execute the command by first running `execute_predefined_command` and then pressing `d`.

**Comment by wenbopeng** [comment]
> Here is a script I wrote for windows:
> 
> First write this script into a batchfile (with '.bat' extension):
> 
> ```
> set /A PAGE=%2
> set /A PAGE=PAGE+1
> echo [[%1#page=%PAGE%]] | clip
> ```
> 
> And add the following to your `prefs_user.config`:
> 
> ```
> execute_command_d D:\sioyek-scripts\copy.bat "%2" %4
> ```
> 
> (you need to replace the path with the path of your script). Now you can execute the command by first running `execute_predefined_command` and then pressing `d`.

I have learned to use this setting of yours, looking forward to `%4` coming soon😀

**Comment by ahrm** [comment]
Did you remove the `"` in
```
execute_command_d D:\sioyek-scripts\copy.bat "%2" %4
```
? You should not remove those quotations because otherwise it would treat the first word as an argument. If you want to remove the quotations you should do that in the script.

**Comment by wenbopeng** [comment]
> 

Yes, after finding the results with `"`, I removed them. Now it works.

**Comment by ahrm** [comment]
By the way a build of sioyek with new changes is available here:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.329

**Comment by wenbopeng** [comment]
yes. I followed it, your development is so fast and your response to users is awesome😀
