### ISSUE TITLE
external_search not working

### ISSUE THREAD

**Issue by faurehu** [ahrm/sioyek#233]
When I select text and then press `s`, the command bar indicates `external_search waiting for symbol`. However, when I press `s` (again) or `l`, it exists 'waiting mode' and I don't get any feedback.

I'm using MacOS 12.3.1 on a M1 Max and using sioyek v1.3.0

**Comment by ahrm** [comment]
Yes, external search appears to not be working on MacOS. I will investigate this issue but for now you can read this thread to see how to emulate external search using another feature of sioyek:
https://github.com/ahrm/sioyek/issues/222

**Comment by ahrm** [comment]
This bug should be fixed in f9a4cbf50a4c4bbd356eea38bffba2df0eb0fb02. Here is an experimental build with latest fixes applied:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.330

**Comment by faurehu** [comment]
Awesome, thank you.
