### ISSUE TITLE
GIO Operation not supported

### ISSUE THREAD

**Issue by ejuarezg** [ahrm/sioyek#237]
Hi,

I started using the sioyek appimage from the latest release (v1.3.0) and I get the following error when reading through the tutorial and using the `ss` and `sl` shortcuts

```
gio: file:https://scholar.google.com/scholar%3Fq=Attention%20is%20all%20you%20need.: Operation not supported
```

I'm no pop os 22.04 and have the `gvfs-backends` package installed if that matters.

**Comment by ahrm** [comment]
Should be fixed in f9a4cbf50a4c4bbd356eea38bffba2df0eb0fb02. Here is a build with that fix: https://github.com/hexomancer/sioyek/releases/tag/v0.31.330
