### ISSUE TITLE
mention changes from qt5 to qt6 (one needs to compile qt3d)

### ISSUE THREAD

**Issue by matu3ba** [ahrm/sioyek#238]
With the instructions from README I get
```txt
Info: creating stash file /home/misterspoon/dev/git/c/sioyek/.qmake.stash
Project ERROR: Unknown module(s) in QT: 3dinput
```

The underlying reason is that qt6 does not ship Qt3D and one needs to build it (not shipped within the installer).
https://forum.qt.io/topic/125867/1-error-project-error-unknown-module-s-in-qt-3dextras-3dcore-3drender-3dinput/12

Alternatively, one needs to configure qmake to use qt5.

**Comment by ahrm** [comment]
Well, we specifically mention that you need Qt 5 in build instructions.
