### ISSUE TITLE
Project ERROR: Unknown module(s) in QT

### ISSUE THREAD

**Issue by SteshinSS** [ahrm/sioyek#24]
Hi. The features look awesome, so I tried to install the viewer.
I did:
`sudo apt-get install qt5-default libharfbuzz-dev`
So :
```bash
> qmake --version
QMake version 3.1
Using Qt version 5.12.8 in /usr/lib/x86_64-linux-gnu
```
But the build is failing:
```bash
In file included from thirdparty/freeglut/src/fg_internal.h:192,
                 from thirdparty/freeglut/src/fg_callbacks.c:29:
thirdparty/freeglut/src/x11/fg_internal_x11.h:42:10: fatal error: X11/extensions/XInput.h: No such file or directory
   42 | #include <X11/extensions/XInput.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makethird:200: build/release/thirdparty/freeglut/src/fg_callbacks.o] Error 1
Info: creating stash file /home/simon/utilities/sioyek/.qmake.stash
Project ERROR: Unknown module(s) in QT: quickwidgets 3dcore 3danimation 3dextras 3dinput 3dlogic 3drender
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat 'sioyek': No such file or directory
```
I googled the error and tried to do `sudo apt install qtdeclarative5-dev`, but the build is still failing with this message:
```bash
Project ERROR: Unknown module(s) in QT: 3dcore 3danimation 3dextras 3dinput 3dlogic 3drender
```

How should I install Qt5 properly? Sorry for noob question, haha

**Comment by guichristmann** [comment]
I literally had the same problem 5 minutes ago. What I was missing was: `sudo apt install qt3d5-dev` on Ubuntu 20.04.

**Comment by SteshinSS** [comment]
Thanks, it worked!

**Comment by SHilser** [comment]
I get the (almost) exact same error, but installing what @guichristmann suggested didn't help in my case. It's still missing the quickwidgets module. 

```
    CC build/release/thirdparty/freeglut/src/fg_callbacks.o
In file included from thirdparty/freeglut/src/fg_internal.h:192,
                 from thirdparty/freeglut/src/fg_callbacks.c:29:
thirdparty/freeglut/src/x11/fg_internal_x11.h:42:10: fatal error: X11/extensions/XInput.h: No such file or directory
   42 | #include <X11/extensions/XInput.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makethird:200: build/release/thirdparty/freeglut/src/fg_callbacks.o] Error 1
Project ERROR: Unknown module(s) in QT: quickwidgets
make: *** No targets specified and no makefile found. Stop.
cp: cannot stat 'sioyek': No such file or directory
```
I already tried searching with `sudo apt search quickwidgets`, but the two packages shown (`python3-pyside2.qtquickwidgets` `libqt5quickwidgets5` are already installed.

I'm on  `Ubuntu 21.04 x86_64` so I'm not sure if that means I can't install the app, because the `qt5-default` package is no longer included? Installing them separately as suggested [here](https://stackoverflow.com/questions/67373586/install-qt5-on-ubuntu-21-04) didn't work either. Not sure that is the reason though. Any other ideas what I'm missing?

I'll make this a new issue and link back here, if people think the problem lies elsewhere.

**Comment by ahrm** [comment]
> I get the (almost) exact same error, but installing what @guichristmann suggested didn't help in my case. It's still missing the quickwidgets module.
> 
> ```
>     CC build/release/thirdparty/freeglut/src/fg_callbacks.o
> In file included from thirdparty/freeglut/src/fg_internal.h:192,
>                  from thirdparty/freeglut/src/fg_callbacks.c:29:
> thirdparty/freeglut/src/x11/fg_internal_x11.h:42:10: fatal error: X11/extensions/XInput.h: No such file or directory
>    42 | #include <X11/extensions/XInput.h>
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makethird:200: build/release/thirdparty/freeglut/src/fg_callbacks.o] Error 1
> Project ERROR: Unknown module(s) in QT: quickwidgets
> make: *** No targets specified and no makefile found. Stop.
> cp: cannot stat 'sioyek': No such file or directory
> ```
> 
> I already tried searching with `sudo apt search quickwidgets`, but the two packages shown (`python3-pyside2.qtquickwidgets` `libqt5quickwidgets5` are already installed.
> 
> I'm on `Ubuntu 21.04 x86_64` so I'm not sure if that means I can't install the app, because the `qt5-default` package is no longer included? Installing them separately as suggested [here](https://stackoverflow.com/questions/67373586/install-qt5-on-ubuntu-21-04) didn't work either. Not sure that is the reason though. Any other ideas what I'm missing?
> 
> I'll make this a new issue and link back here, if people think the problem lies elsewhere.

You need to install xinput (I think it's package name was libxi? I am not sure though).

**Comment by SHilser** [comment]
Hmm, I don't get the fatal errors regarding the xinput anymore, after installing the *dev* package called `libxi-dev` (I already had the regular one called `libxi6` installed). After that I got another fatal error for Xrandr, which again could be solved by installing the dev-package `libxrandr-dev`. After that I'm only left with some warnings and the same Poject error at the end saying 

```
make: Nothing to be done for 'default'.
Project ERROR: Unknown module(s) in QT: quickwidgets
make: *** No targets specified and no makefile found. Stop.
cp: cannot stat 'sioyek': No such file or directory
```
Thanks for the help so far.

**Comment by ahrm** [comment]
> Hmm, I don't get the fatal errors regarding the xinput anymore, after installing the _dev_ package called `libxi-dev` (I already had the regular one called `libxi6` installed). After that I got another fatal error for Xrandr, which again could be solved by installing the dev-package `libxrandr-dev`. After that I'm only left with some warnings and the same Poject error at the end saying
> 
> ```
> make: Nothing to be done for 'default'.
> Project ERROR: Unknown module(s) in QT: quickwidgets
> make: *** No targets specified and no makefile found. Stop.
> cp: cannot stat 'sioyek': No such file or directory
> ```
> 
> Thanks for the help so far.

Have you installed `qtdeclarative5-dev`?

**Comment by SHilser** [comment]
Ah, thanks. that did the trick. After that the `build_linux.sh` script went through.
