### ISSUE TITLE
Some font colours not inverted in Dark Mode

### ISSUE THREAD

**Issue by hasantahir** [ahrm/sioyek#242]
I am on the latest version (v 1.3.0) on MacOS and notice that the colours of some fonts (such as superscripts for references) are not inverted. An example is shown below:

<img width="236" alt="image" src="https://user-images.githubusercontent.com/11236148/169714694-e6dae597-73ab-45ea-b7ad-3775fdd66181.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/11236148/169714699-e79382d2-94fc-44a0-b3d8-c777cb87f8a8.png">

The superscript `3` is unnoticeable against the black background. 

Thanks.

**Comment by hasantahir** [comment]
It is still there after the change.

**Comment by hasantahir** [comment]
Sharing another file with similar font colours for hyperlinks:
[Lab2-SDR.pdf](https://github.com/ahrm/sioyek/files/8755977/Lab2-SDR.pdf)

Adding screenshots from the light and dark modes:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/11236148/169855560-dbf108fc-26fb-44cf-b537-4422a3ffcf40.png">

<img width="935" alt="image" src="https://user-images.githubusercontent.com/11236148/169855565-e5d91fb8-89be-4863-9972-ddfcc3a2c578.png">

**Comment by ahrm** [comment]
What if you put your configs in `~/.config/sioyek/*_user.config`?

**Comment by hasantahir** [comment]
It works, thanks. I was modifying the file in `/Applications/sioyek.app/Contents/MacOS`

**Comment by hasantahir** [comment]
On a similar note, is it possible to change the contrast of the command menu?

<img width="865" alt="image" src="https://user-images.githubusercontent.com/11236148/169868948-88c25028-71ef-4d48-a4a0-b18e9dcc0cd6.png">

At the moment it is dark with black background.
