### ISSUE TITLE
Command :new_window does not open a new window

### ISSUE THREAD

**Issue by kiryph** [ahrm/sioyek#251]
I have compiled sioyek myself from HEAD:
```
❯ git log -n 1
commit ce23feff899497fefa1adaa9d80b1e50ac27801c (HEAD -> main, origin/main, origin/HEAD)
Author: ahrm <a.hr.mostafavi@gmail.com>
Date:   Tue May 24 12:37:03 2022 +0430

    Use the last focused window to open new documents
```

However, `:new_window` does not open a new window.

I have also mapped in `keys_user.config`
```
new_window <C-n>
```
![Screenshot 2022-05-25 at 09 33 15](https://user-images.githubusercontent.com/371756/170206605-b67e8801-572f-435a-92ec-31ae45c77afa.png)

**Comment by ahrm** [comment]
I was not able to reproduce the issue on windows or linux. I did some random changes in 7418435918de859b8a4ac74ad033c2e2d6f163e5 but I am not sure if they fix the issue.

**Comment by kiryph** [comment]
Your "random" change has fixed it for me. 💯  👍 😍.
