### ISSUE TITLE
enable_fastread does not work on linux

### ISSUE THREAD

**Issue by payrim** [ahrm/sioyek#253]

**Comment by ahrm** [comment]
Have you added the following to your `prefs_user.config`?
```
enable_experimental_features 1
use_heuristic_if_text_summary_not_available 1

```

**Comment by wrestlerdude** [comment]
Same here :(

**Comment by wrestlerdude** [comment]
> Have you added the following to your `prefs_user.config`?
> 
> ```
> enable_experimental_features 1
> use_heuristic_if_text_summary_not_available 1
> ```

I get the same issue with linux, even with those lines added. Works perfectly fine on windows.

**Comment by ahrm** [comment]
I think changing
```
enable_experimental_features 1
```
to
```
enable_experimental_features 0
```
fixes the problem.

**Comment by wrestlerdude** [comment]
> I think changing
> 
> ```
> enable_experimental_features 1
> ```
> 
> to
> 
> ```
> enable_experimental_features 0
> ```
> 
> fixes the problem.

Doesn't change anything for me. Although, I do find it out does work... one strange problem though. It only works on any page that isn't the *first*.

**Comment by payrim** [comment]
> > I think changing
> > ```
> > enable_experimental_features 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> > enable_experimental_features 0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > fixes the problem.
> 
> Doesn't change anything for me. Although, I found that fastread does work on Linux... one strange problem though. It only works on any page that isn't the _first_.

did you do anything for it?
yeah nothing works for me
