### ISSUE TITLE
Add cli flag `--reuse-focused-window` when `should_launch_new_window` is set

### ISSUE THREAD

**Issue by kiryph** [ahrm/sioyek#256]
As described in issue #246, I have defined `x` `t` `<string>` to run texdoc to open the documentation for a LaTeX package in the current sioyek window.

`keys_user.config`:
```
execute_predefined_command x
```
`prefs_user.config`:
```
execute_command_t    /Users/kiryph/.local/bin/sioyek_texdoc.sh "%5" &
```

The script is
```sh
#!/usr/bin/env bash
FILENAME=$(texdoc -l --M $1 | head -1 | awk '{print $3}')
/Applications/sioyek.app/Contents/MacOS/sioyek --reuse-instance "$FILENAME"
```

However, when I add `should_launch_new_window 1` to `prefs_user.config`, my intention to open the file in the current window does not work anymore.

As far as I see it, this requires a new cli flag (maybe `--reuse-focused-window`) when the script invokes sioyek to reuse the focused window (if none the last) to override the global default setting to open in new window.

**Override with a cli flag `--reuse-focused-window` the setting `should_launch_new_window 1` occasionally**

**Comment by ahrm** [comment]
Added a `reuse-window` command line option in 0c3e9920961e020bd9162478dbf3cf687911c443.

**Comment by kiryph** [comment]
Thanks for adding this.

However, right now my script `/Users/kiryph/.local/bin/sioyek_texdoc.sh` does not work anymore when called from sioyek but still works when called from the command line.

I did not change anything else than recompiling and replacing /Applications/sioyek.app

The line `FILENAME=$(texdoc -l --M $1 | head -1 | awk '{print $3}')` does not work anymore. The shell variable `FILENAME` is now empty when called from sioyek.

`$1` still contains the result from `"%5"` from sioyek.

Do you have a clue/gut feeling what happened?

**Comment by ahrm** [comment]
That is strange because this line: `FILENAME=$(texdoc -l --M $1 | head -1 | awk '{print $3}')` has almost nothing to do with sioyek, except `$1`, so if the value of `$1` is set properly, I don't know what has happened.

**Comment by kiryph** [comment]
Yes, I also do not think this has anything to do with sioyek. I am really confused.
I added to the script:
```sh
$SHELL --version >> $HOME/sioyek_exe.log
/Library/TeX/texbin/texdoc --help >> $HOME/sioyek_exe.log
echo /Library/TeX/texbin/texdoc -l --M $1 >> $HOME/sioyek_exe.log
/Library/TeX/texbin/texdoc -l --M $1 >>  $HOME/sioyek_exe.log
echo "\$1=$1 FILENAME=\"$FILENAME\" /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window \"$FILENAME\"" >> $HOME/sioyek_exe.log
```

When I run it from sioyek with `x` `t` `fp`, following lines are added to the log
```
zsh 5.8 (x86_64-apple-darwin20.0)
/Library/TeX/texbin/texdoc -l --M fp
$1=fp FILENAME="" /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window ""
```
When I run it from the terminal, following lines are added to the log
```
zsh 5.8 (x86_64-apple-darwin20.0)
Usage: texdoc [OPTION]... NAME...
   or: texdoc [OPTION]... ACTION

Try to find appropriate TeX documentation for the specified NAME(s).
Alternatively, perform the given ACTION and exit.

Options:
  -w, --view        Use view mode: start a viewer. (default)
  -m, --mixed       Use mixed mode (view or list).
  -l, --list        Use list mode: show a list of results.
  -s, --showall     Use showall mode: show also "bad" results.

  -i, --interact    Use interactive menus. (default)
  -I, --nointeract  Use plain lists, no interaction required.
  -M, --machine     Machine-readable output for lists (implies -I).

  -q, --quiet       Suppress warnings and most error messages.
  -v, --verbose     Print additional information (e.g., viewer command).
  -D, --debug       Activate all debug output (equal to "--debug=all").
  -d LIST, --debug=LIST
                    Activate debug output restricted to LIST.
  -c NAME=VALUE     Set configuration item NAME to VALUE.

Actions:
  -h, --help        Print this help message.
  -V, --version     Print the version number.
  -f, --files       Print the list of configuration files used.
  --just-view FILE  Display FILE, given with full path (no searching).

Full manual available via `texdoc texdoc'.

Website: <https://tug.org/texdoc/>
Repository: <https://github.com/TeX-Live/texdoc>
Please email bugs to <texdoc@tug.org>.
/Library/TeX/texbin/texdoc -l --M fp
fp	4.0	/usr/local/texlive/2022/texmf-dist/doc/latex/fp/documentation.pdf		Documentation
fp	1.8	/usr/local/texlive/2022/texmf-dist/doc/latex/fp/README		Readme
$1=fp FILENAME="/usr/local/texlive/2022/texmf-dist/doc/latex/fp/documentation.pdf" /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window "/usr/local/texlive/2022/texmf-dist/doc/latex/fp/documentation.pdf"
```

It certainly looks like the invocation of texdoc (also with an absolute path) does nothing in the case of sioyek.

Can this be related to security settings? (too bad you do not use macOS).
Does `QProcess` sandboxing by default? But it worked before. To be honest, I feel lost. I started googling in all directions.

**Comment by ahrm** [comment]
Can you find the last commit in which your script works?

**Comment by kiryph** [comment]
I could identify the problem by logging stderr as well with `2>&1`:
```
/Library/TeX/texbin/texdoc --version >> $HOME/sioyek_exe.log 2>&1
```
`texdoc` itself calls again `texlua` which was not anymore on the path.
```
zsh 5.8 (x86_64-apple-darwin20.0)
env: texlua: No such file or directory
/Library/TeX/texbin/texdoc -l --M fp
$1=fp FILENAME="" /Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window ""
```
I am not sure what on my system has changed or if sioyek changed how to run processes and how it inherits the system environment variable `$PATH`. Maybe I have invoked sioyek unconsciously until now always from the terminal where `$PATH` was set correctly.

I assume, when sioyek is started from the GUI, the script is run by `zsh --non-interactive --non-login` which ignores `/etc/zprofile` which appends via a helper function the MacTeX Path `/Library/TeX/texbin`:
```
+----------------+-----------+-----------+------+
|                |Interactive|Interactive|Script|
|                |login      |non-login  |      |
+----------------+-----------+-----------+------+
|/etc/zshenv     |    A      |    A      |  A   |
+----------------+-----------+-----------+------+
|~/.zshenv       |    B      |    B      |  B   |
+----------------+-----------+-----------+------+
|/etc/zprofile   |    C      |           |      |
+----------------+-----------+-----------+------+
|~/.zprofile     |    D      |           |      |
+----------------+-----------+-----------+------+
|/etc/zshrc      |    E      |    C      |      |
+----------------+-----------+-----------+------+
|~/.zshrc        |    F      |    D      |      |
+----------------+-----------+-----------+------+
|/etc/zlogin     |    G      |           |      |
+----------------+-----------+-----------+------+
|~/.zlogin       |    H      |           |      |
+----------------+-----------+-----------+------+
|                |           |           |      |
+----------------+-----------+-----------+------+
|                |           |           |      |
+----------------+-----------+-----------+------+
|~/.zlogout      |    I      |           |      |
+----------------+-----------+-----------+------+
|/etc/zlogout    |    J      |           |      |
+----------------+-----------+-----------+------+
```

Anyhow.

By exporting the environment variable `$PATH` with the missing path within the script solved the problem. 
```zsh
#!/bin/zsh
export PATH="/Library/TeX/texbin/:$PATH"
FILENAME=$(/Library/TeX/texbin/texdoc -l --M $1 | head -1 | awk '{print $3}')
/Applications/sioyek.app/Contents/MacOS/sioyek --reuse-window "$FILENAME"
```
