### ISSUE TITLE
[Bug] Keypad `enter` does not accept the input on the search and add_bookmark menus

### ISSUE THREAD

**Issue by PedroLima92** [ahrm/sioyek#259]
- Both these menus seem to be implemented similarly. Other commands may use it, but these are the two that I noticed.
- `KP_enter` works fine on other contexts like choosing a command from the command-list, or a link from the table of contents and alike.

**Comment by ahrm** [comment]
Should be fixed in 43e36c9850f4eb7d393ddec72ac8a43fb36ccef1.
