### ISSUE TITLE
Standardised location for config files

### ISSUE THREAD

**Issue by d-miketa** [ahrm/sioyek#26]
Hi, thanks for this project – seems to be scratching many long-standing itches!

Does the app look for config files in the usual Linux/Mac directories such as `.config/sioyek` etc? If not, could it?

Thanks!

**Comment by ahrm** [comment]
We store it wherever `QStandardPaths::AppDataLocation` returns. I am not sure where it is in each system.

**Comment by d-miketa** [comment]
I see, thanks for pointing me in that direction. 

Looking at https://doc.qt.io/qt-5/qstandardpaths.html, the following standard Linux path is basically what I mean:
`AppConfigLocation | "~/.config/<APPNAME>", "/etc/xdg/<APPNAME>"`

It's customary to read `~/.config/<APPNAME>` (or, more generally, `$XDGCONFIG/<APPNAME>`) in macOS, too, although the standard Qt path is `AppConfigLocation = "~/Library/Preferences/<APPNAME>"`. This helps keep all configuration files in one location, bundle them up into a personal git repo and upload to Github etc.

**Comment by randomn4me** [comment]
I'm currently trying to package this software to archlinux and are also confused by the config paths. I've installed the config files to the location stated by the qstandardpaths documentation mentioned by you @d-miketa `AppDataLocation | "~/.local/share/<APPNAME>", "/usr/local/share/<APPNAME>", "/usr/share/<APPNAME>"`. In my case in the directory `$HOME/.local/share/sioyek`.

However, when running sioyek, it states the following locations for the config files:
```
default_config_path: /usr/bin/prefs.config
default_keys_path: /usr/bin/keys.config
user_config_path: $HOME/.config/.local/share/Sioyek/prefs_user.config
user_keys_path: $HOME/.config/.local/share/Sioyek/keys_user.config
database_file_path: $HOME/.config/.local/share/Sioyek/test.db
tutorial_path: $HOME/.config/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path$HOME/.config/.local/share/Sioyek/last_document_path.txt
```

This seems kind of weird, since it searches for config files within nested hidden directories (`.config/.local`). Is there any way to change this behaviour?

Cheers

**Comment by ahrm** [comment]
I added a compiler option to use more conventional linux paths. If you define `LINUX_STANDARD_PATHS` here:
https://github.com/ahrm/sioyek/blob/ecd653a61704f3c8c0c31a69ca08a33c3e6943aa/pdf_viewer/main.cpp#L82
then we use `~/.local/share/sioyek` for data files and `~/.config/sioyek` for config files.

Of course now the package manager must make sure to put the `shaders` folder and `tutorial.pdf` in `~/.local/share/sioyek` and put the `keys.config` and `prefs.config` files in `~/.config/sioyek` .

**Comment by ahrm** [comment]
But if your only problem is the config files we might be able to add additional config file locations without breaking backward compatibility because I added the ability to have multiple config file locations in 853d88d12bd52d2c55d9ed9de91381ef96bc389d .

**Comment by d-miketa** [comment]
> But if your only problem is the config files we might be able to add additional config file locations without breaking backward compatibility because I added the ability to have multiple config file locations in [853d88d](https://github.com/ahrm/sioyek/commit/853d88d12bd52d2c55d9ed9de91381ef96bc389d) .

Yes, I'm only interested in the config files. And supporting several files (with a clear hierarchy) is common practice, so your proposal seems like the most natural solution!

**Comment by Endle** [comment]
@randomn4me I'm packaging sioyek for fedora. Currently, I'm hardcoding the resource path to `/usr/share/sioyek` with [this patch](https://copr-dist-git.fedorainfracloud.org/cgit/endle/sioyek/sioyek.git/tree/sioyek_use_usr_share.patch?id=128567ed015fc96155251b77002e90d65cc43ab1)

However, I don't like this hard-coding way. Do you have any ideas about these config/shader files path?

[Here is my spec file](https://copr-dist-git.fedorainfracloud.org/cgit/endle/sioyek/sioyek.git/tree/sioyek.spec?id=128567ed015fc96155251b77002e90d65cc43ab1). It works for the minimal functions. Hope it helps

**Comment by randomn4me** [comment]
@Endle I added this line `sed -i 's/\/\/#define LINUX_STANDARD_PATHS/#define LINUX_STANDARD_PATHS/' pdf_viewer/main.cpp` to the pkgfile to uncomment the define (please comment if there is an easier way). This way sioyek uses the default paths, as noted by @ahrm (thanks for pointing this out).

> I added a compiler option to use more conventional linux paths. If you define `LINUX_STANDARD_PATHS` here:
> 
> https://github.com/ahrm/sioyek/blob/ecd653a61704f3c8c0c31a69ca08a33c3e6943aa/pdf_viewer/main.cpp#L82
> 
> then we use `~/.local/share/sioyek` for data files and `~/.config/sioyek` for config files.
> 
> Of course now the package manager must make sure to put the `shaders` folder and `tutorial.pdf` in `~/.local/share/sioyek` and put the `keys.config` and `prefs.config` files in `~/.config/sioyek` .

**Comment by Endle** [comment]
> please comment if there is an easier way

@randomn4me I think we can add such a line in `pdf_viewer_build_config.pro`
```
DEFINES += LINUX_STANDARD_PATHS
```

[ref](https://stackoverflow.com/a/3350169/1166518)

My commit: https://github.com/Endle/sioyek/commit/2af315b5efcd23a92f8ff282a24ef4d66167acce

**Comment by ahrm** [comment]
> > But if your only problem is the config files we might be able to add additional config file locations without breaking backward compatibility because I added the ability to have multiple config file locations in [853d88d](https://github.com/ahrm/sioyek/commit/853d88d12bd52d2c55d9ed9de91381ef96bc389d) .
> 
> Yes, I'm only interested in the config files. And supporting several files (with a clear hierarchy) is common practice, so your proposal seems like the most natural solution!

I added more paths for Mac and Windows in 6e8a58d9134b016335da36d7ca17a65fba4425f3 . I haven't had the chance to test it on MacOS though.

**Comment by PurpleAzurite** [comment]
Why not have the application read the shader and tutorial.pdf file just from /usr/share/sioyek on linux? This is customary practice. On archlinux for example, package managing rules dictate that packages are not allowed to write to a user's home directory by default. If configs are to be written there, it is A) either the application that should do it itself, or B) it is the user's job to copy over the files. Option B is not obvious to most users. Please consider having the application create these files, or just have them be read from usr/share.

You can find the discussion about this on: https://aur.archlinux.org/packages/sioyek-git/

**Comment by ahrm** [comment]
> Why not have the application read the shader and tutorial.pdf file just from /usr/share/sioyek on linux? This is customary practice, and there is no point in an extra copy of these files to exist in the home dir. On archlinux for example, package managing rules dictate that packages are not allowed to write to a user's home directory by default. If configs are to be written there, it is A) either the application that should do it itself, or B) it is the user's job to copy over the files. Option B is not obvious to most users. Please consider having the application create these files, or just have them be read from usr/share. Configs are now happily being read from ~/.config/sioyek, but you could probably have the application automatically write these files there to ease user experience.
> 
> You can find the discussion about this on: https://aur.archlinux.org/packages/sioyek-git/

Does it have to be `/usr/share/sioyek`? `/usr/bin/sioyek` is problematic?

**Comment by PurpleAzurite** [comment]
> > Why not have the application read the shader and tutorial.pdf file just from /usr/share/sioyek on linux? This is customary practice, and there is no point in an extra copy of these files to exist in the home dir. On archlinux for example, package managing rules dictate that packages are not allowed to write to a user's home directory by default. If configs are to be written there, it is A) either the application that should do it itself, or B) it is the user's job to copy over the files. Option B is not obvious to most users. Please consider having the application create these files, or just have them be read from usr/share. Configs are now happily being read from ~/.config/sioyek, but you could probably have the application automatically write these files there to ease user experience.
> > You can find the discussion about this on: https://aur.archlinux.org/packages/sioyek-git/
> 
> Does it have to be `/usr/share/sioyek`? `/usr/bin/sioyek` is problematic?

It is not problematic, so long as it works. But it is customary to put them under user/share/*. It's convention.
Just to clarify, the config files (or anything the user should be able to modify) belongs in .config/sioyek. Anything else should be under /usr/

**Comment by PurpleAzurite** [comment]
Please double check the comment above. I initially provided wrong information. The above comment is now corrected to reflect the rules.

**Comment by randomn4me** [comment]
And the system wide configuration files (to which the `shader` files and the `tutorial.pdf` should not count, as far as I know) could reside in `/usr/etc/`.

So as @PurpleAzurite said, my guess would be that sioyek should accept the following locations:

- `/etc/sioyek/{keys.config,prefs.config}` for the basic config files (could also be in `/etc/xdg currently done, which comply with the freedesktop standards as far as I know). These configurations, however, could be overwritten by a user-defined configuration in `$XDG_CONFIG_HOME/sioyek/{keys_user.config,prefs_user.config}` (or else `$HOME/.config/sioyek/{keys_user.config,prefs_user.config}`)
- `/usr/share/sioyek/{shaders,tutorial.pdf}` for the according files, which are necessary for the sioyek, but are no configuration files.

The rest is managed by the packaging process (location of the binary - in Arch's case `/usr/bin/sioyek`, dektop file, license, etc.). The current problem is the fact, that sioyek requires files inside the `$HOME` directory to properly function.

**Comment by ahrm** [comment]
In 2b342debdd9e19fa62243260233ac1da3b20d20c I have used the paths specified by @randomn4me :
* we use `/etc/sioyek` for default config files
* We use `/usr/share/sioyek` for tutorials and shaders

(Note that you still have to define `LINUX_STANDARD_PATHS` for these paths to apply)

**Comment by randomn4me** [comment]
Thanks for the commit :+1: 
I already packaged it in Arch with this fix and sioyek works now with system-wide files only :trophy:

**Comment by PurpleAzurite** [comment]
Yep and user files now need to be renamed to keys_user.config and prefs_user.config which is intuitive behavior.
