### ISSUE TITLE
[Feature request] Option to display full path in the list of recently opened files 

### ISSUE THREAD

**Issue by toolleeo** [ahrm/sioyek#261]
Problem: When the list of recently opened files (the one that opens with Shift-O) contains more than one file with the same name, it becomes difficult to distinguish the files. It happens to me all the time, since many pdfs are named "paper.pdf" or "thesis.pdf".

Solution: print the full path of the file in the list. This is unique in the filesystem.

Even better: add a configuration option to let the user decide whether he wants the full path or the current filename only.

**Comment by ahrm** [comment]
Added a `show_doc_path` option in 0d5bc0aae6237a484d6eaf6eb944ce865985929e. Can be configured like so:
```
show_doc_path 1
```
