### ISSUE TITLE
Crash when mouse selection on scanned PDF

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#264]
On non-text PDFs, sioyek crashes while holding down the left mouse button and dragging.

**Comment by ahrm** [comment]
Which commit of sioyek are you using? This should already be fixed in 3f71e8cc689b74f52c229d252776ccaed0a6a3cc.

**Comment by wenbopeng** [comment]
[Release Release v0.31.336 · hexomancer/sioyek]( https://github.com/hexomancer/sioyek/releases/tag/v0.31.336 ) solved the problem, thanks！
