### ISSUE TITLE
Bionic reading - toggle_fastread - styling

### ISSUE THREAD

**Issue by dborowiec10** [ahrm/sioyek#265]
I think sioyek is the only tool out there that really supports bionic reading for pdfs, which is amazing!
I was wondering whether it would be possible to modify the intensity of the greying/transparency on the non-boldened text when in fastread mode?
I really like bionic reading and I got used to the idea that focus text is bold and everything else stays as in original text.
It could be a matter of reducing the transparency on non-highlighted text or actually boldening the highlights and leaving other text as original.

**Comment by ahrm** [comment]
Added a `fastread_opacity` option in d735c1a410501024fe18c574e0aba4f525402dec. You can configure it like so:
```
fastread_opacity 0.5
```
