### ISSUE TITLE
Failed to open PDF files in Fedora

### ISSUE THREAD

**Issue by Endle** [ahrm/sioyek#28]
Hi, I'm trying to compile it under Fedora following [README](https://github.com/ahrm/sioyek/blob/main/README.md#linux)

```
g++ -Wl,-O1 -Wl,-rpath-link,/usr/lib64 -o sioyek book.o config.o database.o document.o document_view.o input.o main.o main_widget.o pdf_renderer.o pdf_view_opengl_widget.o sqlite3.o ui.o path.o utils.o synctex_parser.o synctex_parser_utils.o RunGuard.o moc_pdf_renderer.o moc_RunGuard.o   -ldl -Lmupdf/build/release -lmupdf -lmupdf-third -lharfbuzz -lfreetype -lgumbo -ljbig2dec -lopenjp2 -ljpeg -lz /usr/lib64/libQt5OpenGL.so /usr/lib64/libQt5QuickWidgets.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Quick.so /usr/lib64/libQt53DAnimation.so /usr/lib64/libQt53DExtras.so /usr/lib64/libQt53DRender.so /usr/lib64/libQt53DInput.so /usr/lib64/libQt53DLogic.so /usr/lib64/libQt53DCore.so /usr/lib64/libQt5OpenGLExtensions.a /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Sql.so /usr/lib64/libQt5QmlModels.so /usr/lib64/libQt5Qml.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Core.so -lGL -lpthread   
```

However, my compiled sioyek refused to open any pdf file

```
lizhenbo@localhost sioyek$ ./sioyek 
default_config_path: /home/lizhenbo/src/sioyek/prefs.config
default_keys_path: /home/lizhenbo/src/sioyek/keys.config
user_config_path: /home/lizhenbo/.local/share/Sioyek/prefs_user.config
user_keys_path: /home/lizhenbo/.local/share/Sioyek/keys_user.config
database_file_path: /home/lizhenbo/.local/share/Sioyek/test.db
tutorial_path: /home/lizhenbo/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path/home/lizhenbo/.local/share/Sioyek/last_document_path.txt
shader_path/home/lizhenbo/src/sioyek/shaders
config file change listener constructor called1starting index thread ...
figure indexing finished ... 
texture: 5
getting links .... for 0
invalid command; resetting to root
invalid command; resetting to root
invalid command; resetting to root
```

I created a [trivial PR](https://github.com/ahrm/sioyek/pull/27) for troubleshooting, but it provides little information

The AppImage version works well for me

Thanks

**Comment by ahrm** [comment]
Which sioyek executable are you running (you should be running the one in the `build` folder).

**Comment by Endle** [comment]
> Which sioyek executable are you running (you should be running the one in the `build` folder).

Thank you! If I execute `build/sioyek` it would be fine.

What's the difference between `build/sioyek`  and `./sioyek`? I can see `cp sioyek build/sioyek` in build script

**Comment by ahrm** [comment]
> > Which sioyek executable are you running (you should be running the one in the `build` folder).
> 
> Thank you! If I execute `build/sioyek` it would be fine.
> 
> What's the difference between `build/sioyek` and `./sioyek`? I can see `cp sioyek build/sioyek` in build script

`sioyek` assumes that the default configuration files and shaders are located next to the executable so the executable in root directory doesn't work because there are no configuration files next to it.

**Comment by Endle** [comment]
> > > Which sioyek executable are you running (you should be running the one in the `build` folder).
> > 
> > 
> > Thank you! If I execute `build/sioyek` it would be fine.
> > What's the difference between `build/sioyek` and `./sioyek`? I can see `cp sioyek build/sioyek` in build script
> 
> `sioyek` assumes that the default configuration files and shaders are located next to the executable so the executable in root directory doesn't work because there are no configuration files next to it.

Thank you. Seems that this is related to the issue https://github.com/ahrm/sioyek/issues/14#issuecomment-893201571

Would you like to review the PR, given sioyek to find shaders instead of assuming the same directory? I'm [trying to make a RPM package](https://copr.fedorainfracloud.org/coprs/endle/sioyek/) and I don't think putting these resources files under `/usr/bin` is a good idea.

**Comment by Endle** [comment]
> Is there a technical reason why this is the case or this is simply an aesthetic thing? 
> 
> I agree that user-editable configuration files should not be in `/usr/bin` (and they aren't) but why shouldn't the read-only files be placed in `/usr/bin`?
I'm new to linux packaging. IMHO, all packages (unless rare circumstances) should follow [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)


- /usr/bin Non-essential command binaries (not needed in single-user mode); for all users.
- /usr/share | Architecture-independent (shared) data.

I checked my `/usr/bin`. Everything in this directory is executable.
If we want to follow the guideline, I'd prefer to put the files into `/usr/bin/sioyek` and `/usr/share/sioyek/shaders`


>Because semantically the shaders and default configuration files are technically part of the program binary (I could have hard-coded them in the executable instead of putting them in separate files because they are not meant to be edited by users).

I think this is a good solution. combining these files into the binary sioyek could make the packaging process cleaner. I haven't read sioyek code yet. Do you think this approach would make further development, and the release process on mac and Windows easier or more difficult?

Thank you for your detailed reply!

**Comment by ahrm** [comment]
> I think this is a good solution. combining these files into the binary sioyek could make the packaging process cleaner.

I don't like hard-coding them very much because I intended the `keys.config` and `prefs.config` to be a template for users so they can copy the desired configurations from these files to `keys_user.config` and `prefs_user.config` and change them there.

Anyway, as a first step towards fixing path problems, I added support for multiple `keys_user.config` and `prefs_user.config` paths in 853d88d12bd52d2c55d9ed9de91381ef96bc389d so we can add to these paths without breaking backwards compatibility.
> Do you think this approach would make further development, and the release process on mac and Windows easier or more difficult?

This wouldn't change deploying on windows and mac that much, but I would rather not do it because of the reason above. I guess the best course of action would be to move shaders and default config files from next to executable to `/usr/share` as you said.
All path configuration is done in `configure_paths` function in `main.cpp` if you want to change it yourself.

Cheers.

**Comment by ahrm** [comment]
I added a compiler option to use more conventional linux paths. If you define `LINUX_STANDARD_PATHS` here:
https://github.com/ahrm/sioyek/blob/ecd653a61704f3c8c0c31a69ca08a33c3e6943aa/pdf_viewer/main.cpp#L82
then we use `~/.local/share/sioyek` for data files and `~/.config/sioyek` for config files.

Of course now the package manager must make sure to put the `shaders` folder in `~/.local/share/sioyek` and put the `keys.config` and `prefs.config` files in `~/.config/sioyek` .

**Comment by Endle** [comment]
@ahrm Thank you so much!
I'm looking at these changes and I'll update my RPM spec then.
How about close this issue?

**Comment by ahrm** [comment]
Hi!
Note that we recently changed the paths for tutorial/shaders and default config files. See https://github.com/ahrm/sioyek/issues/26#issuecomment-923003838 for more information.
