### ISSUE TITLE
Bug in copy_file

### ISSUE THREAD

**Issue by eshrh** [ahrm/sioyek#287]
This function: https://github.com/ahrm/sioyek/blob/main/pdf_viewer/utils.cpp#L1682 seems to be doing nothing. 

Is this function actually used anywhere (i can't find any references and neither can my LSP, but it's not listed under -Wunused-function by gcc), and could it cause it any problems?

**Comment by ahrm** [comment]
It is used here:

https://github.com/ahrm/sioyek/blob/e77593d9edf97eb51edaebd5dd1c701ee9a7a242/pdf_viewer/main.cpp#L298
