### ISSUE TITLE
Storage of highlights, bookmarks, etc 

### ISSUE THREAD

**Issue by almirnunes** [ahrm/sioyek#29]
Hi,

Many thanks for this great tool. It quickly became my favorite pdf reader.

What I would like to know is where the highlights and other file-related information are stored. I am trying to avoid losing it in case I move files or update Sioyek. Also, I would like to eventually export highlights and bookmarks.

Cheers

**Comment by ahrm** [comment]
They are stored in a sqlite database file named `test.db` (I know, I never bothered to change it!). The location depends on the operating system and whether you are using the portable version or not. In windows it is `C:/Users/<USER>/AppData/Roaming/sioyek` and in linux it is `~/.local/share/Sioyek`.

**Comment by ahrm** [comment]
Note that as of d8c8e1845b4e95d571b4637d53db9265676f1512 we significantly changed the way data is stored. Now we have two database files named `local.db` and `shared.db`. All marks, bookmarks, highlights and portals is stored in `shared.db`. As the name suggests, you can copy the `shared.db` file across machines and it just works. Moreover, we added an option in `prefs.config` named `shared_database_path` which allows you to specify the path for this shared file. For example you could use a path in your dropbox folder for this file and it will be automatically synced across your devices.
We also added the ability to import/export your data into a json file by entering the
`:import` and `:export` commands respectively.

Note that there are still no binary releases with these features available, I just wanted to mention it so future people who read this issue are not confused.

**Comment by almirnunes** [comment]
Thanks ahrm! That's huge!

**Comment by Mickychen00** [comment]
Hi, "shared_database_path" is a useful tool for highlights syn. But when I use my thinkpad laptop to read the pdf file which I have highlighted in another PC's sioyek app. However, I found the highlights' symbols are in wrong location. How can I fix it?

![image](https://user-images.githubusercontent.com/28621570/222340092-53f626de-a422-4ae4-acb8-0fd85818d020.png)
![image](https://user-images.githubusercontent.com/28621570/222340174-533e6a68-d54d-45bf-885e-561d3e89dea0.png)

**Comment by ahrm** [comment]
What happens if you create the highlights from the laptop itself? What is the resolution of you laptop and pc?

**Comment by Mickychen00** [comment]
When I create the highlights from laptop, the symbols appear correctly. But when I switch to my PC, the highlights created from laptop are in wrong location, too. 
My laptop's resolution is 1920 x 1080; My PC's resolution is 2560 x 1440.
Is there a trouble about using devices with different resolution?

**Comment by ahrm** [comment]
> Is there a trouble about using devices with different resolution?

There shouldn't be, if there is a problem then it is a bug. Is there anything special about your display setup? (e.g. multiple monitors, display scaling, etc.)

**Comment by Mickychen00** [comment]
Hi, I have tested sioyek's highlights on my Macbook Pro and my laptop's windows distro ( I use dual system of windows 10 and Manjaro with i3-wm). Both of them are Ok. My PC's system is also Manjaro with i3-wm.
It seems that only my laptop's Manjaro distro have this problem (Wrong location about highlights, vague font).
If it is resolution problem, my laptop's windows distro should encounter same question. But it's not.
I have reinstall the sioyek package (sioyek-appimage in AUR) in my laptop's Manjaro distro to keep same with PC's manjaro. But same trouble appears.
