### ISSUE TITLE
How to install sioyek on Windows 10 with pre-built binaries?

### ISSUE THREAD

**Issue by b4qX** [ahrm/sioyek#290]
Hi, sorry if this is an obvious question, but how do I actually install sioyek on windows with the pre-built binaries? I downloaded and unzipped the `sioyek-windows.zip` file from the releases page. But I couldn't find any executable to actually install the pdf reader, can you please guide me through how I could do so? Thanks.

**Comment by wenbopeng** [comment]
You don't need to install it, just double-click `sioyek.exe` in the unzipped folder to start it. You will be amazed by its power after you master it.
