### ISSUE TITLE
Font rendering broken on monitor in "portrait mode".

### ISSUE THREAD

**Issue by magjir** [ahrm/sioyek#293]
I have second monitor set in portrait mode and when opening a file, font rendering breaks. It fixes after exiting full screen and fullscreening again. See attached video. Everything works correctly on primary monitor.

Version: 1.3.0
OS: Win 10
Primary monitor: 1920x1080
Secondary monitor: 1024x1280

https://user-images.githubusercontent.com/33799459/176192809-93edc8ee-919f-481c-afeb-de6dd1b26062.mp4

**Comment by ahrm** [comment]
I think this is probably fixed in c446f7cf38830a7ac18ec5eb6ac2b30878fccd8b.
