### ISSUE TITLE
Can config files live in ~/.config dir?

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#295]
I have just started trying out sioyek so I might have missed this in the docs but I was wondering if sioyek looks for config files somewhere in the `~/config`? perhaps `~/.config/siyek`?

When I access the config files via the command palette they seem to be somewhere in the .AppImage package which is not great for managing dotfiles.

Unfortunately I couldn't install sioyek via `siyek-git` AUR package (I think it's broken as of 6a3d0e2) so I'm not sure if a proper installation also behaves in the same way

**Comment by ahrm** [comment]
I think you can already put your config files in `~/.config/sioyek`.

**Comment by ahrm** [comment]
Added `~/.config/sioyek` in a91a4e6619ace72339cc392060dd386002bddeac.

**Comment by mil-ad** [comment]
Awesome!!
