### ISSUE TITLE
Is it possible to undefine default keybindings?

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#296]
Adding custom keybindings in `keys_user.config` adds additional bindings for an action. Is it possible to also remove the default one?

**Comment by ahrm** [comment]
You can remove them from `keys.config`. If you want to redefine a key, there is no need to remove it `keys_user.config` overwrites it.

**Comment by mil-ad** [comment]
but `keys.config` could potentially be overwritten in new update right?

**Comment by ahrm** [comment]
Yes, but I don't think it is important enough to complicate the implementation for it.

**Comment by mil-ad** [comment]
Fair enough. Maybe an easy way to get around it would be to add a "No Operation" action that one can be assigned to keys in keys_user.config
