### ISSUE TITLE
goto_begining puts beginning of the page in the center

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#299]
I noticed `goto_begining` puts the beginning of the page in the **middle** of the screen instead of the top. Is this by design? Is there a way to toggle the behavior?

**Comment by ahrm** [comment]
You can achieve this by adding this to your `keys_user.config`:
```
goto_begining;goto_top_of_page gg

```

**Comment by mil-ad** [comment]
Perfect!
