### ISSUE TITLE
goto_page_with_page_number problem

### ISSUE THREAD

**Issue by 0xRZ** [ahrm/sioyek#300]
When issuing `goto_page_with_page_number` page that is jumped from, not saved as a history point. So it can not be navigated with `prev_state`. On the other hand, when using `goto_begining` prefixed with number, the page that is jumped from is saved to history and can be jumped back with `pre_state`. Consistent behavior for both `goto_page_with_page_number` and `<number>goto_begining` would be cool.
Tested with [Release v1.3.0](https://github.com/ahrm/sioyek/releases/tag/v1.3.0)

**Comment by ahrm** [comment]
Should be fixed in 04a42d94465521ed335483df7aba77c96c80d276.
