### ISSUE TITLE
Middle click is a bad default?

### ISSUE THREAD

**Issue by albert-ying** [ahrm/sioyek#303]
Hi, thank you for this tool! I just find that the use of middle click is probably not a friendly default as a lot of people (esp Mac users) use trackpad -- and we don't even have a middle key. Therefore the jump to reference function becomes unusable... Is it possible to change it to something like click while holding ctrl or shift?

**Comment by ahrm** [comment]
Added the ability to bind shift+click and control+click to custom commands in b83a481e714cd1c89d3fdf424ffea93112a3f984, you can configure it like so:
```
shift_click_command smart_jump_under_cursor
```
there are also `control_click_command`, `shift_right_click_command` and `control_right_click_command` options.

**Comment by albert-ying** [comment]
Thank you so much for the quick response!

**Comment by michaelmior** [comment]
Is it possible to use portals without middle click?

**Comment by ahrm** [comment]
Oh never mind that, you can already use portals without middle click. First bind another combination to smart jump:
```
shift_click_command smart_jump_under_cursor
```
Now you can create a portal by first pressing `p` and then shift clicking on the reference.
