### ISSUE TITLE
Raise window when new document is opened

### ISSUE THREAD

**Issue by navdeeprana** [ahrm/sioyek#304]
Currently if sioyek is open but hidden (or minimized), it opens a new document silently and the user has to manually raise/focus the sioyek window. Is it feasible to raise the window automatically whenever a new document is opened?

**Comment by ahrm** [comment]
We already did bring it to foreground, but didn't unminimize it if it was minimized. Should be fixed in 422a26572eaf83c7a11214c08b0645a553e01966.

**Comment by navdeeprana** [comment]
> We already did bring it to foreground
Was this implemented in v1.4.0?

**Comment by ahrm** [comment]
No.

**Comment by navdeeprana** [comment]
I tried to check if the window comes to the foreground by doing the following.

Open a pdf, open some other application and maximize it such that Sioyek window is hidden. Now open another pdf, it opens in the sioyek window but I have to manually raise it. Say via using `Alt-Tab`.

I am using Cinnamon on Arch with Sioyek v1.4.0.

**Comment by navdeeprana** [comment]
No, I am using the AppImage from the releases page.

**Comment by ahrm** [comment]
The AppImages in this repository are from the latest commits:
https://github.com/hexomancer/sioyek/releases

**Comment by ahrm** [comment]
I close the issue for now, feel free to reopen if the issue persists.

**Comment by navdeeprana** [comment]
@ahrm the issue still persists, I noticed the following.
- If sioyek was launched from gui, for example by double clicking a pdf, then opening another pdf via gui or from terminal fails to raise the window.
- If sioyek was launched from terminal, for example `sioyek test.pdf` then if another pdf is opened using gui it fails, however if I use another terminal to open the pdf, the window is raised.
