### ISSUE TITLE
sioyek --version does not returns the version number.

### ISSUE THREAD

**Issue by navdeeprana** [ahrm/sioyek#309]
The output of `sioyek --version` is broken. I have it installed in `/opt/sioyek-appimage` and symlinked to `/usr/bin/sioyek`. Depending upon what I run, it looks like it is returning the command name, see the attached image.
![image](https://user-images.githubusercontent.com/17153984/177804667-e0941e69-f7ca-4c9e-b472-ebb22a49e58b.png)

**Comment by ahrm** [comment]
This option is handled by `QCommandLineParser`[1] and we don't control it. I guess I will have to disable that and handle it manually?
[1] https://doc.qt.io/qt-6/qcommandlineparser.html#addVersionOption

**Comment by ahrm** [comment]
Should be fixed in d65898ae15d11abaf562695b4c42354798ef0dc4.
