### ISSUE TITLE
[Feature Request]: command/ percentage mark substitution to output document position

### ISSUE THREAD

**Issue by sandersantema** [ahrm/sioyek#311]
In light of the features I spoke about [here](https://github.com/ahrm/sioyek/discussions/306) to implement a basic reading progress functionality it would be nice to be able to output x and y coordinates with the current position of the cursor or y coordinate of the lower edge of the window. 

e.g. if `%7` would be the designated percentage number for the x and y position of the cursor this command:
```
execute_command_a echo %7
```

Would output `0 0` if the cursor is in the upper left corner (assuming that's where coordinates start).

**Comment by ahrm** [comment]
Added two new variables for external commands:
* `%{mouse_pos_window}` expands to the position of the mouse curosr (in pixels) within the window
* `%{mouse_pos_document}` expands to the position of mouse cursor in the PDF document which is 3 space separated numbers: page number, x position (in pts), and y position (in pts).

**Comment by sandersantema** [comment]
Really nice how fast you added this feature! Thanks a lot.
