### ISSUE TITLE
Text rendering quality lowered in presentation mode

### ISSUE THREAD

**Issue by mutachre** [ahrm/sioyek#313]
I noticed this. Is there a reason for it? Is it possible to find a solution? I attach screenshots default mode and presentation mode.

<img width="907" alt="Schermata 2022-07-10 alle 14 16 46" src="https://user-images.githubusercontent.com/62408551/178145657-36b76b61-6f3b-4b99-b855-01b25ef3eeb2.png">
<img width="907" alt="Schermata 2022-07-10 alle 14 16 57" src="https://user-images.githubusercontent.com/62408551/178145661-ee659d8c-9661-4740-8a4f-a90bc441bebd.png">
Thank you!

**Comment by ahrm** [comment]
Probably can be fixed by adding this to your `prefs_user.config`:
```
linear_filter 1
```

**Comment by mutachre** [comment]
> linear_filter 1

Thanks for the suggestion, the rendering is slightly improved.
