### ISSUE TITLE
Last update breaking startup

### ISSUE THREAD

**Issue by VolkovIlia** [ahrm/sioyek#315]
My system `ArcLinux Kernel: 5.15.52-1-lts`

`Sioyek` stop working with start error:
```
Error: vertical_line_width is not a valid configuration name
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
SQL Error: database disk image is malformed
SQL Error: database disk image is malformed
SQL Error: database disk image is malformed
SQL Error: database disk image is malformed
SQL Error: database disk image is malformed
cannot create context: incompatible header (1.19.0) and library (1.20.0) versions
could not create mupdf context
```

My free space:

```
Filesystem     1K-blocks     Used Available Use% Mounted on
dev              8124684        0   8124684   0% /dev
/dev/sda1        1046508   106976    939532  11% /boot
/dev/sda2       30787492 25747924   3450320  89% /
/dev/sda3      447600524 75897664 348892492  18% /home
```
```
sioyek 1.4.0
```

**Comment by VolkovIlia** [comment]
I used `AUR` [repo](https://aur.archlinux.org/packages/sioyek-git).

**Comment by ahrm** [comment]
As mentioned in the comments in the `AUR` repository, there are currently some compatibility problems in for archlinux builds. Hopefully it will be fixed soon. In the meanwhile you can use the pre-built packages in [release page](https://github.com/ahrm/sioyek/releases/tag/v1.4.0). They should work fine.

**Comment by ahrm** [comment]
Also, there is another package which supposedly fixes the issue here:
https://aur.archlinux.org/packages/sioyek
