### ISSUE TITLE
Windows version doesn't display any PDF

### ISSUE THREAD

**Issue by wlange69** [ahrm/sioyek#316]
App doesn't display any PDF, window stays white, displaying PDFs with original mupdf.exe works just fine.

Version: 1.40 and all lower
OS: Windows 7 SP1
Graphics: Intel HD Graphics 3000, DirectX 11
PDF: tutorial.pdf coming with app, various other

**Comment by ahrm** [comment]
I think it is an opengl problem? What is the opengl version of your graphics driver (we require at least 3.3).

**Comment by wlange69** [comment]
Latest available drivers are installed, highest supported OpenGL version is 3.1. You may close this issue, I'll remove the app and use MuPDF rather than buying new hardware.
