### ISSUE TITLE
Black-white chessboard image when scrolling down fast

### ISSUE THREAD

**Issue by Endle** [ahrm/sioyek#32]
When opening a pdf file, or scrolling down, a black-white chessboard would appear on the screen

Other PDF readers like Okular would present a white (background colour) page while loading.  The chessboard image would make my screen blink and my eyes are complaining about it.

Thank you.

https://user-images.githubusercontent.com/3221521/132089159-63bbc144-bd4c-4418-b65e-2981074f3cf8.mp4

**Comment by ahrm** [comment]
I added an option to disable checkerboard pattern in eab2988dbd862257e13e4b6601b38532d1e43f3d .

**Comment by Endle** [comment]
@ahrm Thank you! This change is very helpful
