### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by tokisuno** [ahrm/sioyek#322]
I am pretty noob to linux so excuse this probably simple question.
![image](https://user-images.githubusercontent.com/85533116/178503675-a32d0deb-5bb6-41c0-9132-1df57ff786c0.png)
I have dependencies installed. 

I just installed qtdeclarative5-dev and still having this issue.

**Comment by tokisuno** [comment]
![image](https://user-images.githubusercontent.com/85533116/178510269-269fb045-624c-4fac-b4f7-81eca0fbc273.png)

**Comment by ahrm** [comment]
It seems that you do not have write perission for the directory. Either use another directory with write permission or use sudo to build.

**Comment by tokisuno** [comment]
![Uploading image.png…]()

**Comment by tokisuno** [comment]
but... 

![image](https://user-images.githubusercontent.com/85533116/178516337-7c08ff8f-614a-4a14-8546-3f477a03a19b.png)

wat

**Comment by ahrm** [comment]
You need to use the qmake binary that was installed with version 5.14. So instead of running just `qmake` you have to use the full path of the correct qmake version (unless of course the drfault qmake in path is the 5.14 qmake).

**Comment by tokisuno** [comment]
i use mint so things are outdated, so i can only download 5.12.8.

i used the .run installer to get qt5.14.2 but i am confused as to what to do from here.

**Comment by tokisuno** [comment]
accidentally closed while tapping my keyboard kekw

**Comment by tokisuno** [comment]
this may seem frustrating to deal with, however where do i find the path of the new qmake that comes with the new installation?

![image](https://user-images.githubusercontent.com/85533116/178522100-f61f22ae-4a96-48a6-b1c2-bcdc253ead2b.png)

**Comment by ahrm** [comment]
It should be somewhere in the `5.14.2` folder.

**Comment by tokisuno** [comment]
![image](https://user-images.githubusercontent.com/85533116/178525451-513c326c-ff5d-4710-bc7b-66a4dced86b1.png)

this is all i have. that folder in my home is what i got after downloading from the .run file i got from the qt website. idk what to do from here.

**Comment by ahrm** [comment]
I am not sure, it is probably somewhere in `/ust/lib/qt5.*`.

**Comment by ahrm** [comment]
I close the issue for now, feel free to reopen if the issue persists.
