### ISSUE TITLE
/etc/sioyek directory is not created

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#323]
I'm trying to bring the `sioyek-git` AUR package back to life and noticed that `/etc/sioyek` directory is never created. 

We do `standard_data_path.create_directories()` in `main.cpp` but I didn't find a `standard_config_path.create_directories()`

**Comment by ahrm** [comment]
We create the data path because we need it to write the database files, however, config files are optional and they may be in different locations depending on the type of the build and preferences of the package manager.  I think it is the job of the package to create the directories that it needs.
