### ISSUE TITLE
Stop screen from going sideways when zoomed in?

### ISSUE THREAD

**Issue by suhailsaqan** [ahrm/sioyek#324]
When I zoom in its hard to scroll without the screen moving to the side all the time. Is there a way to lock it to only scroll up and down (no sideways)?

**Comment by ahrm** [comment]
Yes, there is a `toggle_horizontal_scroll_lock` command for that.

**Comment by suhailsaqan** [comment]
Thanks for your response. How do I open `prefs.config` though?

**Comment by suhailsaqan** [comment]
Thanks for your response @ahrm. How do I open `prefs_user.config` though?

**Comment by suhailsaqan** [comment]
Nvm got it to work in `keys_user.config` thanks!

**Comment by suhailsaqan** [comment]
> BTW, `prefs_user.config` should be just next to `keys_user.config`, if it is not, you can create it.

Both of them were not there actually so I created both.
