### ISSUE TITLE
`Smart Jump` invertly treats text and reference

### ISSUE THREAD

**Issue by BeautyYuYanli** [ahrm/sioyek#325]
![image](https://user-images.githubusercontent.com/32453863/179251681-92384326-d713-4b71-9b7a-0f741c1565ce.png)
![image](https://user-images.githubusercontent.com/32453863/179250678-1f401b34-1aad-414c-bd1d-f470c42fb036.png)
See the above pictures. `Smart Jump` treats the text as a reference, but the reference is the figure.

**Comment by ahrm** [comment]
Yes, smart jump is a heuristic and doesn't always work. Here it thought that the `Figure 2.37` in the text is the actual reference.

**Comment by ahrm** [comment]
Added the ability to try other possible previews if the default one is wrong in 5e184ccad7d5325c971c508e3c96253dbc5f178c. There are now `next_preview` and `previous_preview` commands which move in a list of possible previews. Here is how it looks like:

https://user-images.githubusercontent.com/6392321/182020908-d023a58c-9509-48e6-a7fe-3ca9e92bd6a8.mp4

**Comment by BeautyYuYanli** [comment]
Thank you for your brilliant work!
