### ISSUE TITLE
[Feature request] Save selection as images

### ISSUE THREAD

**Issue by Endle** [ahrm/sioyek#33]
Hi, I'm switching from [Okular][] to sioyek, and this is a useful function in [Okular][] I wish sioyek could have.

Please let me demonstrate what I mean with this screenshot

![screenshot](https://user-images.githubusercontent.com/3221521/132123619-a86a1c6e-ff51-47d2-957e-5c9152242884.png)

[Okular]: https://okular.kde.org/

Besides, I have a question for @ahrm : Would you like to create a roadmap issue and share your plans about further development plans? Including new format support or code refactoring? (Right, I admit that I've read all open issues for sioyek)

**Comment by ahrm** [comment]
While I understand this is a useful feature, I think this is not the job of the PDF viewer so I don't think I will add this. For example in windows you can use the snipping tool to achieve the same thing and I am sure there are equivalents for linux and mac.

> Besides, I have a question for @ahrm : Would you like to create a roadmap issue and share your plans about further development plans? Including new format support or code refactoring? (Right, I admit that I've read all open issues for sioyek)

Currently I am working on the ability to export/import your data. I don't have any major new features planned and I think I will focus on improving/polishing existing features. I do want to eventually make a version of sioyek for tablet devices but it is not in near future.

**Comment by Endle** [comment]
Thank you!
