### ISSUE TITLE
Windows: the non-portable version is portable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ahrm/sioyek#332]
Forgive me if I make some mistake, but isn't the following the case? Version 1.4 of the file 'sioyek-release-windows.zip' (available [here](https://github.com/ahrm/sioyek/releases/tag/v1.4.0)) is both (1) distinct from version 1.4 of the file 'sioyek-release-linux-portable.zip', (2) _itself_ portable in this sense: one must execute the program directly rather than run an installer?

**Comment by ahrm** [comment]
Yes, the different between portable and non-portable version is the path of config files (they are next to the executable in portable version).

**Comment by LinuxOnTheDesktop** [comment]
You may find that this question recurs. So if I were you I'd stick some explanation about it somewhat prominent. (Better yet, make an installer.)
