### ISSUE TITLE
Windows: dark mode garbles a title graphic

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ahrm/sioyek#333]
My setup: sioyek 1.8, on Windows 10.

The first page of a PDF, when not using sioyek's dark mode:

![image](https://user-images.githubusercontent.com/47056543/179863311-423eb120-2d28-46e2-b422-e24caca20976.png)

Every other PDF reader that I have tried displays that image in that same way (or near enough).

The same page, when using sioyek's dark mode:

![image](https://user-images.githubusercontent.com/47056543/179863421-c7ca18ce-6606-4933-9de7-be11dd384181.png)

**Comment by ahrm** [comment]
Honestly, I prefer our method. For example some documents embed images for equations and symbols. Such documents look terrible in other viewers' dark mode. For example this is an example on acrobat reader:

![acrobat](https://user-images.githubusercontent.com/6392321/179922964-2818b789-03b9-47ed-9c05-da8b32e34240.png)

And here is the same page on sioyek:

![sioyek](https://user-images.githubusercontent.com/6392321/179922998-137eda80-49a2-43ae-941e-0c06bf467923.png)

I think distorting images a little bit is a small price to pay for this.

**Comment by LinuxOnTheDesktop** [comment]
Can't you have your good things without the bad thing, i.e. retain what works well in your dark mode but without distorting graphics?

**Comment by ahrm** [comment]
It is theoretically possible, however it is not easy. We have to somehow distinguish between text and graphic images which is pretty trivial for today's neural networks. However, it has a high performance and file size impact.
