### ISSUE TITLE
Use multiple lines to show long bookmarks

### ISSUE THREAD

**Issue by woaidangyang** [ahrm/sioyek#334]
Currently, all the bookmarks are shown in a single line and long bookmarks are truncated. It would be nice if the long bookmarks can be wrapped into multiple lines so their contents can be fully displayed.

BY THE WAY, is there an easy way to copy the bookmarks/highlights into the system's clipboard?

Thanks!

**Comment by ahrm** [comment]
Add an option to enable multiple lines in bookmarks/highlights menus in 56bf13a321152f1ce950a0ed7a16d5b622b58ca3. You need to add this to `prefs_user.config`:
```
multiline_menus 1
```
Also ce41830f4bfaf7c42d1023ca29417350dccc81ed adds the ability to copy highlight/bookmark texts by pressing `C-c ` in menus.

**Comment by woaidangyang** [comment]
Thank you so much!
