### ISSUE TITLE
Add the ability to sort bookmarks

### ISSUE THREAD

**Issue by woaidangyang** [ahrm/sioyek#336]
Currently, the bookmarks are ordered based on the time when they were added. It would be nice if they are ordered based on their location in the documents.

Thanks!

**Comment by ahrm** [comment]
There is a `sort_bookmarks_by_location` config which does that. You need to add the following to your `prefs_user.config`:


```
sort_bookmarks_by_location 1
```

**Comment by woaidangyang** [comment]
Great! Thank you!
