### ISSUE TITLE
[Bug] Wrong selection loction when selecting text on verticle screen

### ISSUE THREAD

**Issue by hahv** [ahrm/sioyek#338]
I use two screen (the main is the verticle one). When selecting text on verticle screen, the selected location and the position of the cursor/mouse is not matched. See example video of bug [HERE](https://www.youtube.com/watch?v=y6UEGvpw6rs)
Environment details:
- OS: Win10 Pro
- Soiyek version: 1.4.0 (newest, up to now)
- Verticel screen resolution: 1080 x 1920

**Comment by ahrm** [comment]
I was not able to reproduce the issue using this setup:
![monitor_setup](https://user-images.githubusercontent.com/6392321/180400992-5af51d4c-09f3-419c-a447-fd5e7efba521.png)

Maybe upload a screenshot of your exact monitor setup (like the one I posted)? Also details such as whether you start sioyek on the vertical monitor or you start sioyek on the other monitor and then move it to the vertical one might be important.

**Comment by hahv** [comment]
> I was not able to reproduce the issue using this setup: ![monitor_setup](https://user-images.githubusercontent.com/6392321/180400992-5af51d4c-09f3-419c-a447-fd5e7efba521.png)
> 
> Maybe upload a screenshot of your exact monitor setup (like the one I posted)? Also details such as whether you start sioyek on the vertical monitor or you start sioyek on the other monitor and then move it to the vertical one might be important.

Sorry, at this time I am unable to reproduce this issue. Maybe this is not a common bug. I'll close this issue now, and may re-open it when i discover how to reproduce it properly.

**Comment by Imymirror** [comment]
I have the same problem. 
OS: Mac Pro 2015
Soiyek version(git commit hash): 43fbb014a0b20ef970b006279ca7f166e9272116
