### ISSUE TITLE
[Feature request] Go to page number like in vim by pressing ':' + page number

### ISSUE THREAD

**Issue by Yohannfra** [ahrm/sioyek#339]
Having to type **:goto_page_with_page_number** then **Enter** then the **number** isn't convenient at all, it would be great to just be able to type **:44** and go to page 44 of the document.

If you show me the direction of where to look I'd be happy to submit a PR for this.

Thanks you,

**Comment by Yohannfra** [comment]
I know it's possible with [number]gg but I'd prefer with ':'

**Comment by ahrm** [comment]
Added in ed002f78b6b8c02db7a66301a5012ffb9f84614a.
