### ISSUE TITLE
[Feature request] Close window with Ctrl/Cmd+W

### ISSUE THREAD

**Issue by Yohannfra** [ahrm/sioyek#341]
Hi, would it be possible to add Ctrl+w (or CMD+w on mac) to close the current windows ? 

Thanks you,

Yohann

**Comment by Yohannfra** [comment]
Also having Ctrl/Cmd+n to open a new window of the same document (the same behavior as **:new_window**) would be great.

**Comment by ahrm** [comment]
You can configure this using the following in your `keys_user.config` file:

```
close_window <C-w>
new_window <C-n>
```

**Comment by Yohannfra** [comment]
Thanks you didn't know this.
