### ISSUE TITLE
Option to remove the title bar on macos

### ISSUE THREAD

**Issue by albert-ying** [ahrm/sioyek#343]
These buttons are not necessary as the sioyek are keyboard-driven. Removing this bar could reduce the distraction and increase the usage of the screen.

Many modern apps already support this (e.g., iterm2)

<img width="422" alt="image" src="https://user-images.githubusercontent.com/59846322/181783465-f820655c-df8f-423f-a7a0-7f77689284a2.png">

**Comment by albert-ying** [comment]
It is also easy to be done https://developer.apple.com/documentation/uikit/mac_catalyst/removing_the_title_bar_in_your_mac_app_built_with_mac_catalyst

Remove the Title Bar

If you choose to design your window without a title bar, you must remove it from the window. To remove the title bar, set the title bar’s titleVisibility property to UITitlebarTitleVisibility.hidden and the toolbar property to nil. The following code shows how to remove the title bar and its separator from the window during the setup of a new scene.

```

func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    
    guard let windowScene = (scene as? UIWindowScene) else { return }
    
    #if targetEnvironment(macCatalyst)
    if let titlebar = windowScene.titlebar {
        titlebar.titleVisibility = .hidden
        titlebar.toolbar = nil
    }
    #endif


}
```

**Comment by ahrm** [comment]
Why not just fullscreen the window (`toggle_fullscreen` command)?

**Comment by albert-ying** [comment]
> Why not just fullscreen the window (`toggle_fullscreen` command)?

Thank you for the reply! The main reason is that I usually have multiple windows side by side on the screen. Those space title bar and status bar took become critical especially when I work with a laptop screen

**Comment by ahrm** [comment]
Added a `toggle_titlebar` command in 43fbb014a0b20ef970b006279ca7f166e9272116. It is pretty buggy on windows though (doesn't work well with snapped windows). I don't know how well it will work on MacOS.

**Comment by albert-ying** [comment]
Wow, this is quick! I couldn't test it as I encountered some problem when building from the source... Is the prebuilt version available?

**Comment by ahrm** [comment]
There is an experimental build here:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.358

**Comment by albert-ying** [comment]
It seems that it is also buggy on MacOS, the window seems cannot be resized after toggle the titlebar

**Comment by ahrm** [comment]
Yes, that is also the case on windows. I don't know if it can be done in a cross-platform way using Qt.

**Comment by albert-ying** [comment]
Yes, it seems that it is a problem. I found this long issue from `qutebrowser`, as it is also built using Qt and people are asking for the same feature https://github.com/qutebrowser/qutebrowser/issues/4067

It seems that they committed something trying to address this recently, I will keep eyes on this and see if they have the solution.

**Comment by ahrm** [comment]
This seems to be a MacOS-specific solution. I can't really test it on my systems.

**Comment by albert-ying** [comment]
I think in Linux, they can control the appearance of the title bar globally through the windows manager, so Linux support is not needed. So if this works in MacOS, it is sort of 'cross-platform' with the exception of windows.

Let me know if I can help with anything, although I don't know Qt but maybe I can help with testing.

**Comment by The-Compiler** [comment]
Hey! Just saw this linked in the qutebrowser thread. Some good news regarding frameless windows not being resizable:

- This is fixed in Qt 6.3 via [macOS: Handle window titlebar buttons independently from style mask (I2c1a9564) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/371279) - so I suppose once this project migrates to Qt 6, things should just work.
- The workaround proposed in https://github.com/qutebrowser/qutebrowser/pull/7293 seems to work fine for qutebrowser. I have no idea how to do the same thing for a C++ project, though. I suppose it will be more difficult to mix C++ and Objective C there.

@ahrm FWIW, you might be able to get a free hosted Mac via [Open Source Program - Encouraging Open Innovation | MacStadium](https://www.macstadium.com/opensource). That's what I use for qutebrowser, and it's been a lifesaver for testing macOS-specific stuff.

**Comment by ahrm** [comment]
@The-Compiler Thanks for the info, and also for the macstudium suggestion, will definitely check it out. And thanks for your work on qutebrowser.

**Comment by faurehu** [comment]
I just tested `toggle_titlebar` in my mac. What ends up happening is my titlebar stays but the tabs are hidden.

**Comment by albert-ying** [comment]
Any update on this, there seems to be some new issue also related to this #862 #860

**Comment by jinjiaodawang** [comment]
@ahrm, I've tested the toggle_titlebar command on the development branch in macOS, and it works fine.

**Comment by kevinkleine** [comment]
Just installed a fresh sioyek with brew and alas the resize issue is still there. No manual resizing or resizing with yabai. This also means that, when hiding the statusbar as well, there is a lot of padding in the bottom, which can't be changed.

**Comment by ahrm** [comment]
I don't think the brew version is updated to the development branch.

**Comment by ameyakakade** [comment]
> Just installed a fresh sioyek with brew and alas the resize issue is still there. No manual resizing or resizing with yabai. This also means that, when hiding the statusbar as well, there is a lot of padding in the bottom, which can't be changed.

I compiled sioyek with qt 6.8.2, it works as expected.

**Comment by KorigamiK** [comment]
I think there still used to be an issue where you couldn't hide the title bar with the preferences option in the config which is now fixed. https://github.com/ahrm/sioyek/pull/1608
