### ISSUE TITLE
installing on Fedora

### ISSUE THREAD

**Issue by bdarcus** [ahrm/sioyek#344]
Just FYI, it's not convenient at all to install sioyek on Fedora.

The copr you listed explicitly discourages its use, and seems broken anyway (I get missing dependency errors).

Building from source isn't any easier, as I seem to be missing some unstated (in the README) dependencies.

Also, the linux build script assumes a `qmake` binary name, while on Fedora, I have `qmake-qt5`.

I don't need help (I've already spent too much time on this), but thought it might helpful at least to suggest you remove the link to the copr, and maybe consider listing some additional dependencies?

Project seems very cool though; good luck!

**Comment by ahrm** [comment]
Thank you for your feedback. Unfortunately, I don't really have time to maintain separate packages for each distribution myself so they are maintained by volunteers and sometimes they get out of date.

Is there any particular reason you are not using the appimages in release page here:
https://github.com/ahrm/sioyek/releases/tag/v1.4.0

**Comment by bdarcus** [comment]
I totally understand.

I wasn't aware those were AppImages. I can try that then.
