### ISSUE TITLE
"You have macOS 10.15.7. The application requires macOS 11.0 or later."

### ISSUE THREAD

**Issue by universemaster** [ahrm/sioyek#345]
When opening the mac release from the release page I get:

> "You have macOS 10.15.7. The application requires macOS 11.0 or later."

Does the build really need to target 11 rather than 10?

I have a 2014 Macbook, and have lost faith that the MacOS "upgrade" actually will be an upgrade.

**Comment by ahrm** [comment]
> Does the build really need to target 11 rather than 10?
I don't know (and I don't have a mac system so I can't test it, maybe someone with a mac can help?). Theoretically it should not need 11 but I am not sure.

**Comment by thezeroalpha** [comment]
Trying to open the original sioyek.app gives me the same error, but running the binary directly works fine.

So, I set it up on my computer (macOS 10.15.7 Catalina) with a wrapper app, as such:
1. `brew install sioyek`
2. Create a new Automator application as shown here:
    ![automator-app](https://user-images.githubusercontent.com/8124851/186156992-113ecdfa-8f63-4a02-ac28-e495ed8ffb0f.png)

    The "run shell script" action runs `/bin/sh` and contains the line:

    ```sh
    >/dev/null 2>&1 /Applications/sioyek.app/Contents/MacOS/sioyek "$@" & disown
    ```
3. Save the Automator application as (for example) `/Applications/SioyekRun.app`.
4. Whenever you want to open a file with Sioyek, open it with SioyekRun. Spotlight can launch SioyekRun with just the abbreviation `sr`.

So far, I've tested all the features in the tutorial and it seems to be working fine. I also opened a 400 MB PDF and  it worked without issues.

**Comment by thezeroalpha** [comment]
@ahrm I've been using Sioyek quite extensively over the past few days with this setup, I haven't had any issues so I think macOS 11 isn't a requirement, it can run fine on 10.15.7. Is there anything you'd like me to test before you can change the version requirement?

**Comment by ahrm** [comment]
Please test the new build here and see if it works:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.388

**Comment by ahrm** [comment]
So apparently since github actions runs on macos 11, we can not target lower versions, unfortunately I will have to revert the changes.

**Comment by ahrm** [comment]
I don't plan to use that since it is deprecated and will be removed soon anyway.
