### ISSUE TITLE
Features and issues

### ISSUE THREAD

**Issue by alonetrifle** [ahrm/sioyek#351]
### Here are a list of **issues** I've encountered during the use:
1. In the linux build.sh for fedora you have to change `qmake` to `qmake-qt5` in order to use the qmake from qt5
2. Launch new instance when opening a second PDF file instead of closing the previous one and opening a new one
3. Replace the shortcut for page navigation with Arrow keys
4. Sometimes when app is behind a window and the window gets closed the GUI glitches but it gets resolved on its own
### **Suggested features:**
1. Add ePUB support since Sioyek uses muPDF backend, ePUB support can be added to it too.
2. An option to expand or collapse all of the table of contents
3. Add script to create .desktop file for the Appimage or the built package from source

**Comment by ahrm** [comment]
> Launch new instance when opening a second PDF file instead of closing the previous one and opening a new one

You can do this by passing `--new-window` to sioyek when opening a file. Alternatively you can add this to your `prefs_user.config` to make this the default:

```
should_launch_new_window 1
```

> Replace the shortcut for page navigation with Arrow keys

We use the arrow keys for horizontal navigation. If you want this you can change this in your `keys_user.config`:
```
next_page <right>
previous_page <left>
```

> Sometimes when app is behind a window and the window gets closed the GUI glitches but it gets resolved on its own

I don't think this is a sioyek bug. This is probably an issue with your window manager or display server.

> Add ePUB support since Sioyek uses muPDF backend, ePUB support can be added to it too.

We already support epub files.

> An option to expand or collapse all of the table of contents

We already have this option. You can press left/right arrow keys on table of contents to collapse/expand them. You can also use the icon when you hover the mouse next to the items.

**Comment by skjerns** [comment]
Thanks! Was just looking if scrollbars are available, I use them a lot to get an intuitive feeling on "where" in the paper I am (similar to knowing how much you still have to read in a physical book)
