### ISSUE TITLE
after open_link , the number is ambiguous

### ISSUE THREAD

**Issue by Imymirror** [ahrm/sioyek#356]
the paper can be downloaded here : https://weekly.chinacdc.cn/en/article/pdf/preview/10.46234/ccdcw2022.115

When I press f (open_link), the number is ambiguous like this:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/52570325/183650917-5301aebd-b530-47e6-85f2-7f0dfb806900.png">

**Comment by ahrm** [comment]
It seems that the document has two links overlapping each other. I would say this is more the problem of the malformed document rather than a sioyek bug. I will see what I can do though.

**Comment by ahrm** [comment]
Should be fixed in d31f7b9f8543c80ed50c053a70541dc5662ec0fb. Now if there are many links close to each other, we only show the label of one of them.

**Comment by Imymirror** [comment]
I rebuild sioyek.  two links overlapping has been solved. 

but the number is overlaping paper text. It might be a good idea to add a background to the number.
<img width="732" alt="image" src="https://user-images.githubusercontent.com/52570325/183746240-f5f20a33-0c89-4dd9-9cc7-8b46cf23ec17.png">

**Comment by ahrm** [comment]
Fixed in aae25baef33bdf0e84565b0adf10281207dfa165.

**Comment by Imymirror** [comment]
I update code and rebuild sioyek. now works better and more visual. thanks.

I close the issue.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/52570325/183908312-fc53b130-91c4-4149-ad7f-1031b06080b9.png">
