### ISSUE TITLE
open_link doesn't work for web links

### ISSUE THREAD

**Issue by EvaristeFan** [ahrm/sioyek#357]
Platform: Arch linux with dwm, firefox.
I installed sioyek-git from aur.

Open_link with "f" can not open web links. left clicking on web links or opening link of toc works well.

Sioyek(not sioyek-git) from aur seems have a same issue and this version show a warning message: unknown link uri 'https://www.google.com'

**Comment by ahrm** [comment]
Fixed in 414d8d93fb5271fdd7f1c047aa7fd2e50b726fad.

**Comment by EvaristeFan** [comment]
That works.
Thanks!!!
