### ISSUE TITLE
TOC: Show full headings

### ISSUE THREAD

**Issue by tanjeff** [ahrm/sioyek#358]
I'm using sioyek **1.4.0**.

In the TOC, the headings are abbreviated using ellipsis (...) although there is enough room to show more of the heading. It would be helpful to show more of the heading. See screenshot:
![image](https://user-images.githubusercontent.com/530226/183893690-836e9eb5-2afe-4fa7-8060-e13d65130bb4.png)

I have a data sheet, and the headings show register addresses which are useful to find the right registers. If the window is wide enough, the full heading is shown as follows:
![image](https://user-images.githubusercontent.com/530226/183893478-af8051f5-8432-4887-8d52-a7109d601642.png)

Therefore I request to make better use of the remaining space. Or, explain why this is not desired :-)

P.S.: Thanks for that great software! I use it on a daily basis.

**Comment by ahrm** [comment]
Should be fixed in fac66da156c69bb7e7b03db4c3c8a687824de288.

**Comment by tanjeff** [comment]
Version 1.5.0 has the fix. Great work, thanks!
