### ISSUE TITLE
Middle click doesn't have the proper functionality in Win 11.

### ISSUE THREAD

**Issue by jrrippy** [ahrm/sioyek#359]
I'm using the newest Windows release. 

In the tutorial, when I middle click the "1" in "Figure 1" the first time it appears in section 6, it takes me up to the Mandelbrot colorization. When I click the second one at the bottom of the page ("You can see a beautiful colorization of mandelbrot set in Figure 1."), it doesn't take me anywhere. 

In the tutorial, when I middle click the references where it says to in bullet point 6, it doesn't go to the references. Instead, it opens Google Scholar and inputs text into the search that doesn't really belong: 
![image](https://user-images.githubusercontent.com/110940226/184421129-54e7ba57-bdd4-4fb4-9804-fa40296ec5a2.png)
Shift clicking does the same but in Libgen: 
![image](https://user-images.githubusercontent.com/110940226/184421615-0af94180-19c6-4e07-87b1-537217701ff9.png)

Interestingly, when I click the [1] and [2] in the references section, it readjusts the page as if it navigated to the reference successfully. 

If I middle click Benoit B Mandelbrot in reference 2, I get what appears to be some code put into Google scholar:
![image](https://user-images.githubusercontent.com/110940226/184422016-78a8213e-8d51-4167-9ce6-d4184f0227ac.png)

And when I click on the name of the paper in Ref 2, I get the following:
![image](https://user-images.githubusercontent.com/110940226/184422079-2cdd7ea3-ce20-4773-b21c-63ab254ed474.png)

**Comment by ahrm** [comment]
Can you restart sioyek and see if the issue persists? Based on what you have described, I think sioyek is offsetting your mouse position for some reason (it sees the clicks a little higher than where you clicked), restarting sioyek or resizing the screen should fix this.

**Comment by jrrippy** [comment]
When I restarted, it was the same thing. However, when I resized it with ctrl + mousewheel, it now works properly.

However, when I middle click Bodil Branner, I get the same code execution thing as I got before: 
![image](https://user-images.githubusercontent.com/110940226/184426360-c352fc24-8be1-459c-8fcb-34da6987107b.png)

If I middle click the name of the article, it takes me to the correct place. However, middle clicking Proc. symp. appl. math puts what follows into the search bar:
![image](https://user-images.githubusercontent.com/110940226/184426581-367ab0d7-bc43-4fba-b8f5-1f5b7e0f4e00.png)

Clicking Benoit B Mandelbrot now puts all of the authors and the [2] tag into Google Scholar. Middle clicking the paper title inputs the paper as expected. It does include "volume 3", which may be intentional.

**Comment by ahrm** [comment]
> However, when I middle click Bodil Branner, I get the same code execution thing as I got before:

Yes, despite the name, smart jump is not really that smart. You are supposed to middle click either on a paper name or a reference. If you middle click on other things, the behavior is unpredictable.

**Comment by jrrippy** [comment]
Ah, alright! Well, I will consider this closed then. Thanks!
