### ISSUE TITLE
anyway to increse mouse scroll speed?

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#360]
like i am used to a pdf reader with a bit higher mouse scroll speed and switch to sioyek makes my finger always moving on mouse to scroll it , it would be really nice if we have this in config. thanks :)

**Comment by ahrm** [comment]
We have a touchpad sensitivity config that does this. For example add this to your `prefs_user.config`:
```
touchpad_sensitivity 2
```

**Comment by Aneeqasif** [comment]
> 

does this also change mouse scroll wheeel speed?

**Comment by ahrm** [comment]
Yes.
