### ISSUE TITLE
"fit_to_page_width_smart" does not work as a startup command

### ISSUE THREAD

**Issue by jmburgos** [ahrm/sioyek#361]
Hi Ali,
First, thank you for Sioyek.  It is fantastic!

This is my issue.  I would like to open the documents by default using fit_to_page_width_smart.  If I add the the following to the prefs_user_config file

`startup_commands fit_to_page_width_smart`

When I open a pdf I get the following error:
`Job 1, 'sioyek Prampolini2021.pdf' terminated by signal SIGSEGV (Address boundary error)`

Without that line in the config file, the pdf opens fine, and I can use fit_to_page_width_smart with no issues.

I am using the Linux version, running under Fedora.

**Comment by jmburgos** [comment]
Actually I noticed that I am using an old version (1.0.0-1.fc34). I will update and see if this is still an issue with the latest version.

**Comment by ahrm** [comment]
This was a bug in version 1.4 but it should be fixed in the latest commits.

**Comment by BonfireAtNight** [comment]
Incidentally, it's the same for `fit_to_page_width`, but I suppose you are aware of that.
