### ISSUE TITLE
request for okular like accelerated scrolling on mouse drag

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#362]
hy i hope u are doing great , before switching to sioyek i was using okular and that is one of greatest pdf viewer i have ever used most of that is already implemented beautifully in sioyek only thing that i miss is accelerated scrolling when dragging mouse.
it really help browsing through documents where you just want to have quick overview really really convenient 
i asked kde devs on a [reddit post related to the code block related to this feature](https://www.reddit.com/r/kde/comments/wo69lw/can_some_one_please_point_out_to_code_blocks/?utm_medium=android_app&utm_source=share) that might help getting some inspiration.
please have a look
it would me amazing if we have this in sioyek and then it will be my final resort for pdf viewers
thanks and best of luck :)

**Comment by Aneeqasif** [comment]
https://user-images.githubusercontent.com/78728701/184542212-a9900f69-3de6-4a02-aca7-11a684c8f06d.mp4

**Comment by ahrm** [comment]
I did implement something like this a long time ago but didn't like it at all. I don't think animations work well with sioyek's UI. If you want to have a quick overview of a document I suggest zooming out (we allow you to zoom out very far) and then scroll normally.

**Comment by Aneeqasif** [comment]
i dont think its related to animating stuff , may be u can find a more elegant way from okular code anyways its your project u decide what u implement or not i can just only request .
so have a great time and thanks for response

**Comment by ahrm** [comment]
We have added a smooth scroll mode which you can enable by `toggle_smooth_scroll` command.
