### ISSUE TITLE
Search with / doesn't work

### ISSUE THREAD

**Issue by BonfireAtNight** [ahrm/sioyek#365]
In my setup, pressing "/" doesn't do anything, i.e. the search command is not executed. I've tried adding `search <S-seven>` to my `keys_user.config` (as that is where the "/" is located on a German keyboard), but it didn't help, either.

**Comment by ahrm** [comment]
This issue is already fixed. See this thread for more information: https://github.com/ahrm/sioyek/issues/254 . By the way if you want to try out the latest version of sioyek, I regularly make experimental builds in this repository: https://github.com/hexomancer/sioyek/releases/tag/v0.31.367
