### ISSUE TITLE
Text selection with keyboard-overview crushes the application

### ISSUE THREAD

**Issue by BonfireAtNight** [ahrm/sioyek#366]
I saw the video under the "Keyboard Focused" title on the official website and wondered how you would accomplish this. I've found the `keyboard-overview` with I think is what is executed in the video. However, when I enter the position labels and hit Enter, sioyek crushes every time.

**Edit:**: just realized that you select text with the v key, which should have been obvious. However, while it works sometimes, I had some nasty crushes with this, too.

**Comment by ahrm** [comment]
The command for text selection is `keyboard_select`. However, running `keyboard_overview` should not crash sioyek. Can you share the document on which `keyboard_overview` crashes?

**Comment by ahrm** [comment]
The issue was using keyboars_select with a mixture of two-letter and three-letter labels.This issue should be fixed in the latest commits.
