### ISSUE TITLE
Managing Bookmarks

### ISSUE THREAD

**Issue by BonfireAtNight** [ahrm/sioyek#372]
Is there a way to rename bookmarks from within sioyek? And where and how are they stored? Is there an easy way to backup and synch them with other devices?

**Comment by ahrm** [comment]
There is no way to rename bookmarks. See https://sioyek-documentation.readthedocs.io/en/latest/usage.html#data-and-synchronization for how data is stored.

**Comment by BonfireAtNight** [comment]
Ah, I must have overlooked that. Thanks!
