### ISSUE TITLE
[feature request] Explicit refresh/reload command

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#381]
Sioyek is pretty good at reacting to file changes but sometime it shows a blank screen when the underlying file changes under its feet.  it'd be good to have an explicit `refresh` command to force it to reload the file.

**Comment by ahrm** [comment]
We do have a `reload` command.

**Comment by mil-ad** [comment]
🤦🏼 sorry I missed this! Just saw it in the commands palette but seems to be missing from the documentation website.
