### ISSUE TITLE
Commenting, page thumbnails, trackpad buggy

### ISSUE THREAD

**Issue by yosamsimiti** [ahrm/sioyek#382]
Something I really wish for is for one to have the basic ability to directly write notes (and be able to see them on the actual PDF) in the app.   I know it's against your design philosophy and there's been loads of discussion, but this is essentially for anyone in the humanities who wants a pdf solution as close to physically writing on paper books as possible. For example, in my gigantic 3000 page physical copy of the Norton Shakespeare, I've got all sorts of colours, post-it notes, sticky bookmarks galore...and all that good stuff really does helps me study. I mean, I'm an academic too, shouldn't my concerns matter in addition to all those scientists out there? So when I look for PDF software, I'm -- alongside the principles that went into designing Sioyek -- looking ALSO for an app that makes things feel as organic as conventional pencil written and post-it notes do in physical books.  

Indeed, for those of use who enjoy the simple pleasure of directly writing AND SEEING your notes directly on the printed page...well this app doesn't cut it.

My other gripe is not being able to highlight/mark/bookmark (and hopefully in the future, make notes) on the page thumbnail that pops up when you right click on a link (using a mac, note sure if 'thumbnail' is the right word, but that little box that pops up showing the information upon which the link points to).

thirdly using the app with a trackpad (on my macbook), is REALLY, REALLY, REALLY buggy.  I fiddled with the pref and key config settings for a good solid half hour before giving up.  Using a keyboard is fine, but trackpad scrolling is jittery, inconsistent, strangely at times, even delayed.

Again, I really wanted to use this app, but because of all these issues, I sadly can't.

Really hoping things improve.  And yes, I will certainly buy you that coffee, if you manage to get to this things.  Otherwise, it's PDF Expert for me (a much lauded pdf app in the mac app store, if you haven't heard of it).

**Comment by 875d** [comment]
Did you try Xournal++ already?

**Comment by yosamshiyam** [comment]
Yeah.  Xournal++ is still quite buggy on macs, so that prevented me from using it.  also, it's still in beta as far as iPadOS and iOS are concerned.  So where I really need it (my iPad), I'm unfortunately stymied Apple's no-betas-on-app-store rule.  Hopefully this will in time.

**Comment by ahrm** [comment]
By the way some of the features you have requested are added as extensions here:
https://github.com/ahrm/sioyek-python-extensions

(e.g. embedding highlights and adding text annotations)

**Comment by ahrm** [comment]
We have added:

* Visible bookmarks
* Freetext notes
* Freehand drawings

In the development branch.
