### ISSUE TITLE
Configuration defaults when no configurations are found

### ISSUE THREAD

**Issue by grtcdr** [ahrm/sioyek#385]
Hi there,

I'd like to preface this PR by thanking you for your work on sioyek.

> Before I dive in, I really hope that I haven't read past any important sections that make this PR a waste of time for you.

Upon installing sioyek through the [AUR
package](https://aur.archlinux.org/packages/sioyek-git) provided by
[@randomn4me](https://github.com/randomn4me), it seems that the build
script neither pulls nor places the configuration files into their
intended location.

This renders sioyek useless for the first 30 minutes, leaving the user
in the dark, unable to move around (or do anything, really)... Until
one realizes that something (crucial) is missing.

Now, we could say that the build script is behaving incorrectly, and
this would be correct, but I'd like to propose a different approach.

Sioyek should perhaps set its defaults even when none of the paths
where it expects a configuration file to exist are actually found and
parsed.

**Comment by ahrm** [comment]
I think this is more of an issue with AUR package, so you should contact the maintainer. It is expected that packages put the required files in the correct location. I don't think this is an unreasonable request, for example even if we can hard-code the configurations, what do we do about binary files (the tutorial file for example)?

**Comment by grtcdr** [comment]
Hi, thanks for considering my request.

I'll go ahead and contact the maintainer.

It doesn't seem worth the effort to hardcode the tutorial into the application, so you could make an exception there.
