### ISSUE TITLE
Unable to communicate with the running instance

### ISSUE THREAD

**Issue by heyrict** [ahrm/sioyek#386]
`sioyek` complains about unable to connect to IPC server when an existing instance of it is running.

```
$ sioyek --reuse-instance
shader_path: /usr/share/sioyek/shaders
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application successfully attached to shared memory block.
Secondary application cannot connect to IPC server.
Socker error:  QLocalSocket::ConnectionRefusedError
```

Tested `sioyek` version: fd4c8d9 (AUR sioyek-git), v1.5.0 AppImage

**Comment by ahrm** [comment]
Is this a reproducible issue? I think it may be caused by an improperly closed version of sioyek being present in memory. Does this issue happen after a system restart?
By the way `reuse-instance` is deprecated, use `new-window` and `reuse-window` instead.

**Comment by heyrict** [comment]
Thanks for your kind hint! This issue does not persist after restarting the window manager. I'll close it now.
