### ISSUE TITLE
Aspect ratio not kept when rotating

### ISSUE THREAD

**Issue by heyrict** [ahrm/sioyek#387]
The document seems squeezed along y axis when rotated in latest git version fd4c8d9 (AUR sioyek-git). This does not happen in the latest release (v1.5.0 AppImage).

![Screenshot-2022-08-28T09:13:36](https://user-images.githubusercontent.com/25698503/187053534-c0430d8b-b54d-493f-9ab5-d0e7a2ac8cc3.png)

**Comment by ahrm** [comment]
Should be fixed in f52431b74082253064ea411c0843f755d64de65e.

**Comment by heyrict** [comment]
Thanks for your incredibly fast fix! I can confirm the rotated page is returned to normal now.
