### ISSUE TITLE
Default dark mode not respected in new window

### ISSUE THREAD

**Issue by heyrict** [ahrm/sioyek#388]
When opening a new window with `:new_window` command, the newly opened window will always show in light mode even if `default_dark_mode 1` is set in the config.

Edit: Dark mode is also not applied to portals.

Tested sioyek version: fd4c8d9 (AUR sioyek-git), v1.5.0 AppImage

**Comment by ahrm** [comment]
Default dark mode is deprecated. Use the following instead:
```
startup_commands toggle_dark_mode
```
