### ISSUE TITLE
Horizontal scroll wheel scrolls in the wrong direction

### ISSUE THREAD

**Issue by danielfomin96** [ahrm/sioyek#39]
When scrolling to the right, the page is scrolled to the left and vice versa. If this was done consciously maybe consider adding an option to flip the direction of the horizontal scrolling.

I built from the current main branch.

On another note: Thank you very much for this program, using it already feels for me to be more efficient than other pdf readers.

**Comment by Endle** [comment]
Hi, what's your platform? Win/Mac/Linux?

**Comment by danielfomin96** [comment]
Arch Linux

**Comment by ahrm** [comment]
Yeah it's probably wrong because I didn't have the hardware with horizontal mouse wheel to test it. It should be fixed in 7e5bca3895bad93f32e67ac37d663d14c1cd1af3 .

**Comment by danielfomin96** [comment]
Thank you for the quick fix. I am building with the current commit now.

**Comment by danielfomin96** [comment]
Everything works now for me as expected. Thanks
