### ISSUE TITLE
Feature request: Customize Document Colors

### ISSUE THREAD

**Issue by pqnhan** [ahrm/sioyek#390]
If sioyek could customize the Page Background color and Document text color using the color wheel or hex color codes, that would be really cool compared to just inverting the colors from light to dark or vice versa.

I don't know how much work it takes to implement this functionality, but it will certainly be pleasing to the eyes of many sioyek users rather than just pure black and white.

**Comment by ahrm** [comment]
We do have this feature.
See https://sioyek-documentation.readthedocs.io/en/latest/configuration.html#custom-background-color-and-custom-text-color.
