### ISSUE TITLE
Sioyek fails to open files if they contain a fullwidth character in the filename

### ISSUE THREAD

**Issue by eshrh** [ahrm/sioyek#392]
If the filename contains a fullwidth character, then sioyek is not able to open it

Error:
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
```

Reproduce:
```
cp "tutorial.pdf" "tutorial書.pdf"
sioyek "tutorial書.pdf"
```
Sioyek 1.5.0 - Ubuntu 20 LTS

**Comment by MiuKaShi** [comment]
> I think this issue should already be fixed. Please try with experimental builds here and see if the issue persists: https://github.com/hexomancer/sioyek/releases/tag/v0.31.389

works for "tutorial書.pdf" but still failed for "tutorial 書.pdf"  when there is a space in filename

**Comment by ahrm** [comment]
> > I think this issue should already be fixed. Please try with experimental builds here and see if the issue persists: https://github.com/hexomancer/sioyek/releases/tag/v0.31.389
> 
> works for "tutorial書.pdf" but still failed for "tutorial 書.pdf" when there is a space in filename

I am unable to reproduce this issue. How are you opening this file in sioyek?

**Comment by wenbopeng** [comment]
> 

the same issue
Sioyek will not crash if you set `should_launch_new_instance    1` , and a new window is started when a new file is opened. 
But if set to `should_launch_new_instance 0`, when there is Chinese in the file path like `D:\文档\Citavi\Citavi 6\Projects\基础知识\Citavi Attachments\file.pdf`, the current sioyek window will crash.

**Comment by bentleyxia** [comment]
> I think this issue should already be fixed. Please try with experimental builds here and see if the issue persists: https://github.com/hexomancer/sioyek/releases/tag/v0.31.389

This version fix the issue, but the latest one crash again.
