### ISSUE TITLE
G does not jump to the page number if it is the first page

### ISSUE THREAD

**Issue by gjgress** [ahrm/sioyek#394]
To my understanding, in vim the inputs `gg1` and `1G` have the same interpretation: jump to line 1 (as G is just the jump-motion counterpart to gg). For the most part, this translates to sioyek. However, interestingly enough, while `gg1` works as intended, `1G` does not; instead, it just jumps to the last page (as if 1 was not pressed). All other page numbers seem to work as intended.

(I would appreciate it if someone could try this on their system and replicate this... for some reason, after installing sioyek, I am encountering some rather unrelated keyboard input bugs. Perhaps something is wrong with my sioyek install)

**Comment by ahrm** [comment]
I was able to reproduce the problem. It should be fixed in 077893018fd2caed7c93cab8ef05b010a4e8c2f0.
