### ISSUE TITLE
[Feature request] Custom dark-mode colors (and some thoughts on custom theming in general)

### ISSUE THREAD

**Issue by gjgress** [ahrm/sioyek#397]
While you can set a custom color for the background, you can't add a corresponding custom dark mode color set; if you turn on dark mode, it just disables the custom color and goes to the default dark mode.

It would be nice if these could be set independently, so toggling dark mode while in custom colors goes to a custom dark mode color set, if it exists. For example, I like to set my light and dark theme to the solarized palette, and there's no way to have both accessible, currently.

An alternate, perhaps simpler, implementation would be to allow for multiple custom palettes; then one could do it manually by just switching palettes.

---

In an ideal world, I think adopting a more thorough color theming system akin to zathura or vim would be best. For example, [this](https://github.com/lennonwoo/zathura-solarized/blob/master/zathura-solarized-dark) is another user's zathura solarized theme. The benefit to this system is that users can create all sorts of themes, just as vim users have done, and if the author so chooses, can even include some of these themes with the package. It's not really important, but it does add some flair and variety, especially when you start to tire of your current theme.

Actually, if zathura's level of customizability is provided, I bet it wouldn't be too hard for a user to write a shell script to enable a theme which can be executed as a custom extension. I don't think it makes for a great community-sharing method, I'm not a fan of downloading bash scripts from the internet, but it's a place to start. I would love to hear if anyone else has other ideas on how to implement this.

Also, I personally like the color-hex code system better than an rgb system, but it doesn't really matter.

**Comment by ahrm** [comment]
I added the ability to define macros and added some commands to change the custom foreground and background color in 63f38e9628552283f29bc813330aba9de21b7be3. Using the new features, what you want can be implemented in `prefs_user.config` like this:

```
new_macro _set_solaris_theme set_custom_text_color(#b58900);set_custom_background_color(#586e75)
new_macro _set_normal_theme set_custom_text_color(#000000);set_custom_background_color(#ffffff)
new_macro _set_dark_theme set_custom_text_color(#ffffff);set_custom_background_color(#000000)

```

Now `_set_solaris_theme`, etc. are like built-in sioyek commands (requires a sioyek restart after changing the config files). You can execute them using the command menu or bind them in your `keys_user.config`.

**Comment by gjgress** [comment]
Wow, awesome. I like this solution a lot, custom macros are super nice.
I'll try this out tomorrow and play around with it.

I'll go ahead and close this issue, since this addresses the problem as
stated.

**Comment by ahrm** [comment]
I extended this functionality considerably in f7b4d28701b6b93c75ef11e3b7bf64bac88086a6. Now for every configuration named `config_name` we have a command named `setconfig_config_name` that can be used to set the value of that config. This means you can use these commands in macros to dynamically set the value of every configuration.

**Comment by omuhr** [comment]
> I extended this functionality considerably in [f7b4d28](https://github.com/ahrm/sioyek/commit/f7b4d28701b6b93c75ef11e3b7bf64bac88086a6). Now for every configuration named `config_name` we have a command named `setconfig_config_name` that can be used to set the value of that config. This means you can use these commands in macros to dynamically set the value of every configuration.

Sorry to bring this up so much later, what is the currently recommended method for having multiple themes you can switch between? I want a custom light and dark theme and to be able to go back to default to check.

I got the macro method working fine but the config doesn't look very nice and is clumsy to edit. I didn't understand the setconfig_ method you described, or at least couldn't get it to work. I assumed that I could put a *.config file with settings ([e.g.](https://github.com/catppuccin/sioyek/blob/main/themes/latte.config)), and that Sioyek would scan all .config files and populate the setconfig_ commands but that doesn't seem to be happening.
