### ISSUE TITLE
Cannot delete highlights without mouse

### ISSUE THREAD

**Issue by cdpath** [ahrm/sioyek#398]
I can delete highlight with mouse left click and `dh`, but cannot do so with pure keyboard.

The doc says: 

> Alternatively, you can press the delete button on the keyboard in the highlight list.

However, when I enter highlight list with `gh`, select the very highlight I'd like to delete with `ctrl-n`/`ctrl-p`, then `delete`. The selected highlight is still there.

basic info:

> sioyek 1.5.0, installed with brew, on M1 MacBook Pro
> vanilla sioyek configuration without any changes

Thank you in advance!

**Comment by ahrm** [comment]
I assume this is a mac-specific issue, because on my windows and linux systems the delete key works as intended.

I would appreciate it if someone with both a mac and windows/linux system could weigh in on this issue.

**Comment by admorgan** [comment]
I have to click on the first letter in the hightlight or it does not work. I would expect selecting anywhere in the highlight, or selecting the hightlight in the search then using dh would work, but I can only delete the highlight by clicking on the first letter. This is on Ubuntu 20.04 using flatpack installed today.

**Comment by ahrm** [comment]
> I have to click on the first letter in the hightlight or it does not work. I would expect selecting anywhere in the highlight, or selecting the hightlight in the search then using dh would work, but I can only delete the highlight by clicking on the first letter. This is on Ubuntu 20.04 using flatpack installed today.

I think the flatpak build is pretty old. Can you reproduce the issue on the latest builds here? : https://github.com/ahrm/sioyek/releases/tag/v1.5.0

**Comment by admorgan** [comment]
You are correct the flatpack is 1.4.0. With 1.5.0 I can click anywhere in the highlight and delete it. I cannot select the highlight from the search and delete it without clicking though.

**Comment by ahrm** [comment]
Are you using `goto_highlight_g` or `goto_highlight`? We don't allow you to delete highlights in `goto_highlight_g`, because we don't want to accidentally delete highlights of some other document. We only allow deleting highlights of current document opened using `goto_highlight`.

**Comment by admorgan** [comment]
I gh, select the highlight then dh.

**Comment by ahrm** [comment]
> I gh, select the highlight then dh.

You need to press the `delete` key (dedicated delete key on the keyboard) not `dh`.

**Comment by admorgan** [comment]
`delete` works in the gh screen, but not when I visit the highlight through the search, nor after clicking on the highlight in any location.

I also don't feel it would be obvious to use the delete key outside of the gh screen.

**Comment by ahrm** [comment]
I guess I exlpained poorly. In the document you are supposed to delete highlights by first clicking on them and then pressing `dh`. In the list of highlights you obviously can not press `dh` (because that would just type `dh` in the search bar) so you have to use the `delete` key.
