### ISSUE TITLE
Is there is a scroll bar?

### ISSUE THREAD

**Issue by li-aolong** [ahrm/sioyek#400]
Sometimes it is very convenient to use a scroll bar. Does sioyek have it?

**Comment by li-aolong** [comment]
@ahrm Thanks for your reply. 

But for the first situation, sometimes I will not remember some formula or some other information. I just need to have a rough look and I haveto keep scrolling the scroll wheel without a scroll bar, which is slow and inconvenient. For the second situation, the contents can't be seen clearly while it is zoomed out far and scrolled in the meantime. 

Will a scroll bar be added in the future?

**Comment by li-aolong** [comment]
Or could you tell me how to add a scroll bar? Thanks.

**Comment by ahrm** [comment]
Personally, I hate scrollbars and I don't think it works well with sioyek's ui. Here is another idea:
what if we had a mode which you could toggle using a keybind which increased scrolling speed considerably? Then for these situations you could enable this mode, scroll back and then disable it. Would this fix your use-case?

**Comment by li-aolong** [comment]
I'm afraid this model can't fix my use-case, cause the situations when I want to use a scroll bar are various. For example, I suddenly want to see results or the motivation, and I just look a through and begin to think. My left hand may be off the keyboard and I just  need to take a look at the whole with the mouse. In general, sometimes I just want to use a mouse and don't want to use my left hand.

**Comment by ahrm** [comment]
Added a `toggle_scrollbar` command in 5f76ee681a18efe203aa0bcde250a6b10ede1672.

**Comment by li-aolong** [comment]
@ahrm Thanks a lot!
