### ISSUE TITLE
Closing one sioyek window closes all open sioyek windows

### ISSUE THREAD

**Issue by gjgress** [ahrm/sioyek#401]
I am using the flag `should_launch_new_window 1` because I need multiple instances of sioyek running (reading multiple papers, textbook references, etc).

If more than one sioyek window is open, then using `:quit` on one window closes all open sioyek windows. My guess is that even though sioyek has separate windows, they run on the same server (instance), and `:quit` stops the server and hence all windows. Because if one uses `should_launch_new_instance 1`, this bug does not occur.

EDIT: I just noticed-- if a sioyek window is already opened, then compiling a PDF in vimtex does not open a new window or instance of sioyek, regardless of which flag is set. I am guessing it is related to this issue, but if not I can open a new issue for it.

As a related note, not really a bug, but perhaps sioyek should be able to open multiple PDFs with `sioyek 1.pdf 2.pdf`.

Why was the instance flag deprecated? Are there issues that arise from it?

**Comment by ahrm** [comment]
We replaced `--new-instance` and `should_launch_new_instance` with `--new-window` and `should_launch_new_window` respectively, which do the same thing, only better and more efficiently.

If you want to close a single window, you should issue `close_window` command not `quit`.

**Comment by gjgress** [comment]
Does issuing `close_window` do the same thing as `quit` when there is only one window? If so, that should be ok.

Nevertheless, this bug:
> EDIT: I just noticed-- if a sioyek window is already opened, then compiling a PDF in vimtex does not open a new window or instance of sioyek, regardless of which flag is set. I am guessing it is related to this issue, but if not I can open a new issue for it.
still occurs. Should I open a new issue for it?

**Comment by ahrm** [comment]
> EDIT: I just noticed-- if a sioyek window is already opened, then compiling a PDF in vimtex does not open a new window or instance of sioyek, regardless of which flag is set. I am guessing it is related to this issue, but if not I can open a new issue for it.

Do you use the `--new-window` flag in vimtex to open sioyek?

**Comment by gjgress** [comment]
I do not. My understanding is that sioyek launching through vimtex still uses the config files that launching it normally does, so I'd guess that using `should_launch_new_window 1` would be sufficient.

I would try it to see if it works, but I cannot replicate the bug today, so it is moot. I wouldn't be surprised if I had a hanging sioyek process going on somewhere in the background, with how much I was messing with these parameters yesterday.

I'll close this for now, but if this issue crops up again I'll reopen this and investigate further.
