### ISSUE TITLE
compile Error on pdf_viewer/main_widget.cpp

### ISSUE THREAD

**Issue by EvaristeFan** [ahrm/sioyek#402]
pdf_viewer/main_widget.cpp:3031:39: error: ‘std::string’ {aka ‘class std::__cxx11::basic_string<char>’} has no member named ‘starts_with’
 3031 |     if (current_pending_command->name.starts_with(config_prefix)) {

installed it on archlinux

**Comment by ahrm** [comment]
Should be fixed in 12b43c92a5002e07e9123af2f617bd7670a6da0f.
