### ISSUE TITLE
statusbar covers part of the document in presentation mode

### ISSUE THREAD

**Issue by pitkling** [ahrm/sioyek#403]
When entering presentation mode with an activated statusbar, the statusbar covers a small stripe of the document at the bottom. This is particularly annoying if the window is wider than the document. I would expect that when the statusbar is active, presentation mode scales the content such that it fits into the **visible** part of the window (i.e., window area minus the area covered by the statusbar).

Btw. thanks for the great tool and continuous development of great and novel features!

**Comment by ahrm** [comment]
Thanks for your feedback, for now as a workaround you can hide the statusbar in presentation mode by issuing `toggle_status_bar` command.

**Comment by ahrm** [comment]
Should be fixed in 867ba7fc64790ea8bf6ca9afa685424539cdc450.
