### ISSUE TITLE
Cannot zoom in

### ISSUE THREAD

**Issue by raffaem** [ahrm/sioyek#404]
I have sioyek 1.5.0 downloaded from Github release page, portable version, running on Fedora Workstation 36.

I cannot zoom in neither with `+` nor with  `shift+=`. Zooming out with `-` works.
Zooming in with undocumented `ctrl+mouse wheel up` works too.

**Comment by ahrm** [comment]
I assume it is a keyboard layout issue. Are you using staandard english layout? See this issue for more information: https://github.com/ahrm/sioyek/issues/254 .

**Comment by raffaem** [comment]
> I assume it is a keyboard layout issue. Are you using staandard english layout? See this issue for more information: #254 .

Yes I have an italian layout.

There seems to be no `keys_new.config` in the repository?

Can you post a passage-by-passage list of things I have to do?

**Comment by raffaem** [comment]
There seems to be no need for `use_legacy_keybinding 0`.

Just putting `zoom_in +` in `keys_user` works.

**Comment by ahrm** [comment]
I have not created `keys_new.config` yet. You just have to add `use_legacy_keybinds 0` to your `prefs_user.config`. This might cause some of your keybinding to stop working. You have to manually define those in your `keys_user.config`. For example, instead of `<S-+>` as a keybinding for zoom in, you just need to use `+`.

**Comment by raffaem** [comment]
> I have not created `keys_new.config` yet. You just have to add `use_legacy_keybinds 0` to your `prefs_user.config`. This might cause some of your keybinding to stop working. You have to manually define those in your `keys_user.config`. For example, instead of `<S-+>` as a keybinding for zoom in, you just need to use `+`.

Looks like I have to re-define a lot of things, including `:` to access the command line and `O` to open previous documents.

I will wait until that file is ready.
