### ISSUE TITLE
Print actual database locations

### ISSUE THREAD

**Issue by erooke** [ahrm/sioyek#405]
When starting sioyek it prints out what looks like diagnostics:
```
default_config_path: /etc/sioyek/prefs.config
default_keys_path: /etc/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/ethan/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/ethan/.config/sioyek/keys_user.config
database_file_path: /home/ethan/.local/share/sioyek/test.db
local_database_file_path: /home/ethan/.local/share/sioyek/local.db
global_database_file_path: /home/ethan/.local/share/sioyek/shared.db
tutorial_path: /usr/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/ethan/.local/share/sioyek/last_document_path.txt
shader_path: /usr/share/sioyek/shaders
```

What's interesting is the `global_database_file_path` is just printing the default location. My config is the following:
```
shared_database_path	/home/ethan/documents/library/.sioyek.db
```
and it still prints `/home/ethan/.local/share/sioyek/shared.db`.

I find this to be very counter intuitive. I was reading that line to confirm that my config changes had taken. I think it would make more sense to print out the configured locations as opposed to the default ones.

**Comment by ahrm** [comment]
We print these diagnostics before parsing configuration files (because we want to have them if there is any issue with the configuration files). So it is impossible to print the path that is modified in the configuration file.
