### ISSUE TITLE
[Feature Requested] auto adaption of visual scroll mode for two column papers

### ISSUE THREAD

**Issue by yishifengyin** [ahrm/sioyek#408]
I enjoy using the visual scroll mode for reading papers. But I found it is not convenient for two column papers:

In current version, the visual mark can only appear in the left-hand-side column. When there is need to focus on the right-hand-side column, I have to move the visual mark scroll down LHS columns and restart from the RHS.

I think a more appropriate behavior should be record the position of right-clicks. When entering the visual scroll mode, the visual mark would auto adapt its position in LHS or RHS according to the recent records.

Thanks

**Comment by yishifengyin** [comment]
Or like the vim, using hjkl to move the visual mark? currently, only jk are used

**Comment by ahrm** [comment]
Which sioyek version are you using? This issue should be fixed in version 1.5 .
