### ISSUE TITLE
Can not compile Sioyek MacOS

### ISSUE THREAD

**Issue by fanmih** [ahrm/sioyek#41]
Hello!
MacOS: `10.15.7`
QT installed from home-brew: `qt: stable 6.1.3 (bottled)`
compilation fails:
`Project ERROR: Unknown module(s) in QT: openglextensions`
Any ideas how to troubleshoot?

**Comment by ahrm** [comment]
Hmmm I can't be sure because I don't have a Mac computer but maybe the problem is with the Qt version? We use Qt 5.14, I don't know how backwards compatible Qt 6 is.

**Comment by fanmih** [comment]
I managed to compile on MacOS with the following:
Installed Qt 5 with homebrew:
`brew install qt@5`
then follow the instructions on
`brew info qt@5`
to add the Qt5 executables and libraries in the path:
```bash
echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> ~/.zshrc
export LDFLAGS="-L/usr/local/opt/qt@5/lib"
export CPPFLAGS="-I/usr/local/opt/qt@5/include"
export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"
```
then run the build script
`./build_mac.sh`


It looks like a very promising app!
Thanks!
