### ISSUE TITLE
Infinite page scrolling loop in reference quick overview

### ISSUE THREAD

**Issue by sim642** [ahrm/sioyek#411]
When right-clicking on a reference to open its quick overview window, then it's possible to scroll inside that overview window. Very confusingly, it only scrolls that single page infinitely: inside the overview at the end of the page, the same page starts again.
Not only is this confusing, it also prevents scrolling multi-page tables and the like.

**Comment by ahrm** [comment]
Should be fixed in cd94d6a133b0da7c14f7c381c0f4f00fc9f91a46. We still show one page at a time (for performance reasons) but we allow you to scroll between pages in overview window. Also we disallow scrolling past the beginning/end of the document.
