### ISSUE TITLE
Horizontal scroll reversed

### ISSUE THREAD

**Issue by amanjitsk** [ahrm/sioyek#412]
I have the following in my `keys_user.config`
```conf
move_left           h
move_right          l
```
but pressing `h` moves right (instead of left), and vice-verse for `l`. This is probably just an easy bug to fix (I hope its not something super weird on my end).

**Comment by ahrm** [comment]
`move_left` moves the "camera" to the left, which moves the document to the right. I know it sounds weird, but I think it is more natural the way it is (you can always reconfigure it if you don't like it).

**Comment by amanjitsk** [comment]
ok thanks makes sense! I will just switch them around!
