### ISSUE TITLE
Request for exhaustive list of all commands and options that are available

### ISSUE THREAD

**Issue by CodePurble** [ahrm/sioyek#414]
I wanted to use Sioyek the moment I found out about it, but I always felt held back by the a lack of documentation for the configuration options. The "readthedocs" page is pretty good, but I still think it is not exhaustive. For example, I wanted to know if a "fit page to window height" command was available. The `prefs.config` and `keys.config` don't have that option anywhere, but when I searched the GitHub Issues, I discovered that there is an option for that. Having to search in multiple places to check whether an option is there or not is a bit of a pain. A single source of truth will fix all of this. Maybe just add all possible options to the non user-config files so that they can be used as reference, or keep the `readthedocs` page more complete? If I'm looking in the wrong place, please show me where I can find this information. I really appreciate the project and your connect with the users.

Thanks

**Comment by CodePurble** [comment]
I am adding a list of "undocumented" commands/settings that I have stumbled upon here:

- `toggle_statusbar`
- `fit_to_page_height_smart`
- `fit_to_page_height`

**Comment by ahrm** [comment]
Added a commands page to the documentation here:
https://sioyek-documentation.readthedocs.io/en/latest/commands.html
