### ISSUE TITLE
Disable scrolling past document boundaries

### ISSUE THREAD

**Issue by CodePurble** [ahrm/sioyek#415]
Is it possible to to stop scrolling if the top or bottom of the document is reached? Currently, it does a half-page scroll past the ends (Even when we use `gg` and `G`)

![image](https://user-images.githubusercontent.com/49452779/189129177-ee5d414f-4a02-47d3-84d3-837acdbb404e.png)

**Comment by ahrm** [comment]
Also see this issue:
https://github.com/ahrm/sioyek/issues/374
