### ISSUE TITLE
[Help]：Display the bookmarks string of the current page in the status bar.

### ISSUE THREAD

**Issue by windily-cloud** [ahrm/sioyek#416]
I want to display the bookmarks of the current page in the status bar. Like this：
<img width="584" alt="image" src="https://user-images.githubusercontent.com/30640638/189469749-06bc024a-5312-48d5-81ea-8f636cedb05b.png">

The way I currently do it is this：
Your latest version was updated with a custom add status bar string, I write a python script:
1. read the current page number to find the current bookmark in the database
2. use the custom command to display it on the status bar.

But this requires an infinite loop that makes every page displayable, which may not be too elegant. Do you have any good suggestions?

**Comment by ahrm** [comment]
Added a `show_closest_bookmark_in_statusbar` config in 9eef6581ca5aa1720112e24494051c8c507d56ba. You can enable it by adding the following to your `prefs_user.config`:
```
show_closest_bookmark_in_statusbar 1
```

**Comment by windily-cloud** [comment]
Thank you very much and Happy Mid-Autumn Festival!😆😆😆😆
