### ISSUE TITLE
Custom keybinds not working on Debian 11

### ISSUE THREAD

**Issue by MatiasPujado** [ahrm/sioyek#421]
Hello! My daily driver its been Debian 11 for over a year. A friend of mine recommended me to start using this app, and he is a Windows user. I am currently struggling trying to make the pre-compiled version to use my custom keybinds. I have tried on several directories with both versions (non-Portable and Portable versions), in the order specified here:

```
❯ sioyek
Setting $XDG_CONFIG_HOME to /opt/sioyek/Sioyek-x86_64.AppImage.config
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
default_config_path: /tmp/.mount_sioyekEZGzHf/usr/bin/prefs.config
default_keys_path: /tmp/.mount_sioyekEZGzHf/usr/bin/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /opt/sioyek/Sioyek-x86_64.AppImage.config/sioyek/prefs_user.config
user_config_path: [ 2 ] /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/prefs_user.config
user_config_path: [ 3 ] /home/coder/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /opt/sioyek/Sioyek-x86_64.AppImage.config/sioyek/keys_user.config
user_keys_path: [ 2 ] /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/keys_user.config
user_keys_path: [ 3 ] /home/coder/.config/sioyek/keys_user.config
database_file_path: /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/test.db
local_database_file_path: /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/local.db
global_database_file_path: /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/shared.db
tutorial_path: /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/tutorial.pdf
last_opened_file_address_path: /opt/sioyek/Sioyek-x86_64.AppImage.config/.local/share/Sioyek/last_document_path.txt
shader_path: /tmp/.mount_sioyekEZGzHf/usr/bin/shaders
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application successfully attached to shared memory block.
Secondary application sent message to IPC server.
```
Now every single time Sioyek starts reads only this file **/tmp/.mount_sioyekEZGzHf/usr/bin/keys.config**. I already tried giving the app 775 permissions but still it wouldnt work. 
I was trying to avoid compling sioyek myself given that I have no much experience, and since its my first time using the app made sense to start with the AppImage. 
Is there a way I can actually customize keybinds and preferences for the pre-compiled version?
Its worth to mention that sioyek folders were correctly created by the app under .local and .config directories. But the app its not picking up settings from this location.
Thank you in advance

**Comment by ahrm** [comment]
You can always put your `keys_user.config` and `prefs_user.config` in `~/.config/sioyek`.

**Comment by MatiasPujado** [comment]
Im sorry, I thought I was clear. I already tried different directories, the one you just mentioned is among them. 
It didnt work. Sioyek its only reading this file: /tmp/.mount_sioyekEZGzHf/usr/bin/keys.config
Since I dont know what else to do Im here asking for help. I already went through the whole documentation.
Is there anything I can do to make it work?

**Comment by ahrm** [comment]
> Sioyek its only reading this file: /tmp/.mount_sioyekEZGzHf/usr/bin/keys.config

How have you verified this? Are you sure there is no error in your user config files?

Also have you tried both the portable and non-portable AppImages?

**Comment by MatiasPujado** [comment]
> How did you verify this? Are you sure there is no error in your user config files?
When I opened sioyek and looked for the file keys.config it would open as [Read-only] file. Thanks to the console output i shared earlier and and the text editor that confirmed the program is currently reading only 1 file.
Its a fresh install of Debian, I've tested this on my other user accounts and I got the same result. 

>Also have you tried both the portable and non-portable AppImages?
Yes, I already explained this above

**Comment by ahrm** [comment]
I will try to test this on a debian VM in the following days.

**Comment by MatiasPujado** [comment]
Alright, thank you! I appreciate your assistance on this matter. 
Its a wonderful app and I'd love to tweak it to be more comfortable with it.

**Comment by ahrm** [comment]
I just tested it on a vanilla debian 11 install and it seems to work fine. Are you sure your config files are correct? Maybe share your `keys_user.config` file that you use for testing here?

**Comment by MatiasPujado** [comment]
Sure, here it is: https://pastes.io/9krog4qnen  I only changed a few lines, between 22 and 34. 
I made a copy of the content of the file: /tmp/.mount_sioyekEZGzHf/usr/bin/keys.config (which is the output of selecting the **keys** command), and pasted it in ~/.config/sioyek/keys_user.config (output of keys_user command)

**Comment by ahrm** [comment]
You don't need to copy the entire file, just the configs that you want to
change. Of course if it is not working it is still a bug and should be
fixed, but for now, try using a minimal configuration file and see if the
issue persists.
