### ISSUE TITLE
[ SIGNING REQUIRED ] "“sioyek.app” cannot be opened because the developer cannot be verified."

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#422]
I installed it on macOS Monterey with M1 Pro and this error doesn't let me open the app.

**Comment by ahrm** [comment]
You need to give permission to open sioyek. See
https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac
.

**Comment by ibehnam** [comment]
Thank you, this solved it.
