### ISSUE TITLE
Sioyek not working on multiple resolutions?

### ISSUE THREAD

**Issue by EsbenMadsen** [ahrm/sioyek#423]
I'm using Sioyek at my home office, using a second monitor, as well as on my laptop, but I've run into issues doing this. Ever since using Sioyek on my second monitor, it no longer works on my laptop screen. It continues to work fine while connected to my secondary monitor, even when dragging Sioyek from the secondary to the laptop screen. However, when disconnected from the secondary monitor, the window is just black. The program is still running underneath (I can see the pages changing when scrolling) but not displaying anything.

I suspect it has something to do with changes in the configuration file being made when connecting to the secondary monitor and not changed back when disconnecting. Let me know which steps I can take to reproduce this and help debug this.

**Comment by ahrm** [comment]
Yes, I assume the problem is that sioyek memorizes the window configuration, and when the second monitor is disconnected it still tries to show it on the second monitor. So sioyek is probably open, it is just outside of the screen so you can move it back into screen by alt-tabbing into it and moving it using keyboard shortcuts.

**Comment by EsbenMadsen** [comment]
I should add that when disconnecting the monitor while Sioyek is open, the window on the laptop is black and you can see the overlay (this might be solved by what you say, I will test when I get the chance). When closing and reopening the window while disconnected, the screen is blank (white) and there is no overlay or other kind of response. This is not solved by the above suggestion.

**Comment by ahrm** [comment]
This is strange, which operating system are you using?
Also it may be a zoom issue? (try executing `fit_to_screen_width` on the black window and see what happens.)

**Comment by EsbenMadsen** [comment]
I'm using windows 11 home. I tried using fit_to_page_width on the white screen with no response. Will test with black screen later.

**Comment by EsbenMadsen** [comment]
Just returning to say I performed the test, and it made no difference

**Comment by ahrm** [comment]
I have no idea what the issue might be. I can't reproduce it. Maybe delete `auto.config` file (it should be in `AppData/Roaming/sioyek`) and see if it helps.

**Comment by EsbenMadsen** [comment]
Hello, just checking back in to say I tried a few things, none of which worked. However, I just updated windows, and now the issue seems to be resolved. Thanks for the effort and this amazing PDF reader.
