### ISSUE TITLE
How to use papers_folder_path

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#425]
I set papers_folder_path D:\folderA, but I don't know how to open files in target folderA

**Comment by ahrm** [comment]
The only special thing about the papers folder is that they will be the destination of a portal if there is a pending portal when they are added to the folder. You have to open them like you open files in any other location.

**Comment by wenbopeng** [comment]
> 

But after I press `p`, I still can't get to folderA directly. My purpose is to be able to go directly to folderA

**Comment by ahrm** [comment]
You would have to use some other program to create a hotkey to open that document (AutoHotKey for example).
