### ISSUE TITLE
Feature Request: Some trackpad config options

### ISSUE THREAD

**Issue by Slickytail** [ahrm/sioyek#427]
It would be nice if trackpad sensitivity also applied to zoom sensitivity.
The other big thing would be smooth scrolling.

**Comment by wenbopeng** [comment]
According to the developer, this PDF reader is currently focused on keyboard users. 😀

**Comment by ahrm** [comment]
We have already added smooth scrolling in 1ce9d365ac602e277dfcd34a82c08c789c84ac24 (not in a released build yet).

**Comment by rroohhh** [comment]
@Slickytail if your trackpad supports high precision scrolling (most newer ones do afaik) my recent changes should improve things quite a bit for trackpad usage.
