### ISSUE TITLE
Keyboard_select until start of closing word, but exclusively

### ISSUE THREAD

**Issue by KeAWang** [ahrm/sioyek#433]
Right now, keyboard_select followed by e.g. `aa bb` will select text that starts at the first character of the `aa` word until the first character of the `bb` word.

For example, if the sentence is "foo bar baz" and `aa` is "foo" and `bb` is "baz", sioyek will highlight "foo bar b". This seems rather unintuitive. Is there a way to improve the syntax so that we highlight until _but excluding_ the `bb` word, i.e. not inclusive of the closing word?

**Comment by ahrm** [comment]
Improved `keyboard_select` in f8487bc3eac40e6dad933ec350a156a7bf590493. Now we shouldn't select the first character of the last word. Also added the ability to select a single word using `keyboard_select` by just entering the tag corresponding to that word.
