### ISSUE TITLE
Case insensitive search with super-fast search

### ISSUE THREAD

**Issue by hrdl-github** [ahrm/sioyek#435]
Do you have an opinion on supporting case-insensitive search in combination with super-fast search, as supported by the original search function?

**Comment by ahrm** [comment]
We also have a `regex_search` command which can be used to do more advanced searches. For example, if you want to find the word example without case sensitivity you can do something like this: `[Ee]xample`.

**Comment by ahrm** [comment]
In general I am open to it if the search is still fast.
