### ISSUE TITLE
Allow 'alt' key as a modifier

### ISSUE THREAD

**Issue by rien333** [ahrm/sioyek#44]
In zathura (which this project seem to draw some inspiration from?), one has the ability to not only use the <kbd>shift</kbd> and <kbd>ctrl</kbd> keys as modifiers, but also the <kbd>alt</kbd> key. Any chance this modifier could be added to the existing roster?

In zathura, the way to configure such a keybinding would look like this:

```
goto_page_with_page_number		<A-g>
```

**Comment by ahrm** [comment]
Added in 89a011797c4ed28313896278faee809ce4711ffe.
