### ISSUE TITLE
[feature] prerender pages configuration

### ISSUE THREAD

**Issue by SichangHe** [ahrm/sioyek#440]
# Add a configuration on the number of pages prerendered
## Problem to solve
When paging through PDFs rapidly, sometimes sioyek does not render the newly visible page quick enough, so the user see a page that is not rendered for a while (up to around 500 ms). This degrades the user experience a lot.
## Objective
Mitigate the said problem by providing an option to prerender more pages around the current visible page.
## Comments
Using a larger number of prerendered pages will cause more memory usage, however, the user should be willing to pay for that if they choose to configure sioyek to do so.
Alternatively, the problem can also be solved by rendering pages faster, although I assume sioyek is already doing that at its best.

**Comment by ahrm** [comment]
I have added this option, but I can't push it to github because [my piece of shit government is blocking my internet](https://slate.com/technology/2022/09/iran-protests-mahsa-amini-internet-censorship.html). I can view github but I can't push anything. You'll have to wait until my internet returns to normal.

**Comment by SichangHe** [comment]
No worry! Please tell me (and add the documentation) when you push so I can try it out.
Your government at least lets you view GitHub.

**Comment by ahrm** [comment]
Added a `prerendered_page_count` setting in 20b7b30a72235cc4e69affe2c9cdcc288015613b.

**Comment by SichangHe** [comment]
I tried this on [Release v0.31.406](https://github.com/hexomancer/sioyek/releases/tag/v0.31.406) just now. Forward prerendering works.
But, backwards prerendering does not work. To be specific, if I scroll up, I still encounter unrendered pages.
