### ISSUE TITLE
Multiple windows issues

### ISSUE THREAD

**Issue by samtrek** [ahrm/sioyek#442]
creation of issue
in the config add these additional options

1 should_launch_new_window                1

2 startup_commands   toggle_select_highlight;toggle_horizontal_scroll_lock; 

all the above options are enabled in the first opened PDF and ignored in the second or the other PDF windows, in addition their is no highlight in the second opened PDF window despite that highlight has been made on the PDF before. And the highlight can only be seen if all windows are closed and the PDF is opened as the first window.

**Comment by ahrm** [comment]
Which sioyek version are you using? This was a bug in 1.5 but should be fixed in 4992e3288c698c89f61853407097047c7359cf8d. There are experimental builds of newer commit available in this repository:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.393

**Comment by samtrek** [comment]
Using 1.5 on linux let me switch to the git version and give you feedback on it, will close the issue since it is een worked on

**Comment by samtrek** [comment]
fixed in the latest git release thanks for your great effort I am closing the issue
