### ISSUE TITLE
Status bar is too small for text

### ISSUE THREAD

**Issue by GoldsteinE** [ahrm/sioyek#444]
![image](https://user-images.githubusercontent.com/12019211/193463919-985fc330-19eb-453f-af69-68d2dd94093b.png)

I use NixOS, X11, bspwm, sioyek 1.5.0

**Comment by ahrm** [comment]
Does setting `status_bar_font_size` in `prefs_user.config` help? For example:
```
status_bar_font_size 20
```

**Comment by GoldsteinE** [comment]
It does, actually, thanks.
