### ISSUE TITLE
[Enhancement/Bug] ToC feature does not detect all possible tables of contents, example included

### ISSUE THREAD

**Issue by ArgyleSocks** [ahrm/sioyek#445]
There is this textbook on OpenGL: https://mathweb.ucsd.edu/~sbuss/MathCG2/SecondEdDraft.pdf which has a table of contents, but it is ostensibly not formatted in such a way that the ToC feature can reliably detect it. Specifically, the entire ToC goes undetected, but some arbitrary five pages throughout the textbook are entered as ToC entries, but this is incorrect. Perhaps this particular example may want to be looked at for future improvement of the ToC detection heuristics.

**Comment by raffaem** [comment]
Your document seems not to contain any table of contents according to the [PDF 1.4 specification](https://www.pdfa.org/resource/pdf-specification-index/).

I don't know what sioyek is picking.

It has some algorithm to infer a table of content and apparently that is failing.

**Comment by ArgyleSocks** [comment]
Yes, I am referring to the feature for inferred ToC. From the website, "Sioyek can even generate the table of contents if the document doesn't have one!", so this seems to be a meaningful report; Sioyek did not correctly infer the ToC, even creating a nonsense ToC, but it is intended to.

**Comment by raffaem** [comment]
Can you try PR #458?

**Comment by ahrm** [comment]
Merged the pull request, seems to fix the issue for this document format. Note that the table of contents generation is a heuristic, so it is always possible to find documents that don't work with our heuristic.

**Comment by raffaem** [comment]
@ahrm close this issue?
