### ISSUE TITLE
can the bookmark order by page number rather then adding time?

### ISSUE THREAD

**Issue by Imymirror** [ahrm/sioyek#446]
1.  type `ab` add multiple bookmarks .
2. type `gb` show the bookmarks, sorted by time.

How can i show the bookmarks ordered by page number rather then adding time.

**Comment by ahrm** [comment]
We have a `sort_bookmark_by_location` option: https://sioyek-documentation.readthedocs.io/en/latest/configuration.html#sort-bookmarks-by-location

You can enable it like so:
```
sort_bookmark_by_location 1
```

**Comment by Imymirror** [comment]
thank you! It solve my problem. So I close the issue.
