### ISSUE TITLE
[Question]: Is the database with the highlights synchronizable between different devices and operating systems?

### ISSUE THREAD

**Issue by lucidBrot** [ahrm/sioyek#447]
I am considering using syncthing to keep my sioyek database files synchronized between my computers. That should make the highlights in a file hopefully also available on all my other devices.

Before I try it out, I would like to know whether it might work or whether it is clear from the start that it won't (e.g. because the paths are different even if the file is the same one).

I am aware of the `embed_annotations` command, but it would be great if I could avoid the manual effort.

**Comment by ahrm** [comment]
Yes, see the documentation:
https://sioyek-documentation.readthedocs.io/en/latest/usage.html#data-and-synchronization

**Comment by lucidBrot** [comment]
Oh, lovely!

Thank you for the link! I am not used to finding such things actually documented, great work!

**Comment by lucidBrot** [comment]
It works! Follow-up information that could be useful for future visitors:

I had installed sioyek with `flatpak` on ubuntu 18.04 (because building myself failed due to missing dependencies and I couldn't be bothered to find them) and because of this the files were at:

* `/var/lib/flatpak/app/com.github.ahrm.sioyek/x86_64/stable/SOME_HASH/files/sioyek/prefs_user.config`
* `~/.var/app/com.github.ahrm.sioyek/config/.local/Share/sioyek/shared.db`

On windows, the original `shared.db` was at `%AppData%\sioyek`. The `prefs_user.config` did not yet exist (I believe) but there is also the option to open it by running from the command-line `./sioyek.exe --execute-command prefs_user`. The [documentation](https://sioyek-documentation.readthedocs.io/en/latest/configuration.html#shared-database-path) is actually quite good and explains all of this except for the flatpak-specific paths. Also that the syntax in the config is simply 
```
shared_database_path /the/path/to/The/shared.db
```

I am not 100% certain, but I believe I had to create a new highlight before the synced highlights appeared. It is working now even though the full paths of the pdf are very much not identical.

**Comment by ahrm** [comment]
> even though the full paths of the pdf are very much not identical.

Yes, let me explain exactly how it works so there is no confusion.

We use md5 hash of the file to store highlights/bookmarks/etc. So they are sharable across computers (because hash of the file stays constant). However, note that if you change the file (for example if you embed annotations) then this will not work anymore because the hash of the file is changed.
