### ISSUE TITLE
remove pdfs from the prev_doc list

### ISSUE THREAD

**Issue by rjrobben** [ahrm/sioyek#448]
Is there any ways to remove some pdfs from the prev_doc list? Want to keep the list clean sometimes. Thanks.

**Comment by ahrm** [comment]
You can press the `delete` button while the file is selected in the list.

**Comment by rjrobben** [comment]
Will you consider adding it in the documentation? As I seems cannot find the relevant part in the current doc. I am more than happy to help if you want.

**Comment by ahrm** [comment]
I can't fix it now because [my piece of shit government is blocking my internet](https://slate.com/technology/2022/09/iran-protests-mahsa-amini-internet-censorship.html). I can view github but I can't push anything. I can merge it if you do a pull request though.

**Comment by rjrobben** [comment]
That's not great. Does vpn help? Sure I will do it.

**Comment by ahrm** [comment]
Most VPNs have stopped working. The ones that do work still have the same problem.

**Comment by ahrm** [comment]
Added documentation here:
https://github.com/ahrm/sioyek-documentation/commit/6e61a91fd7c690846f7d3723bc77b8f6c645767b
