### ISSUE TITLE
Error while opening cyr named files

### ISSUE THREAD

**Issue by VolkovIlia** [ahrm/sioyek#449]
Steps to reproduce 
rename `example.pdf` to `пример.pdf`

`sioyek пример.pdf`

OS Linux 5.19

```
terminate called after throwing an instance of 'std::filesystem::__cxx11::fil
  what():  filesystem error: Cannot convert character sequence: Invalid or in
 or wide character
Aborted
```

**Comment by ahrm** [comment]
This issue should already be fixed. Does this happen in latest experimental builds here? :
https://github.com/hexomancer/sioyek/releases/tag/v0.31.395

**Comment by VolkovIlia** [comment]
Yep, it fixed in AUR `sioyek-git` version.  

Thanks.
