### ISSUE TITLE
[FR] Source command for config file

### ISSUE THREAD

**Issue by raffaem** [ahrm/sioyek#450]
The config file should have a `source` command that will source another config file.

This is very useful for theming.

**Comment by ahrm** [comment]
We have the following method for theming: https://github.com/ahrm/sioyek/issues/397

**Comment by raffaem** [comment]
No no.

When you build a theme, you ask the user to download a file, and run something like:
```
cp mytheme.config ~/.config/sioyek
echo "sourcetheme mytheme.config >> ~/.config/sioyek/prefs_user.config
```

**Comment by ahrm** [comment]
okay?

**Comment by raffaem** [comment]
Look for example at how [the dracula theme for vim get installed](https://draculatheme.com/vim)

**Comment by ahrm** [comment]
Well not everything in sioyek is supposed to be exactly like vim. Here is how you do it in sioyek:

1. You define a macro, say, `_set_dracula_theme` that sets the theme.
2. Now the user can call this command if they want to switch to this theme, or the can add it to their `startup_commands` if they want it to be the default.

**Comment by raffaem** [comment]
But how I have the user put the macro in `prefs_user.config`?

Appending to the file is prone to errors and may lead to a long file if the user installs more than a theme.

Isn't better to put the commands for the theme in a separate file and source this file from `prefs_user.config`?

**Comment by ahrm** [comment]
> Isn't better to put the commands for the theme in a separate file and source this file from prefs_user.config?

Yes, you are right.

**Comment by ahrm** [comment]
Added a `source_config` command in 76bd1e393138d135948bf3055ba0f9970095b76b. If you want to load another source file at startup, you can add it to startup commands like this:

```
startup_commands source_config(/path/to/config/file.config)
```

**Comment by raffaem** [comment]
Thanks,

I have tested it and have few comments in order of importance:

1. The source file is not able to issue "startup_commands" of its own. This is necessary for "toggle_custom_color"
2. The path to the sourced file must be full. It should default to `~/.config/sioyek` or to the local folder in case of relative path
3. If the source file is not found, it silently fails without any error in the terminal

**Comment by ahrm** [comment]
Added a `source` option to prefs config file. Now you can do something like this:
```
source /path/to/other/file.config
```

Issues 2 and 3 should be solved. Issue 1 is not solvable, the user has to manually add `toggle_custom_color` to their startup_commands.

**Comment by raffaem** [comment]
Wow, thanks!

> Issue 1 is not solvable, the user has to manually add toggle_custom_color to their startup_commands.

Damn, but then you have to search in the config file whether you already have `startup_commands` or not.

Couldn't that be turned into an option, instead of a start-up command?

**Comment by ahrm** [comment]
I don't consider this a problem, the user has to modify their config file anyway, so it is not too much to ask them to add `toggle_custom_color` to their `startup_commands` if they want it to be the default.

**Comment by raffaem** [comment]
So, the instructions I wanted to provide to the user to install the theme were something like:

1. Open a terminal
2. Run `git clone github.com/sioyek/the-beautiful-theme`
3. `cd the-beautiful-theme`
4. `cp the-beautiful-theme.config ~/.config/sioyek`
5. `echo "source the-beuatiful-theme.config" >> ~/.config/sioyek/prefs_user.config`

Now is adding:
6. `echo "startup_commands toggle_custom_color" >> ~/.config/sioyek/prefs_user.config`

would work in any case or if the user *already* has a startup_commands he has to search for it?

**Comment by ahrm** [comment]
No, this will overwrite the previous `startup_commands` if the user has any. It is better to just instruct the user to add `toggle_custom_color` to their startup commands.

**Comment by raffaem** [comment]
ok thanks :)
