### ISSUE TITLE
searching with /

### ISSUE THREAD

**Issue by samtrek** [ahrm/sioyek#459]
I have tried several times but the alternative for ctrl f seems not to work at all can you please look into it
from the terminal the general log is seen below as 

Warning: invalid command (key:/); resetting to root
Warning: invalid command (key:/); resetting to root

**Comment by ahrm** [comment]
Are you using non-english keyboard layout? If so, see this issue: https://github.com/ahrm/sioyek/issues/254.

**Comment by ahrm** [comment]
Should be fixed in 247d0cd13e44741051fb0a4b1eda804389611f27.
