### ISSUE TITLE
Feature request: bindings non-latin keys

### ISSUE THREAD

**Issue by VolkovIlia** [ahrm/sioyek#464]

**Comment by ahrm** [comment]
Added in 0fd8ec7ad2527e0d38853fc5d705d96d2ada517b.

**Comment by VolkovIlia** [comment]
Works well, thank you! 

To close the issue of layouts it would be nice to add using the same layout as the pressed button in the visual mod, or to change the selection in the visual mod to numbers. Right now, if I press the "м" button for visual mode, the selection range is still in English.

**Comment by ahrm** [comment]
Added a `numeric_tags` option in caf5569ae896d1d945ec891dddbd48732a5be475.
