### ISSUE TITLE
Some weirdness with font colour and footnotes/headers

### ISSUE THREAD

**Issue by ashprice** [ahrm/sioyek#465]
The font colour is changed from the first footnote until the end of the page. It doesn't change upon further footnotes or anything. See image attached. 

![out](https://user-images.githubusercontent.com/48685381/195494893-79de52b5-05c6-4268-9436-c1b5702a1002.png)

Happens with other files, too, for example, in one file, the whole pdf has the colour changed after one heading introducing a list of illustrations. 

And the same here after another heading in a different pdf, until a heading a bit lower in the page:

![2022-10-13-045536_2560x1440_scrot](https://user-images.githubusercontent.com/48685381/195495644-c9a5b380-af7b-4f4d-acef-396115e3d677.png)

sioyek is v. 1.5.0, let me know if I can supply any other info. 

An example file is attached. 

[ex1.pdf](https://github.com/ahrm/sioyek/files/9770326/ex1.pdf)

**Comment by ahrm** [comment]
The problem is with the document. If you screenshot the document and use a color picker tool you will see that the first characters' color is `#000000` while the later characters have the color of `#221f1f`. So this is an issue of malformed document, we can't do anything about that.
