### ISSUE TITLE
No clear way to delete marks

### ISSUE THREAD

**Issue by mwmuni** [ahrm/sioyek#467]
While the bookmark feature has a way to delete bookmarks `db`, the logical equivalent `dm` does not delete the closest mark; nor does it have any apparent way to delete marks.

Suggestion: Add `dm` as the way to delete the closest mark and add this to the tutorial.

OS: Windows 11
Sioyek Release Version: 1.5.0

**Comment by ahrm** [comment]
Why would you want to delete marks? You can always overwrite them. I don't see the point in deleting the marks.

**Comment by mwmuni** [comment]
> Why would you want to delete marks? You can always overwrite them. I don't see the point in deleting the marks.

For the same reason someone would want to delete a bookmark or portal.

**Comment by ahrm** [comment]
An unused bookmark will pollute the bookmarks list, and an unwanted portal is shown in the portal window. However, there is no list where marks are shown so ... .

**Comment by mwmuni** [comment]
> An unused bookmark will pollute the bookmarks list, and an unwanted portal is shown in the portal window. However, there is no list where marks are shown so ... .
