### ISSUE TITLE
Feature request: add a command line parameter `--nowait` for sioyek to return immediately

### ISSUE THREAD

**Issue by hammerfunctor** [ahrm/sioyek#468]
As the title says.

**Comment by ahrm** [comment]
Why don't you create an alias that calls something like this:
```
sioyek <params> & > /dev/null
```

**Comment by hammerfunctor** [comment]
When the main window is created by this line, it will be shutdown down when current shell exit.

**Comment by ahrm** [comment]
You should be able to do something like this:
```
sioyek > /dev/null 2>&1
```
