### ISSUE TITLE
Support .cbz and .cbr

### ISSUE THREAD

**Issue by PurpleAzurite** [ahrm/sioyek#47]
Thank you for the program. It is easily the best pdf viewing experience I had. Please consider supporting CBZ and CBR files which are the standards for digital comic books.

**Comment by ahrm** [comment]
Supporting other formats is something that I want to do at some point but it is not in the immediate future because it takes a lot of work.

**Comment by ahrm** [comment]
I just found out that mupdf supports cbz so we were supporting it already! The only thing was that files with cbz extension were not shown in the open file menu which is fixed in 1f5565e5d14aed7b74e3bd721e9a97c38671386d .

**Comment by ahrm** [comment]
> Yes i just found out about this by accident! It could be nice if .cbr files are also supported. Simply adding .cbr to the QFileDialog options should be enough.

No, mupdf does not support `.cbr` because (I assume) unlike zip, RAR is a proprietary file format.

**Comment by Endle** [comment]
> > 
> 
> No, mupdf does not support `.cbr` because (I assume) unlike zip, RAR is a proprietary file format.

You're right, the most used `unrar` is using a GPL-noncompatible license, [reference](https://fedoraproject.org/wiki/Licensing:Unrar)

There is also a `unrar-free` <https://gitlab.com/bgermann/unrar-free> , released in GPL v2. I haven't used it, and I'm not sure if it's reliable enough.

It may be possible bundle `unrar-free` into sioyek. Is it worth the effort?

**Comment by ahrm** [comment]
> > > 
> > 
> > 
> > No, mupdf does not support `.cbr` because (I assume) unlike zip, RAR is a proprietary file format.
> 
> You're right, the most used `unrar` is using a GPL-noncompatible license, [reference](https://fedoraproject.org/wiki/Licensing:Unrar)
> 
> There is also a `unrar-free` https://gitlab.com/bgermann/unrar-free , released in GPL v2. I haven't used it, and I'm not sure if it's reliable enough.
> 
> It may be possible bundle `unrar-free` into sioyek. Is it worth the effort?

That's interesting. I'll take a look but adding `cbr` support is not currently high on my priority list. (converting a `cbr` file to `cbz` is extremely easy, you just unrar the `cbr` file and then zip it again)
