### ISSUE TITLE
Feature Request: Support for PDF Page Labels

### ISSUE THREAD

**Issue by kiryph** [ahrm/sioyek#476]
1. Show pdf page labels and page numbers in the status bar. For an illustration see this comment: https://github.com/ahrm/sioyek/issues/86#issuecomment-1144426909
2. Allow to jump to page label `:goto_page_label <label>` (possibly with partial or fuzzy matching; in the example document below, the page label `Cover` does not have to be entered completely and lowercase is also possible)
3. Allow to configure to use `:<input>` to navigate by `:<page number>` or `:<page label>`. The configuration variable could look like: `default_colon_navigation="number|label"`.
4. Allow to configure `42gg` to refer to page number or page label. The configuration variable could look like `gg_navigation="number|label"`.

For the last two points, if a document does not have page labels, sioyek should fall back to page numbers.

### Example PDF Document

File: [demo-pdf-pagelabel.pdf](https://github.com/ahrm/sioyek/files/9826649/demo-pdf-pagelabel.pdf)

generated from following LaTeX document:
```tex
\documentclass{book}
\usepackage{hyperref}
\begin{document}
\begingroup
  \renewcommand*{\thepage}{Cover}
  \pagestyle{empty}
  \Huge Cover
  \cleardoublepage
\endgroup
\frontmatter
\tableofcontents
\listoffigures
\listoftables
\mainmatter
\chapter{Abc}
page 1
\end{document}
```
based on https://tex.stackexchange.com/questions/246705/pdf-page-labels

### Motivation

To quickly jump with the keyboard to a specific page using page labels which agree with the printed page numbers is useful. Knowing the page offset for each document is not practical.

### PDFs with page labels

PDFs from platforms such as [link.springer.com](https://link.springer.com/) contain page labels.

### Tools to generate PDFs with page labels

- LaTeX package **hyperref**, https://ctan.org/pkg/hyperref
- Python cli tool **pagelabels-py** https://github.com/lovasoa/pagelabels-py (using pdfrw which has the issue to generate only PDFs with version 1.3)
- Python package **pikepdf**, 
  https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.Page.label
  https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.NumberTree
- Python package **pymupdf**,
  https://pymupdf.readthedocs.io/en/latest/page.html#Page.get_label
  https://pymupdf.readthedocs.io/en/latest/document.html#Document.set_page_labels
- **Cairo**,
  https://cairographics.org/manual/cairo-PDF-Surfaces.html#cairo-pdf-surface-set-page-label

**LibreOffice**
PDFs generated by LibreOffice Writer apparently do not export PDF page labels, even though you might have defined Roman page numbers for the front matter. see bug report https://bugs.documentfoundation.org/show_bug.cgi?id=98219

I did not check MS Word or Apple Pages.

### Viewer Supporting PDF Page Labels

- **Adobe Acrobat Reader** (but not for Android)
- **Apple Preview.app** (preinstalled PDF viewer on macOS)
- **Skim.ap**p (free PDF viewer for macOS with synctex support)
- **Xodo PDF Reader** for Android Devices

I assume Evince, Okular and similar support page labels as well. However, I cannot check right now Linux or Windows PDF Viewers. I would argue that support is not uncommon, i.e. users coming from other pdf viewers might expect this.

### References for PDF Page Labels

- https://www.w3.org/TR/2014/NOTE-WCAG20-TECHS-20140408/PDF17

- PDF 3200 2008, 
https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf#page=382

**Comment by ahrm** [comment]
We have added this in the development branch.
