### ISSUE TITLE
Feature Request: Option to show page boundary

### ISSUE THREAD

**Issue by navdeeprana** [ahrm/sioyek#478]
As the title says, it is possible to show the page boundary. Possible solutions:
- A small gap ( Evince style)
![image](https://user-images.githubusercontent.com/17153984/198252642-29f18c5c-8a05-4b9e-ab55-19c20ba7e4ec.png)

- A black boundary (Zathura style)
![image](https://user-images.githubusercontent.com/17153984/198252488-c224e316-9b33-421a-af04-90fb902f94ce.png)

**Comment by ahrm** [comment]
There is a parge separator option (though it only shows the vertical boundary):
```
page_separator_width 3
page_separator_color 0.5 0.5 0.5
```

**Comment by navdeeprana** [comment]
Aah, I looked at the documentation but did not find it. Should have put more effort into it. This works. Thank you very much.
