### ISSUE TITLE
More than 1 page scroll for overview window

### ISSUE THREAD

**Issue by cnut1648** [ahrm/sioyek#479]
Hello, I have similar question as https://github.com/ahrm/sioyek/issues/411. With overview window (right click on reference) currently there is only 1 page, and scrolling pass the one page becomes blank. It seems that scrolling more than 1 page is implemented but I still cannot scroll more than 1 page using the latest version (1.5.0). I wonder if there is some special config that users need to set. Thank you.

**Comment by ahrm** [comment]
As you mentioned, this issue is already fixed but it is not yet released in a stable build. There are experimental builds of more recent commits here if you want to try it out:
https://github.com/hexomancer/sioyek/releases/tag/v0.31.406

**Comment by cnut1648** [comment]
Oh I see, thanks @ahrm !!
