### ISSUE TITLE
Inverse search open the external editor twice in Synctex mode (Enabled by press the F4 key)

### ISSUE THREAD

**Issue by BarryArch** [ahrm/sioyek#480]
When I do inverse search(PDF -> tex source code )  in Synctex mode (Enabled by press the F4 key) by click on the pdf, sioyek seems to run the 'inverse search command ' twice, which lead to a result that there are two external editor windows open.
The example described in the manual using vscode for external editor works just fine because it use -r flag, I guess it means reuse.
So open twice will not actually open two vscode windows.

But for other editor which is not in "remote mode" or the so called "reuse mode", will open two windows:(
It's not a big deal, but quite annoying. 

By the way : 
I am using the version of 1.5.0 , running on windows 10 , and I use nvim as the tex external editor, and the Inverse search
command I configured is ：
```
nvim %1 +%2 
```

**Comment by ahrm** [comment]
Every time you right click on a document in synctex mode, we perform a synctex search to that location in the latex file. So every time you right click, we execute the inverse search command, and if you don't use some sort of reuse option that means we open multiple files. I don't know what else you expected.
I don't use nvim without vimtex plugin, but I am sure there there is a way to instruct it to reuse the previous file.

**Comment by BarryArch** [comment]
I think you misunderstand me. I mean just one click sioyek will open two new nvim windows. One click open just one nvim window is what I expected

**Comment by ahrm** [comment]
Should be fixed in 44cd5d07a60b1a0ea736332b94ab7a4564aa841f.

**Comment by BarryArch** [comment]
Great!
Is there a schedule to publish next version or a preview build version maybe?

**Comment by ahrm** [comment]
Experimental releases are available here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.407

**Comment by BarryArch** [comment]
Great!
