### ISSUE TITLE
Sioyek crashes if "ó" is in path of file

### ISSUE THREAD

**Issue by BonfireAtNight** [ahrm/sioyek#483]
Currently I'm working with George Pólya's *How to Solve It*. Initially, I had the file in `~/Literature/PólyaG/polya2004.pdf`. Running `sioyek ~/Literature/PólyaG/polya2004.pdf`, Sioyek crashed. Doing the same for `~/Literature/PolyaG/polya2004.pdf` ("o" instead of "ó") and it runs fine.

It's probably an instance of a more general issue of which you are aware, but I thought I let you know.

**Comment by ahrm** [comment]
Does it still happen with latest experimental builds here? : https://github.com/hexomancer/sioyek/releases/tag/v0.31.407

**Comment by BonfireAtNight** [comment]
Thanks for your quick answer! I just tried with the experimental build and the file opened just fine. So, apparently the issue was solved already. Great!
