### ISSUE TITLE
[Bug] In document, with hyperlink preview, clicking hyperlink & back makes the reader choppy and hyperlink jumps break

### ISSUE THREAD

**Issue by Harimus** [ahrm/sioyek#487]
First I'd like to thank you for this AWESOME PDF reader.  Best one out there hands down.

I have noticed a weird behavior.  I use sioyek with hyperlink preview to check references while I read papers. Like the screenshot below
![Screenshot from 2022-11-09 14-40-11](https://user-images.githubusercontent.com/25958309/200748552-ec58eac1-92a5-4f5e-9cb8-3be64187bc45.png)

Hovering over a hyperlink:
![Screenshot from 2022-11-09 14-40-26](https://user-images.githubusercontent.com/25958309/200748652-7f264a76-e8b3-4c08-bbd0-a81dce59c6a3.png)

Now, after I click the hyperlink, and jump to its location and then click backspace to go back to the original location, the text/view becomes choppy (see below, it's slightly hard to notice, but if you check the figure legends text, it has white choppy areas) and also hyperlink preview stops working and I cant click on any links. After scrolling for a bit, I realized that the hyperlink preview works sometime but at weird locations, and I still cant click on any of the links.

![Screenshot from 2022-11-09 14-40-48](https://user-images.githubusercontent.com/25958309/200753893-f6b46b97-43ed-4275-939a-9a5a3bce9fd1.png)

I use Sioyek on Ubuntu 20.04 default with a nividia-driver 515.65.01 if that helps.  If you need more info on my setup/env I'll append it!

**Comment by ahrm** [comment]
Does it still happen with the latest experimental build here? :
https://github.com/hexomancer/sioyek/releases/tag/v0.31.409

**Comment by ahrm** [comment]
No it should be fine, there just might be a few bugs but nothing dangerous.

**Comment by Harimus** [comment]
Ok thank you! Problem solved :100:  thanks for the quick reply :)
