### ISSUE TITLE
Sioyek allows multiple duplicate highlights

### ISSUE THREAD

**Issue by A3EKV** [ahrm/sioyek#49]
Hi,
After playing with Sioyek, it appears that it allows multiple duplicate hughlights, for example you can press:
```
hkhkhkhk
```
This will create the same highlight 4 times. 

These duplicates appear also when you export them.
So I wonder why Sioyek allows this? is it a feature or a bug?

Thank you

**Comment by ahrm** [comment]
Fixed in ec0e3118b964fdcb72cf1c4ef1e5288b6fed5357.

**Comment by A3EKV** [comment]
> Fixed in [ec0e311](https://github.com/ahrm/sioyek/commit/ec0e3118b964fdcb72cf1c4ef1e5288b6fed5357).

That commit solved the case when there is nothing is selected. But still you can create the same selection and highlight multiple times
For example:
I can **select with the mouse** the following text

The equation is solved using the algorthim foo

Then I press `hkhkhkhkhk`  it will create only one highlight and I can confirm that by pressing `gh` to show the list of highlights.

However if I **click somewhere** else and **re-select again the previous text** and press `hk`
it will create a duplicate of the previous highlight.

So in theory, the program should keep only a single copy of the highlight: Maybe this can be solved by hashing both the highlight key and the text itself and create a data structure that doesn't allow duplicates, such as a dictionary.
Thank you

**Comment by ahrm** [comment]
> > Fixed in [ec0e311](https://github.com/ahrm/sioyek/commit/ec0e3118b964fdcb72cf1c4ef1e5288b6fed5357).
> 
> That commit solved the case when there is nothing is selected. But still you can create the same selection and highlight multiple times
> For example:
> I can **select with the mouse** the following text
> 
> The equation is solved using the algorthim foo
> 
> Then I press `hkhkhkhkhk` it will create only one highlight and I can confirm that by pressing `gh` to show the list of highlights.
> 
> However if I **click somewhere** else and **re-select again the previous text** and press `hk`
> it will create a duplicate of the previous highlight.
> 
> So in theory, the program should keep only a single copy of the highlight: Maybe this can be solved by hashing both the highlight key and the text itself and create a data structure that doesn't allow duplicates, such as a dictionary.
> Thank you

Yes but I don't consider that a bug because it doesn't happen by accident. The only way that it can happen is when the user actively tries to do it.
