### ISSUE TITLE
on macOS, Sioyek does not work in command line

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#492]
When I do `sioyek`, I get "command not found". I installed Sioyek using the official instruction (HomeBrew). 
This bug also prohibits me from using plugins/extensions.

**Comment by ahrm** [comment]
The homebrew version is not an official version of sioyek, the official binaries are in the release section of this repository. You would have to contact the maintainer of the homebrew package.

**Comment by ibehnam** [comment]
I just uninstalled the brew version and used the official release `dmg` but both version are the same (1.5.0) and the program still does not work in command line (`sioyek: command not found`).

**Comment by danilshvalov** [comment]
Use `alias sioyek="open -a sioyek"`
