### ISSUE TITLE
when having to instances of sioyek open, only the first one uses the user prefs_user.config file

### ISSUE THREAD

**Issue by emilBeBri** [ahrm/sioyek#493]
Hi thank you for an amazing piece of software, finally something good enough to replace zathura but with modern featureset.

To recreate the bug, it's easy: open to pdfs. use, for example, the 

`dark_mode_contrast`

setting, which has easy visual identification of the change. go to dark mode in both pdfs.

now change dark_mode_contrast to something else. Only the first pdf changes, the second does not (it seems like the second one does not read the user prefs file at all, so it's not only changes to the file, but the file itself, that does not change.

```

version: sioyek 1.5.0


on manjaro w. i3, fully updated,
```

**Comment by ahrm** [comment]
Does it still happen with the builds of latest commits here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.409 ?

**Comment by emilBeBri** [comment]
Ok it seems like, when changing the prefs, it only updates the settings when the window is active - meaning you have to change the value, then select all instances of sioyek where you want  the change applied to. 

This is the cause of my confusion, because I would save the config, go to one of the windows and read there, and then wonder why it did not update the other, too. But  it's just a matter of selecting both of them. I can live with that.
