### ISSUE TITLE
(macOS) Mouse scroll acceleration not working

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#496]
mouse scrolling is completely linear in sioyek, which makes it difficult to use. On one hand, we need to set `vertical_move_amount 4` to have a decent scrolling experience using keyboard. But then with even small values of `touchpad_sensitivity`, mouse/touchpad scrolling scrolls way too fast.

It'd be great to separate those two settings (i.e., `vertical_move_amount`): one for keyboard and one for mouse. also it'd be nice to have **smooth beginning** and **smooth end** as well as acceleration for mouse scrolling, like all other apps.

**Comment by ahrm** [comment]
> even small values of touchpad_sensitivity

Note that you can set `touchpad_sensitivity` to smaller values than 1. For example:
```
touchpad_sensitivity 0.1
```
> smooth beginning and smooth end

We added a smooth scroll mode in https://github.com/ahrm/sioyek/commit/1ce9d365ac602e277dfcd34a82c08c789c84ac24. You can toggle it by executing `toggle_smooth_scroll_mode` and the speed and deacceleration are configured by the following configs:
```
smooth_scroll_speed 3
smooth_scroll_drag 3000
```
