### ISSUE TITLE
[ BUG ] `gg` adds a padding at the top

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#498]
`gg` should go to the top of the doc, but it also adds extra padding:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/58621210/203445295-cda9a802-3cb0-41d2-ad65-2b3d9a50fc4b.png">

Expected behavior:

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/58621210/203445336-ba06a9c3-ae8c-4cdb-be75-1d53ec3155d2.png">

Same thing with `G` (go to the end).

**Comment by ahrm** [comment]
See this issue:
https://github.com/ahrm/sioyek/issues/374#issuecomment-1221540897 .
