### ISSUE TITLE
Command mistyped?

### ISSUE THREAD

**Issue by A-bnk** [ahrm/sioyek#499]
Hi, really love your work so far. Just a quick question: when i try to execute the command *goto_beginning* using *gg* it does not work. So on further investigation i found that sioyek only knows the command  *goto_begining* (notice only one n). So my question is how can I correct it? Did I mess up when I tried to copy the new keys.config file for non-us-keyboards on my windows machine? 

![mistyped_command](https://user-images.githubusercontent.com/71699719/203620916-7f2fd420-c9f9-4458-81ac-23ff2e5d6d31.png)

**Comment by ahrm** [comment]
You need to also add `use_legacy_keybinds 0` to your `prefs_user.config`.

**Comment by A-bnk** [comment]
I already did, otherwise the goto_end G would not work either.
