### ISSUE TITLE
PDFs don't render

### ISSUE THREAD

**Issue by rien333** [ahrm/sioyek#50]
Probably hard to debug, but not a single one of my pdfs seems to render. I can interact with the menus in sioyek just fine, and even navigate to different pages, but whatever I do, there's no actual rendered output. To give a visual impression: 

![2021-09-19-1632084777](https://user-images.githubusercontent.com/10417027/133942729-b4147b2b-2c87-4a49-b195-d5ac34341147.jpg)

It seems like no interesting errors/warnings are shown on the terminal. Still, here is an  example of the information that is displayed when opening a pdf:

``` console
$ sioyek Arbib2008.pdf
default_config_path: /home/rw/.config/sioyek/prefs.config
default_keys_path: /home/rw/.config/sioyek/keys.config
user_config_path: [ 0 ] /home/rw/.config/sioyek/prefs_user.config
user_config_path: [ 1 ] /etc/xdg/sioyek/prefs_user.config
user_keys_path: [ 0 ] /home/rw/.config/sioyek/keys_user.config
user_keys_path: [ 1 ] /etc/xdg/sioyek/keys_user.config
database_file_path: /home/rw/.local/share/sioyek/test.db
local_database_file_path: /home/rw/.local/share/sioyek/local.db
global_database_file_path: /home/rw/.local/share/sioyek/shared.db
tutorial_path: /home/rw/.local/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/rw/.local/share/sioyek/last_document_path.txt
shader_path: /home/rw/.local/share/sioyek/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
adding child command to a final command
adding child command to a final command
adding child command to a final command
adding child command to a final command
adding child command to a final command
adding child command to a final command
adding child command to a final command
adding child command to a final command
config file change listener constructor called1starting index thread ...
getting links .... for 0
figure indexing finished ...
texture: 5

```

### Version information ###

I'm using a sioyek build from the newest git commit (by way of the [AUR package](https://aur.archlinux.org/packages/sioyek-git/#news)), which would be bf48fc4e2047e9f7c5da09d338837a613b50c4ae.

I'm using Arch linux (so everything should be at its newest possible version), with kernel version 5.14.5.

**Comment by rien333** [comment]
If it helps, changing the value of `background_color` does nothing, but, for whatever reason,  `dark_mode_background_color` does seem to work. 

Could this be related to something with shaders? I had to create the `~/.local/share/sioyek/shaders` directory myself, because sioyek didn't auto-create `~/.local/share/sioyek/` or any subfolders for me.

**Comment by rien333** [comment]
Apparently related to https://github.com/ahrm/sioyek/issues/26. 

Installing sioyek on Arch Linux, the shaders directory resides in `/usr/share/sioyek/shaders/`. For whatever reason, sioyek needs those files to actually reside in the user's home directory  (`~/.local/share/sioyek/shaders` to be exact). 

This seems really weird to me — as an user, I'm totally uninterested in editing those files, so sioyek should just be picking them up from `/usr/share`.

**Comment by ahrm** [comment]
Which sioyek executable are you running? You should be running the one in the build folder.

**Comment by rien333** [comment]
> Which sioyek executable are you running

Sorry, I meant that I installed sioyek from the AUR. It works fine now I guess, its just that the package manager in Arch doesn't touch home directories, and I wasn't aware that the shaders directory had to go there. (I would expect sioyek to look in a systemwide directory like `/usr/share`

**Comment by ahrm** [comment]
> > Which sioyek executable are you running
> 
> Sorry, I meant that I installed sioyek from the AUR. It works fine now I guess, its just that the package manager in Arch doesn't touch home directories, and I wasn't aware that the shaders directory had to go there. (I would expect sioyek to look in a systemwide directory like `/usr/share`)

Well, by default the shader files are in `/usr/bin/sioyek`, however you can configure sioyek to look inside user folders instead. See https://github.com/ahrm/sioyek/issues/28#issuecomment-911642232 for more information.
I didn't create the AUR package but whoever created it probably enabled the flag.
The reason I put them in `/usr/bin` instead of `/usr/share` is because they are semantically part of the program executable (I could have hard-coded them in the source code of the program itself.
