### ISSUE TITLE
[FEATURE] Manually Fill Out TOC

### ISSUE THREAD

**Issue by naveace** [ahrm/sioyek#500]
First of all, amazing idea. I have been looking for something like this for so long and am glad to see I am not the only one! I have noticed there are some PDFs for which Soiyek cannot find a way to make a TOC, and some for which it gets the TOC slightly wrong. From what I have observed it seems to mostly be using the top right of the page to figure out what section a given page is in. Where in the codebase does the TOC parsing occur? And would be be easy or feasible to make it so the user can manually fix/add to the TOC for documents where the auto parsing fails?

**Comment by ahrm** [comment]
You could use bookmarks for that.

**Comment by naveace** [comment]
Thanks so much for the suggestion; I had the same thought. The only downside is with bookmarks I don't believe there is a way to pull up a list of them like with the TOC. Is that correct? I might have just missed the feature in the docs.

**Comment by ahrm** [comment]
You can open a list of bookmarks by executing `goto_bookmark` (the default keybinding is `gb`).

**Comment by naveace** [comment]
Ahh awesome, that really helps. Thanks so much!
