### ISSUE TITLE
Macos cannot verify the developer

### ISSUE THREAD

**Issue by ChiragAgg5k** [ahrm/sioyek#501]
I tried installing the app both through brew cask and by .dmg file. The results stay the same

<img width="261" alt="Screenshot 2022-11-26 at 10 38 39 PM" src="https://user-images.githubusercontent.com/110609663/204100840-b8bee118-9b44-41e2-ad29-7253b62e0429.png">

**Comment by ahrm** [comment]
You need to give it permission in Privacy and security options.

**Comment by ahrm** [comment]
You need to give it permission in Privacy and security options.

**Comment by ChiragAgg5k** [comment]
which one
<img width="496" alt="Screenshot 2022-11-27 at 12 50 36 AM" src="https://user-images.githubusercontent.com/110609663/204105661-a1a7a6c4-f00b-4fe3-8368-629792d727a1.png">

**Comment by ChiragAgg5k** [comment]
also i never had this issue with any other open source app. can't you make yourself a identified developer?

**Comment by ahrm** [comment]
See this for example:
https://www.alphr.com/cannot-be-opened-because-the-developer-cannot-be-verified/

> also i never had this issue with any other open source app. can't you make yourself a identified developer?

No I can't because I live in Iran (sanctions).

**Comment by ChiragAgg5k** [comment]
Oh.. Okay. Thanks for the help
