### ISSUE TITLE
[ Suggestion ] Keybinding to cycle through currently open documents (tabs)

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#502]
It'd be great to have something like `CTRL-TAB` functionality of Chrome/Preview/etc. in Sioyek. I know we can do `<S-o>` to see the list of recent docs, but that's not exactly the same as `CTRL-TAB`ing through currently open docus.

**Comment by sandersantema** [comment]
I would suggest `gt` for going to the next tab and `gT` for going to the previous tab. This is consistent with vim keybindings.

**Comment by ahrm** [comment]
We do have a `goto_window` command which allows you to switch to other windows.

**Comment by ibehnam** [comment]
> I would suggest `gt` for going to the next tab and `gT` for going to the previous tab. This is consistent with vim keybindings.

Thanks for your quick reply.  Unfortunately, `goto_window` does not work on the macOS version. I've assigned `ctrl-z` to it and the selection popup opens, but upon pressing `enter` on any tab, nothing happens.

**Comment by ahrm** [comment]
What if you double click on a tab?

**Comment by ibehnam** [comment]
Still nothing happens.

**Comment by ahrm** [comment]
It does work on windows and linux, so it is definitely a mac-specific issue. Unfortunately it is very difficult for me to debug because I currently don't have access to a mac machine.

**Comment by ibehnam** [comment]
No problem, hopefully it'll be resolved in the future.

**Comment by ahrm** [comment]
I just tried `goto_window` on a friend's macbook and it seems to work. Maybe it is an issue with the specific version of sioyek that you are using?

**Comment by ibehnam** [comment]
How should I check sioyek's version? I installed the release version, I think it was v1.5.0.
I should say that with pressing enter to switch to a file in the goto_window page: sometimes it works and sometimes it doesn't.

**Comment by faurehu** [comment]
+1, I can't figure out how to check which version I'm running.

**Comment by faurehu** [comment]
`brew list --versions sioyek` does not return anything. However, my `Info.plist` file inside the sioyek app installed by brew has a string called `CFBundleShortVersionString` with value 1.5, which matches the latest version published by this repo.

**Comment by ahrm** [comment]
Does it work with the builds of latest commits here? :
https://github.com/hexomancer/sioyek/releases/tag/v0.31.415

**Comment by faurehu** [comment]
It does not work.

**Comment by ahrm** [comment]
I tested it again and both `goto_window` and `new_window` are working. One thing that may be confusing you is that in MacOS for some inexplicable reason, when you open the command menu the textbox is not properly focused. So in order to execute a command you have to double click on it. This is fixed when you switch to another window and then switch back to sioyek.

**Comment by faurehu** [comment]
`new_window` is working but not `goto_window`. Also, strangely enough, I cannot trigger `new_window` with my custom key binding, which I know works because it used to before I udpated it.

**Comment by ahrm** [comment]
We have added tab support in the development branch. You can switch between tabs using `goto_tab` command.
