### ISSUE TITLE
sudo make install look for shaders in the wrong directory

### ISSUE THREAD

**Issue by 875d** [ahrm/sioyek#505]
`sudo make install` install shaders in `/usr/share/sioyek/shaders`:

```
❯ sudo make install
[...]
/usr/bin/qmake-qt5 -install qinstall [MYPATH]/sioyek/pdf_viewer/shaders /usr/share/sioyek/shaders
[...]
```

But `/usr/bin/sioyek` looks for shaders in the wrong directory:
```
❯ /usr/bin/sioyek
[...]
shader_path: /usr/bin/shaders
Error: shader_path: /usr/bin/shaders doesn't exist!
[...]
```

**Comment by ahrm** [comment]
I think you are building the portable version which looks for the files next to the executable.

**Comment by 875d** [comment]
I don't know what the "portable version" is.

I'm following the instructions [here](https://github.com/ahrm/sioyek#generic-distribution).

There are no instructions to install the software after building it.

It `sudo make install` is the correct command to install it, it should work. Currently it doesn't as it looks for shaders in the wrong folder.

Otherwise, please provide the correct instructions to install it after build.

**Comment by ahrm** [comment]
> Otherwise, please provide the correct instructions to install it after build.

After building the project into the build folder you can create a symlink from bin directory to the generated binary.

**Comment by Rodrigodd** [comment]
Also stumble on this. `make install` has any purpose, or it is just broken?
