### ISSUE TITLE
An option to jump to the True end of a document

### ISSUE THREAD

**Issue by A3EKV** [ahrm/sioyek#51]
Currently, When you press End key it will show the top part of the last page (correct me if that's wrong) so If I want to to reach the true end page I still have to press the "down" arrow key multiple times to achieve that.

I wonder if there is an option in Sioyek to allow this behaviour (in parallel with the current bahviour, or maybe allowing to override it).

Thanks

**Comment by PurpleAzurite** [comment]
Personally I think overriding G to go to the true end of the document is more intuitive and conventional.

**Comment by ahrm** [comment]
Fixed in 6de44e33c15c3d43f12fe3c03a90a48abdc82468 .
