### ISSUE TITLE
Support for full URIs

### ISSUE THREAD

**Issue by 875d** [ahrm/sioyek#510]
sioyek needs to support full URIs like:
```
sioyek file:///home/USERNAME/Documents/article.pdf
```
in order to be compatible with nnn.

Currently passing a full URI results in a black window.

**Comment by 875d** [comment]
See https://github.com/jarun/nnn/issues/1535

**Comment by ahrm** [comment]
Should be fixed in 415d00aac129aecdcaade963f5458f5168a4044d.

**Comment by 875d** [comment]
It works! Thank you so much! :)
