### ISSUE TITLE
[ BUG REPORT ] `toggle_highlight` doesn't get activated upon startup

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#511]
The docs say that this option is disabled by default, so I added `toggle_highlight` to my startup commands but it won't activate. Other commands do get activated at startup.

Another issue with this feature is that once you press `f` to go to a highlight, the highlights get deactivated again. So far I've had to assign a key (`) to this command but I thought maybe you want to look into it.

**Comment by ahrm** [comment]
You opened this exact issue here XD : https://github.com/ahrm/sioyek/issues/497 . It should be fixed in the latest commits.
