### ISSUE TITLE
why screen_down only half screen scroll down, how can scroll one screen?!

### ISSUE THREAD

**Issue by jin6220** [ahrm/sioyek#515]
when use PageDown or Space , only half screen scroll down. it's not convenient to read ebook.
because u need press 2 times.
how to one screen scroll down or up?

**Comment by ahrm** [comment]
You can configure it in `prefs_user.config` like so:
```
move_screen_ratio 1
```

**Comment by jin6220** [comment]
> 

thank you very much! 
it  take effect !
