### ISSUE TITLE
[Bug] Inconsistent case senitivity for ctrl shortcuts

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#519]
Some shortcuts only work for lower-case letters:

- `<C-l>` works
- `<C-L>`does not  work

While some shortcuts only work with upper-case letters: 

- `<C-h>` does not work
- `<C-H>` works

I'm assuming the intended behavior is for only lower-case letters to work. It seems like `H`, ` J`, and `M` need to be upper-case to work in combination with `ctrl`. `alt` does not seem to be affected.

**Comment by ahrm** [comment]
The issue was that <C-h> was producing '\b' (backspace) character and we were basically treating it as <C-<backspace>>. It should be fixed in 59fcbce2e4878b3cbbd731778221afcf2d445110.

**Comment by HakonHarnes** [comment]
It works.
