### ISSUE TITLE
sioyek‘s dark mode is not real dark mode, hope to improve it!

### ISSUE THREAD

**Issue by jin6220** [ahrm/sioyek#521]
**first，i set  BackgroundColor and TabextColor  of sumatraPDF and sioyek, thay have same value!
then, open the dark mode!**

sumtraPDF:
https://www.sumatrapdfreader.org/free-pdf-reader
https://github.com/sumatrapdfreader/sumatrapdf/discussions

 **this is SumatraPDF 's dark mode :**
![001-20221207_115605](https://user-images.githubusercontent.com/22074843/206127611-65ea9cd8-3501-42b3-bf55-e354e30d5fce.png)

 **this is sioyek 's  :**
![002-20221207_115456](https://user-images.githubusercontent.com/22074843/206127637-8f4fd49b-5809-470a-a7e8-be290a7bb151.png)

**this is original pdf :**
![003-20221207_115642](https://user-images.githubusercontent.com/22074843/206127945-8cc33425-cca0-443a-b168-30aff74e9b88.png)

so hope to  repair it ,thanks!

**Comment by ahrm** [comment]
I like sioyek's version more. We try to keep the color hues while reducing lightness.
