### ISSUE TITLE
[Bug] Sioyek crashes when opening certain .pdf files

### ISSUE THREAD

**Issue by mhagar** [ahrm/sioyek#522]
When opening some .pdfs that were downloaded through Zotero, sioyek immediately closes. This does not occur if the .pdf is downloaded through the journal website, only the zotero copy.

I have not had a chance to try replicating this on a different machine. I am running sioyek on Ubuntu 20.04 LTS

This is a .pdf from the publisher:
[pnas.0901237106.pdf](https://github.com/ahrm/sioyek/files/10181050/pnas.0901237106.pdf)

This is the copy from Zotero (not openable with Sioyek, but opens in other .pdf viewers such as Okular)
[Eustáquio et al. - 2009 - Biosynthesis of the salinosporamide A polyketide s.pdf](https://github.com/ahrm/sioyek/files/10181046/Eustaquio.et.al.-.2009.-.Biosynthesis.of.the.salinosporamide.A.polyketide.s.pdf)

Let me know if there's a way to generate a log dump or something

**Comment by ahrm** [comment]
Can't reproduce the issue, I think the issue might be special characters in the file name which should be already solved. Can you reproduce the issue on the latest experimental builds here:?
https://github.com/hexomancer/sioyek/releases/tag/v0.31.413

**Comment by TangdizhiH** [comment]
> 

Yes, I can confirm the problem is solved on some new commits. But the thing is that the current release has not yet included this fix. Compile the sioyek from github source can solve this problem.

**Comment by mhagar** [comment]
Can confirm the problem is resolved in the main build if I rename files to remove funny characters (periods, greek symbols). Can also confirm the problem doesn't exist in the experimental build linked by @ahrm .

Thanks!
