### ISSUE TITLE
Sioyek halts when try to exit from entering bookmark description

### ISSUE THREAD

**Issue by TangdizhiH** [ahrm/sioyek#526]
Description: the app stucks when you try to use esc to escape from bookmark.

How to reproduce: 1) open a PDF file 2) enter b for bookmark 3) press esc (in my case I map it to CapsLock).

Current behavior: the sioyek stucks and have no response to the subsequent inputs.

Expected behavior: sioyek exit the bookmark mode so user can regret the bookmark operation.

Platform: 
- Distribution: Archlinux
- Desktop Environment: KDE on wayland

BTW, thank you for this great pdf reader. I always dreamt of  a pdf reader that can support vim keybinding and highlights. Sioyek even support on the academic purpose reading.Keep up with this great work!

**Comment by ahrm** [comment]
Can't reproduce the issue.

**Comment by TangdizhiH** [comment]
> Can't reproduce the issue.

Hi ahrm, thank you for the reply. I can't reproduce the problem today either. I'll close the issue temporarily until I can consistently reproduce it. Thanks
