### ISSUE TITLE
[Feature Request] <num>j and <num>k bindings

### ISSUE THREAD

**Issue by gitdramaqueen** [ahrm/sioyek#528]
Hi, if this feature is already available, I couldn't find how to set it up in the `keys_user.config` . If anyone from the user community knows how to get it, I'd appreciate the help.

I'm looking for a behavior similar to vim. Especially when using the **visual mark** in a double-column page, I expect people would enjoy the ability to move say 50 lines quickly, since the mark starts on the left column by default. It would conveniently move the mark into the next column.

Thanks in advance.

**Comment by ahrm** [comment]
Added in 6f0bcec883e7c06af846418b98a344dd4dec37e2.

**Comment by gitdramaqueen** [comment]
Thanks a lot @ahrm I'll test it as soon as I get a chance.

**Comment by gitdramaqueen** [comment]
@randomn4me, are you still maintaining the aur package sioyek-git? Last update is from September.

Sorry if this isn't the best place to ping you, but I'm not registered at the AUR.

**Comment by randomn4me** [comment]
Hi @gitdramaqueen, no, I'm not maintaining the package anymore [1].

Cheers

[1]: https://aur.archlinux.org/packages/sioyek-git
