### ISSUE TITLE
Checkerboard

### ISSUE THREAD

**Issue by 875d** [ahrm/sioyek#532]
When I open a PDF file, a checkerboard is shortly visualized before the actual PDF file is visualized.

Is it possible to get rid of that?

**Comment by ahrm** [comment]
Yes, it is disabled by default using this config in default prefs file:
https://github.com/ahrm/sioyek/blob/e055a821e36a114deeb572c2bb665ee4af98599a/pdf_viewer/prefs.config#LL82C9-L82C9

**Comment by 875d** [comment]
oh yeah, I don't see it anymore since I loaded the default pref. Thanks!
