### ISSUE TITLE
Smart Jumps Multiple Occurances

### ISSUE THREAD

**Issue by shammahrashad** [ahrm/sioyek#533]
I noticed that the Smart Jump feature takes you to the most closest occurance of the number. When this happens sometimes it shows Examples rather than Equations. It would be cool if there was an option to traverse through the occurances in the small popup just like the search feature or maybe instead show the **First** occurance of the number in the document and/or add logic to distinguish Equations, Examples, Figures etc with same number/references.

**Comment by ahrm** [comment]
You can do this using `next_preview` and `previous_preview` commands.
