### ISSUE TITLE
Visual mode markers are wrong

### ISSUE THREAD

**Issue by 875d** [ahrm/sioyek#534]
![image](https://user-images.githubusercontent.com/118444583/208236517-79f68e30-92b8-4774-8da4-498b67256d06.png)

The `tluh` is in reality `uh`, while the `xjj` is in reality `xj`

**Comment by ahrm** [comment]
When there are two close characters, sometimes their labels overlap. So `tluh` is actually `tl` and `uh`. Same with the other, `xjj` is actually `wj` and `xj` where 'w' is underneath the `x`.

**Comment by 875d** [comment]
I request an option to set minimum distance between visual markers

**Comment by ahrm** [comment]
Should be improved in the latest commits.

**Comment by 875d** [comment]
Yes it is much better, although on the commas there are 2 markers:

![image](https://user-images.githubusercontent.com/118444583/209444931-c538d823-65fd-431e-b9f9-9fae5fb1dca4.png)

Is it one for the comma and one for the following word?

**Comment by ahrm** [comment]
Yes.

**Comment by 875d** [comment]
ok perfect. Thank you very much :)
