### ISSUE TITLE
[FR] toggle_select_highlight

### ISSUE THREAD

**Issue by 875d** [ahrm/sioyek#536]
Feature requests for `toggle_select_highlight`:

1. After highlighting, the text should be unselected (the selection should be gone)
2. The actual selected text should be highlighted, without going to the end of the word automatically
3. The status bar should signal when `toggle_select_highlight` is on

**Comment by ahrm** [comment]
> The actual selected text should be highlighted, without going to the end of the word automatically

We have a `exact_highlight_select` config option which enables this.

> 1 and 3

Added in d96ad565820e4018e8b454325d81a2331d679d3e. Now when highlight select is on, in the statusbar we have:
```
[ hs: a]
```
instead of
```
[ h: a]
```

**Comment by 875d** [comment]
It looks perfect now. Thanks!
