### ISSUE TITLE
Support negative values for `set_page_offset`

### ISSUE THREAD

**Issue by amanjitsk** [ahrm/sioyek#537]
Suppose I have a document with pages numbered from 87 to 154 (inclusive), meaning the document has 68 pages.
I'd like to set a negative offset using `set_page_offset` so that if I set it to `-86`, so that when I press `87G` it should go 
to the first page in the document, and so on. This setting works well with positive values, but I think it is also equally valuable to have this work with negative offsets. Currently, it doesn't work as expected with negative numbers.

**Comment by ahrm** [comment]
Added in 18a291e379b50cd60616a3b923e80b6418aa4fde.

**Comment by amanjitsk** [comment]
Awesome, thank you!
