### ISSUE TITLE
Unmapping a default keybinding

### ISSUE THREAD

**Issue by infokiller** [ahrm/sioyek#542]
Hi,

I want to define keybindings that start with the prefix `t` (for example, `toggle_fullscreen tf`). However, this doesn't work because of the following default mapping:

https://github.com/ahrm/sioyek/blob/7cb948face57b56ee55224b62d841c316e85294c/pdf_viewer/keys.config#L88-L89

Is there a way to unbind a default keybinding, other than editing in `/etc/sioyek/keys.config`?

Thanks

**Comment by ahrm** [comment]
No, you'll have to edit the `keys.config` file.

**Comment by infokiller** [comment]
Would it be possible to add this option?
Editing files in `/etc/sioyek` requires root, so I think it's better for a user to be able to override everything they want

**Comment by ahrm** [comment]
Yes, I will probably add it at some point.

**Comment by ahrm** [comment]
Added in 610ebdf7474d6db62ca49cdc26a580032f53566e. Now we automatically unmap prefixes when you defined longer keybinds.

**Comment by infokiller** [comment]
Thanks for the quick fix!
This addresses the original issue which is great, but I foresee another possible issue: if I want to disable a specific keybinding (for example, because I'm accidentally pressing a certain bound key all the time), I still can't do that, though there's an easy workaround (map a key sequence that starts with this key to something else).

**Comment by ahrm** [comment]
Added a `noop` command in 1ad173099b63698e0286eff106f5a183c0b86805 which does nothing. You can unbind by remapping to keybind to this command.

**Comment by infokiller** [comment]
Perfect, thanks a lot!
Should I close this issue now, or wait for a release?

**Comment by ahrm** [comment]
We can close this for now.
