### ISSUE TITLE
[Feature request] Show status bar when showing search results

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#544]
I prefer hiding the status bar, except for when I go through search results. Manually toggling it when searching is a bit cumbersome. A solution to this would be to add an option, e.g. `display_status_bar_during_search`, that would do the following: 

- Display the status bar when search results are presented (after pressing enter)
- Hide the status bar after pressing esc to exit the search

**Comment by ahrm** [comment]
Added it as the default behaviour in 7c5bc14bfae92020881499d613f85703a4b749cf.
