### ISSUE TITLE
[Bug] Selection highlight color in menu is white 

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#547]
The selection highlight color in the status bar is white. If you set `status_bar_color` to white it is impossible to see which entry is selected when browsing the toc or command palette. Suggestion: Add a `status_bar_highlight_color` option.

**Comment by ahrm** [comment]
We already have these options which do that:
```
ui_selected_background_color 1 0 0
ui_selected_text_color 0 1 1
```

**Comment by HakonHarnes** [comment]
> We already have these options which do that:
> 
> ```
> ui_selected_background_color 1 0 0
> ui_selected_text_color 0 1 1
> ```

My bad! Thanks.
