### ISSUE TITLE
[Bug] Jittery mouse drag mode 

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#548]
**Steps to reproduce:**

1. Zoom out a few times. 
2. Enter mouse drag mode, and go all the way to the left or right. 
3. Zoom in a few times. 
4. Move the document using mouse drag mode. 

The document will "jump around" to fit into the viewport. This might be the intended behavior, but it's a bit annoying when using mouse drag mode since it is quite jittery and unpleasant.

**Comment by ahrm** [comment]
Should be fixed in 8c25689d247d5e501467b133a2361b0d3a16f7b9.
