### ISSUE TITLE
[Feature Request] Remove delay when holding j/k/up/down

### ISSUE THREAD

**Issue by ryanwwest** [ahrm/sioyek#549]
On Windows, a keyboard key starts repeating after a certain configurable delay. However, even at the shortest delay possible, it annoys me a little that whenever I want to scroll using the default arrow keys or j/k, I have to wait for that bit of delay before the scrolling begins. Other tools like https://github.com/gdh1995/vimium-c ignore this delay by default - is there any way we could have a preference to ignore the delay on these keys or on keys in general?

**Comment by ahrm** [comment]
I don't think this is possible because Qt seems to have hard-coded delay times here: https://code.qt.io/cgit/qt/qtbase.git/tree/src/platformsupport/input/libinput/qlibinputkeyboard.cpp?h=dev. I may be wrong though.

Of course, you could always configure it at on OS-level.
