### ISSUE TITLE
[Feature Request] Inertia when panning on touch screen

### ISSUE THREAD

**Issue by ryanwwest** [ahrm/sioyek#550]
With command `toggle_mouse_drag_mode` you can use your finger on touch screens (or a mouse) to drag the document around instead of using keys. However, most modern applications (and smartphones apps) will continue to scroll and slow down after your finger finishes swiping up or down, which is helpful if you want to quickly jump down several pages with a big swipe. 

However, sioyek currently doesn't implement this inertia (perhaps there is a better term) so when you finish swiping, the document immediately stops moving. It would be nice to have it behave more like other applications in this mode.

**Comment by ryanwwest** [comment]
I found https://github.com/ahrm/sioyek/issues/16 which mentions that there will be limited touch support for this app. So I understand if the proposed FR is a lower priority, though I could see future versions of this supporting touch and keyboard alike (I use a Surface Pro 9 and frequently switch between all keyboard vim and all touch portrait tablet-mode).

Another helpful touch optimization might be a default for panning with touch AND selecting with mouse left-click-and-drag, similar to Chrome (which doesn't treat touch drag events as left mouse-click-and-drag). I know there's a keybinding and that's a good fallback, but this would be more seamless. I can make another Issue for this, but since it's related and touch FRs may not be a priority I won't for the moment.

**Comment by ahrm** [comment]
In the development branch we have added extesive touch support, including inertia, touch menus and freehand drawings.
