### ISSUE TITLE
[Bug] Unknown option '--reuse-instance'

### ISSUE THREAD

**Issue by Jusb3** [ahrm/sioyek#555]
I noticed that my synctex integrartion with VS Code no longer worked after updating to latest release version. I then tried to run the same commandline string from cmd.exe, and got error messagebox with text "Unknown option '--reuse-instance'".

**Comment by ahrm** [comment]
`--reuse-instance` is removed, you should use `--reuse-window` instead.

**Comment by Jusb3** [comment]
Yeah, I just read trough the code and realized that. The documentation about configuring synctex still states the old syntax.

**Comment by ahrm** [comment]
Updated the tutorial in 58bba04dd418945be7db23d0a153b770873fdfb3.

**Comment by HakonHarnes** [comment]
The man page for sioyek still contains `--reuse-instance`.

**Comment by MuziIsabel** [comment]
Even now.
