### ISSUE TITLE
[Feature Request] add `open_synctex` cmd

### ISSUE THREAD

**Issue by mathjiajia** [ahrm/sioyek#556]
It is helpful to use`open_synctex` (not `toggle_synctex `) for forward search of latex.

**Comment by ahrm** [comment]
You mean like `synctex_under_cursor`?

**Comment by mathjiajia** [comment]
sorry I did not explain clearly.

I added '--execute-command toggle_synctex'  in forward search configuration.
Currently, for the second time of forward search, the `synctex` will turn off.

**Comment by ahrm** [comment]
Added a `turn_on_synctex` command in ea686354b219f437248d426ecb42300e63c7f161.

**Comment by mathjiajia** [comment]
perfect!

Thank you.
