### ISSUE TITLE
Sioyek no longer automatically opens last opened file.

### ISSUE THREAD

**Issue by PurpleAzurite** [ahrm/sioyek#56]
I believe this was the behavior of the application prior to recent updates, and it's very desirable.

**Comment by ahrm** [comment]
I think this is the result of changing the file locations in recent commits. Do you still have this issue after using the new version multiple times?

**Comment by PurpleAzurite** [comment]
The issue remains.

**Comment by PurpleAzurite** [comment]
This issue is also fixed by manually creating the sioyek folder in user .local
