### ISSUE TITLE
[Feature request] Go to last entry in menu 

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#561]
Jump to the last entry in a menu  (e.g. ToC, command list) by pressing up (or ctrl + k).

**Comment by ahrm** [comment]
You can use page up/ page down to quickly navigate lists.

**Comment by HakonHarnes** [comment]
> You can use page up/ page down to quickly navigate lists.

I think arrow up is a more intuitive approach than page up to go to the last entry. This is how Google, Youtube, etc. do it. Most laptops don't have dedicated page up/page down keys, either.

**Comment by ahrm** [comment]
Added ability to use alt+j/k to go to the last/first element in a list in 8e4d3c3f1fd85b53a89415d158d33bfc042e3d9a.

**Comment by HakonHarnes** [comment]
> Added ability to use alt+j/k to go to the last/first element in a list in 8e4d3c3f1fd85b53a89415d158d33bfc042e3d9a.

Awesome!
