### ISSUE TITLE
[Feature request] Highlight all search results

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#562]
Highlight all search results, preferably with a different color than the currently selected search result. Firefox implements this by highlighting all search results with a pink highlight, and the currently selected search result with a green highlight. See attached screenshot. 

![image](https://user-images.githubusercontent.com/89907156/209254355-f78ed82f-2b69-4749-a7e3-f61eec1783fc.png)

**Comment by ahrm** [comment]
Added a `should_highlight_unselected_search` config option in 54c48f8b3945d6fd9b6c91dec28fdee4d7d97866. Also you can configure the color using `unselected_search_highlight_color`.


https://user-images.githubusercontent.com/6392321/209358325-e8be8403-680d-4738-9798-97c1c63afa92.mp4

**Comment by HakonHarnes** [comment]
Thanks! It works great.

**Comment by ryanwwest** [comment]
This looks awesome!

**Comment by svonjoi** [comment]
works well; btw its missing in the latest release
