### ISSUE TITLE
[BUG] Keyboard selection initials can overlap

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#563]
Pressing `v`:

<img width="483" alt="image" src="https://user-images.githubusercontent.com/36224762/209363141-d0890f4d-e8e4-45c7-970a-7cea448e13bc.png">

As you can see, the three letter hints have overlapped and look like four letter hints. Adding borders to the hints can somewhat help. 

In the long term, better solutions might be possible. E.g., see [avy](https://github.com/abo-abo/avy#avy-goto-char). I am not sure if their approach of typing the first letters of the jump destination can work in a PDF though.

An easy improvement is to make the displayed hints not be three characters all the time. You can use two characters for most cases.

Another improvement is to use prefix-code hints, so that the hint can be recognized automatically without also having to press Enter.

**Comment by ahrm** [comment]
> An easy improvement is to make the displayed hints not be three characters all the time. You can use two characters for most cases.

We already do that.

**Comment by NightMachinery** [comment]
> > An easy improvement is to make the displayed hints not be three characters all the time. You can use two characters for most cases.
> 
> We already do that.

I can't see a border here though?

<img width="103" alt="image" src="https://user-images.githubusercontent.com/36224762/209364888-d9a95908-e29d-4196-8f54-380bbebd157e.png">

**Comment by NightMachinery** [comment]
> > An easy improvement is to make the displayed hints not be three characters all the time. You can use two characters for most cases.
> 
> We already do that.

Are the candidates filtered to the visible portion of the screen?

I don't have that many candidates visible but they are three-lettered.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/36224762/209365031-fb04fd90-be1b-4c0a-b651-1a341820896f.png">

**Comment by ahrm** [comment]
If there are more than 26 * 26 = 676 words then we'll use three letters. Are there less than 676 words in that page?

**Comment by NightMachinery** [comment]
> If there are more than 26 * 26 = 676 words then we'll use three letters. Are there less than 676 words on that page?

The idea is to discard the words that can be inferred to be invisible. I don't know how possible that is.

**Comment by ahrm** [comment]
Should be improved in ac53298bbd34ab5b41df99b54f48dff93a15a879 and a8e756a43929ed4663199833d2ae89834fd39bbf. Now we slightly offset the labels when they are close to each other and we show labels only for visible words.
