### ISSUE TITLE
`toggle_horizontal_scroll_lock` also locks keyboard scrolling

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#564]
`toggle_horizontal_scroll_lock` is very useful for trackpad scrolling, but scrolling using the keyboard should still be allowed.

A possible solution is to introduce commands `move_left_ignore_lock`, `move_right_ignore_lock`, and bind these to the keyboard keys.

**Comment by ahrm** [comment]
Should be fixed in 39d6355618c2bb14eaacac5effaca51d878b44a8.
