### ISSUE TITLE
[Feature request] Gamma correction

### ISSUE THREAD

**Issue by char101** [ahrm/sioyek#566]
Hi,

It would be useful if the gamma or the rendered page can be adjusted so that some fonts that are too thin can be made bolder.

For example here is a screenshot from the tutorial pdf. The bottom part has been gamma adjusted (using gimp -> colors -> levels).

![2022-12-25 15_55_34-tutorial pdf](https://user-images.githubusercontent.com/71255/209462730-e8534521-d3fa-46c4-bd93-3217fbb5041d.png)

**Comment by JoelOliva** [comment]
I was wondering why text looked blurry when I switched to sioyek from firefox's pdf viewer, I think this is the default for firefox. Hoping this doesn't get ignored, thicker bold text would be a nice addition.

**Comment by ahrm** [comment]
We have added a `gamma` config in development branch.

**Comment by char101** [comment]
Hi,

Thanks for adding the gamma option. I have just tested it and it doesn't seem to work in dark mode

gamma=1
![dark1](https://github.com/ahrm/sioyek/assets/71255/c5e3b46e-1557-46a7-93d8-dce124d59656)
gamma=2
![dark2](https://github.com/ahrm/sioyek/assets/71255/25cb31d3-fa4b-47ae-859c-93ab773895db)

**Comment by ahrm** [comment]
We already had a `dark_mode_conrast` option which did this in dark mode.

**Comment by char101** [comment]
I tested `dark_mode_contrast` with values of `0.5` and `1`. It looks to me that what the option do is changing the background contract. The font itself doesn't seem to look _bolder_.

contrast=0.5
![ct05](https://github.com/ahrm/sioyek/assets/71255/679b06c1-b603-4a09-8bad-62a1a513ea14)
contrast=1.0
![ct1](https://github.com/ahrm/sioyek/assets/71255/88b32ef7-d0b6-4041-b83e-7f8c460ab380)

**Comment by ahrm** [comment]
You can set it to values greater than 1.

**Comment by char101** [comment]
You are right, setting the contrast value to 2 do make the text looks bolder. Unfortunately the background also become pure black.

**Comment by char101** [comment]
I just found that mupdf itself can do gamma adjustment, so I tried to use it to set the gamma to 3 and found that the result is much better in dark mode.

using `fz_gamma_pixmap(mupdf_context, rendered_pixmap, 3.0);`

![2024-01-26 23_16_39-geometry pdf](https://github.com/ahrm/sioyek/assets/71255/c6341e05-9703-4de3-938e-e38e4dcdc246)

using dark_mode_contrast=2

![2024-01-26 23_19_38-geometry pdf](https://github.com/ahrm/sioyek/assets/71255/9f332570-e4b1-4987-b80d-7f400f2b6a3c)

normal dark mode

![2024-01-26 23_19_58-geometry pdf](https://github.com/ahrm/sioyek/assets/71255/da0386bc-be7d-4e9a-972d-1d956291fe48)


As you can see the mupdf gamma adjust text is much more readable, especially in dark mode. In light mode, I found that he text anti aliasing is also better although not as different as in dark mode.

This is what I modified in the code

```diff
diff --git a/pdf_viewer/pdf_renderer.cpp b/pdf_viewer/pdf_renderer.cpp
index 8259d85..e894bd7 100644
--- a/pdf_viewer/pdf_renderer.cpp
+++ b/pdf_viewer/pdf_renderer.cpp
@@ -599,6 +599,8 @@ void PdfRenderer::run(int thread_index) {
 
                 }
 
+                fz_gamma_pixmap(mupdf_context, rendered_pixmap, 3.0);
+
 
                 RenderResponse resp;
                 resp.thread = thread_index;
```

**Comment by ahrm** [comment]
Added your suggestion in https://github.com/ahrm/sioyek/commit/8eedf2f1b25abaea5d1774998ce428f43f4a1393.
