### ISSUE TITLE
[FR] Optionally use external fuzzy search in menus

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#567]
The current implementation of fuzzy searching is minimal. There are some great fuzzy searchers out there. I personally recommend [fzf](https://github.com/junegunn/fzf), though it would need to be run as an external process. But I think it's worth it.

The crucial piece currently missing is that whitespace should act as logical OR when doing fuzzy searching: `knowled lat` should match `latent_knowledge_in_the_brain`, for example. But `fzf` has a lot more goodies implemented with a great sorting algorithm, so using it wholesale is preferable.

Related:
- https://github.com/ahrm/sioyek/issues/155
- https://github.com/ahrm/sioyek/issues/164

**Comment by ahrm** [comment]
Using external programs for searching is not going to happen because it would be too slow and would cause all sorts of compatibility problems. Added a `fuzzy_searching` config option in a4f52be854fd1f65c68ef8ca435bbcacd36e1a1b which uses a fuzzier algorithm for searching.

**Comment by ahrm** [comment]
Updated fuzzy search algorithm to fzf, as I said we will not be using external program so I will close this issue.
