### ISSUE TITLE
background_color when using custom colours

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#569]
Is there an equivalent for `background_color` when you're in custom colour mode? I want to have different colours for the actual PDF and the UI when I'm in custom mode but it seems that `custom_background_color` is used for both the UI and the PDF. Is this possible?

**Comment by ahrm** [comment]
Added in 0c2251b1bea4b22b0e3b5ad01170f7c7c6cd1309. Now we have a `custom_color_mode_empty_background_color`.
