### ISSUE TITLE
page separator is off by a few pixels

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#570]
Nitpicking but I noticed that the page separator misses a one (or a few) pixels on the right side:

![image](https://user-images.githubusercontent.com/686449/209668054-0c30e04c-981f-437c-a6fe-fab6c8f18ada.png)

(changed colours for better visibility)

**Comment by ahrm** [comment]
We added a `real_page_separation` config option in the development branch, which enables actual page separation instead of the virtual box that we draw normally. Note that the original non-separated pages are way faster, so this option is disabled by default.
