### ISSUE TITLE
Allow adjusting contrast in custom color mode

### ISSUE THREAD

**Issue by xulongwu4** [ahrm/sioyek#573]
We have the field `dark_mode_contrast` to adjust constrast in the dark mode. Is it possible to have a corresponding setting for the custom color mode?

Fantastic work by the way. I love your pdf reader very much and really appreciate your diligent and excellent work!

**Comment by ahrm** [comment]
You can set the foreground and background colors to have exactly the contrast that you want so it is pointless in custom color mode. It makes sense in the dark mode because you can't specify the colors.
