### ISSUE TITLE
[FR] Add option to set the font size of keyboard hints

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#574]
I want to use bigger keyboard hints:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/36224762/209709033-844325ab-637f-43ef-b37c-573223ca576d.png">

**Comment by ahrm** [comment]
Added a `keyboard_select_font_size` config option in 93f98300c2413ac30c129c4edca915f6e82ba842.

**Comment by NightMachinery** [comment]
Thanks!
