### ISSUE TITLE
Creating a bookmark with an existing name should update the old bookmark

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#575]
Currently, bookmarking with an existing name creates new bookmarks:
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/36224762/209822285-54d76477-a156-4074-b62b-954f2d52e71c.png">

But it's better to update the old bookmark.

**Comment by ahrm** [comment]
I disagree. There are many use cases for using the same bookmark name for various places.

**Comment by NightMachinery** [comment]
@ahrm Can you add an option for this? I use bookmarks with the same name to keep my last place in different books. I don't see how I can do that without this functionality. If I use different names, the bookmarks will become very cluttered.

PS: I think the last location of different files is automatically saved, but since this is an implicit action, it's easy to lose one's place. E.g., I go to a different bookmark in the same file, and then quit the app. The next time I open the app, I can't go back to my last read location, as I didn't close the file on that location.

**Comment by NightMachinery** [comment]
Update: I just noticed that the marks are also persistent, and are local to each file; so marks are effectively what I wanted here. Thanks.
