### ISSUE TITLE
Probably update README or description

### ISSUE THREAD

**Issue by uncomfyhalomacro** [ahrm/sioyek#576]
Sioyek uses MuPDF as the backend. afaik, this means that sioyek can also be an EPUB viewer. I have tried this with an epub file and it does. 
![image](https://user-images.githubusercontent.com/66054069/209956148-bb091040-8750-436c-ab41-406ed82098df.png)

**Comment by ahrm** [comment]
I am aware. However, we don't have some epub-specific features (e.g. reflowing). So I am hesitant to advertise epub support.
