### ISSUE TITLE
Feature request: Reading from stdin

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#580]
Can sioyek read PDFs from stdout? This would very useful for scripting. 

Zathura supports this like: `some_command | another_command | zathura -`

**Comment by ahrm** [comment]
No, we assume PDFs are files and I don't think it is worth the extra complication to remove this assumption (for example all files in the database have a path field, removing this assumption would be a headache).

We live-reload the documents anyway, so except very special circumstances where you don't want to create a file (why?) this doesn't add anything.
