### ISSUE TITLE
[Feature request] Command data in keymaps

### ISSUE THREAD

**Issue by Apeiros-46B** [ahrm/sioyek#581]
It would be nice to be able to specify command data in keymappings.
With that, things like the following could be achieved:
![image](https://user-images.githubusercontent.com/61390942/210158830-af1507ee-7e1b-4837-aee4-aee358454462.png)
(Moving the visual mark then centering it on-screen)

**Comment by ahrm** [comment]
You can achieve this like this, first define a macro in `prefs_user` like this:
```
new_macro _focus_next_line move_visual_mark_down;goto_mark(`)
```
then bind it in `keys_user` like this:
```
_focus_next_line <C-j>
```

**Comment by Apeiros-46B** [comment]
I see. Thank you.
