### ISSUE TITLE
Release on fork "hexomancer/sioyek" fails to build for MacOS

### ISSUE THREAD

**Issue by qingshuizheng** [ahrm/sioyek#589]
Hi ahrm, thanks for the great app, and thanks for offering a build version for the latest commit on https://github.com/hexomancer/sioyek/releases

Seems that the build for the macOS in that repo has been down for 2 weeks, is it that due to some errors or you actually are not building the macOS version? The size of the macOS version is 34.1 KB, which is not right apparently.

Just curious and could not wait to try out the most recent fix of https://github.com/ahrm/sioyek/issues/542 & https://github.com/ahrm/sioyek/issues/564. 

Feel free to close this issue, since it's not something big deal. 

Thanks,
Zheng

**Comment by ahrm** [comment]
Should be fixed now.

**Comment by qingshuizheng** [comment]
> Should be fixed now.

Cool, thanks so much! @ahrm
