### ISSUE TITLE
[bug] crash when open files if filename is chinese or japanese

### ISSUE THREAD

**Issue by MiuKaShi** [ahrm/sioyek#590]
Assume we have three files

File1: test.pdf
File2: 测试1.pdf
File3: 测试2.pdf

open each file is ok, but problem occurs when open file with order:
1. file1 -> file2 (crashed)
2. file2 -> file1 (crashed)
3. file2 -> file3 (crashed)

This bug has been discussed before #428 , but has not been well fixed. 

Now, I have tested the sioyek and sioyek-git packages under arch linux, all have this problem.

Try to set should_launch_new_instance 1 also did not solve the problem.

Hope someone can solve this bug.

**Comment by ahrm** [comment]
How do you open the second files? From command line or within sioyek?

**Comment by MiuKaShi** [comment]
> How do you open the second files? From command line or within sioyek?

I open the second files with command line, if open within sioyek, everything is fine.

**Comment by ahrm** [comment]
I will look into the issue. As a workaround for now, you can open a new window from within sioyek by executing `new_window` command and then open the file from that window.

**Comment by ahrm** [comment]
Should be fixed in 651cc6b9e7d3acda9f4704927fca953517dd228c.

**Comment by MiuKaShi** [comment]
> Should be fixed in [651cc6b](https://github.com/ahrm/sioyek/commit/651cc6b9e7d3acda9f4704927fca953517dd228c).

I just test it, the problem has been fixed. 
Thank you

**Comment by MiuKaShi** [comment]
> Should be fixed in [651cc6b](https://github.com/ahrm/sioyek/commit/651cc6b9e7d3acda9f4704927fca953517dd228c).

After using this version, I found all custom command was failed.
I think it is a new bug due to this patch.

**Comment by ahrm** [comment]
What is an example of a command that has stopped working?

**Comment by MiuKaShi** [comment]
> What is an example of a command that has stopped working?

For example, I have defined the following command in prefs_user.config file (located in ~/.config/sioyek)

execute_command_a cp %1 /home/data
execute_command_b command1 %1

and defined the following shortcuts in keys_user.config file (located in ~/.config/sioyek)

execute_command_a <C-a>
execute_command_b <C-b>

If I use the patched version or sioyek-git version, all custom commands not work.

But change to sioyek 2.0.0, all commands works.

**Comment by ahrm** [comment]
Yeah `execute_command_*` is removed. Use named commands instead like:

```
new_command _copy_file cp %1 /home/data
```

And in `keys_user.config`:
```
_copy_file <C-a>
```

(Note that custom command names must start with an underscore).
