### ISSUE TITLE
It's possible to build a pre-built binary of Sioyek for macOS Sierra(viz. macOS 10.12.6)?

### ISSUE THREAD

**Issue by Kairotopos** [ahrm/sioyek#592]
Bonjour @ahrm!
Could you please build the Sioyek for some lower version macOS, for example, macOS 10.12.6(I don't want to upgrade my macOS)? I have checked the conditions of building the pre-built binary of Sioyek, and the necessary usage of tools, viz, Xcode and Qt 5, seems to be  somewhat difficult for my Mac system. There are still many users of the lower version, as I found that many people around me are also using the Sierra version.

**Comment by ahrm** [comment]
No. I don't have a mac computer myself, I use github actions to make the macos builds. See this issue for more information: https://github.com/ahrm/sioyek/issues/345.
