### ISSUE TITLE
Keybind for `previous_item N` does not work

### ISSUE THREAD

**Issue by amanjitsk** [ahrm/sioyek#598]
Does not work on master currently. Forward search (`next_item n`  ) works fine,
but backward search using `previous_item N` does not work as expected (it jumps to the previous page).
Is this just a keybinding issue?

**Comment by ahrm** [comment]
Thanks for the report. Should be fixed in ef24e9149a2f766e0e1ecbb6cf4fa55197e7ddbb.

**Comment by amanjitsk** [comment]
Great, thanks for the quick fix!
