### ISSUE TITLE
feature request: ignore invalid last_document_path

### ISSUE THREAD

**Issue by perprit** [ahrm/sioyek#6]
Hi, thanks for the great project.

I've been using the viewer in Windows (and it works great :D), I find it a little inconvenient whenever the file I viewed the last time doesn't exist at the directory it was originally located at (which is often my scenario), the binary doesn't launch at all.

Could you consider adding a default action for the invalid last document path?

Thanks in advance!

**Comment by ahrm** [comment]
Hi!
This is already fixed in 2719638910439a11fec950b8d03e173fab6d5284. I just have not created a new release since then. (I am waiting for Linux and MacOS build to be fixed so I can make a simultaneous release on all platforms).
