### ISSUE TITLE
future roadmap #2 - integrate openai

### ISSUE THREAD

**Issue by johndpope** [ahrm/sioyek#600]
this code in notebook format allows you to ask questions from a given paper.

https://github.com/keerthanpg/talktopapers

https://twitter.com/keerthanpg/status/1614466942831833089

@keerthanpg
@nuwandavek

**Comment by ahrm** [comment]
I have already implemented something like this as an extension. However, the problem is deployment, it is not very useful ran locally because it is too slow and also requires beefy GPUs (weird for a PDF viewer). And I don't have the infrastructure to run it on a server.

**Comment by johndpope** [comment]
is there a branch or git commit I can reference to get started?

**Comment by ahrm** [comment]
I did not publish it as it was not very polished. But it was nothing complicated, I just used a pre-trained question answering model, here is the code, it is old though so I am not sure if it works verbatim with the recent sioyek versions.

[sematic_local.txt](https://github.com/ahrm/sioyek/files/10425368/sematic_local.txt)
