### ISSUE TITLE
[Feature request]: split pdf horizontally like vim

### ISSUE THREAD

**Issue by xuwei152** [ahrm/sioyek#606]
I know there have been features like the "new command" and "port" already. However, they create new windows and the management of windows is terrible in MS Windows. It is very inconvenient for switching windows and adjusting sizes. So is it possible to add a feature to split the windows like vim does with corresponding shortcuts.

Thanks in advance

**Comment by rohit-kumar-j** [comment]
This would be a nice feature

**Comment by ahrm** [comment]
Added two page mode in the development branch (`toggle_two_page_mode` command).
