### ISSUE TITLE
[Feature request] Improved background color configuration

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#607]
I usually prefer to set the background and paper color to the same color, seamlessly blending the paper into the background. However, that is not always the case. For instance, when resizing the window to fit it to the page dimensions, it would be useful to quickly be able to switch from a white background to a black background and vice versa. I have tried to set up the following keyboard shortcuts: 

- `setconfig_background_color 0 0 0 tb`
- `background_color 0 0 0 tb` 

Which doesn't seem to work. What am I missing here? Are you not able to pass parameters to commands defined in `keys_user.config`? If not, could you add a `toggle_inverted_background` command to alleviate the issue? 

Another improvement could be to add an option to change the background color in custom color mode (not the paper color), such that we can also here achieve the seamless mode where the paper color is the same as the background color. I find it a bit confusing that `background_color` and `dark_mode_background_color` changes the background color, while `custom_background_color` changes the _paper_ color. 

Suggestion: 

- `custom_background_color` changes the _background_ color. 
- `custom_paper_color` changes the _paper_ color.  

Forgive me if any or all of this is currently possible using the existing configuration options, but I sure couldn't figure it out.

**Comment by ahrm** [comment]
This is already fixed in https://github.com/ahrm/sioyek/commit/0c2251b1bea4b22b0e3b5ad01170f7c7c6cd1309. We have a `custom_color_mode_empty_background_color` option which changes the background color.

> setconfig_background_color 0 0 0 tb
background_color 0 0 0 tb

This doesn't work. You need to first define a macro in your prefs_user like this:
```
new_macro _my_commnad setconfig_background_color(0 0 0)
```
and then bind it in keys_user like this:
```
_my_command tb
```

**Comment by HakonHarnes** [comment]
Okay, that's great! Neither `custom_color_mode_empty_background_color` or `new_macro` has any documentation, though. Also, please reconsider the name of `custom_color_mode_empty_background_color`. My issue is this: 

- `background_color`: Changes the _background_ color in normal mode. 
- `dark_mode_background_color`: Changes the _background_ color in dark mode.
- `custom_background_color`: Changes the _paper_ color in custom mode. 
- `custom_color_mode_empty_background_color`: Changes the _background_ color in custom mode. 

You'd expect `custom_background_color` to have the same functionality as `background_color` and `dark_mode_background_color`, but it doesn't. The following approach makes a lot more sense to me: 

- `background_color`: Changes the _background_ color in normal mode. 
- `dark_mode_background_color`: Changes the _background_ color in dark mode.
- `custom_mode_background_color`: Changes the _background_ color in custom mode. 
- `custom_mode_paper_color`: Changes the _paper_ color in custom mode. 

That's my two cents. I also think it's odd to have "background" and "empty background" refer to the same thing, and "background" sometimes referring to the background, but other times referring to the paper. What do you think?

**Comment by ahrm** [comment]
I agree with your point, but changing `custom_background_color` would break a lot of users' configuration so I don't think I will do it.

**Comment by HakonHarnes** [comment]
> I agree with your point, but changing `custom_background_color` would break a lot of users' configuration so I don't think I will do it.

That's understandable!
