### ISSUE TITLE
[Feature request]Reduce the width of the toc window, so that the text is in the middle of the screen.

### ISSUE THREAD

**Issue by wenbopeng** [ahrm/sioyek#608]
![image](https://user-images.githubusercontent.com/74350447/214268316-28768260-8208-4b10-9132-704dec5309c1.png)
![image](https://user-images.githubusercontent.com/74350447/214268888-b204a51d-f644-4c35-85f4-8a34cbfeeaf5.png)

**Comment by ahrm** [comment]
Added in https://github.com/ahrm/sioyek/commit/d06746e94dce4a616fc141137283f2f2a0af92f8.
