### ISSUE TITLE
[Feature request] Save pdf

### ISSUE THREAD

**Issue by jmburgos** [ahrm/sioyek#609]
Most pdf readers have a "Save as" or "Write" command to save the current pdf to a file with a different path or name.  Would it be possible to implement a ":write" command in Sioyek to do this?

**Comment by gitdramaqueen** [comment]
You may be looking for `embed_annotations`

#120 #160 #234 #354

**Comment by jmburgos** [comment]
Actually, I am looking for a "save as" option for the current pdf.  The reason is that I often dowload pdfs from the web, and save them in my "references" folder only after checking if they are useful.  With zathura (my default pdf reader, as with any other pdf reader) I can simply write a copy of the pdf file into a new file in my references folder, giving them the name matching their bibtex key (something I need to do so my reference/note taking system works).  Zathura has a ":write" command that takes a filename and writes a copy of the pdf to that file.  It would be good if Sioyek could do that.

**Comment by ahrm** [comment]
This can be easily added using custom commands, for example here is a simple version:

```
new_command _write cp "%1" "%{command_text}"
```

**Comment by jmburgos** [comment]
Ah! Yes, I did not thought about it.  This opens lots of possibilities!  Thank you.
