### ISSUE TITLE
Unable to find  `keys_user.config` and `prefs_user.config`

### ISSUE THREAD

**Issue by Aurawn** [ahrm/sioyek#613]
I install `sioyek` from the software shop for Debian(testing), I can find `keys.config` and `prefs.config` in `/etc/sioyek/`, but i can not find  `keys_user.config` and `prefs_user.config`, if I can create them in my `$HOME/.config/...` to configure my `sioyek` ？This is my first time to submit issue, so please forgive me if this is not the right way.

**Comment by ahrm** [comment]
You can create them manually in `~/.config/sioyek`.

**Comment by Aurawn** [comment]
> 

Thanks for solving the problem!
