### ISSUE TITLE
Dark mode inverses image colors

### ISSUE THREAD

**Issue by xezo360hye** [ahrm/sioyek#620]
I am using `toggle_dark_mode` option without any color customization. Here is a normal verion:

![image](https://user-images.githubusercontent.com/79970533/216308660-78f25714-64d6-40d2-a516-d4fbed42cdf1.png)

And here it is in dark mode:

![image](https://user-images.githubusercontent.com/79970533/216308724-ff39d9a4-4270-4c01-b1a2-6fc1a5a177ab.png)

As you can see, it doesn't look quite well. Is there an option to instruct sioyek not to touch images at all, or just make them darker or lower contrast or something else without making such inversions?

**Comment by ahrm** [comment]
Which version of sioyek are you using?

**Comment by xezo360hye** [comment]
> Which version of sioyek are you using?

2.0.0-1 from AUR

> Anyway, this is mainly caused because of jpeg compression

But my file is PNG... (`Pictures/tux_disk.png: PNG image data, 1280 x 1063, 8-bit/color RGB, non-interlaced`)

**Comment by ahrm** [comment]
Probably it was originally a jpeg (or some other compressed format) file which was converted into png.

**Comment by xezo360hye** [comment]
Well here's another image which I did not modify after downloading

![image](https://user-images.githubusercontent.com/79970533/216317613-bc5d1d2c-2957-427b-8a9e-2674c40dd47d.png)

![image](https://user-images.githubusercontent.com/79970533/216317524-dff66b0f-b7e1-4c0b-a37f-b09f102ef7c7.png)

**Comment by ahrm** [comment]
Again, the fact that it is png doesn't mean that it was not lossily compressed beforehand.

**Comment by xezo360hye** [comment]
OK here is my newly-created PNG image from scratch using GIMP:

![image](https://user-images.githubusercontent.com/79970533/216319717-831e858e-74b5-4d0e-899c-7acf74dbbf11.png)

And in dark mode:

![image](https://user-images.githubusercontent.com/79970533/216319794-dc8596d5-1f0d-4a55-9bf2-5ad6923b358d.png)

**Comment by ahrm** [comment]
Added a `preserve_image_colors_in_dark_mode` config option in https://github.com/ahrm/sioyek/commit/b22b931b57e13e69f68c2791d36509c5279aa1e0.
