### ISSUE TITLE
Use "hjkl.." instead of "1234..." as label when open link.

### ISSUE THREAD

**Issue by buddhiko1** [ahrm/sioyek#627]
Numbers are not easy to type on a keyboard .

**Comment by ahrm** [comment]
Added an `alphabetic_link_tags` config option in 48d12760a3f8d379a2ce737833a9f939c02af0f2.

**Comment by ahrm** [comment]
Improved in 49bfc8005ec11b12d455a3e4822aa18a31cdc58e. Now, if there are less than 26 links visible when `alphabetic_link_tags` option is set, `open_link` command will behave as a symbol command so when you press the alphabet letter we immediately jump to the link (no need to press enter). Also this commit adds the following commands to create a portal or open an overview to PDF links:
* `overview_link`
* `portal_to_link`

**Comment by buddhiko1** [comment]
@ahrm  
if i have a paypal account, I'll buy you coffee. but i can't bind my bank card.
so, thanks for your excellent project.

**Comment by userrand** [comment]
I am using a previous version but i think (I am not sure, is there a way to check ? ) that the version I am using is more recent than the commit mentioned above.
 
alphabetic_link_tags did not work for me (and i did not find it in the documentation web page). Also, I see overview_definition and not overview_link.
