### ISSUE TITLE
Load the default configuration for individual options when the user configs do not override them.

### ISSUE THREAD

**Issue by PurpleAzurite** [ahrm/sioyek#63]
Currently, if the application gets updated and a new configuration option is added (eg. a new keybinding hook), user config files in the home directory will not contain them and the newly added options won't work. (For example the new embedded file opening interface will not work unless the user adds the open_embedded line manually.

Having the application only use user configs as overrides, and the defaults when they are absent should solve this issue.

**Comment by ahrm** [comment]
This is how we handle things. We use both the user config files and the default config files with the user config files having a higher priority. Is it not working as intended?

**Comment by PurpleAzurite** [comment]
Interesting. No, I was not able to pull up the new embedded file system (Ctrl+O) until I manually added the config file. I will do more testing later tonight.

**Comment by PurpleAzurite** [comment]
The AUR package has not yet update so I was not able to test there, but from what i can observe, building sioyek with source (with linux defines) and using the personal configuration that does not contain the new bindings, makes it so it's not possible to pull up the new embedded file picker.

**Comment by ahrm** [comment]
> The AUR package has not yet update so I was not able to test there, but from what i can observe, building sioyek with source (with linux defines) and using the personal configuration that does not contain the new bindings, makes it so it's not possible to pull up the new embedded file picker.

Well, when you compile sioyek yourself then you have to manually copy the keys.config and prefs.config from the source location to the default location of these files in your file system. Did you do this? (this is done automatically when you use the package manager, also if you don't define `STANDARD_LINUX_PATHS` then we directly use the files in the build directory)

**Comment by fanmih** [comment]
On Mac OS:
Pressing C-o brings up the usual open file dialog (as pressing 'o')
Adding the option to the user config keys file does not help. 
I will check it again together with other options. 

(@ahem As you said you are not on a Mac so you can not test this but I just mention it here). 

By the way, on the Mac :
 the user preferences are stored in:
~/Library/Application Support/sioyek/

The default config files are stored in the sioyek.app package

**Comment by Endle** [comment]
> The AUR package has not yet update so I was not able to test there,

How about invite the AUR author to this discussion? It would be much easier

**Comment by PurpleAzurite** [comment]
> > The AUR package has not yet update so I was not able to test there, but from what i can observe, building sioyek with source (with linux defines) and using the personal configuration that does not contain the new bindings, makes it so it's not possible to pull up the new embedded file picker.
> 
> Well, when you compile sioyek yourself then you have to manually copy the keys.config and prefs.config from the source location to the default location of these files in your file system. Did you do this? (this is done automatically when you use the package manager, also if you don't define `STANDARD_LINUX_PATHS` then we directly use the files in the build directory)

Yes I had already done this. I put the files in the correct locations as discussed before and used the correct compile flags.

I want to clarify that everything else works properly, except for the newly added keybinding. It will not use the default binding, when user config files are present in the home directory, and the new keybinding line is missing.

**Comment by ahrm** [comment]
> > > The AUR package has not yet update so I was not able to test there, but from what i can observe, building sioyek with source (with linux defines) and using the personal configuration that does not contain the new bindings, makes it so it's not possible to pull up the new embedded file picker.
> > 
> > 
> > Well, when you compile sioyek yourself then you have to manually copy the keys.config and prefs.config from the source location to the default location of these files in your file system. Did you do this? (this is done automatically when you use the package manager, also if you don't define `STANDARD_LINUX_PATHS` then we directly use the files in the build directory)
> 
> Yes I had already done this. I put the files in the correct locations as discussed before and used the correct compile flags.
> 
> I want to clarify that everything else works properly, except for the newly added keybinding. It will not use the default binding, when user config files are present in the home directory, and the new keybinding line is missing.

This is weird. I mean the symptoms indicate that you are using a previous version of `keys.config` file (because other keys seem to be working except the new key binding). Could you paste the output of running sioyek from console here?

**Comment by PurpleAzurite** [comment]
I am no longer able to reproduce this issue. I removed the line from my user config and recompiled, using the old systems-wide configs and now it works.
