### ISSUE TITLE
Opening links to other PDFs - "warning: unknown link uri"

### ISSUE THREAD

**Issue by pprotas** [ahrm/sioyek#636]
Hello! I might be doing something wrong, but I'm trying to click a link to a different `.pdf` file, and I keep getting this error:
```
warning: unknown link uri file://<myfile>.pdf#page=1
```

The link opens fine in `zathura` or Acrobat Reader.

Does `sioyek` expect a different link format? For context, the PDF is generated using `pandoc` by converting from `markdown` to `pdf`.

**Comment by ahrm** [comment]
I did not even know that you could link to a different file in a PDF. What if the file doesn't exist?
Can you upload an example PDF with such links so I can test on it?

**Comment by pprotas** [comment]
Yeah, here you go. If you open these files in Adobe Acrobat or `zathura`, you can click the link in `one.pdf` to be redirected to `two.pdf`.

It does seem like a non-standard functionality, because so far the PDF readers I've tried have are very finnicky with this (Acrobat seems to crash, `zathura` only works if using the `zathura-pdf-poppler` plugin).

[one.pdf](https://github.com/ahrm/sioyek/files/10776461/one.pdf)
[two.pdf](https://github.com/ahrm/sioyek/files/10776463/two.pdf)
