### ISSUE TITLE
text is too pixelated

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#639]
may be its beacuse i am using fractional scalling i dnt know but its unsabley blurry . please adress this issue

# document viewer gnome
![image](https://user-images.githubusercontent.com/78728701/219872703-0d405e03-15fe-4c80-a6c7-30234417cbc1.png)

# sioyek 
![image](https://user-images.githubusercontent.com/78728701/219872655-f46646f6-25b5-43c2-bf25-c8156810954a.png)

**Comment by ahrm** [comment]
Does the issue still happen in the latest experimental builds here? https://github.com/hexomancer/sioyek/releases/tag/v0.31.431

**Comment by Aneeqasif** [comment]
yes the version u shared works well but there is also an issue that in this issue to table of content view look very outdated and not much polished  desing while the toc selector in the version that i have (with pixelated text) has much more polished ui.
please address this in a version that solve both issues

## version with good text rendering but bad ui of toc
![Screenshot_20230219_001251](https://user-images.githubusercontent.com/78728701/219884081-dfbeeab2-237a-4314-91db-a7c1e70109c6.png)

## verion with pixelated text rendering but with alot more polished and modern toc ui

![Screenshot_20230219_001335](https://user-images.githubusercontent.com/78728701/219884186-ac7a431e-d7b8-41b9-a3fb-ec09276d40cf.png)

**Comment by ahrm** [comment]
There is no code change for table of contents rendering, so if it is changed between versions either it has changed because of changes in Qt (which I can't do anything about), or because of your configs.

**Comment by Aneeqasif** [comment]
right so which verion should i used the forked one or from ahrm/sioyek repo , shouldnt the pixelated issue be resolved in orignal sioyek verion ?

**Comment by Aneeqasif** [comment]
as the version u suggested in 5 comits behind so it might be missing some functionality from official verion

**Comment by ahrm** [comment]
> right so which verion should i used the forked one or from ahrm/sioyek repo , shouldnt the pixelated issue be resolved in orignal sioyek verion ?

Probably the forked version. This issue will be fixed when we do a new release. At this point version 2.0.0 is a couple of months old so it is way more than 5 commits behind.

**Comment by Aneeqasif** [comment]
i tried buliding the orignal verion following the build instructions , and then run sioyek from build directory it ran perfectly as expected without any issue, but i dont know how to properly install it in system , i did sudo make install but when i try to run sioyek from m y menu system in kde sioyek doesnot run properly and it was not responding, then i ran $which sioyek and then `/usr/bin/sioyek` it showed same response as it open it from menu system some errors was on terminal like `cannot find /usr/bin/shaders` etc so , i have successfully build the orignal version that ran find but please help to properly install it system wide

**Comment by ahrm** [comment]
You can just create a symlink from `/usr/bin` to sioyek's executable.

**Comment by Aneeqasif** [comment]
right , but isnt there any proper way to do it for system wide installation

**Comment by ahrm** [comment]
That *is* the proper way.

**Comment by Aneeqasif** [comment]
> That _is_ the proper way.

ok so i tried this but one thing is not  working that is cross document portal
steps to i did
open 2 docs
press p on one doc
press p again on other document
then went back to first document and press f12 
the portal didnt open in the showing part from  2nd doc in helper window (that remian blank black)

it worked just fine if i create a portal within same  document

- secondly i have added ```startup_commands    toggle_statusbar``` in config and it hide the status bar of the first document that i open but whenever a new sioyek window is opened the statusbar is not toggled off

**Comment by ahrm** [comment]
Can't reproduce either of these issues. Do they occur with the build of latest commits here: https://github.com/hexomancer/sioyek/releases/tag/v0.31.432 ?

**Comment by Aneeqasif** [comment]
no i have tested it on version [v0.31.431]( https://github.com/hexomancer/sioyek/releases/tag/v0.31.431) that u suggested in previous comment

# demo of statusbar toggle issue on startup and the portals issue in cross doc portal
https://user-images.githubusercontent.com/78728701/219967725-5a388256-723b-4765-99ae-907ee8bb6c8e.mp4

**Comment by Aneeqasif** [comment]
as u can see when  i open 2 pdfs there was no statusbar on first one as aspected and set in config, but in  2nd pdf the statusbar is there and secondly i cannot create a portal from other pdf in first pdf

**Comment by ahrm** [comment]
Which command does `open with sioyek` execute?

**Comment by Aneeqasif** [comment]
> Which command does `open with sioyek` execute?

it is opened by desktop file in which use /usr/bin/sioyek which is symlinked to the executable thats in build folder i have also tested it with the full direct path of the binary that i built

**Comment by Aneeqasif** [comment]
should i try it on virtual machine to further investigate?

**Comment by ahrm** [comment]
Can you share the desktop file here?

**Comment by Aneeqasif** [comment]
[Desktop Entry]
Name=Sioyek
Comment=PDF viewer for reading research papers and technical books
Keywords=pdf;viewer;reader;research;
TryExec=/home/aneeq/Downloads/Compressed/sioyekHamxe/build/sioyek
Exec=/home/aneeq/Downloads/Compressed/sioyekHamxe/build/sioyek %f
StartupNotify=true
Terminal=false
Type=Application
Icon=sioyek-icon-linux
Categories=Development;Viewer;
MimeType=application/pdf;

**Comment by Aneeqasif** [comment]
> Can you share the desktop file here?

you can see the desktop file in above comment

**Comment by ahrm** [comment]
The desktop file looks okay, unfortunately I am not able to reproduce the statusbar issue. Note that the portal issue is not really a bug, we don't have the ability to link between different sioyek windows yet, so if you want to create a portal to another document you have to use the same sioyek window to open the second document (I understand creating portals between windows is a useful feature and I will probably add it in the future.).

**Comment by Aneeqasif** [comment]
thanks for responding i really appreciate your time and effort

**Comment by ahrm** [comment]
Added the ability to create portals between windows in c8a532acbf87b57b9e58ec3367071db49dbb0433.

**Comment by Aneeqasif** [comment]
> Added the ability to create portals between windows in [c8a532a](https://github.com/ahrm/sioyek/commit/c8a532acbf87b57b9e58ec3367071db49dbb0433).

thats awesome :heart:
