### ISSUE TITLE
Two pages mode in Sioyek

### ISSUE THREAD

**Issue by lanw0622** [ahrm/sioyek#64]
First of all, Thanks for your awesome work. 
And I wonder how do I view two pages in Sioyek?

**Comment by ahrm** [comment]
There is no such feature in sioyek.

**Comment by julianofhernandez** [comment]
Is this feature going to be added, multiple pages would be super helpful.

**Comment by ahrm** [comment]
Currently, viewing the PDF as a continuous scroll is pretty baked in the source code. If I can find some way to cleanly add two page mode without complicating the code too much I will add it but currently I have no plans to add it.

**Comment by ahrm** [comment]
Added two page mode in the development branch (`toggle_two_page_mode` command).
