### ISSUE TITLE
WSL / vimtex compatibility fix

### ISSUE THREAD

**Issue by elu00** [ahrm/sioyek#640]
Hi,

Thanks as always for the work!
I've recently upgraded my vimtex+wsl+sioyek setup from 1.5 to 2.0, but it looks like I've broken reverse search in the process.
I'm fairly sure the regression is because of [this commit](https://github.com/ahrm/sioyek/commit/f57f91806c26cd67830a67e469c6e2632aee8c30), which breaks stuff since the synctex data for my setup has linux-style paths.
Would it be possible to add a configuration flag to disable the extra formatting here? (and sorry if this is a case of [this](https://xkcd.com/1172/) haha)

**Comment by ahrm** [comment]
Added a `vimtex_wsl_fix` boolean config option in 83d77a7a77ad831387fbfabae3270a9b06a5aa15. Don't know if it fixes the issue though.

**Comment by elu00** [comment]
Hmm alright, seems like that wasn't quite it.
I'll just stick to 1.5 for now and try to do some more debugging when I have time.
Thanks!
