### ISSUE TITLE
By default, text opens as being highlighted

### ISSUE THREAD

**Issue by turner-julian** [ahrm/sioyek#641]
<img width="1363" alt="Screen Shot 2023-02-19 at 3 38 48 PM" src="https://user-images.githubusercontent.com/98372094/219973974-c6575f4e-0489-40ae-abfd-4fc6abfb4c87.png">

I recently installed nvim + vimtex + sioyek on my system, and I am trying to compile latex files to view in sioyek, but every time it opens, the first text is automatically highlighted.  

I apologize if the fix is simple because I am pretty new to all of this, but don't see how to disable this feature.

Thanks.

**Comment by ahrm** [comment]
Which vimtex command are you using to open sioyek? If you are doing a forward search this is the intended behaviour.

**Comment by ahrm** [comment]
We have improved this in the development branch. Now we just flash the synctex search and then hide it.
