### ISSUE TITLE
search progress has 2 %s

### ISSUE THREAD

**Issue by classabbyamp** [ahrm/sioyek#643]
![image](https://user-images.githubusercontent.com/5366828/220460218-17616299-4524-4b35-beb6-c060a7fc7d87.png)

version is 2.0.0 on void linux 

probably caused by this:
https://github.com/ahrm/sioyek/blob/6cee4eef615567c629aa4728d66cd40ed4e775c9/pdf_viewer/main_widget.cpp#L569

**Comment by ahrm** [comment]
Should be fixed in 426b7886907a4e527bb6db47c00884cce10b1b6d.
By the way, the fact that you could see the search progress tells me that you probably have not enabled `super_fast_search`, I really recommend enabling it as it makes almost all searches instantaneous.

**Comment by classabbyamp** [comment]
thanks!
