### ISSUE TITLE
Feature Request : Tabs but in sioyek way

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#644]
so i am wondering if we have tabs in sioyek that is a missing feature , i know we can just open last recent pdfs from menu and use it as replacement for tabs but it is not the solution , i purpose having a basic functionality of tabs in sioyek . in which a user can be able to open multiple files in same window as tabs , that can be selected and switched by a simplr menu like TOC menu instead of tab bar preserving the minimalism of sioyek. if this feature got successful and seems sane enough , some more functionality that can be very usefull can be added in sioyek like for example saving a session of tabs as a group of tabs with all relevant pdf under study packed up in a grouped that can be stored in database and can be opened up whenever some user wants to study that topic , may be a toc like menu can also be used to show tab groups as parents and the pdf files in them in child nodes to make selection ,

**Comment by ahrm** [comment]
> open multiple files in same window as tabs , that can be selected and switched by a simplr menu like TOC menu

You can already open multiple windows and switch between their windows using an interface you described by using `goto_window` command. Even if I did implement tabs, it would look exactly like this from the user's perspective, the only difference would be that you could not switch between the windows using operating system's alt+tab anymore. So I don't really see a huge benefit to implementing tabs.

**Comment by davidgilbertson** [comment]
My 2 cents, the benefit to tabs is that currently I have about a dozen papers open, but don't want a dozen windows in my Windows alt+tab list (for the same reason I don't want every chrome tab to be a window).

With tabs, you get a second layer of navigation (that one can tab through with ctrl+tab in most apps) that I find very useful.

**Comment by bambirombi** [comment]
If tabs are added I think it would be better to add vertical tabs as [sidebery addon](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) does. It makes possible to read all the filename, something that it is not possible with horizontal tabs. It would be also interesting to search the tabs or buffers and have a number attached to them to jump faster as with Helix editor.

**Comment by Eternex49** [comment]
Alternatively, Syioyek could start supporting xembed. This would make it possible for it to be used with a utility like Suckless' tabbed, together with a variety of others.

**Comment by Aneeqasif** [comment]
> Alternatively, Syioyek could start supporting xembed. This would make it possible for it to be used with a utility like Suckless' tabbed, together with a variety of others.

what do u think about this workflow https://github.com/ahrm/sioyek/issues/796

**Comment by Eternex49** [comment]
It seems very clunky, honestly. At the end of the day, tabs are, for many people, a fundamental feature.
Natively supporting them is not essential, but there should be, at the very least, the possibility of adding them in some other way.
For example, zathura by supporting xembed allows the use of external applications to add the feature.

**Comment by Aneeqasif** [comment]
> For example, zathura by supporting xembed allows the use of external applications to add the feature.

sioyek is a cross platform application so i guess adding support for some features in one platform not other might leads to inconsistency and irrelevant bug reports from other platform users

**Comment by Eternex49** [comment]
Tons of apps support os-specific features. This obvisouly adds complexity; The ideal solution would be to natively support for tabs . I understand that the maintainer is not favourable, but it really is a fundamental feature which, I think, most people already use in other software and that would be found very useful (if not essential, like in my case). Otherwise, there really doesn't seem to be an easy non-convoluted solution.

**Comment by NightMachinery** [comment]
I really like the original design proposed: just have all the "tabs" open in the background such that we can switch between them using a menu by `switch_between_open_documents`. Having different open windows is not a solution as it interacts badly with the OS. (E.g., I use sioyek maximized on macOS, and I absolutely do not want other open windows.)

**Comment by michaelfortunato** [comment]
Hi all, is there a way delete tabs?
