### ISSUE TITLE
[Request/Suggestion] Nightly/dev builds in Homebrew

### ISSUE THREAD

**Issue by pprotas** [ahrm/sioyek#645]
Since the release cadence of `sioyek` seems to be quite low, even though there is a lot of active development on this repo, I would like to request a way to install the development/nightly build of the tool through a package manager.

An example of this is how `neovim` handles this type of versioning: https://formulae.brew.sh/formula/neovim#default

As you can see, `neovim` can be installed with the stable version (default) or with the `--HEAD` flag to install the nightly build.

Here's how I look at it:

Pros:
- Users who are willing don't have to wait for a stable build to be released
- It is optional, most users can still use the stable version without unexpected bugs
- Faster feedback/bug reports for new features that aren't released in the stable release yet
- No need to manually build the binary from source 

Cons:
- More effort to support the dev build in the package repositories & GitHub Actions

What do you think?

**Comment by ahrm** [comment]
I do frequently make experimental builds in this fork: https://github.com/hexomancer/sioyek. I don't maintain the hombrew build so you'll have to contact the maintainer for this.

**Comment by pprotas** [comment]
Out of curiosity, why not release more often? The last release was over 2 months ago

**Comment by ahrm** [comment]
I want to create new releases when there have been a meaningful amount of change to warrant an upgrade.
