### ISSUE TITLE
Newer versions cannot launch more windows if no file is specified

### ISSUE THREAD

**Issue by IceAsteroid** [ahrm/sioyek#650]
This quirk began in previous versions of sioyek up to 2.0.0, and is still persistent.

I can't recall exactly the time when this quirk occurred.

When the option "should_launch_new_window" in conf is set to 1, **it won't open a new window of sioyek without a file specified, if there's a sioyek window already opened**.

In my case, this quirk occurs when I launch sioyek in a terminal.

It's quit frustrating, since, it's better for me, first to launch sioyek, and then second to open file within sioyek, instead of browsing through the filesystem or something and call "sioyek FileName", or to use default application to launch the file.

Ouput message of the first launch of sioyek:

**Note**: The last two lines occur when the second launch is launched in another terminal, but they don't matter as they also occur when a file is specified to open without problem.

```
default_config_path: /etc/sioyek/prefs.config
default_keys_path: /etc/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/xxx/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/xxx/.config/sioyek/keys_user.config
database_file_path: /home/xxx/.local/share/sioyek/test.db
local_database_file_path: /home/xxx/.local/share/sioyek/local.db
global_database_file_path: /home/xxx/.local/share/sioyek/shared.db
tutorial_path: /usr/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/xxx/.local/share/sioyek/last_document_path.txt
shader_path: /usr/share/sioyek/shaders
Creating shared memory block...
Shared memory created: this is the primary application.
Starting IPC server...
IPC server started.
warning: invalid page object
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```

Output message of the second launch:
```
default_config_path: /etc/sioyek/prefs.config
default_keys_path: /etc/sioyek/keys.config
user_config_path: [ 0 ] /etc/xdg/sioyek/prefs_user.config
user_config_path: [ 1 ] /home/xxx/.config/sioyek/prefs_user.config
user_keys_path: [ 0 ] /etc/xdg/sioyek/keys_user.config
user_keys_path: [ 1 ] /home/xxx/.config/sioyek/keys_user.config
database_file_path: /home/xxx/.local/share/sioyek/test.db
local_database_file_path: /home/xxx/.local/share/sioyek/local.db
global_database_file_path: /home/xxx/.local/share/sioyek/shared.db
tutorial_path: /usr/share/sioyek/tutorial.pdf
last_opened_file_address_path: /home/xxx/.local/share/sioyek/last_document_path.txt
shader_path: /usr/share/sioyek/shaders
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application successfully attached to shared memory block.
Secondary application sent message to IPC server.
```

Anyway to fix this?

**Comment by IceAsteroid** [comment]
@ahrm, I do know this feature does exist.

But isn't it far more convenient when opening other windows in other workspaces with a program launcher, instead of to go to the workspace that the first launch is at, and use that shortcut to launch other windows than move to workspaces that I intend to?

**Comment by ahrm** [comment]
Improved in https://github.com/ahrm/sioyek/commit/e5417bd7238d6df1b31afc1beed6efaae8308621. Now if you explicitly pass the `--new-window` command line option, then we create a new window even when no file is specified.

**Comment by IceAsteroid** [comment]
Thank you!
