### ISSUE TITLE
Highlighting via middle-click does not immediately clear selection or render highlight

### ISSUE THREAD

**Issue by hrdl-github** [ahrm/sioyek#651]
The new command system seems to have broken middle-click induced highlighting. To reproduce, configure `highlight_middle_click 1`, highlight some text, and press the middle mouse button. The highlight is not rendered until another action is taken, e.g. a scrolling action or a trying to copy the selection to the clipboard.

Looking at
https://github.com/ahrm/sioyek/blob/7f1dc973be552d8f3622a59f981bf8c1816c7e12/pdf_viewer/main_widget.cpp#L1689-L1693
and https://github.com/ahrm/sioyek/blob/7f1dc973be552d8f3622a59f981bf8c1816c7e12/pdf_viewer/input.cpp#L1518-L1523 I don't immediately see what is going wrong.

Last good commit: ac988bc48c158c81cdcd1eb52c7a7a9a52fc97d3

**Comment by ahrm** [comment]
Should be fixed in e44df4f674465ed97e4ce25888bc1fe381d118d8.
