### ISSUE TITLE
[ SUGGESTION ] Make the statusbar be on top of ToC

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#658]
Just a little suggestion! I think it'd make more sense to let the table of contents be behind the statusbar. ↓

<img width="569" alt="image" src="https://user-images.githubusercontent.com/58621210/224365204-b0d08632-c4ec-414b-93fe-e4be6c4ca8b1.png">

**Comment by ahrm** [comment]
This should be fixed in the development branch.
