### ISSUE TITLE
[Feature request] Add Gesture support like in CrxMouse Chrome™ Gestures or Gesturefy on Firefox

### ISSUE THREAD

**Issue by userrand** [ahrm/sioyek#660]
This project is awesome. It is by far the best pdf app. I was looking for an app that had vim keybindings and I got much more. Thank you all for this great work.

When browsing on the web I want to use either only the mouse or only the keyboard. For the keyboard I use SurfingKeys which is quite similar to this project. One part that has me a bit confused is whether there is support for expanding a selection like in visual mode with vim using w,b,e,k or j.

When using the mouse I like using one of the apps mentioned in the title above that can significantly simplify how I use the mouse by binding gestures to commands. 

Perhaps there is some module somewhere that would make integrating gestures not too much work and that could lead to an even more tranquil pdf experience.

**Comment by userrand** [comment]
I was able to this at the OS level in KDE linux with native gesture shortcuts in the settings that I associated to simulated key presses using a command line function

**Comment by ahrm** [comment]
Closing as I think the OS-level solution is best, it is too niche to implement in sioyek itself.

**Comment by userrand** [comment]
For anyone that might happen to read my initial post, as I mentioned surfingkeys in my post, I should also mention what I think I learned later about a previous sketchy update from the author, that one should perhaps be aware of before installing it: https://github.com/brookhong/Surfingkeys/issues/1796 .
