### ISSUE TITLE
Synctex inverse search filename spaces aren't escaped

### ISSUE THREAD

**Issue by jackwoodside** [ahrm/sioyek#661]
When setting the synctex `inverse_search_command` option, the variable `%1` is used for the filename, however it doesn't escape spaces in the path which can lead to the command not working properly. Is it possible to change the variable to have the spaces be escaped, or have another variable `%3` for it?

**Comment by ahrm** [comment]
Surrounding the `%1` with `'` or `"` (depending on your OS) doesn't help?

**Comment by jackwoodside** [comment]
> Surrounding the `%1` with `'` or `"` (depending on your OS) doesn't help?

Hmm using single quotes worked on the command-line but not when added to the config so it didn't seem to work, but now with double quotes it does work, thanks
