### ISSUE TITLE
Feature request: default zoom level

### ISSUE THREAD

**Issue by javidcf** [ahrm/sioyek#664]
As far as I can tell, Sioyek always defaults to opening new documents with "fit to page width" zoom level. This is a very minor nitpick but it would be great if it were possible to set a default zoom level for newly opened documents. It could be set to fit to width or height with or without margins, although I personally would prefer to have also the option to set a "percentage" zoom (what other readers use as percentages, I assume "100%" means the actual document size considering the screen resolution and DPI?). Maybe this "zoom to percentage" should be a different feature request previous to this one.

**Comment by ahrm** [comment]
We do have a  `fit_to_page_width_ratio` command in. You can configure it in `prefs.config` like so:
```
fit_to_page_width_ratio 0.75
```
Now when you execute the `fit_to_page_width_ratio` command, we just use 75% of the screen width.
