### ISSUE TITLE
The Command Line Table Display Issue

### ISSUE THREAD

**Issue by bestdax** [ahrm/sioyek#666]
Hi,

I'm so happy we can have sioyek.

I'm on macOS(M1), this command line table looks strange. Some shortcuts are not displayed well.

I tried to build it from source, it is same.

![image](https://user-images.githubusercontent.com/22925996/225879439-ed75ce45-e230-4144-8107-e73e2e1d5bfd.png)

**Comment by ahrm** [comment]
This is fixed in the development branch.
