### ISSUE TITLE
Embedded highlights can get too darks

### ISSUE THREAD

**Issue by Animaly0** [ahrm/sioyek#667]
When embeddeng annotations, the highlights darkens.
So much that for some colors, it sometimes gets difficult to read the text.
 
![image](https://user-images.githubusercontent.com/52257781/225890556-4d16cadc-d0c2-4de0-afe9-4a1be3693f3a.png)

Is there any way to control how much the highlights gets dark after embedding or just disable the change of colors alltogether ? 

I couldn't find anything in the doc or the config file that could relate to this issue.

**Comment by ahrm** [comment]
Fixed in https://github.com/ahrm/sioyek/commit/36cff8dbec4bebdab441c21d4128e01fb89b4237.
