### ISSUE TITLE
[Feature request]how to map escape to crtl+[

### ISSUE THREAD

**Issue by Prajwalg19** [ahrm/sioyek#668]
i want to have a key binding of 'ctrl+[' as escape. I searched both the config files i.e keys and prefs but didn't find any key binding for this purpose. Didn't find it in the docs also , please help me with mapping escape with ctrl+[ as I am used to using this key in vim

**Comment by ahrm** [comment]
Added an `escape` command in 0305c2c7c85d9be1b8c8dafe29002409b4cd377a. You can bind it in `keys_user` like so:
```
escape <C-[>
```
