### ISSUE TITLE
[Feature Request] Open Table of Contents to active page

### ISSUE THREAD

**Issue by iamkroot** [ahrm/sioyek#67]
When using the ToC, I usually want to jump to nearby sections. Currently, when I press `t` to open the ToC, the topmost entry is highlighted and I have to scroll down to the current section (can't use text filter).

It would be great if the ToC entry containing the current (active) page would be highlighted and centered on open.

Bonus points if you could also add right-aligned page numbers corresponding to each entry. For example, this is what Okular's ToC looks like:
![Okular ToC](https://user-images.githubusercontent.com/29517049/134769264-5b9f11c4-500a-443e-9bf4-6ba5d70ddbfc.png)

Thanks for your hard work!

**Comment by ahrm** [comment]
Added in 7ad4623341b4b26576134edb4f114b25c323015c.

**Comment by iamkroot** [comment]
Thanks for the amazingly quick response. I tried it out and seems to be working properly. Just wanted to share a minor nitpick- The page number for the highlighted entry seems to have incorrect padding. The text is stuck to the top-left corner, whereas all other page numbers (non-active) are centered. See
![pagenum](https://user-images.githubusercontent.com/29517049/134797948-bf2b24c8-9ffe-46fe-885b-7db16bfaf56a.png)
(The `[362]` is stuck to the top of the highlight, so it looks odd).

**Comment by ahrm** [comment]
> Thanks for the amazingly quick response. I tried it out and seems to be working properly. Just wanted to share a minor nitpick- The page number for the highlighted entry seems to have incorrect padding. The text is stuck to the top-left corner, whereas all other page numbers (non-active) are centered. See
> ![pagenum](https://user-images.githubusercontent.com/29517049/134797948-bf2b24c8-9ffe-46fe-885b-7db16bfaf56a.png)
> (The `[362]` is stuck to the top of the highlight, so it looks odd).

Weird, there is no such issue in my window build. I suspect this is a Qt bug because there is no difference between how my code handles selected and unselected elements, so I doubt there is any simple way that I can fix this issue.

**Comment by ahrm** [comment]
In 58fbee2baa2afa595b92703325e0559232f18294 I manually vertically align the pages but since I could not reproduce the issue in my build, I am not sure if it fixes the issue.

**Comment by iamkroot** [comment]
Looks like that worked - the entry is vertically centered.
![vert_toc](https://user-images.githubusercontent.com/29517049/135274953-14c67524-ca2f-4e0f-a807-30160a3872f5.png)
I'm assuming this can be repeated to make it horizontally centered too?

**Comment by iamkroot** [comment]
While we're at it, I do have one related UI request- could you please make the scrollbar more visible? Right now, the thin 1px grey border does nothing to distinguish it from the background. Maybe a pure-white 2px border might help?
