### ISSUE TITLE
[Feature Request] Side by side view of duplicated window

### ISSUE THREAD

**Issue by userrand** [ahrm/sioyek#670]
Thank you for maybe the best pdf viewer ever.

One can duplicate a window using the new_window command. Then one could set it to the side in Linux (and maybe windows) by using the window key + left or +right. Then go back to the previous window using goto_window and select the second duplicated item in the list I think. Then open that window and use the window key plus the arrow key again to have a side-by-side view of two parts of the current document.

The procedure above required involving the OS system and involved many steps. Is it possible to make a command that does the above automatically like the chrome web extension Tab Resize ? Or maybe instead opens a tab rather than a window and include an option to see tabs side by side like vscode ?

**Comment by ahrm** [comment]
This can be achieved in this commit in development branch using javascript scripting API: https://github.com/ahrm/sioyek/commit/fc2495be9b4d788cf9c3e45f8165790f900cda98.

`split.js`:
```
let state = sioyek_api.get_json_state();

let width = state["window_width"];
let height = state["window_height"];

sioyek.set_window_rect("0 0 " + Math.floor(width / 2) + " " + height);

let new_window_id = sioyek.new_window();
let new_window_size_string = "" + Math.floor(width / 2) + " 0 " + Math.floor(width / 2) + " " + height;
sioyek_api.run_macro_on_main_thread("set_window_rect(" + new_window_size_string + ")", false, new_window_id);
```
`prefs_user.config`:
```
new_js_command _split split.js
```

`keys_user.config`:
_split <keybind>

**Comment by userrand** [comment]
Quite cool thank you. I did not know there was a Javascript API. It seems quite flexible if it can make a duplicated window in so few lines. I might check it out.
