### ISSUE TITLE
Highlights cover text

### ISSUE THREAD

**Issue by enrico223** [ahrm/sioyek#671]
Hi, I am using `sioyek 2.0.0` on `EndeavourOS`.
If I highlight directly on sioyek, import them from the pdf or embed it, the highlights cover the text.
This does not happen when I open the pdf on e.g. Okular. 

![screenshot-2023-03-23-15:55:20](https://user-images.githubusercontent.com/72576597/227252979-6c032ef4-40cf-48ce-adae-26df01699d25.png)
Sioyek

![screenshot-2023-03-23-15:55:44](https://user-images.githubusercontent.com/72576597/227253060-122319ad-2fb8-41f7-bb2c-e6b97670b02c.png)
Okular

**Comment by ahrm** [comment]
This is fixed in the development branch.
