### ISSUE TITLE
[Feature Request] More than one instance for "toggle_custom_color"?

### ISSUE THREAD

**Issue by IceAsteroid** [ahrm/sioyek#672]
Greetings.

Is it possible to have more than one instance of "custom_background_color" & "custom_text_color" for toggle_custom_color?

For instance, I need to have two schemes of custom_background_color, one scheme for use in day time, another one for use in night time. 

I could've been using "toggle_dark_mode" for night & "toggle_custom_color" for day time, but the pdf's background in dark-mode is too dark while I have set "dark_mode_contrast" to be fairly low such as "0.5". It doesn't act like contrast-shift like in other pdf viewers.

**Comment by ahrm** [comment]
You can achieve this by defining new commands to change the custom color colorscheme. For example:
```
new_macro _set_colorscheme_1 setconfig_custom_background_color(1 0 0);setconfig_custom_text_color(0 0 1)
new_macro _set_colorscheme_2 setconfig_custom_background_color(0 0 1);setconfig_custom_text_color(1 0 0)
```

Then you can create keybindings to run `_set_colorscheme_*` commands.

**Comment by IceAsteroid** [comment]
I got this working. Phenomenal. I didn't know this feature before, my bad, sorry for the noise.

**Comment by ahrm** [comment]
My bad, I seem to have forgotten to add `new_macro` to the documentation. I am on a trip right now but will add it when I return.

**Comment by IceAsteroid** [comment]
Cheers, have a good journey!
