### ISSUE TITLE
Menu font not changing in Flatpak

### ISSUE THREAD

**Issue by kchousos** [ahrm/sioyek#674]
Hello! First of all, thank you for this amazing program and for the time that you've commited to its developement.

Although I change the `ui_font` to Iosevka, only the status bar changes. The menu font stays the same.

Status bar:
![image](https://user-images.githubusercontent.com/79325777/228096545-a3baf407-b8e7-47af-9c54-260656506338.png)

Menu:
![image](https://user-images.githubusercontent.com/79325777/228096592-8ca966af-55be-4fa5-a2b8-92cb992ebaf4.png)

Is there any solution to this problem?

**Comment by ahrm** [comment]
Added a `ui_font` config option (in addition to `status_font`) in https://github.com/ahrm/sioyek/commit/0dfbf5f63ac80e6078dab2e40eea85d3ac98620d.

**Comment by Aman9das** [comment]
I have the same issue..

**Comment by p00f** [comment]
@ahrm I'm on `b312fe0` (using the AUR package sioyek-git), and setting `ui_font` has no effect
