### ISSUE TITLE
New_command cannot execute: "QString::arg: Argument missing" 

### ISSUE THREAD

**Issue by Fireond** [ahrm/sioyek#676]
As in the documentation, I tried to implement a translation tool using python script. But when I execute the command `_translate`, the output is 
```
QString::arg: Argument missing: python ~/.config/sioyek/scripts/translator.py "%{sioyek_path}" "%{selected_text}", /path/to/my/pdf
```
I just copy and paste commands from the documentation and don't know where went wrong.

Also when I run `sioyek` in the command line it output some `WARNING`:
```
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'uvs' not read by fragment shader
WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

WARNING: Output of vertex shader 'screen_pos' not read by fragment shader

Data set on unsupported clipboard mode. QMimeData object will be deleted.
```
I don't know if this is the problem.

Environment: Macbook m1 air, Ventura 13.2.1
Install by homebrew

**Comment by ahrm** [comment]
Maybe try replacing the `"`s in the command with `'`, for example replace `"{%sioyek_path}"` with `'%{sioyek_path}'`.

**Comment by Fireond** [comment]
> Maybe try replacing the `"`s in the command with `'`, for example replace `"{%sioyek_path}"` with `'%{sioyek_path}'`.

It does not work, it output
```
QString::arg: Argument missing: python ~/.config/sioyek/scripts/translator.py '%{sioyek_path}' '%{selected_text}', ...
```
Also if I set `ruler_mode 1` in the `prefs_user.config` file, it does not take effect, but the keybindings in the `keys_user.config` can work successfully.

**Comment by ahrm** [comment]
Maybe run the command in a command line (after replacing the `%{}` variables with the correct values) and see if there are any errors?

> Also if I set ruler_mode 1 in the prefs_user.config file, it does not take effect

What do you expect should happen when you set `ruler_mode`? What about other configs, do they work?

**Comment by Fireond** [comment]
> Maybe run the command in a command line (after replacing the `%{}` variables with the correct values) and see if there are any errors?
> 
> > Also if I set ruler_mode 1 in the prefs_user.config file, it does not take effect
> 
> What do you expect should happen when you set `ruler_mode`? What about other configs, do they work?

It can run rightly and can print the translation on the status bar.
Here is my `prefs_user.config`:
```
default_dark_mode
font_size 20
new_command _translate python ~/.config/sioyek/scripts/translator.py '%{sioyek_path}' '%{selected_text}'
```
It does not open with dark mode, by the font size changes, and the `_translate` command does not work.

**Comment by ahrm** [comment]
This is wrong:
```
default_dark_mode
```

it should be 
```
default_dark_mode 1
```

**Comment by Fireond** [comment]
Sorry, I correct it and it works, but the `ruler_mode` and `new_command` still cannot work.

**Comment by ahrm** [comment]
Maybe the issue is with the homebrew package (I don't maintain that)? Can you reproduce the issues on the prebuilt package in releases here: https://github.com/ahrm/sioyek/releases/tag/v2.0.0 ?

**Comment by Fireond** [comment]
> Maybe the issue is with the homebrew package (I don't maintain that)? Can you reproduce the issues on the prebuilt package in releases here: https://github.com/ahrm/sioyek/releases/tag/v2.0.0 ?

I just tried, it still not work.

**Comment by ahrm** [comment]
Oh one thing: ruler mode only applied when you move the highlighted line, does it not work when you move the line?

About the translate, does installing the python package and using the config described here work? : https://github.com/ahrm/sioyek-python-extensions#-translate

**Comment by Fireond** [comment]
> Oh one thing: ruler mode is only applied when you move the highlighted line, does it not work when you move the line?
> 
> About the translate, does installing the python package and using the config described here work? : https://github.com/ahrm/sioyek-python-extensions#-translate

Oh in this case it can work. But I have problem installing the python package, I would try after I can install it, thanks!
