### ISSUE TITLE
In dark mode, link_highlight_color is hardly visible

### ISSUE THREAD

**Issue by csdvrx** [ahrm/sioyek#677]
Would it be possible to have a separate link_highlight_color option defaulting to a lighter color when dark mode is enabled?

FWIW I've tried setting `link_highlight_color 0.8 0.8 0.8` in ~/.config/sioyek/prefs_user.config but it didn't help

**Comment by ahrm** [comment]
`link_highlight_color ` takes 4 values (including alpha for transparency).

**Comment by mostafatouny** [comment]
I have exactly the same problem, and setting `link_highlight_color` changes nothing.

![screen130](https://github.com/ahrm/sioyek/assets/56471405/e7a52d80-1ac1-414c-99b2-54ffcc058e4b)
![screen129](https://github.com/ahrm/sioyek/assets/56471405/7e801d9f-a6c4-4a58-86f7-a015de4049a5)

**Comment by ahrm** [comment]
We used to implement dark mode by inverting colors but a lot of users had issues with that ([you ](https://github.com/ahrm/sioyek/issues/171 for example). You can try custom color mode with very dark background color, it uses a different algorithm and it might look better.

**Comment by mostafatouny** [comment]
> We used to implement dark mode by inverting colors but a lot of users had issues with that ([you ](#171 for example). You can try custom color mode with very dark background color, it uses a different algorithm and it might look better.

Thanks for your quick reply. The following worked fine for me in prefs_user:
```
custom_background_color 0.0 0.0 0.0                     
custom_text_color 1.0 1.0 1.0          
```

![screen131](https://github.com/ahrm/sioyek/assets/56471405/835a4edc-b1d6-424b-b450-14a1c304e822)

**Comment by mostafatouny** [comment]
For the records setting `dark_mode_contrast 2` fixes the issue also.

![screen132](https://github.com/ahrm/sioyek/assets/56471405/14ec571e-87fa-47d8-a13e-d858affcf8fd)
