### ISSUE TITLE
`show_document_name_in_statusbar` not working

### ISSUE THREAD

**Issue by Araaha** [ahrm/sioyek#679]
Version: sioyek 2.0.0
OS: Arch Linux
WM: Openbox

So far I've tried setting `show_document_name_in_statusbar 1` in both prefs_user and in the command line to no success. However, 
`sioyek --execute-command set_status_string --execute-command-data %{file_path}` works as intended as a new command.

**Comment by ahrm** [comment]
Yes, we have made the statusbar string configurable and the default config doesn't include document name. You have to add something like this to your prefs:

```
status_bar_format  Page %{current_page} / %{num_pages}%{chapter_name}%{search_results}%{search_progress}%{link_status}%{waiting_for_symbol}%{indexing}%{preview_index}%{synctex}%{drag}%{presentation}%{visual_scroll}%{locked_scroll}%{highlight}%{closest_bookmark}%{close_portal}%{rect_select}%{custom_message}%{document_name}
```

**Comment by Araaha** [comment]
Thanks. Working as expected.
