### ISSUE TITLE
[Feature request] Improve reloading 

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#685]
## Description 
I've recently started using the [Typst](https://github.com/typst/typst) markup language and I've been working on integrating it in neovim + sioyek. One great benefit of using Typst over LaTeX is incremental compilation, using the `typst watch` command. This results in fast compilation times. 

Sioyek and Zathura automatically update the document when it detects changes, although Zathura flickers when updating and also segfaults sometimes. The issue I'm having with Sioyek is that the file is not updated frequently enough, i.e. there is a delay. In Zathura there is no delay before the document is updated.

To overcome this I've been using mupdf, watching for file changes using `inotifywait`, and sending the `pkill -HUP mupdf` signal to instantly update mupdf. See the difference between mupdf and sioyek below: 

https://user-images.githubusercontent.com/89907156/233563461-0246967f-c732-4730-ad5a-223de9d5a7fa.mp4

(Sioyek on bottom, mupdf on top)

I've also tried sending `sioyek --execute-command reload` on file changes, but then the document flickers when updating (momentarily blank page).

## Expected behavior 

Expected behaviour is to update the document as fast as mupdf and Zathura. 

## Solution 

If Sioyek uses some kind of polling approach, expose a config option to set the polling interval. 

If Sioyek uses some kind of notification + delay approach (Sioyek is notified of a file change, but only displays the change after a certain delay, effectively buffering changes before displaying), then expose a config option to set the delay. Setting the delay to `0` should instantly reload the document.

**Comment by ahrm** [comment]
Changing this probably causes sioyek to crash when editing latex files. See these lines https://github.com/ahrm/sioyek/blob/ceae13b12df5653d3fe9e087167081e69a2ad48c/pdf_viewer/main_widget.cpp#L456-L462 .

**Comment by HakonHarnes** [comment]
> Changing this probably causes sioyek to crash when editing latex files. See these lines

That makes sense and might explain why Zathura sometimes segfaults when displaying pdfs compiled with typst. 

Can I force Sioyek to update when I know the compilation has completed? At the moment I'm doing:

```bash
#!/bin/bash

PDF_FILE="$1"

sioyek "$PDF_FILE" &

while true; do
  inotifywait -e close_write,moved_to,create -qq "$PDF_FILE"
  sioyek --execute-command reload
done
```

But when executing `sioyek --execute-command reload` the document flickers (momentarily white) and it focuses the Sioyek window, which I don't want.

**Comment by ahrm** [comment]
We have a `--newfocus` command line option which should prevent focusing.  As for the flicker, I don't think we have a solution right now, but I will look into it.

**Comment by HakonHarnes** [comment]
> We have a --newfocus command line option

I have the latest version from the AUR: 

```
aur/sioyek-git 1:1.5.0.r34.g95fe563-2 [+7 ~0.19] [Installed: 1:2.0.0.r93.gceae13b-1]
```
But I get this error: 
```
$ sioyek --newfocus main.pdf
sioyek: Unknown option 'newfocus'.
```

**Comment by ahrm** [comment]
My bad I meant `--nofocus`.

**Comment by HakonHarnes** [comment]
> My bad I meant `--nofocus`.

Thanks! That works. 

What's the difference between triggering reloading using `sioyek --execute-command reload` and just letting Sioyek poll for file changes and then automatically reload? When it automatically reloads there is no flickering.

**Comment by ahrm** [comment]
`reload` basically restarts sioyek but we only change the rendered pages when file has changed.

**Comment by HakonHarnes** [comment]
> we only change the rendered pages when file has changed.

Is it possible to add a flag for doing this? E.g. `sioyek --execute-command refresh` or `sioyek --reload-pages` or something.

**Comment by ahrm** [comment]
Probably. Currently I am busy working on porting sioyek to android so I don't want to add many new features before that is done, but I will get back to it once it is ported.

**Comment by HakonHarnes** [comment]
I see! I'll have a look in [sioyek/pdf_viewer/main_widget.cpp](https://github.com/ahrm/sioyek/blob/ceae13b12df5653d3fe9e087167081e69a2ad48c/pdf_viewer/main_widget.cpp#L456-L462) when I have the time and see if I can figure something out.

**Comment by ahrm** [comment]
Added a `reload_no_flicker` command in development branch of this repo.
