### ISSUE TITLE
Fail to render long PDF—PDF with irregular page size

### ISSUE THREAD

**Issue by SichangHe** [ahrm/sioyek#686]
Sioyek could not render this PDF at all, for example.

[QBTGiva98QevGWRcs-philosophical-approaches-to-work-and-labor-stanford-encyclopedia-of-philosophy.pdf](https://github.com/ahrm/sioyek/files/11184535/QBTGiva98QevGWRcs-philosophical-approaches-to-work-and-labor-stanford-encyclopedia-of-philosophy.pdf)

**Comment by ahrm** [comment]
This should be fixed in the development branch. Now we have a sliced rendering mode (it is off by default, you can turn it on by setting `sliced_rendering` config) which should be able to handle such documents.

**Comment by SichangHe** [comment]
Hey, thanks for getting back! I noticed that new development builds are no longer coming out of https://github.com/hexomancer/sioyek/releases, and we have not had a release on this repo since v2.0. May I ask why?

**Comment by ahrm** [comment]
The new version is still under heavy development, I will release the binaries when it is reasonably stable.

**Comment by SichangHe** [comment]
I see. Thank you for your information!
