### ISSUE TITLE
how can I print a pdf with fast read (bionic)

### ISSUE THREAD

**Issue by 1hachem** [ahrm/sioyek#687]
Is there a way to print a pdf with bionic reading enabled ? 
btw I love fastread feature really nice work !

**Comment by ahrm** [comment]
No, there is not even a way to print a PDF without bionic! (see https://github.com/ahrm/sioyek/issues/80).

**Comment by ahrm** [comment]
No, bionic mode is simply a rendering trick, we don't modify the PDF itself.

**Comment by 1hachem** [comment]
thank you for your help !
