### ISSUE TITLE
[ SUGGESTION ] Add feature to write notes on PDF

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#697]
It would be really nice to be able to write custom notes on PDFs. Maybe notes can also be linked/associated to highlights. For example, you might highlight something and want to add your own thoughts about that piece.

**Comment by ahrm** [comment]
There is an extension that does that here: https://github.com/ahrm/sioyek-python-extensions#-add_text.

**Comment by ibehnam** [comment]
unfortunately extensions don't work on macOS.

**Comment by ibehnam** [comment]
Actually, is it possible to add the extension features to the app itself? Most importantly, the ability to add text notes on PDFs. I really like Sioyek but have to keep going back to other apps just to add text notes.

**Comment by ahrm** [comment]
That would increase the app size a considerable amount because I would have to bundle python along with the required libs with the application.

When I first implemented extensions I tested them on a friend's macbook and they seemed to work. I remember having to change I few things (I think one was changing the "s to 's) but I don't remember all of it.

**Comment by ibehnam** [comment]
I understand. So does that mean even the add_text feature requires bundling Python along with the required libs?

**Comment by ahrm** [comment]
Yes.

**Comment by ibehnam** [comment]
@ahrm I think I figured out why the `add_text` extension doesn't work. Checking the extension repo, I saw [this line](https://github.com/ahrm/sioyek-python-extensions/blob/5317e955e80169ffb392122ced738c2ca22ce510/src/sioyek/sioyek.py#L820) which calls the `add_freetext_annot` method. But I couldn't find that method in the repo. Any chance it was deleted by mistake?

**Comment by ahrm** [comment]
No, it is part of the mupdf library.

**Comment by ahrm** [comment]
Added ability to create visible bookmarks and draw freehand drawings in the development branch of this repo.
