### ISSUE TITLE
[Feature Request] Add the ability to hide the statusbar on startup

### ISSUE THREAD

**Issue by Anskrevy** [ahrm/sioyek#701]
Not much to say about this one. I have either missed this in the docs, or issues if this is already possible.

**Comment by ahrm** [comment]
We do have a `toggle_statusbar` command. You can run it at startup by adding this to your prefs:
```
startup_commands toggle_statusbar
```

**Comment by Anskrevy** [comment]
Perfect, thank you for pointing this out.
