### ISSUE TITLE
[Feature Request] Add next_file and prev_file commands

### ISSUE THREAD

**Issue by Anskrevy** [ahrm/sioyek#702]
I have got a small python script filling this void at the moment but it would be nice if this was natively implemented.

To elaborate, the command would open the next/prev (compatible) file in the cwd of the open file. My implementation does cycle through the files in the cwd. So if you go to the next file from the last one in the directory it would open the first and vice versa for the prev file.

If this could be implemented in python I would be happy to post my code to help make this a part of sioyek.

**Comment by ahrm** [comment]
In the developent branch of sioyek we have built-in javascript functionality. So this can be implemented in a script like so:

File `next_doc.js` next to `prefs_user.config`:
```
sioyek_async.$open_document_embedded_from_current_path();
sioyek_async.control_menu("down");
let file_name = sioyek_async.control_menu("get");
if (file_name.endsWith(".pdf")){
    sioyek_async.control_menu("select");
}
```

`prefs_user.config`:
```
new_async_js_command _next_doc next_doc.js
```

`keys_user.config`:
```
_next_doc <keybind>
```
