### ISSUE TITLE
Is page_number off by one?

### ISSUE THREAD

**Issue by raphaelfournier** [ahrm/sioyek#704]
I recently discovered Sioyek, and first: thank you for all those good ideas (I'm an academic).

### context: writing a small extension
I sometimes want to extract some pages from a long pdf, either to print them on paper, or to send to others just the necessary pages. However, selecting the pages is often cumbersome, requiring to have a small text file where I input manually the pages I want to keep, to then feed them to pdfjoin or the OS print dialog. 
Yesterday I thought that I could write a small sioyek extension to do it. Basically, just press a key and the current page number should be appended to a text file (so that, when scrolling through the file, I can visually select the pages to keep). 

Here is the code for the small extension: https://github.com/raphaelfournier/sioyek-pagenumber
BTW, feel free to add this to a repository of extensions for sioyek. It's very limited in scope, but if it may help…

However, as you can see in my `pagenumber.sh` file, I had to add 1 to the page number, because the value displayed in sioyek status bar did not match with the one recorded in the file when pressing the key. 

### issue
So, the issue is: **isn't there a problem with the `%{page_number}` variable from sioyek?**

**Comment by ahrm** [comment]
Yes, for display purposes we use 1-based indexing because it is more natural for normal users, but when it comes to code, we use 0-based indexing.
