### ISSUE TITLE
support font changing

### ISSUE THREAD

**Issue by zerone0x** [ahrm/sioyek#706]

**Comment by xissshawww** [comment]
Yes, could sioyek support changing font when we reading a ePub? or could we configure it inside config files? It would be more elegant and flexible if this is supported. Thank you!

**Comment by ahrm** [comment]
Added support for epub font size and css in development branch:
```
epub_css *{color: red; font-family: "Times New Roman"}
epub_font_size 10
```

**Comment by httpsrichard** [comment]
> Added support for epub font size and css in development branch:
> 
> ```
> epub_css *{color: red; font-family: "Times New Roman"}
> epub_font_size 10
> ```

I noticed that this isn't documented. Is it a deliberate decision?

**Comment by ahrm** [comment]
The documentation is not updated for the development branch (it is for the main branch).
