### ISSUE TITLE
Remap default click options

### ISSUE THREAD

**Issue by Squirreljetpack** [ahrm/sioyek#707]
For example, on mac, cmd+click is middle click. When I want to copy some text, I often accidentally open a browser searching it. It would be nice to remap middle click, right click and other modifier clicks, not just grant them extra functionality.

**Comment by ahrm** [comment]
Added `right_click_command` and `middle_click_command` in https://github.com/ahrm/sioyek/commit/69a714eae5c15f599bbe2d8ca49c833106abc3b4.
