### ISSUE TITLE
Easier page navigation | Slide mode

### ISSUE THREAD

**Issue by Animaly0** [ahrm/sioyek#712]
I really love your project, it really helps me a lot, especially being able to mark/focus line as I'm reading.

Because this project is focus on scientific research, I was wondering why it was so difficult to use it to present my slides.
By default, going to the next page, you have to hold Ctrl and pagedown … It's pretty easy to remember but it isn't really the closest things on any keyboard layout and having to hold two keys during a talk isn't really the best.

I was wondering if we couldn't make it so we enter a Slide mode, and have specific keyboard shortcuts in this mode where we could use the arrows to change slides instead of holding Ctrl + pagedown.

Hoping I made myself understable <3

**Comment by ahrm** [comment]
We already have a `toggle_presentation_mode` that does that.

**Comment by Animaly0** [comment]
omg I'm terribly sorry, you're perfectly right.
I completely missed it in the doc.
Great job <3
