### ISSUE TITLE
How can 2 pages be shown side by side?

### ISSUE THREAD

**Issue by csdvrx** [ahrm/sioyek#713]
It may be very basic, but I can figure out how to put the current and the next page side-by-side on a landscape screen.

It is possible, while cutting the margins so the screen is fully used for displaying content?

**Comment by ahrm** [comment]
It is not possible.

**Comment by csdvrx** [comment]
Could it be added as a feature? Even without cutting the margins, it could help reduce clicking/keying to move to the next page, thus increasing concentration on the material being read.

**Comment by ahrm** [comment]
Maybe in the future. Currently I am working on other features though so it won't be soon.

**Comment by ibehnam** [comment]
There's an extension that supposedly does that but I wasn't able to run the extensions on macOS.

**Comment by ahrm** [comment]
Added `toggle_two_page_mode` in the development branch.
