### ISSUE TITLE
Warning: invalid command (key:d); resetting to root with `screen_down d`

### ISSUE THREAD

**Issue by ashprice** [ahrm/sioyek#716]
I want to configure `screen_up` and `screen_down` to be operated with the `u` and `d` keys respectively. I have tried to do this with both:

```
screen_down <d>
screen_up <u>
```

and

```
screen_down d
screen_up u
```

In both cases, I get similar warnings printed into the terminal:

```
Warning: invalid command (key:d); resetting to root                                update)
```

In both cases, screen_up works, though it produces the same message, but screen_down doesn't work. I have no idea why this might be - to my knowledge there isn't any key in my config that conflicts, and I couldn't see such a case in the default bindings (maybe I missed it?)

Given I see previous issues opened that referred to locale issues, my `locale` is:
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

Thanks for any pointers, let me know if there's any further info I can provide.

**Comment by ahrm** [comment]
Can you share your full `keys_user` and `prefs_user` files?

**Comment by ahrm** [comment]
Closing because no response.
