### ISSUE TITLE
PDFs don't render (or crashes) unless executed with root privileges

### ISSUE THREAD

**Issue by mactemporal** [ahrm/sioyek#717]
Hello,
The rendered PDF is entirely white. I don't know if it's relevant but it seems to happen with really large documents like for thousands of pages. But with `sudo` even the thousand-page one renders normally.

Installed via [sioyek AUR](https://aur.archlinux.org/packages/sioyek) on Arch. Thank you for your time!

**Comment by mactemporal** [comment]
After executing with sudo privileges, it prompts :
```
shader_path: /usr/share/sioyek/shaders
Creating shared memory block...
Shared memory already exists: this is a secondary application.
Secondary application attaching to shared memory block...
Secondary application cannot attach to shared memory block.
Secondary application successfully attached to shared memory block.
Secondary application cannot connect to IPC server.
Socker error:  QLocalSocket::ServerNotFoundError
```
After reboot, I am able to render little PDFs but some still don't.

**Comment by ahrm** [comment]
Does it happen with the official appimages here? https://github.com/ahrm/sioyek/releases/tag/v2.0.0

**Comment by mactemporal** [comment]
Thanks for answering. The PDFs (even the big ones) render properly with the provided AppImage. I will try the AUR release of the AppImage.

After trying the AUR with the AppImage, it works! Thank you very much! (
Best document viewer for me)
