### ISSUE TITLE
Useless binary when compiled from source

### ISSUE THREAD

**Issue by KoshulaDora** [ahrm/sioyek#722]
Salam, 

I have followed the installation directions to letter (and had to install an extra package called `qt3d5-dev`) but after compiling with build_linux.sh, it stops at some point and the resulting `./sioyek` binary is incapable of registering the shortcuts, opening pdfs, and basically doing anything beside being a black square on screen.  

My distro is Pop OS 22.04 (Essentially Ubuntu 22.04 packages)  and there are no extra mupdf installed. The script stops at this point 

```
g++ -Wl,-O1 -o sioyek book.o config.o database.o document.o document_view.o input.o main.o main_widget.o pdf_renderer.o pdf_view_opengl_widget.o checksum.o new_file_checker.o coordinates.o sqlite3.o ui.o path.o utils.o synctex_parser.o synctex_parser_utils.o RunGuard.o OpenWithApplication.o moc_pdf_renderer.o moc_RunGuard.o moc_OpenWithApplication.o   -ldl -Lmupdf/build/release -lmupdf -lmupdf-third -lmupdf-threads -lharfbuzz -lz /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt53DInput.so /usr/lib/x86_64-linux-gnu/libQt53DCore.so /usr/lib/x86_64-linux-gnu/libQt5OpenGLExtensions.a /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread 
```

`echo $status` returns 1, which means an error happened at some point but the output never mentions it. (The specific error seems to mean operation not permitted but running with `sudo` also returns same error)

The rest of the requirements like Qmake using QT 5 and libharfbuzz-dev being installed are also satisfied.

**Comment by ahrm** [comment]
Note that you need to run the binary in the `build` directory not the executable in the root directory.

**Comment by KoshulaDora** [comment]
There is no such directory post and pre-script as far as I see.

**Comment by ahrm** [comment]
Okay it appears that the culprit was this PR: https://github.com/ahrm/sioyek/pull/709. I think `rm` fails if the build directory doesn't exist so we stop the build process and don't create the `build` folder. For now you can delete `set -e` line from `build_linux.sh` and re-run it.

**Comment by KoshulaDora** [comment]
It worked.  Thank you.
