### ISSUE TITLE
Extracted annotations don't follow a logical order of the text

### ISSUE THREAD

**Issue by overclockworked64** [ahrm/sioyek#723]
I have a multi-column PDF document I want to highlight. However, when I extract annotations, they come in the wrong order relative to the logical order of the text. To illustrate, if I highlight something in the left column near the bottom of the page, and highlight something in the right column near the top of the page, the second highlight is going to appear first when extracted.

**Comment by ahrm** [comment]
Using `extract_highlights` extension?

**Comment by overclockworked64** [comment]
The way I checked this was to use the `extract_annotations` command, then used the `PDF Highlights` extension in Obsidian to extract the highlights.

`extract_highlights` extension sort of works, but it seems to encompass other text, too, not just what was annotated. Is this expected behavior?

**Comment by ahrm** [comment]
We don't have an `extract_annotations` command, is it an extension?  

> Is this expected behavior?

Yes, we include some of the context.

**Comment by overclockworked64** [comment]
Yeah, I meant the `extract_annotations` extension.

I'm using [this paper](https://static1.squarespace.com/static/56f5c928356fb063f3e181fb/t/6080cf76248c3052ce65b2cf/1619054455011/Zerwas%2526Ford_2021.pdf).

The parts I'm highlighting are on the first page.

Left column:

>Despite a common ethos that happiness is good for you, much evidence suggests that valuing happiness to an extreme degree can backfire such that the more people value happiness, the less happy they are.

Right column:

>Taken together, this complementary approach across levels of analysis helps researchers make better predictions about when, why, and for whom the pursuit of happiness is most likely to backfire and when it might succeed.

Thanks.

**Comment by ahrm** [comment]
There are no extensions on a fresh install of sioyek. Do you mean `embed_annotations` command?

**Comment by overclockworked64** [comment]
Yeah, `embed_annotations` it is. Sorry for the confusion.

**Comment by ahrm** [comment]
We add the highlights in the chronological order that they were added to page, I think this is an Obsidian bug rather than sioyek bug.
