### ISSUE TITLE
new user issues

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#727]
I have switched to sioyek from zathura and I have a few things I'd like to change/configure:

1. How can remove the padding/margin at the top and at the bottom of any file.  
1. Is there a way I can doodle on the pdf? Or maybe and notes to highlights? It can really useful for working with research papers and writing interpretations.
1. Plus when I press ":" it takes up the entire screen and display all the commands. Is there a way I can reduce the dimensions of this command window (I tired changing the size of helper_window in prefs_user.config but it didn't seem to have an effect). Also I want it display suggestions only after I start typing and not an entire list.

**Comment by ahrm** [comment]
1. There is no padding, see https://github.com/ahrm/sioyek/issues/299.
2. There is no built-in way, but we have an extension that allows you to write text here: https://github.com/ahrm/sioyek-python-extensions#-add_text
3. There is no way to do that currently.

**Comment by nikinbaidar** [comment]
Thank you.  I'd also like to add when I update `keys_user.config` file and launch sioyek from my terminal I get all sorts of warning messages. Is there a way I can turn off warnings and in fact fork the sioyek to the background so that my terminal is usable. I didn't see this happening on your videos where you're using Windows. I'm on Linux.

**Comment by ahrm** [comment]
You can do something like this:
```
sioyek > /dev/null 2>&1
```
So sioyek output doesn't appear in your terminal.

**Comment by nikinbaidar** [comment]
Thank you for pointing that out. That should've crossed my mind. 

> Moreover, when I search for a piece of text and hit enter, it waits for me to press n or N instead of directly jumping to the page where it finds the first instance of the text. I don't know if this is intended but as a new user I think this is very counter-intuitive. 

What about this part? I also have one last question, does it have support for epubs and djvu files? I've just started to use it since yesterday and I've already liked it a lot but support of epub and djvu is something I feel it is missing out on.

**Comment by ahrm** [comment]
The search behavior is intended.
We do support epub (no reflowing though) but we don't support djvu.

**Comment by nikinbaidar** [comment]
Do you have any plans of supporting it in coming releases?

**Comment by ahrm** [comment]
No.

**Comment by nikinbaidar** [comment]
Thanks for answering all of my questions.
