### ISSUE TITLE
Cannot find Sioyek in "Open with" in Manjaro

### ISSUE THREAD

**Issue by kaiwizz** [ahrm/sioyek#73]
I can open Sioyek from the application Launcher. But when I try to open a file with Sioyek, I do not see  it listed as an option. I vaguely rememeber that I was able to open pdfs with sioyek this way in the past. Any suggesions?

I uninstalled and installed sioyek just in case but it did not work.

**Comment by kaiwizz** [comment]
Also, I do not see sioyek listed in `/usr/bin`

**Comment by Endle** [comment]
How did you install sioyek? By AUR?

**Comment by Endle** [comment]
How about @randomn4me how is the author of that AUR?

**Comment by kaiwizz** [comment]
I have not contacted them yet but I just uninstalled the AUR package and built it as it is mentioned in the README section. It is running and all my keybindings are working fine. But the issue persists, I cannot find Sioyek in the "Open with" section. I think it should be a simple fix but I am not quite sure what it should be. Sioyek should make a folder in `/usr/bin/` folder ?

**Comment by Maxoz99** [comment]
What desktop environment are you using? I could not reproduce the problem on KDE also installed via pamac. Sioyek does not make a folder in `/usr/bin/` but puts its executable there as it should.

**Comment by Maxoz99** [comment]
Found a workaround based on [https://itsfoss.com/add-application-list-open-applications-ubuntu-1310/](https://itsfoss.com/add-application-list-open-applications-ubuntu-1310/).

Open the `sioyek.desktop` file at `/usr/share/applications` and change `Exec=sioyek` to `Exec=sioyek %F`.
After that, you want to run `sudo update-desktop-database`.

**Comment by randomn4me** [comment]
I think this discussion should be moved to the AUR package threat (https://aur.archlinux.org/packages/sioyek-git/) since it is a system specific problem, no bug in the program itself.

But to make sure everyone is on the same page: The AUR package indeed stores the executable `sioyek` in `/usr/bin`. Just run `pacman -Ql sioyek-git` in your commandline, which outputs the following on my system:

```
sioyek-git /etc/
sioyek-git /etc/sioyek/
sioyek-git /etc/sioyek/keys.config
sioyek-git /etc/sioyek/prefs.config
sioyek-git /usr/
sioyek-git /usr/bin/
sioyek-git /usr/bin/sioyek
sioyek-git /usr/share/
sioyek-git /usr/share/applications/
sioyek-git /usr/share/applications/sioyek.desktop
sioyek-git /usr/share/icons/
sioyek-git /usr/share/icons/sioyek-icon-linux.png
sioyek-git /usr/share/licenses/
sioyek-git /usr/share/licenses/sioyek-git/
sioyek-git /usr/share/licenses/sioyek-git/LICENSE
sioyek-git /usr/share/man/
sioyek-git /usr/share/man/man1/
sioyek-git /usr/share/man/man1/sioyek.1.gz
sioyek-git /usr/share/sioyek/
sioyek-git /usr/share/sioyek/shaders/
sioyek-git /usr/share/sioyek/shaders/dark_mode.fragment
sioyek-git /usr/share/sioyek/shaders/debug.fragment
sioyek-git /usr/share/sioyek/shaders/highlight.fragment
sioyek-git /usr/share/sioyek/shaders/simple.fragment
sioyek-git /usr/share/sioyek/shaders/simple.vertex
sioyek-git /usr/share/sioyek/shaders/undendered_page.fragment
sioyek-git /usr/share/sioyek/shaders/unrendered_page.fragment
sioyek-git /usr/share/sioyek/shaders/vertical_bar.fragment
sioyek-git /usr/share/sioyek/shaders/vertical_bar_dark.fragment
sioyek-git /usr/share/sioyek/tutorial.pdf
```

I'm going to check, whether the executable is listed in the `open-with` dialog in the future (currently I'm not sure how to force it).

Cheers,
randomn4me

**Comment by kaiwizz** [comment]
> Open the `sioyek.desktop` file at `/usr/share/applications` and change `Exec=sioyek` to `Exec=sioyek %F`. After that, you want to run `sudo update-desktop-database`.
Thank you so much, that solved my problem, I think I should have realized that it is gnome issue!

> Followup: I tried to replicate the behaviour using thunars _Open With_ option and selected _Open with other application_, which lists sioyek. Hence, I'm not able to replicate the problem.

I could see it before but  somehow it dissapeared after some update. you can try removing that %F from the sioyek.desktop file. that might recreate the issue.
