### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by yondchang** [ahrm/sioyek#730]
Hi all,

I followed exactly the instruction but got the follow build error after running ./build_linux.sh (with Ubuntu 20.04)

make: *** No targets specified and no makefile found.  Stop.

Any idea?

thanks.

**Comment by ahrm** [comment]
Does qmake succeed? What happens when you run
```
qmake "CONFIG+=linux_app_image" pdf_viewer_build_config.pro
```
?

**Comment by yondchang** [comment]
thanks for your fast response

qmake --version does succeed
![image](https://github.com/ahrm/sioyek/assets/8464964/d3b5b0e4-6400-442d-8045-d17a7c1f663a)

but when I run your above command it errors out
![image](https://github.com/ahrm/sioyek/assets/8464964/d4b3f7e1-1842-4855-8913-b8de1e0d9f23)

**Comment by ahrm** [comment]
I think you need to install `qt3d5-dev` or something (the name of package is different for different distributions.).

**Comment by yondchang** [comment]
thanks, now running "qmake "CONFIG+=linux_app_image" pdf_viewer_build_config.pro" finished without any error but no other output as well.

running ./build_linux.sh still gives the same error
"make: *** No targets specified and no makefile found.  Stop."

**Comment by ahrm** [comment]
Hmmm what happens when you run `make` manually?

**Comment by yondchang** [comment]
![image](https://github.com/ahrm/sioyek/assets/8464964/069408e4-04de-4e16-8fb5-73583623706f)

**Comment by ahrm** [comment]
Did you pass `--recursive` when cloning the repo?

**Comment by yondchang** [comment]
aha, that must be it, let me reclone and try again, thanks a lot

**Comment by yondchang** [comment]
got a new error
![image](https://github.com/ahrm/sioyek/assets/8464964/3b145b22-ac51-49e2-9029-276cf4ad176b)

**Comment by yondchang** [comment]
fixed after sudo apt-get install libxi-dev libxrandr-dev

**Comment by ayush-india** [comment]
Thanks man
