### ISSUE TITLE
Navigation via TOC freezes sioyek in latest rev

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#733]
I think this is a regression in recent revisions but I'm not sure when it started happening and it definitely doesn't happen in all PDFs: navigating to different sections of the file via sioyek's toc causes it to freeze. I don't see any errors in stdout. `q` does work for exiting but only for a while, if I keep choosing different sections in toc nothing happens and eventually even `q` stops working. I'm sure the links in the PDFs do actually work because they work in Zathura. Is this a known issue?

**Comment by ahrm** [comment]
Which version of sioyek are you using? (are you using the official appimage or some other package?)

**Comment by mil-ad** [comment]
I'm using 2.0.0 via `sioyek-git` [package on AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sioyek-git)

**Comment by ahrm** [comment]
I think that package uses an incompatible version of `libmupdf`, can you reproduce the issue on the appimage package?

**Comment by mil-ad** [comment]
ah, you're right. Doesn't happen with the appimage!

**Comment by mil-ad** [comment]
I'll try fixing the aur package

**Comment by josephs07** [comment]
same issue. I am using v2.0.0 from [nix pkgs](https://search.nixos.org/packages?channel=unstable&show=sioyek&from=0&size=50&sort=relevance&type=packages&query=sioyek)

**Comment by mil-ad** [comment]
@josephs07 there's [sioyek-git](https://aur.archlinux.org/packages/sioyek-git) on Arch AUR that has patch files to make it work with latest mupdf. You might find them useful

**Comment by josephs07** [comment]
I'm on NixOS, can't use AUR. I'll just  make do with appimage for now. Thanks anyway.
