### ISSUE TITLE
At full support same as readline Vi mode when typing

### ISSUE THREAD

**Issue by Archie-2021** [ahrm/sioyek#738]
When typing any thing (a command or fuzzy finding) only `<C-u>` of readline Vi keybindings is currently supported. Add support for `<C-w>` and `<C-h>` for removing the last word and character (respectively) too please.

Thank you very much

**Comment by ahrm** [comment]
Added in https://github.com/ahrm/sioyek/commit/c9c99fe961fa9fbac224b7f083866d3fa7ca06e2 in development branch. Works only when `emacs_mode_menus` config is set.

**Comment by Archie-2021** [comment]
> Added in [c9c99fe](https://github.com/ahrm/sioyek/commit/c9c99fe961fa9fbac224b7f083866d3fa7ca06e2) in development branch. Works only when `emacs_mode_menus` config is set.

Why not in vi keybinding?

**Comment by ahrm** [comment]
We already had this config which supported `<C-h>`. I don't want to add a thousand different options which only slightly differ.
