### ISSUE TITLE
White space in text copied to clipboard is replaced with invalid characters

### ISSUE THREAD

**Issue by maxigaz** [ahrm/sioyek#739]
While viewing [the PDF version](https://github.com/swaroopch/byte-of-python/releases/download/vadb91fc6fce27c58e3f931f5861806d3ccd1054c/byte-of-python.pdf) of A Byte of Python, highlight any part of the text with the mouse, copy it to the system clipboard with Ctrl-c, and paste it in a text editor like Neovim. In the pasted passage, all white space is replaced with invalid characters.

For example, let's say I want to copy this snippet from page 28:

```py
# Filename : var.py
i = 5
print(i)
i = i + 1
print(i)
```

After I paste it, it will turn into this:

```
#�Filename�:�var.py i�=�5 print(i) i�=�i�+�1 print(i) 
```

I can only reproduce it with this particular PDF file, with Sioyek 2.0.0 on Arch Linux.

If I open the same document with Zathura, I can copy and paste the same text without any issues.

**Comment by ahrm** [comment]
There seems to be a Unicode character with value 65533 (REPLACEMENT CHARACTER) embedded in this document in various places. I don't know why it doesn't show up in other PDF viewers. I have handled it now by replacing it with a space. It will be released when I push the next version of sioyek.

**Comment by maxigaz** [comment]
Thank you for looking into it!

Is it also going to handle new lines correctly? As you can see in the original post, newline characters become regular spaces, which also happens only with this particular PDF file and Sioyek (but not Zathura).

**Comment by ahrm** [comment]
No it doesn't. This is weird, I will have to look into this further.

**Comment by Dale-Muccignat** [comment]
I have a 'somewhat' similar issue where a particular pdf I'm reading copy/pastes invalid symbols. Might not be relevant here so sorry if that's the case but I found this to be related as it was happening on zathura as-well: https://superuser.com/questions/1124583/text-in-pdf-turns-gibberish-on-copying-but-displays-fine

**Comment by ahrm** [comment]
I can't download the PDF provided in the link.

**Comment by ahrm** [comment]
This should be fixed in the development branch.
