### ISSUE TITLE
[Bug] Crash when opening files with certain names

### ISSUE THREAD

**Issue by vxld100** [ahrm/sioyek#744]
This is the first time I write an issue on github, so please forgive me if I miss some things.

The issue I am encountering is that files with certain names cannot be opened twice. As a matter of fact when files with certain names are opened, trying to open any other file in a new window causes sioyek to crash. One such file is for example named "#3 FS22_Prüfung Finanzielle Führung-EN". It's clear it's the name of the file which is the issue, since I can recreate the problem with a blank pdf with the same name (and this isn't an isolated instance either).

The issue for this particular file seems to be caused by the "ü" as I can get other files that sioyek would normally be able to treat like expected to be affected by this bug by simply adding it somewhere in the name.

The error message I get is the following:

terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: Cannot convert character sequence: Invalid or incomplete multibyte or wide character
Aborted

I am using voidlinux with kernel version 6.1.31_1, and sioyek 2.0.0. However, this problem has NOT appeared with the latest release or any recent updates on my system. It's been going on for a while now.

**Comment by OopsYao** [comment]
Can confirm with AUR sioyek-appimage 2.0.0-2, but this does NOT happen with AUR sioyek 2.0.0-3. Actually other unicode characters like CJK and EN DASH `–` (U+2013) can cause this problem as well. But it seems like that it was fixed as mentioned in #393.
