### ISSUE TITLE
issue with syncing shared.db from linuxto windows

### ISSUE THREAD

**Issue by imenyoo2** [ahrm/sioyek#749]
i moved my pdfs and `shared.db` to windows, most of my pdfs annotations and bookmarks synced properly, i just have to open the pdf and close sioyek, and when i open it again it import my bookmarks and annotations for that pdf, but however, one specific pdf didn't, i tried importing the `json` file generated from export command instead and that didn't work either, i also tried changing the name of that pdf and modifying the `json` file and that didn't work eather
## questions:
- what maybe happening here ?
- is there other ways to sync annotations other then what i tried?

any help would be appreciated, thank you 🙏

**Comment by ahrm** [comment]
If the PDF is not private, can you share the PDF and the exported json so I can test it?

**Comment by imenyoo2** [comment]
it's copyright protected, it's a pdf version of a textbook

**Comment by ahrm** [comment]
Another possibility is that maybe you have modified the PDF file before sharing it to the other computer? (e.g. maybe by adding a native PDF bookmark)?
Since sioyek uses file hashes to identify files and modifying them changes the hash.
