### ISSUE TITLE
'Keyboard only use' possible?

### ISSUE THREAD

**Issue by ju-sh** [ahrm/sioyek#750]
Hi. Thanks for making sioyek.

Is it possible to select and highlight text using only the keyboard?

I used to use zathura and was looking for a way to use sioyek without having to use the mouse.

**Comment by ahrm** [comment]
Yes, you can select text using `keyboard_select` command, then you enter the labels corresponding to the begin and end of selection and press enter. We also have some other `keyboard_` commands to perform other operations that usually involve mouse.

**Comment by ju-sh** [comment]
Thank you. Could do that.

I had another 'keyboard' use case.

Would it be possible to open a new file without needing a gui file explorer popup?

Maybe from the command mode, with auto-completion for available files in current directory as in a shell?

Right now I'm opening a new file with the `o` shortcut.

Pardon me if it's already mentioned in the documentation.

**Comment by ahrm** [comment]
Yes, using `open_document_embedded` commands.

**Comment by ju-sh** [comment]
I am using the AppImage version of sioyek.

I tried placing `keys_user.config` file inside my `~/.config/sioyek` but it doesn't seem to have effect.

Doing `keys` in command mode opens a file at `/tmp/.mount_Sioyekbyyeke/usr/bin`

Tried `reload` and `reload-config` from an already open session too.

Is this how we should reload?
Or could it be that I messed up the config file?

**Comment by ju-sh** [comment]
Is there a way to go to a specific page in the pdf without being prompted?

Like `3-home` going to the 3rd page?

Instead of pressing `home` and entering 3 on being prompted?

Not much of a difference, but got familiar to that from vim... 😅

**Comment by ju-sh** [comment]
And is there a way to expand the selected block of text once it has been selected using `v`?

**Comment by ahrm** [comment]
> Is there a way to go to a specific page in the pdf without being prompted?

Yes, you can do `3gg` exactly like vim.

> And is there a way to expand the selected block of text once it has been selected using v?

Not currently. (This is already implemented and will be released with the next version of sioyek).

**Comment by ju-sh** [comment]
I changed the key to quit sioyek from q to C-q to make myself less prone to accidentally closing it.

C-q is working, but q has not been unbound and still closes sioyek. Is there a way to unbind existing shortcuts?

**Comment by ju-sh** [comment]
And the right way to put changes in the config files into effect is to run `reload-config` right?

**Comment by ahrm** [comment]
> C-q is working, but q has not been unbound and still closes sioyek. Is there a way to unbind existing shortcuts?

You can bind to to noop:
```
noop q
```

> And the right way to put changes in the config files into effect is to run reload-config right?

Most configs reload automatically when you change the file, a few of them require `reload-config`.

**Comment by ju-sh** [comment]
Regarding the overview feature for references in pdfs, square bracket style of citations is okay right?

It is working for me in other pdfs, but for one of them, it isn't.

This is the link to the file: https://repository.upenn.edu/cgi/viewcontent.cgi?article=1248&context=cis_papers

For example, in the last paragraph of page 4, overview is showing up blank when right-clicking on the `[19]`.

Is it because the pdf is ill-formed or something?

**Comment by ahrm** [comment]
The smartjump feature is a heuristic and doesn't work for all documents. It doesn't work with the document format you provided because the references in the reference section are not clearly marked with brackets.

**Comment by ju-sh** [comment]
Ah.. okay.

Thanks so much for your guidance! I got sioyek set up the way I want now (as in vim-like 😃).

And thank a lot for your work on sioyek.

**Comment by ju-sh** [comment]
Shall I close this issue?

**Comment by ahrm** [comment]
> Is it possible to have an explicit cursor in the text of the pdf? Which can be moved around with the keyboard?

I have added this feature (not available in public commits yet) and it will be released with the next version of sioyek.

> Currently I do toggle_custom_color each time I open sioyek. Is there a way to have this custom color as default?

See the documentation: https://sioyek-documentation.readthedocs.io/en/latest/configuration.html#startup-commands

**Comment by ahrm** [comment]
> Is there a way to use vim keys for that? jklh?

You can use <C-j> and <C-l>.

> And do pdfs once opened stay loaded in memory?

Yes.

> If that's the case, is there a way to explicitly unload a pdf which was opened earlier but is no longer needed?

Not currently but it will be in the next version of sioyek.

**Comment by ahrm** [comment]
> Is there an option to have j instead of <C-j>? Or would it conflict with something?

Typing in menus searches them, so we can't use simple characters.
