### ISSUE TITLE
How to cross compile to arm7/arm64?

### ISSUE THREAD

**Issue by jaum20** [ahrm/sioyek#754]
It is possible to compile this to run on a raspberry?

**Comment by viccie30** [comment]
It should be. Raspberry Pi OS is based on Debian and Debian's packages [build successfully on all 3 types of ARM supported by Debian](https://buildd.debian.org/status/package.php?p=sioyek). Sioyek was however not included in bullseye, the version of Debian that Raspberry Pi OS is currently based on. It might be possible to backport the current Debian package, but I have not tried that myself.

**Comment by viccie30** [comment]
You can also use Debian or another distribution that includes sioyek instead of Raspberry Pi OS if you don't want to compile sioyek yourself.

**Comment by LiamKearn** [comment]
Nixpkgs has an aarch64 output for sioyek: https://search.nixos.org/packages?channel=23.05&show=sioyek&from=0&size=50&sort=relevance&type=packages&query=sioyek.
