### ISSUE TITLE
compilation terminated due to fatal error for `GL/gl.h: No such file or directory`

### ISSUE THREAD

**Issue by prikarsartam** [ahrm/sioyek#755]
Every time I build sioyek in my `Ubuntu 22.04.2 LTS` I receive the following error 

```In file included from thirdparty/freeglut/include/GL/freeglut.h:17,
                 from platform/gl/gl-app.h:36,
                 from platform/gl/gl-annotate.c:23:
thirdparty/freeglut/include/GL/freeglut_std.h:143:13: fatal error: GL/gl.h: No such file or directory
  143 | #   include <GL/gl.h>
      |             ^~~~~~~~~
compilation terminated.
make: *** [Makefile:115: build/release/platform/gl/gl-annotate.o] Error 1```


And the compilation terminates. What to do here?

**Comment by ahrm** [comment]
Does this help?:
```
apt-get install libmesa-dev
```

**Comment by Stradichenko** [comment]
Hi;
I have been having the same issue trying to build it in `Linux fedora 6.4.14-200.fc38.x86_64 `.
This is the last part of the output:

```
...
In file included from thirdparty/freeglut/include/GL/freeglut.h:17,
                 from platform/gl/gl-app.h:36,
                 from platform/gl/gl-annotate.c:23:
thirdparty/freeglut/include/GL/freeglut_std.h:144:13: fatal error: GL/glu.h: No such file or directory
  144 | #   include <GL/glu.h>
      |             ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:115: build/release/platform/gl/gl-annotate.o] Error 1
```

Rergarding the libmesa-dev library, is not found on the dnf package manager; tried with `Mesa-libOSMesa-devel` but no luck.

**Comment by MithicSpirit** [comment]
On Arch Linux, `GL/gl.h` and `GL/glu.h` are provided by the packages `libglvnd` and `glu`, respectively. Maybe you can try looking for packages with similar names in your own distros? Or, if your distro has a way to search through repo packages for specific files (like Arch's `pkgfile`) you can try that too (although you'll probably get some false positives since it seems like some libraries vendor those headers).

**Comment by ahrm** [comment]
I am closing this issue because it is not really a sioyek issue. You need to install some library which provides these headers, it is usually `libmesa-dev` but can be different in different linux package managers. You need to google it.

**Comment by lukeflo** [comment]
> On Arch Linux, `GL/gl.h` and `GL/glu.h` are provided by the packages `libglvnd` and `glu`, respectively. Maybe you can try looking for packages with similar names in your own distros? Or, if your distro has a way to search through repo packages for specific files (like Arch's `pkgfile`) you can try that too (although you'll probably get some false positives since it seems like some libraries vendor those headers).

Its the same for Void Linux. `libglvnd` and `glu` must be installed
