### ISSUE TITLE
File occupied after being closed

### ISSUE THREAD

**Issue by YijunYuan** [ahrm/sioyek#758]
Platform: Windows 11

Step to reproduce:

1. Set `should_launch_new_window` in `prefs.config` to 1 (or just use `new_window` command after step 2)
2. Open `A.pdf`
3. Open `B.pdf`
4. Close `A.pdf`
5. Delete `A.pdf` ----> **This Action Cannot Be Completed Because the File Is Open in sioyek.exe** (This message is translated from my Windows system in Chinese)

If I close both `A.pdf` and `B.pdf`, then they can be deleted as expected.

This should be some kind of thread-related issue.

**Comment by ahrm** [comment]
This is by design, we keep the documents you have visited in memory because the back/forward feature works across documents, in the next version of sioyek there is a feature where you can manually unload a document if you want.
