### ISSUE TITLE
command `keys` does not open file `keys.config`

### ISSUE THREAD

**Issue by zb-zombie** [ahrm/sioyek#761]
Command `keys` does not open file `keys.config`. Also commands `keys_user`, `prefs`, `prefs_user` do not open corresponding files.

I tried creating `prefs_user.config` file in the `~/.config/sioyek/` folder manually and writing `super_fast_search 1` in it, but it didn't work.

How can I solve this issue or how can I know where to place the `prefs_user.config` so that sioyek can load it.

> Release: [sioyek-release-windows.zip](https://github.com/ahrm/sioyek/releases/download/v2.0.0/sioyek-release-windows.zip) of [v2.0.0](https://github.com/ahrm/sioyek/releases/tag/v2.0.0)

**Comment by ahrm** [comment]
It is possible that sioyek doesn't have the permission to open the files. You can always place them here:
`C:/ProgramData/sioyek/prefs_user.config` or `C:/Users/<user>/AppData/Roaming/sioyek/prefs_user.config`.

**Comment by zb-zombie** [comment]
It works. Thank you!

**Comment by prosoitos** [comment]
I am also unable to open any of the key or config files. In my case, it is not a permission problem.

How does sioyek open the files? (What command does it run in the background? Does it open in the default text editor?).

Thanks!

**Comment by ahrm** [comment]
It opens the file using qt's functions which use the default text editor. I think if no text editor is set for `.config` files it might fail on some operating systems.

**Comment by prosoitos** [comment]
I have:

```sh
export VISUAL="emacsclient"
```

in my .xinitrc and normally all applications can read this default.

I am not sure how to set more explicitly for sioyek.

(I am on Arch Linux).
