### ISSUE TITLE
Dynamic config file reloading

### ISSUE THREAD

**Issue by jghauser** [ahrm/sioyek#767]
Thanks a lot for this super useful piece of software!

Is it possible to have sioyek dynamically reload the config file when it changes (that is, without restarting the application)? I saw there's a reload_config command, but I'm not sure how to get it to work (nothing seems to change when I run the command), and I don't seem to see any documentation about it.

On my system, I switch between light and dark mode by writing changes to various config files and then have these changes be picked up by the various applications. I'd love for sioyek to either do this automatically or to be able to run a `reload_config` command (if the command indeed does what I thought it might/ought to be doing).

**Comment by ahrm** [comment]
This is already the case (except for a handful of configs which do require a reload).

**Comment by jghauser** [comment]
That's great to hear, thanks! Now I just need to figure out why it doesn't seem to be happening on my machine. I can see that the values in the config file change, but somehow this isn't being picked up?
Here's my `prefs_user.config` (light mode):
```
background_color 0.996094 0.996094 0.996094
custom_background_color 0.996094 0.996094 0.996094
custom_text_color 0.300781 0.300781 0.296875
font_size 15
horizontal_move_amount -1
new_command _embed_annotations_in_file embed_annotations_in_file.py %{sioyek_path} %{local_database} %{shared_database} %{file_path}
should_launch_new_window 1
status_bar_color 0.875000 0.875000 0.875000
status_bar_font_size 15
status_bar_text_color 0.300781 0.300781 0.296875
ui_font Noto Sans
```
and dark mode:
```
background_color 0.113281 0.121094 0.128906
custom_background_color 0.113281 0.121094 0.128906
custom_text_color 0.769531 0.781250 0.773438
font_size 15
horizontal_move_amount -1
new_command _embed_annotations_in_file embed_annotations_in_file.py %{sioyek_path} %{local_database} %{shared_database} %{file_path}
should_launch_new_window 1
status_bar_color 0.156250 0.164062 0.179688
status_bar_font_size 15
status_bar_text_color 0.769531 0.781250 0.773438
ui_font Noto Sans
```

Do you have any idea what might be going wrong? I'm on NixOS (unstable, sioyek 2.0.0), and the config file is a sym link to a file my NixOS config generates, just in case that might matter...

**Comment by ahrm** [comment]
> config file is a sym link to a file my NixOS config generates

I think this might be the culprit. Perhaps we can't handle symlinks?

**Comment by jghauser** [comment]
I'll check in a bit and report back!

**Comment by jghauser** [comment]
You are exactly right, the issue is with the symlink. It would be great if sioyek could follow them to their targets and check whether these get modified. Thanks for the quick debugging! :)

**Comment by jghauser** [comment]
Just a quick follow-up. I think the solution here isn't that sioyek should monitor the modification of the target file, but rather that sioyek doesn't monitor the modification of the link. In my case, when switching between dark and light mode, the link gets updated to link to a different target but the target files themselves aren't modified.

**Comment by ahrm** [comment]
We use `QFileSystemWatcher` to monitor changes and this seems to be the relevant bug: https://bugreports.qt.io/browse/QTBUG-15522. Which hasn't been fixed in the past 14 years so it is unlikely to be fixed soon. I am closing this issue because it is a byproduct of the qt bug and will be automatically fixed when the qt bug is fixed.

**Comment by LnLcFlx** [comment]
I think I have a similar issue.
I have
```
source ~/.local/share/colorscheme/renders/.current/sioyek.config
```
in my `prefs_user.config` where `~/.local/share/colorscheme/renders/.current` is a symlink to a folder containing a file `sioyek.config` with my color definitions inside.
When I change the `.current`-symlink to a folder that contains different colors and I do `reload_config` nothing changes.

How can I fix this?

**Comment by srfsh** [comment]
For anyone on the internet, on Linux, I was able to make it work by just overriding the `pref_user.config` using darkman scripts. In the script, you just `cp -f dark.config pref_user.conf` or `cp -f light.config pref_user.config` depending on whether it is in light mode scripts or dark mode scripts. You must specify the same common config in both dark and light config files, and then the custom theme or dark theme. If you use custom theme, make sure you activate it on startup.

The `use_system_theme` option seem to does not work for me. Neither using symlinks to `pref_user.config` or even using `source` with a symlink to one of the dark or light variants (to have rest of the common config in the same place).
