### ISSUE TITLE
Unable to open reverse sync file in the same VScode window

### ISSUE THREAD

**Issue by HuntFeng** [ahrm/sioyek#768]
I am running things on Linux. I use latex workshop in VScode to write & compile tex files, and I would like to configure sioyek as my default pdf reader. 

In my `prefs_user.config` file, I set
```
inverse_search_command code -r -g %1:%2
```
as the document suggests.

In my vscode settings, I set
```json
"latex-workshop.view.pdf.viewer": "external",
  "latex-workshop.view.pdf.external.viewer.command": "/home/huntfeng/sioyek/Sioyek-x86_64.AppImage",
  "latex-workshop.view.pdf.external.synctex.command": "/home/huntfeng/sioyek/Sioyek-x86_64.AppImage",
  "latex-workshop.view.pdf.external.synctex.args": [
    "--inverse-search",
    "code -r -g %1:%2",
    "--reuse-window",
    "--forward-search-file",
    "%TEX%",
    "--forward-search-line",
    "%LINE%",
    "%PDF%"
  ],
```

The top left window is the my tex file, I can successfully open sioyek and view the pdf, foward sync also works fine. However, when I do backward sync, the inverse search command always open vscode in a new window (bottom left). And it seems the new vscode window don't have my vscode configurations.
![Screenshot from 2023-07-17 15-14-10](https://github.com/ahrm/sioyek/assets/33592421/52a62059-0f18-4f2c-a473-2b6f80642264)

Does anyone know what is going on? How to open the reverse sync file in the same window?

**Comment by ahrm** [comment]
Maybe the vscode you use the and vscode that is launched by `code` command are different?

**Comment by HuntFeng** [comment]
Never mind, I solved the problem. Here is my solution.

First I extracted the sioyek AppImage 
```bash
./Sioyek-x86_64.AppImage --appimage-extract
```
This gives me a `squashfs-root` folder with excutable `AppRun` in it. Then I created a symbolic link of the `Apprun` to the `~/.local/bin/` (I believe we can also create a symbolic link to `/usr/bin/`, I just prefer this way)
```bash
ln -s <full-path-to-AppRun> ~/.local/bin/sioyek
```
Now I can directly launch sioyek in command line by typing `sioyek`.

Then I just need to change the `settings.json` of vscode to
```json
"latex-workshop.view.pdf.viewer": "external",
  "latex-workshop.view.pdf.external.viewer.command": "sioyek",
  "latex-workshop.view.pdf.external.synctex.command": "sioyek",
  "latex-workshop.view.pdf.external.synctex.args": [
    "--inverse-search",
    "code -r -g %1:%2",
    "--reuse-window",
    "--forward-search-file",
    "%TEX%",
    "--forward-search-line",
    "%LINE%",
    "%PDF%"
  ],
```

I guess when I run sioyek by calling its AppImage, the environment is a little different. I'm not a linux expert and I only know AppImage is like a container so user can distribute it and run it conveniently because the dependencies are contained in it. Anyway, by doing the above steps, the reverse sync works perfectly :D

**Comment by HuntFeng** [comment]
> Maybe the vscode you use the and vscode that is launched by `code` command are different?

After figuring out the solution, I think the situation is more like "the `code` command launch by sioyek.AppImage is different from the `code` command I used"

**Comment by HuntFeng** [comment]
Just an additional comment, using arguments like `--reuse-window` or `--reuse-instance` partially breaks the synctex.

In my machine, using `--reuse-window` breaks inverse sync, and `--reuse-instance` breaks forward sync.

 By removing both `--reuse-window` and `--reuse-instance`, everything works perfectly
```json
"latex-workshop.view.pdf.viewer": "external",
  "latex-workshop.view.pdf.external.viewer.command": "sioyek",
  "latex-workshop.view.pdf.external.synctex.command": "sioyek",
  "latex-workshop.view.pdf.external.synctex.args": [
    "--inverse-search",
    "code -r -g %1:%2",
    "--forward-search-file",
    "%TEX%",
    "--forward-search-line",
    "%LINE%",
    "%PDF%"
  ]
```
