### ISSUE TITLE
How to increase font size of open_link labels ?

### ISSUE THREAD

**Issue by userrand** [ahrm/sioyek#772]
I do not know if there has been a modification since the version that I'm using, but changing font_size in the user configuration doesn't seem to change the size of the font of the labels when using open_link. 

Also is there an option to change the color of the labels of open_link ?

**Comment by ahrm** [comment]
Currently there is no option to do that. Will probably add it in the next version of sioyek.

**Comment by userrand** [comment]
> Currently there is no option to do that. Will probably add it in the next version of sioyek.

Is there an option to increase the font globally? I have trouble seeing most of the text in the UI.

**Comment by ahrm** [comment]
We have `font_size` and `status_bar_font_size` config options.

**Comment by userrand** [comment]
> We have `font_size` and `status_bar_font_size` config options.

Thank you I think I used the command palette to search for font settings but I should have checked the documentation online instead

**Comment by ahrm** [comment]
This is fixed in the development branch of this repo. Now we have config options for font size and colors of labels.

**Comment by userrand** [comment]
@qadzek perhaps you are using the pre release since for example the option to use letters to select a link looks like it was added on Feb 18, 2023 according to the commit https://github.com/ahrm/sioyek/commit/48d12760a3f8d379a2ce737833a9f939c02af0f2 whereas the latest release is from 2022

**Comment by qadzek** [comment]
> [@qadzek](https://github.com/qadzek) perhaps you are using the pre release since for example the option to use letters to select a link looks like it was added on Feb 18, 2023 according to the commit [48d1276](https://github.com/ahrm/sioyek/commit/48d12760a3f8d379a2ce737833a9f939c02af0f2) whereas the latest release is from 2022

It’s indeed very likely that I was using the pre-release when I posted the comment above. It’s still by far my favorite PDF reader, although a new release would be nice.
