### ISSUE TITLE
When deleting overlapping highlight, give priority to the shortest one

### ISSUE THREAD

**Issue by flabou** [ahrm/sioyek#773]
Sometimes I use two different highlight styles in the same area, because I want to emphasize part of an existing highlight. So I end up in situation where I have overlapping highlight, usually one smaller highlight fully contained within one bigger highlight. 

In that case, I would like the smallest highlight to be deleted first if I click on it. But the current behavior seems to be that the highlight that was added first gets deleted first.

_Here's an example with markdown, where italic would be one style of highlight, **and bold would be another style** of highlight._

I would like to be able to delete only the bold highlight, by clicking on it. I can easily delete the italic highlight because it has non-overlapping area. So it makes more sense to give priority to the inner highlight.

If the highlight is not fully contained, I would give the priority to the smallest length wise, to remain consistent. This rule can be extended to more than two highlights, always delete the smallest first.

**Comment by ahrm** [comment]
Added in this commit in the development branch: https://github.com/ahrm/sioyek/commit/18e1fe98f6e1c57f0c37d73c4b77cb9504cbe6de. We also now distinguish the selected highlight so there is no confusion:


https://github.com/ahrm/sioyek/assets/6392321/2d3943ef-7a63-4618-b799-f3e8bbe318b8
