### ISSUE TITLE
Feature request: Use fzf's algorithm for the fuzzy matcher

### ISSUE THREAD

**Issue by flabou** [ahrm/sioyek#774]
I wanted to open an issue to add a fuzzy finder, but while searching through the issue, I realized there is already a fuzzy search functionality.

However, in my opinion, the [algorithm](https://github.com/junegunn/fzf/blob/master/src/algo/algo.go) from [fzf](https://github.com/junegunn/fzf) is much more forgiving against typo, which makes it easier to find something when you are not sure exactly what you are looking for. The biggest problem is that the main algorithm is implemented in Go. Apparently it [has been ported to C](https://github.com/nvim-telescope/telescope-fzf-native.nvim), but maybe C++ implementation would be better for Sioyek. It would be nice to have this in every UI search (command search, file search, bookmark search, etc.).

It's probably easier to grasp behavior of fzf's algorithm by trying fzf, but the top of the algo.go file gives a nice explanation:

> Algorithm
> ---------
> 
> FuzzyMatchV1 finds the first "fuzzy" occurrence of the pattern within the given
> text in O(n) time where n is the length of the text. Once the position of the
> last character is located, it traverses backwards to see if there's a shorter
> substring that matches the pattern.
> 
>     a_____b___abc__  To find "abc"
>     *-----*-----*>   1. Forward scan
>              <***    2. Backward scan
> 
> The algorithm is simple and fast, but as it only sees the first occurrence,
> it is not guaranteed to find the occurrence with the highest score.
> 
>     a_____b__c__abc
>     *-----*--*  ***
> 
> FuzzyMatchV2 implements a modified version of Smith-Waterman algorithm to find
> the optimal solution (highest score) according to the scoring criteria. Unlike
> the original algorithm, omission or mismatch of a character in the pattern is
> not allowed.
> 
> Performance
> -----------
> 
> The new V2 algorithm is slower than V1 as it examines all occurrences of the
> pattern instead of stopping immediately after finding the first one. The time
> complexity of the algorithm is O(nm) if a match is found and O(n) otherwise
> where n is the length of the item and m is the length of the pattern. Thus, the
> performance overhead may not be noticeable for a query with high selectivity.
> However, if the performance is more important than the quality of the result,
> you can still choose v1 algorithm with --algo=v1.
> 
> Scoring criteria
> ----------------
> 
> - We prefer matches at special positions, such as the start of a word, or
>   uppercase character in camelCase words.
> 
> - That is, we prefer an occurrence of the pattern with more characters
>   matching at special positions, even if the total match length is longer.
>     e.g. "fuzzyfinder" vs. "fuzzy-finder" on "ff"
>                             ````````````
> - Also, if the first character in the pattern appears at one of the special
>   positions, the bonus point for the position is multiplied by a constant
>   as it is extremely likely that the first character in the typed pattern
>   has more significance than the rest.
>     e.g. "fo-bar" vs. "foob-r" on "br"
>           ``````
> - But since fzf is still a fuzzy finder, not an acronym finder, we should also
>   consider the total length of the matched substring. This is why we have the
>   gap penalty. The gap penalty increases as the length of the gap (distance
>   between the matching characters) increases, so the effect of the bonus is
>   eventually cancelled at some point.
>     e.g. "fuzzyfinder" vs. "fuzzy-blurry-finder" on "ff"
>           ```````````
> - Consequently, it is crucial to find the right balance between the bonus
>   and the gap penalty. The parameters were chosen that the bonus is cancelled
>   when the gap size increases beyond 8 characters.
> 
> - The bonus mechanism can have the undesirable side effect where consecutive
>   matches are ranked lower than the ones with gaps.
>     e.g. "foobar" vs. "foo-bar" on "foob"
>                        ```````
> - To correct this anomaly, we also give extra bonus point to each character
>   in a consecutive matching chunk.
>     e.g. "foobar" vs. "foo-bar" on "foob"
>           ``````
> - The amount of consecutive bonus is primarily determined by the bonus of the
>   first character in the chunk.
>     e.g. "foobar" vs. "out-of-bound" on "oob"
>                        ````````````

Also interesting is how fzf handles case. If you type the pattern in lowercase, case is ignored. If you use at least one uppercase, case is matched.

**Comment by 7415963987456321** [comment]
> Also interesting is how fzf handles case. If you type the pattern in lowercase, case is ignored. If you use at least one uppercase, case is matched.

+1 to this, this is also what vim does with its 'smartcase' functionality, I use it heavily, it helps a lot in searching for something more specific than a general word in the document.

**Comment by nickel8448** [comment]
I really like the idea and have been pondering about the same for a while.
As a workaround, I use ripgrep-all to search through a set of PDFs prior to opening them in sioyek. ripgrep-all has a function in their documentation that has an implementation with fzf. 
I know it is not exactly what you are looking for but it might be worth trying.

PS: I am not a contributor to sioyek. I just lurk around the repo :)

**Comment by flabou** [comment]
I was mostly thinking about the command/bookmark/highlight search functionality instead of the text search, for which we already have regex capability, and fuzzy finder needs a length limit so I think it wouldn't work on the whole text. What you mentioned is also interesting but it's a different feature request IMO. It would be extending the regex search to all known PDF instead of the open one. Personally I would rarely need such functionality, so I would be fine with ripgrep, but may be useful for some people.

**Comment by ahrm** [comment]
Added fzf in https://github.com/ahrm/sioyek/commit/4f9866bb0d257ea562c24030a69c422b71a50340.

**Comment by flabou** [comment]
Thank you! 
Sioyek is honestly my favorite PDF viewer, I find it so efficient. So many cool ideas! Thank you for your work.
