### ISSUE TITLE
should_launch_new_window renders previous open window blank.

### ISSUE THREAD

**Issue by adithyarao3103** [ahrm/sioyek#776]
When trying to open two pdf files with should_launch_new_window set to 1, the previously opened window becomes blank. 
Please see the attached image for references

![image](https://github.com/ahrm/sioyek/assets/64120705/8bdff81b-f32e-49cb-b931-d35a90a75b43)

**Comment by ahrm** [comment]
How do you open the second window? (e.g. using gui or command line, and if so, which command?)

**Comment by adithyarao3103** [comment]
I have the should_launch_new_window set to 1 in the .config file.
I have sioyek set as the default pdf viewer, so I open the second window by
simply double clicking on the file.

**Comment by zqni** [comment]
Hi, thanks for developing this awesome software. I met with the same problems using the 2.0 release version in Win11. Do you have any plans to publish the fixed version? Thanks again.

> Hmm it appears to be a bug in 2.0 release which has been fixed in the latest versions (not released publicly yet).

**Comment by ahrm** [comment]
See this thread: https://github.com/ahrm/sioyek/discussions/734 .

**Comment by ahrm** [comment]
The source for new version is released in development branch of this repo.
