### ISSUE TITLE
could not find "Incremental Search" option

### ISSUE THREAD

**Issue by kaiwizz** [ahrm/sioyek#78]
I could not locate how to turn "incremental search" on. Does Sioyek have incremental search?

**Comment by ahrm** [comment]
> oh, Alright. Are you planning to implement this in the future?
> 
> and what's the protocol here? ShouldI keep this issue open or closed or something else?!

I currently don't have a plan to implement it but let's keep it open, maybe I could implement it in the future.

**Comment by HakonHarnes** [comment]
+1 This would be a really nice feature!

**Comment by ahrm** [comment]
Added in https://github.com/ahrm/sioyek/commit/ac33b3830c590a04b259f4dff35751ff0b9edf95. It only works when `super_fast_search` option is enabled. Video:

https://github.com/ahrm/sioyek/assets/6392321/0e039005-5190-4ac0-99d0-b21b1690f712
