### ISSUE TITLE
Windows Build Help?

### ISSUE THREAD

**Issue by sk0rabu** [ahrm/sioyek#780]
First of all, thank you very much for this project. Looks very promising. Since there hasn't been stable builds for a while I decided to build it myself in Windows.

I got the following questions:
- The batch file for making windows builds `build_windows.bat` still uses Unix syntax. Can you update it?
- Can you shed light on what needs to be changed inside the `sioyek.vcxproj` file? I see a lot of library references that only applied to your own machine, e.g. directory structures. Also can you point me in what other libraries I have to prepare for x64 Windows builds? Not sure about which specific ones you used. Also I'm getting 
```
 libmupdf.lib(compress.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; ad
         d /LTCG to the link command line to improve linker performance
     1>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
// bunch of errors
```
when I tried to link built libmupdf.lib.

I have completed building everything up to: (per your config file)
```
cd mupdf\platform\win32\
msbuild mupdf.sln /property:Configuration=Debug
msbuild mupdf.sln /property:Configuration=Release
cd ..\..\..

cd zlib
nmake -f win32/makefile.msc
cd ..

qmake -tp vc "DEFINES+=NON_PORTABLE" pdf_viewer_build_config.pro
```

Errors pop up when executing: `msbuild -maxcpucount sioyek.vcxproj /property:Configuration=Release`

Many thanks in advance.

**Comment by ahrm** [comment]
> The batch file for making windows builds build_windows.bat still uses Unix syntax. Can you update it?

Is it? My own main platform is windows and I frequently use that file to generate build files.

> Can you shed light on what needs to be changed inside the sioyek.vcxproj file?

What sioyek.vcxproj? If you mean the one generated by build.bat then there should not be any specific paths to my system.

> Also I'm getting

The parts you posted are warnings and are not very important.

> Errors pop up when executing

Which errors exactly?

**Comment by sk0rabu** [comment]
In the generated sioyek.vcxproj file I'm seeing, under `<AdditionalLibraryDirectories>` and `<AdditionalDependencies>`: (below as an example)
```
<AdditionalLibraryDirectories>mupdf\platform\win32\Release;zlib;C:\openssl\lib;C:\Utils\my_sql\mysql-5.6.11-winx64\lib;C:\Utils\postgresql\pgsql\lib;C:\openssl\lib;C:\Utils\my_sql\mysql-5.6.11-winx64\lib;C:\Utils\postgresql\pgsql\lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
```

They are auto generated but I don't have any libraries stored in C:\. Also the path to libmupdf was in error - I corrected it from `mupdf\platform\win32\x64\Release` to `mupdf\platform\win32\Release`.

Errors being thousands of `error LNK2001: unresolved external symbol....`

**Comment by ahrm** [comment]
Which qt version are you using?

**Comment by sk0rabu** [comment]
It's 5.12.12

**Comment by ahrm** [comment]
Hmmm it is kind of hard for me to debug with the information provided, but rest assured, the build_window.bat file is completely generic and is not specific for my PC. In fact we use that script to build the released on the release page using github actions.

**Comment by ahrm** [comment]
Closing because I can't help much here.
