### ISSUE TITLE
accessing the table of contents breaks the program

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#782]
`sioyek --version`
2.0.0

When I open a pdf file and press t to access the table of contents and select any chapter from there the program hangs. The pdf viewer jumps to that page but nothing is displayed at all. I have been using it for a few months now and it didn't use to do that before.

The content reapper if I press `=` to rescale the pdf viewr to `fit-to-page-width`.

Adding 
`goto_toc;fit_to_page_width t`  to the config does not work.

**Comment by ahrm** [comment]
Which sioyek package are you using? Are you using the official appimages in the release section?

**Comment by albertobasaglia** [comment]
> Which sioyek package are you using? Are you using the official appimages in the release section?
I have the same problem with version 2.0.0-2 from the AUR.
Flatpak version works for me.

**Comment by ahrm** [comment]
The issue is with the AUR package because it was compiled with an incompatible version of libmupdf. You should contact the maintainer of the package for that.
