### ISSUE TITLE
Highlight highlights entire line for some pdfs

### ISSUE THREAD

**Issue by DeonteVanterpool** [ahrm/sioyek#785]
I love the app. I works almost perfectly for what I have to do, but I have a PDF (attached below), which when I try to highlight specific words in the book, entire lines get highlighted. I don't have this issue with other apps like Xodo and All PDF Reader on my phone. 
[AtomicHabits.pdf](https://github.com/ahrm/sioyek/files/12270138/AtomicHabits.pdf)

I also have another PDF which allows me to highlight words in some places (page 59 "248 people"), but in other places (page 59 "first group"), it continues to highlight entire lines. PDF attached below:
[atomic-habits.pdf](https://github.com/ahrm/sioyek/files/12270156/atomic-habits.pdf)

Other PDFs seem to be working fine, so I'm guessing its something to do with how the PDF is formatted. I tried repairing the PDF using qpdf to no avail. 

I am using arch linux by the way, and am using Sioyek version 2.0.0.

**Comment by DeonteVanterpool** [comment]
The workaround would be to set exact_highlight_select to 1

**Comment by DeonteVanterpool** [comment]
> The workaround would be to set exact_highlight_select to 1

Update: The exact highlighting is not a good workaround, as when I reload the document, the exact highlights go back to line highlights.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/c12306b99be7940438e89745cb4c0391d7762677.
