### ISSUE TITLE
Keyboard_select labels are too big

### ISSUE THREAD

**Issue by mrkskk** [ahrm/sioyek#787]
When using the keyboard_select tool (v) is it possible to alter the font size of the labels that appear. 
Especially in two collumn pdf's they tend to cover not only cover the pdf's text to make that unreadable, but also overlap each other so I can't discriminate the letters within the labels.

If the font was smaller it would be easier to use the tool.
Additionally, will  caret mode be available as an alternative to selecting text with the keyboard only.

![Screenshot 2023-08-09 at 14 39 29](https://github.com/ahrm/sioyek/assets/61738474/58d5a78a-a0dd-4b82-91ac-67996fe06a47)

**Comment by asgerkromand** [comment]
Hi, has this config option been made available?

**Comment by ahrm** [comment]
Not yet.

**Comment by ahrm** [comment]
The code is released in the development branch of this repo.
