### ISSUE TITLE
key to increment the visual mark by 1 line

### ISSUE THREAD

**Issue by RichardJActon** [ahrm/sioyek#79]
[feature request]

I quite like using the visual mark to keep my place but I find myself reaching for the mouse a lot to move it around it would be nice to have a key, (maybe the space bar?), mapped to moving the mark down one line. 
maybe some additional stuff like shift space for decrement, <N> space for move N lines, ctrl space for a larger increment e.g. 5 lines that you can set in the config.

(Thanks for Sioyek - its default pdf viewer in my Zotero now)

**Comment by ahrm** [comment]
Added in 2d63e1ec92b78d1b7220845cab1a79ca250df959.

We have two new commands which allow the highlight to be moved the the next/previous line. For example I have this in my `keys_user.config`:
```
move_visual_mark_down	j
move_visual_mark_up	k
```
https://user-images.githubusercontent.com/6392321/136592038-01548af8-a773-4409-9e9c-3330765c7a7e.mp4
