### ISSUE TITLE
[ SUGGESTION ] Change the font used in the PDF to custom font

### ISSUE THREAD

**Issue by ibehnam** [ahrm/sioyek#790]
Most serif fonts are difficult to read on display (esp. <4k resolution). It'd be nice to replace those fonts with custom sans serif fonts. I don't know if it's feasible given the project's dependencies, just a thought.

**Comment by ahrm** [comment]
This can't be easily done and the results are not predictable. You can use external tools such as this script to do the conversion:
https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/font-replacement/repl-font.py .
