### ISSUE TITLE
[request] allow to configure size  of labels and label bg transparency 

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#792]
as can be seen in screenshot labels can overlap each other and it can get quit confusing when labels are hiding each other, either some transparency of the yellow bg of label or an option to set max size of label text so that they do not overlap each other will make things better. thanks

 
![image](https://github.com/ahrm/sioyek/assets/78728701/fc5bae9e-ff3d-4e00-a761-1bb4e89d2cad)

**Comment by ahrm** [comment]
We have `keyboard_select_font_size`,`keyboad_select_background_color` and `keyboard_select_text_color` config options in the development branch.
