### ISSUE TITLE
open_overview_links only

### ISSUE THREAD

**Issue by ngocbh** [ahrm/sioyek#793]
I would like to open an overview for links only. Similar to `open_links` but `open_links_overview` instead. I can set keyboard_overview, but it seems pretty dense. I would like to have the option to choose an open overview of several links that are displayed on the screen only. How can I do it?

**Comment by ahrm** [comment]
It is not currently possible but we will have  an `overview_link` command in the next version.

**Comment by ngocbh** [comment]
Thank you, @ahrm, for the information. What do you think about making Sioyek more friendly for mouse users? Sometimes, using a mouse instead of a keyboard is more convenient. Some features like highlighting and going back and forth the state history might be enough.

**Comment by ahrm** [comment]
We do have a select highlight mode where we automatically highlight any text you select.
Also if your mouse has extra buttons then they can be used to go forward/backward in history.

**Comment by ngocbh** [comment]
I'm aware of that solution, but it still seems inconvenient. Several buttons on a small tool bar would be a much better solution, I think.

**Comment by ahrm** [comment]
Added an optional context menu in development branch here: https://github.com/ahrm/sioyek/commit/b6c68cf1cdd746f3c0758db6bf4eb624319936c8 .

It can be configured like so:
```
right_click_context_menu 1
context_menu_items overview_under_cursor|close_overview|add_highlight_with_current_type|delete_highlight|smart_jump_under_cursor
```
