### ISSUE TITLE
one chapter forward (gc) working only  once, then I got invalid command

### ISSUE THREAD

**Issue by danieltomasz** [ahrm/sioyek#794]
Greate app!
Next chapter (gc) seems to works only once on MacOS and Linux, after that  I am receiving in console (when I start from console)

```
Warning: invalid command (key:g); resetting to root
Warning: invalid command (key:c); resetting to root
```
 with chapter back (gC) I dont have this problem, but maybe I dont understand something

**Comment by ahrm** [comment]
Maybe there is a key configuration that is causing the issue? Can you share your `keys_user.config` here?

**Comment by ahrm** [comment]
Closing because I did not receive a response. Feel free to reopen if the issue persists.
