### ISSUE TITLE
[bug] open_prev_docs sometimes do not work properly to sort item based on their last use

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#796]
hi ahrm , i hope you are doing great

### summary :
 when doing open_prev_doc sioyek list all previously opened docs on basis of when they were used last but some times it do not rank the last used doc on top ,when i go to a doc B from doc A and jump back it should rank doc B on top which i do occasionally but the behavior is not consistent and it just rank doc A on top.

### An Interesting use of open_prev_menu as replacement for tabs

honestly i felt very dishearten when i feel that there is not going to be any tab support in sioyek after this #644  and i need it because of reason mentioned well [in the issue thread](https://github.com/ahrm/sioyek/issues/644#issuecomment-1496625019)
so i was looking for something so that i can save myself from the quest of finding required window from alot of pdf windows in alt+tab and luckily i found a workaround

the workaround is i 
- map ctrl+n to open_prev_doc 
- open a bunch of docs in same window
- and press [ctrl+n and enter] or [ctrl+n , ctrl+n , enter] to go to last used tab as it is ranked on top of the list
- if need to go to some other tab type some words from file names exactly and then enter

at first it feels like unlocking a new power in the game but soon enough i feel some issues/requests

1. if there is support fot fuzzy matching in the open_prev_doc menu it would be alot easier 
2. the inconsistent behaviour of ranking the last used pdf forces me to type the file name even if i just need to switch back and forth between only 2 last opened tabs

if the ranking bug got fixed it can serve as a replacement workflow for tabs for now, i am guessing your are thinking about the fuzzy matching functionality already so i hope that it will come at its time.
sioyek version = 2.0.0
### video recording 

https://github.com/ahrm/sioyek/assets/78728701/8d93e7ac-eef3-48cd-860e-888528db57b3

**Comment by ahrm** [comment]
This happens because the resolution of the timestamp of opened file is 1 second. So if you open two files within one second (or "alt tab" twice within one second) then it might confuse the order of the two files. I don't think it is something that happens in natural use though.

**Comment by Aneeqasif** [comment]
would changing it to something like half sec cause performance overhead?

**Comment by ahrm** [comment]
No but it does requires changing the database schema.

**Comment by Aneeqasif** [comment]
> No but it does requires changing the database schema.

idk much about databases so ig this change  might be a bit hard or may be it make sioyek inconsistent so i think i should close this issue if this (timestamp resolution) is not going to be change
