### ISSUE TITLE
How to open new PDF file maximized?

### ISSUE THREAD

**Issue by karimmd** [ahrm/sioyek#797]
Is there any way to make changes to prefs.config which would allow me to open a new PDF file with a maximized window? Thanks.

**Comment by karimmd** [comment]
Thank you for your comment. Actually, I was looking to maximize the window on the startup not the full screen. Currently, there are some files which are opening with window is maximized while some others are opening with normal window. I want to force all the new file to open in the maximized window.

Instead of
![image](https://github.com/ahrm/sioyek/assets/6984392/6e2c7222-1779-409d-a69c-bab55cf994c2)

I want to achieve for all the new files to open in the maximized window like this
![image](https://github.com/ahrm/sioyek/assets/6984392/0ea49e81-e6ca-44e7-ac82-a1910930e0de)

I have checked the window_size option but I often use multiple monitors; so setting a fixed resolution or size may have impact on different monitor or in my laptop screen.
single_main_window_size
single_main_window_move
main_window_size
main_window_move
helper_window_size
helper_window_move

Thanks.

**Comment by ahrm** [comment]
I guess we could add a command like `maximize_window` that works similar to `toggle_fullscreen`. It probably will be available in the next release of sioyek.

**Comment by karimmd** [comment]
Thanks

**Comment by ahrm** [comment]
We added a `maximize` command in development branch here: https://github.com/ahrm/sioyek/tree/development.
