### ISSUE TITLE
In presentation mode, cover statusbar region when it is toggled off

### ISSUE THREAD

**Issue by engeir** [ahrm/sioyek#798]
From what I can see, when presentation mode is toggled on, the page will span the same height no matter if the status bar is toggled on or off.

With the status bar off, that leaves a line at the bottom where the status bar would fit, but now with the background color instead.

The behavior I would expect was that, in presentation mode, the height is adjusted to fill the whole screen height depending on whether the status bar is present or not. I would personally also expect that "status bar off" was the default in presentation mode since one most likely want to show only the slide in this case, but that might be just preference.

I saw that [this issue](https://github.com/ahrm/sioyek/issues/403) mention a workaround where one used to be able to toggle off the status bar to be able to show the full slide, which I suppose is the end result I am thinking of.

**Comment by ahrm** [comment]
As a workaround we currently have a `ignore_statusbar_in_presentation_mode` config option.

**Comment by engeir** [comment]
Thanks for the quick reply, that's great! Wasn't able to find it in the docs, but I see now that it shows up in the command list of the PDF viewer.
