### ISSUE TITLE
How To Print a Document

### ISSUE THREAD

**Issue by kaiwizz** [ahrm/sioyek#80]
I could not figure out how to print a document.

**Comment by ahrm** [comment]
There is no such feature in sioyek (and no plans to add it).

**Comment by x61** [comment]
Any reasons why this feature is not included? For sioyek to be the default pdf reader, it would help for it to have printing functionality options.

**Comment by ferdinandyb** [comment]
I'm no expert, but shouldn't Sioyek be able to delegate this to the OS? At least from a user experience point of view it seems applications just call some system thing for printing and leave the rest to the OS.

**Comment by ahrm** [comment]
See these discussions about why I am not motivated to add printing to sioyek and how you can use  the external command system to add this functionality:

https://github.com/ahrm/sioyek/discussions/380
https://github.com/ahrm/sioyek/discussions/618

**Comment by ferdinandyb** [comment]
On Wed Feb 22, 2023 at 13:43, ahrm wrote:
> See these discussions about why I am not motivated to add printing to sioyek and how you can use  the external command system to add this functionality:
>
> https://github.com/ahrm/sioyek/discussions/380
> https://github.com/ahrm/sioyek/discussions/618

Thanks for linking these! Is there a way to execute a command dynamically instead of defining previously with new_command? An easy way to print would be using `lp -d [printername] %1`, but with new_command I'd have to define a command for each of the printers I would be potentially using.

**Comment by ahrm** [comment]
Yes, using `execute` command.

**Comment by ahrm** [comment]
Also, commands can have custom text inputs (using `%{command_text}`), so you could define a custom command that only requires you to enter printername instead of the whole command.

**Comment by ferdinandyb** [comment]
On Wed Feb 22, 2023 at 14:19, ahrm wrote:
> Also, commands can have custom text inputs (using `%{command_text}`), so you could define a custom command that only requires you to enter printername instead of the whole command.

Nice! Just to document if people are also searching for this, this is what I came up with:

new_command _printto lp -d %{command_text} %{file_path}
new_command _print lp %{file_path}
new_command _evince evince %{file_path}

It doesn't seem to be explicitly documented, but it seems to me the leading underscore is a must for self-defined commands? At least without that the new commands did not show up in the list.

Thanks very much for your help (and the software)!


-- 
+36305425054
bence.ferdinandy.com

**Comment by ahrm** [comment]
It is documented here: https://sioyek-documentation.readthedocs.io/en/latest/scripting.html

> Note that custom command names must begin with an underscore so as not to be confused with built-in sioyek commands.

**Comment by ferdinandyb** [comment]
On Wed Feb 22, 2023 at 14:34, ahrm wrote:
> It is documented here: https://sioyek-documentation.readthedocs.io/en/latest/scripting.html
>
> > Note that custom command names must begin with an underscore so as not to be confused with built-in sioyek commands.
Mea culpa for not properly RTFM ...


-- 
+36305425054
bence.ferdinandy.com

**Comment by maribox** [comment]
For anyone else looking for a clean solution with a dialog:
1. Make sure [yad](https://github.com/v1cont/yad) is installed and in PATH
2. Add to `prefs_user.config`:
```
new_command _print yad --print --type=RAW --filename=%{file_path}
```
3. Add to `keys_user.config`:
```
_print <C-p>
```
4. Print with Ctrl + p

P.S. If you want to remove the "Print To LPR" option, add to `~/.config/gtk-3.0/settings.ini`:
```
[Settings]
gtk-print-backends=file,cups,pdf
```
