### ISSUE TITLE
[Feature request] Add best fit to page functionality (i.e. auto select fit to page or fit to height)

### ISSUE THREAD

**Issue by flabou** [ahrm/sioyek#800]
It would be nice, in addition to fit_to_page_{width,height} and fit_to_page_{width,height}_smart, to have a fit_to_best that automatically selects width or height to avoid losing content on the screen. 

It makes sense when you want to combine it with other commands. For instance, in my case, I mapped the next page / previous page keys to also fit to height, because this way I can easily see the whole content at the page, and I like it better than pressing a fit_to_page_x key before changing page (also it resets it on every page so if something goes wrong because of inconsistent page size, it still works). But I also sometimes place sioyek on a vertical screen. And there, it doesn't work because the page is cropped on the side, especially with landscape pages. Having fit_to_best would solve this.

**Comment by ahrm** [comment]
Added a `fit_to_page_smart` command in https://github.com/ahrm/sioyek/commit/29772b6e218e76ade989350e9ddbf9d863aa5c59. There is no need for a separate non-smart command becasue it can be done by executing `toggle_presentation_mode` twice.
