### ISSUE TITLE
Can not set 5;move_up to a key to scroll faster

### ISSUE THREAD

**Issue by userrand** [ahrm/sioyek#802]
In a vim one may configure 5j to a key to scroll 5 times faster. This did not seem to work setting 5;move_up to a key.

**Comment by ahrm** [comment]
It is not exactly elegant but you could do something like this in `keys_user.config`:
```
move_up;move_up;move_up;move_up;move_up <keybind>
```

**Comment by userrand** [comment]
Nice ! Thank you, that seems to work. I guess I could also have just added a new command with a script to do that but I have not tried scripting yet. Thanks .

**Comment by userrand** [comment]
> It is not exactly elegant but you could do something like this in `keys_user.config`:
> 
> ```
> move_up;move_up;move_up;move_up;move_up <keybind>
> ```

Nice ! Thank you, that seems to work. I guess I could also have just added a new command with a script to do that but I have not tried scripting yet. Thanks .
