### ISSUE TITLE
Error on compilation in Linux Mint Una

### ISSUE THREAD

**Issue by AsbjornPreuss** [ahrm/sioyek#807]
When trying to build the program from scratch, I get the following error message. Haven't worked with Qt before, but wondering if that might be the problem. Any help would be appreciated.

`make: Nothing to be done for 'default'.
g++ -c -pipe -std=c++17 -O2 -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQT_3DINPUT_LIB -DQT_OPENGL_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_WIDGETS_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_3DINPUT_LIB -DQT_3DCORE_LIB -DQT_OPENGLEXTENSIONS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Ipdf_viewer -Imupdf/include -Izlib -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DInput -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGLExtensions -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o config.o pdf_viewer/config.cpp
pdf_viewer/config.cpp: In function ‘bool colorn_validator(const wstring&)’:
pdf_viewer/config.cpp:245:45: error: ‘Qt::SplitBehaviorFlags’ has not been declared
  245 |  auto parts = qstr.trimmed().split(' ', Qt::SplitBehaviorFlags::SkipEmptyParts);
      |                                             ^~~~~~~~~~~~~~~~~~
pdf_viewer/config.cpp: In function ‘bool bool_validator(const wstring&)’:
pdf_viewer/config.cpp:291:45: error: ‘Qt::SplitBehaviorFlags’ has not been declared
  291 |  auto parts = qstr.trimmed().split(' ', Qt::SplitBehaviorFlags::SkipEmptyParts);
      |                                             ^~~~~~~~~~~~~~~~~~
pdf_viewer/config.cpp: In constructor ‘ConfigManager::ConfigManager(const Path&, const Path&, const std::vector<Path>&)’:
pdf_viewer/config.cpp:313:7: warning: unused variable ‘vec3_deserializer’ [-Wunused-variable]
  313 |  auto vec3_deserializer = vec_n_deserializer<3, float>;
      |       ^~~~~~~~~~~~~~~~~
make: *** [Makefile:714: config.o] Error 1
`

**Comment by ahrm** [comment]
I think you are using an older version of Qt. You can either update your Qt or just remove the second argument to `split`. It won't matter if your config file is correctly formatted.
