### ISSUE TITLE
fit_to_page_width_ratio incorrect documentation

### ISSUE THREAD

**Issue by MithicSpirit** [ahrm/sioyek#809]
The command `fit_to_page_width_ratio` is documented as
```
## Same as fit_to_page_width_smart, but instead of filling the screen width, it fills the ratio of screen that is
## configured in `prefs_user.config` using `fit_to_page_width_ratio` config. See https://github.com/ahrm/sioyek/issues/162#issuecomment-1059738730.
```
Specifically, "Same as fit_to_page_width_smart". However, when setting the option `fit_to_page_width_ratio 1.0` it is revealed that it actually behaves like `fit_to_page_width` (non-smart). To fix this, either the documentation should be changed to remove the `_smart`, or it should be changed to fit based on text width rather than page width. Personally I would prefer the latter.

**Comment by ahrm** [comment]
Fixed in https://github.com/ahrm/sioyek/commit/a7c34f53b43a464c5e413a13777ec81eda7bf97a.
