### ISSUE TITLE
Horizental scroll seems not working in macOS

### ISSUE THREAD

**Issue by toorukt** [ahrm/sioyek#812]
I found this excellent app recently and really like it.

However, I noticed the horizontal scroll does not work as expected.
For example, after I zoom in a PDF,
neither shift + mouse scroll wheel nor the horizontal scoll whell from logicool master 3 working,
but the touchpad seems to be working fine.

I'm wondering it is just me or it is a bug?
BTW, I'm using the newest version of sioyek and macOS 13.5.2.

Thanks for your kindly help.

**Comment by ahrm** [comment]
This should be fixed in the latest commits in the development branch.
