### ISSUE TITLE
the portable binaries on Ubuntu 20, how to display references as pop-up window

### ISSUE THREAD

**Issue by ouboub** [ahrm/sioyek#815]
Hi
I downloaded the compiled binaries (portable) to a Laptop running Ubuntu 20.
The viewer started without problems. Now the manual indicates that the viewer is able to display references as pop-up windows, even if the pdf file (say using latex) was not generated (compiled) with hyperlinks. This is the feature I am interested most (Because sometimes I receive such pdf files, and the references to equations are no hyperlinks)
I am, however, unable to get this feature to work,
I attach a screenshot (using the latest version of evince) with displays references to equations as pop-up windows, but the document had to be compiled with hyperref).
So, is the sioyek viewer able to do the same for pdf files, even no hyperref has been used?
thanks and regards

Uwe Brauer

![evince-pop-up](https://github.com/ahrm/sioyek/assets/5957203/6d026bf6-2fe5-49de-9e79-ad8384a8cceb)

**Comment by ahrm** [comment]
The automatic reference detection algorithm is a heuristic and doesn't work on all document reference types. If you have an example pdf document I could try it out and see if sioyek works with that.

**Comment by ouboub** [comment]
> The automatic reference detection algorithm is a heuristic and doesn't work on all document reference types. If you have an example pdf document I could try it out and see if sioyek works with that.

Thanks for the quick reply. Just to understand this completely in evince, I just put the cursor/pointer/mouse on the reference, then the pop-up windows shows up automatically without further actions from the user.
 is the same behaviour to be expected for sioyek, or shall I press some mouse-button.
 this is not entirely clear to me.

**Comment by ouboub** [comment]
OK, then indeed it works (the manual does not state this very cleary for me)
so I will close this issue. Thanks,
And it is wonderful, I have to also upgrade my Distribution 
it seems that it really simplify my life considerably, since mathematical
papers without hyperlinks have been a pain...
So I will then think about the coffee question.....
