### ISSUE TITLE
Cannot open large files

### ISSUE THREAD

**Issue by alonetrifle** [ahrm/sioyek#822]
I've been trying to read a book about pharmacology containing 1600 pages it is stuck in indexing, and cannot load the whole document tried using both flatpak and appimage issue is the same.
Thank you

**Comment by ahrm** [comment]
I have tested sioyek on very large files. The document should be opened even while indexing. If this  is not the case then it is a bug but I can't reproduce it with any of the documents I have. What is the name of this book? Maybe I can test on it.

**Comment by alonetrifle** [comment]
> I have tested sioyek on very large files. The document should be opened even while indexing. If this is not the case then it is a bug but I can't reproduce it with any of the documents I have. What is the name of this book? Maybe I can test on it.

Goodman  Gilman’s The Pharmacological Basis of Therapeutics

**Comment by alonetrifle** [comment]
I checked with zathura it had same problem while using mupdf engine but the problem was fixed by using poppler as the engine, I think the problem is from mupdf

**Comment by euglevi** [comment]
What I am having with a large file is that the file opens. Then, if I want to go to a specific page by scrolling down everything works fine. If I want to use the table of contents, it goes to a blank page that never gets refreshed into the actual one.

**Comment by jbirnick** [comment]
I had the same issues with using the AUR package. It doesn't happen if you use the AppImage (which is also available in the AUR), there are a couple of threads on the web on this. (It's because of different libmupdf versions or so.)
However, the AppImage in turn has to Wayland support, so please support [this issue](https://github.com/ahrm/sioyek/issues/867).

**Comment by ahrm** [comment]
I am closing this issue since the problems seem to be mupdf/aur package related.
