### ISSUE TITLE
Link to a local PDF made with Latex doesn't work

### ISSUE THREAD

**Issue by waskou** [ahrm/sioyek#827]
This is a simple issue:

1. Build a PDF with Latex that has the hyperref package and the line

\href{run:my_file.pdf}{Click here to open}
or
\href{my_file.pdf}{Click here to open}

where my_file.pdf is located in the same folder as the original PDF.

2. In the original PDF "Click here to open" appears as a hyperlink, but when clicked simply scrolls up to the top of the original PDF, instead of opening my_file.pdf

If I open the PDF's with some other PDF viewer, such as Preview, links between them work as expected. I am on Mac M1 and I tried a bunch of Latex build recipes: pdflatex, latexmk... with the same result. Also links to labels in other PDF's created with the more complicated xr-hyperref package don't work on sioyek either, while they work on Preview.

**Comment by birromer** [comment]
Have you had any news on your side? I also have problems with the exact same usage (href command, files in the same folder, scrolling up upon click).

**Comment by ahrm** [comment]
This should be fixed in the development branch here: https://github.com/ahrm/sioyek/tree/development.
