### ISSUE TITLE
Overview flickering

### ISSUE THREAD

**Issue by Thain** [ahrm/sioyek#836]
When using overview (which I use for previewing search results), as I tab through the results, often times it takes a second to load the next result and display it. This leads to a flash of blank screen before the next result loads. This is understandable, though it doesn't seem to matter how long I wait, that is, if I wait ten seconds, if the next result is sufficiently far away from the current one, there is still a flash of blank screen. I found several configuration settings for preloading pages, but couldn't find one to preload for overviews. Let me know if I missed something there.

In any case, I don't mind the slight pause between search results. The bigger problem is that the flash of blank is always white, despite me playing with all of the following background color settings:
- `background_color`
- `dark_mode_background_color`
- `custom_background_color`
- `ui_background_color`
- `ui_selected_background_color`
I use a custom background color that is pretty dark, and so the flash of white is really jarring. It seems as though the background color of this overview window should be controlled by at least one of these, ideally the first/second (depending on mode) or the third if `toggle_custom_color` has been used (as I do).

Version 2.0.0-4 installed from AUR.

**Comment by ahrm** [comment]
I think I have already fixed this (not released yet though). It will be released with the next version of sioyek.

https://github.com/ahrm/sioyek/assets/6392321/5d0f11cb-7c33-4744-9a73-a389636d4a1a

**Comment by Thain** [comment]
Great to hear. I'll report back to confirm it works when the new release is out.

**Comment by ahrm** [comment]
The source for new version is available in development branch of this repo (no binary released yet).
