### ISSUE TITLE
libgumbo.so.1: cannot open shared object file

### ISSUE THREAD

**Issue by no-vici** [ahrm/sioyek#837]
After upgrading my system, I had this error:

`sioyek: error while loading shared libraries: libgumbo.so.1: cannot open shared object file: No such file or directory`

Looked everywhere and could not find the solution until asking [ZZZ Code.AI](https://zzzcode.ai/answer-question?id=291424fb-f60b-4ac9-a04b-cae7f7b91408)

Created a symbolic link then problem solved.

If you have any better solution, please share it with me ;)

**Comment by topoipat** [comment]
Which symbolic link did you create here? I'm having the same issue.

**Comment by ahrm** [comment]
Closing as this is an OS-specific problem and I don't really have a better solution.
