### ISSUE TITLE
Pattern matching within most pdfs is incorrect and misplaced

### ISSUE THREAD

**Issue by joshuaspiral** [ahrm/sioyek#838]
Searching for all "a"s in a text in zathura:
![image](https://github.com/ahrm/sioyek/assets/82312141/52918a2f-ece4-4492-b5dc-3a002fd34ae7)

Searching for all "a"s in sioyek:
![image](https://github.com/ahrm/sioyek/assets/82312141/6152ea9b-22e5-483a-82f0-104726cc7028)

As shown in the latter image, the search does not properly highlight the pattern and misses. However, this doesn't occur in LaTeX-made pdfs.

It would be nice if this is fixed, as this is the only thing preventing me from switching.

**Comment by joshuaspiral** [comment]
Here is a document where the same issue happens:
https://www.gutenberg.org/files/33283/33283-pdf.pdf

**Comment by ahrm** [comment]
Unfortunately I can't reproduce the issue:

https://github.com/ahrm/sioyek/assets/6392321/23f2f0d1-a926-458f-9098-d210b55228d9


Which version of sioyek are you using (which operating system, which package, etc)? Also information about your display setup might be relevant (e.g. are you using multiple monitors, if so, does the issue happen when using only a single monitor? Are you using display scaling? etc.)

**Comment by ahrm** [comment]
Does this issue happen with the appimage builds here: https://github.com/ahrm/sioyek/releases/tag/v2.0.0 ?

**Comment by joshuaspiral** [comment]
It works for the Appimage. Thanks for the help.
