### ISSUE TITLE
set_page_offset resets after restarting sioyek

### ISSUE THREAD

**Issue by joshuaspiral** [ahrm/sioyek#839]
The page_offset is not persistent and is reset everytime I reopen sioyek. On Appimage build.

**Comment by ahrm** [comment]
This is expected. In the next version of sioyek (unreleased) we have support for page labels so `page_offset` will be removed probably.

**Comment by nikinbaidar** [comment]
> This is expected. In the next version of sioyek (unreleased) we have support for page labels so `page_offset` will be removed probably.

Any updates? When will the next version be released?

**Comment by ahrm** [comment]
Next version is in the development branch here: https://github.com/ahrm/sioyek/tree/development. I don't know when the binaries for the next version will be released.

**Comment by ahrm** [comment]
The command name is `goto_page_with_label`.

**Comment by nikinbaidar** [comment]
> The command name is `goto_page_with_label`.

Hi, I tired it. With `goto_page_with_label` I press a page number and it will take me to that page number in the pdf not the book I'm reading. Do you have to add labels ourselves?

**Comment by ahrm** [comment]
The PDF itself should provide the page labels.

**Comment by nikinbaidar** [comment]
> The PDF itself should provide the page labels.

example pdf?

**Comment by ahrm** [comment]
https://arxiv.org/pdf/2106.10165.pdf

**Comment by nikinbaidar** [comment]
> https://arxiv.org/pdf/2106.10165.pdf

`go_to_page_with_label` works with this. But not every file can do that. I have a bunch of technical manuals that keep making forward and backward references. Persistent page_offsets would be really helpful. I urge you to consider implementing this feature.

**Comment by poiug07** [comment]
Any ways to add labels to pages in pdf by ourselves? I use sioyek to read some pdf of book. Pdf file itself has been split into 2 using MuPDF poster tool. Good file is not available since book is from 90s scanned version, no OCR.
