### ISSUE TITLE
Feature Request - Integration with OSX Spoken Content

### ISSUE THREAD

**Issue by D00mch** [ahrm/sioyek#842]
Currently, when I select text anywhere and press a shortcut to activate the OSX Spoken Content app, it starts speaking the selected text. Unfortunately, this feature doesn't work as expected with Sioyek. I suspect that somewhere in the codebase, there may be a need to inform OSX that specific text is selected, and everything else will work out of the box.

### Current Workaround

For those who require this feature, there is a workaround. Three commands in the `prefs_user.config` file:

```bash
new_command _read_visual_line say "%{line_text}" -r 270
new_command _read_selected_text say "%{selected_text}" -r 270
new_command _read_kill killall say
```

Shortcuts in the `keys_user.config` file:

```bash
_read_visual_line s
_read_selected_text gs
_read_kill gk
```

With it, while using the ruler (visual mode), you can press `s` (speak) to have the current line spoken. Or you can select the desired text and press `gs` (go speak). Press `gk` for "go kill."

**Comment by ahrm** [comment]
We don't quite have Spoken Content integration (mainly because it is platform-specific), but in the next version of sioyek (not released yet) we will have a `start_reading` command that reads from the selected line and keeps highlighting the line being read as it reads:


https://github.com/ahrm/sioyek/assets/6392321/f759c5b4-f87f-4c1d-8cf2-8d488a5bc42a

**Comment by D00mch** [comment]
Looks fantastic, thank you!

**Comment by D00mch** [comment]
It would be awesome to have a toggle_reading option, so we can play and stop with just one button

**Comment by ahrm** [comment]
Added `toggle_reading` command in https://github.com/ahrm/sioyek/commit/bcd68abca385882f1e20718397fa7b879eda6087. Also I have tested the TTS with macos and it works fine.

**Comment by peterjumper** [comment]
> Added `toggle_reading` command in [bcd68ab](https://github.com/ahrm/sioyek/commit/bcd68abca385882f1e20718397fa7b879eda6087). Also I have tested the TTS with macos and it works fine.

that's awesome, can i change the speed through config ?

**Comment by ahrm** [comment]
Yes, using `tts_rate` config.

**Comment by peterjumper** [comment]
> Yes, using `tts_rate` config.

founding it !!!!

(Set reading speed) that's great:)

cann't use mouse scrolling while setconfig_autocenter_visual_scroll, with visual scroll locked ,
i want really to have center visual scroll with my mouse.  (it worked with older version)

**Comment by ahrm** [comment]
You need to enable visual scroll mode (`toggle_visual_scroll` command)

**Comment by peterjumper** [comment]
> You need to enable visual scroll mode (`toggle_visual_scroll` command)

tried, didn't work somehow, thanks for making the greatest pdf application of all time. It officially can replace my APP Expert.app now 😄 💯 
Is there any tips about saving the annotations directly to the current file(Embed the annotations into a current PDF file)? (or just pip install sioyek and use it like the old way)

thanks

**Comment by ahrm** [comment]
You can use the `embed_annotations` command to embed the annotations into a new PDF file, no need for python extension anymore.

**Comment by peterjumper** [comment]
> You can use the `embed_annotations` command to embed the annotations into a new PDF file, no need for python extension anymore.

is there any way to save within the current file , cause embed_annotations require manually typing all the filename, filetype 

i wish to have like <C-s> than save embed_annotations into current file ,
similar to other application , command+s to save the file

embed_annotations "%{sioyek_path}" "%{local_database}" "%{shared_database}" "%{file_path}" <C-s>
