### ISSUE TITLE
[feature request] is it possible to use mouse to select an rect area to highlight ?

### ISSUE THREAD

**Issue by SakuraWald** [ahrm/sioyek#843]
Currently, sioyek supports the pure-text pdf perfectly.
But i have readed the document and its extensions, still don't konw how to create a highlight rect-area if reading a non-text pdf file (like some pdf file from scanner)

**Comment by ahrm** [comment]
It is not possible.

**Comment by SakuraWald** [comment]
> It is not possible.

Waiting for a workaround to solve this dirty case, or I will try to write an extension to do this.
Maybe fallback to an classical pdf reader for this case.
