### ISSUE TITLE
[Feature] Show file name in statusbar

### ISSUE THREAD

**Issue by HakonHarnes** [ahrm/sioyek#845]
I'm running i3wm+arch with no title bar. As such, there is no way for me to know which file is open (see screenshot). This feature request proposes adding the document file name in the statusbar. 

![image](https://github.com/ahrm/sioyek/assets/89907156/035241cd-dea8-4c7a-b861-5b7fcf2e6d76)

I've set this in my config: 

```
show_document_name_in_statusbar 1
```

But it doesn't appear to resolve the issue. Is there a difference between the "document name" and "file name"?

**Comment by ahrm** [comment]
We have made the statusbar format more customizable and now you can set the format like so for example:

```
status_bar_format %{document_name} Page %{current_page} / %{num_pages}%{chapter_name}%{search_results}%{search_progress}%{link_status}%{waiting_for_symbol}%{indexing}%{preview_index}%{synctex}%{drag}%{presentation}%{visual_scroll}%{locked_scroll}%{highlight}%{closest_bookmark}%{close_portal}%{rect_select}%{custom_message}%{download}
```

(you still need to set `show_document_name_in_statusbar` for `%{document_name}` to work, which is probably a bug).

**Comment by HakonHarnes** [comment]
I see - that works! But shouldn't setting `show_document_name_in_statusbar` work without the need for also setting the `status_bar_format` manually? 

Also, it seems like download field is not properly expanding for me: 

![image](https://github.com/ahrm/sioyek/assets/89907156/9a8d0279-a31f-42ee-98ba-7c7bd0bd8202)

**Comment by ahrm** [comment]
`show_document_name_in_statsubar` was added before we allowed customization of status_bar_format, it probably will be removed in future versions. I copied the config from the development version of sioyek which allows you to download papers by clicking on their name, the `%{downoad}` is the indicator that we are downloading which doesn't exist in the version you are using. You can remove the `%{download}` from your config.

**Comment by HakonHarnes** [comment]
That makes sense. Where can I find a list of variables that will be expanded when used in the `status_bar_format` command?

**Comment by ahrm** [comment]
Unfortunately I have not documented it yet. You can see the list of string being replaced in this function: https://github.com/ahrm/sioyek/blob/757c8935511d07a9ae2012a18924bbc2fd63ee88/pdf_viewer/main_widget.cpp#L546 .

**Comment by HakonHarnes** [comment]
Thanks. 

> you still need to set show_document_name_in_statusbar for %{document_name} to work, which is probably a bug

Here's the bug: 


https://github.com/ahrm/sioyek/blob/757c8935511d07a9ae2012a18924bbc2fd63ee88/pdf_viewer/main_widget.cpp#L560C4-L565C6

I'd suggest removing `if (SHOW_DOCUMENT_NAME_IN_STATUSBAR)` and the `show_document_name_in_statsubar` property. Another approach (if you still want to keep `show_document_name_in_statsubar`) is to append `%{document_name}` to `status_string` if `SHOW_DOCUMENT_NAME_IN_STATUSBAR` is set, and then expanding `%{document_name}` like normal.

**Comment by NightMachinery** [comment]
> Unfortunately I have not documented it yet. You can see the list of string being replaced in this function:
> 
> https://github.com/ahrm/sioyek/blob/757c8935511d07a9ae2012a18924bbc2fd63ee88/pdf_viewer/main_widget.cpp#L546
> 
> .

Can we have a status bar item to show the freehand drawing mode is active and the color and thickness? Something like `Red:3` when the mode is active and invisible when it's not.

**Comment by ahrm** [comment]
Added in https://github.com/ahrm/sioyek/commit/0e506774f3abcbaff5976e16479a5248ab1b08fb.
