### ISSUE TITLE
startup_commands don't run on new windows

### ISSUE THREAD

**Issue by mil-ad** [ahrm/sioyek#849]
I want all new windows to open with custom colors so I have this setting in my pref file:

```
startup_commands toggle_custom_color
```

This works for the first window but not for subsequent windows. I think there's some interaction with `should_launch_new_window` setting, when it's set to 0 startup commands always run but when it's 1 they only run for the first window?

**Comment by ei14** [comment]
Similar issue here. Namely `default_dark_mode 1` is ignored on all subsequent windows that are opened as a result of `should_launch_new_window 1`.

**Comment by aravezskinteeth** [comment]
I have `should_launch_new_window` set to 0. I have added `default_dark_mode 1` which didn't work until I added it to `startup_commands`, however `toggle_custom_color` is ignored for some reason. I have the following :

```config
default_dark_mode 1
should_launch_new_window  0
startup_commands    toggle_custom_color;toggle_visual_scroll;toggle_dark_mode
custom_background_color 0.1412 0.1529 0.2275
custom_text_color 0.7922 0.8275 0.9608
```

**Comment by ahrm** [comment]
You are running toggle_dark_mode after toggle_custom_color which overrides it.

**Comment by aravezskinteeth** [comment]
> You are running toggle_dark_mode after toggle_custom_color which overrides it.

Thank you, you were right. It works now.

**Comment by ahrm** [comment]
This should be fixed in the development branch. Now we correctly execute startup_commands on new windows. `default_dark_mode` is deprecated and should be replaced with:
```
startup_commands toggle_dark_mode
```
