### ISSUE TITLE
Memory leak upon following table of contents entry

### ISSUE THREAD

**Issue by ei14** [ahrm/sioyek#852]
On a PDF copy of the Algebra textbook by Dummit & Foote, following any table of contents entry instantly brings me to page 1 and occupies about 2GB of additional RAM. If I repeatedly try to follow a table of contents entry, my entire system's RAM is quickly depleted, resulting in an OS crash fairly quickly.

**Comment by ahrm** [comment]
I assume this was an issue with the AUR package. Feel free to open if the issue still persists.
