### ISSUE TITLE
keyboard_select cannot select the last character on line

### ISSUE THREAD

**Issue by atanasj** [ahrm/sioyek#854]
When I use the keyboard_select function, it does select the last character on any given line. For example, say I have a phone number on a line, '1234 567 890', when I use the keyboard_select function and choose the first and last points using the beginning and end points, e.g., ab cd, it only selects '1234 567 89' if the '0' is the final character on a line. It seems that the keyboard_select function used the word boundary of the next work in the selection algorithm.

My expectation is that it can select up to and including the final character on a line. 

The workaround for this is to select the beginning of the next word on the newline.

**Comment by ahrm** [comment]
This is already fixed in the devlopment branch here: https://github.com/ahrm/sioyek/tree/development .
