### ISSUE TITLE
Scrolling in portal is faster than in main document

### ISSUE THREAD

**Issue by JoostScheffer** [ahrm/sioyek#855]
I'm using a touchpad to scroll.
When trying to scroll a small amount in the portal the document moves way more than expected.
When scrolling using larger movements the scrolling amount seems roughly the same.

In the following video I first scroll a small amount in the main document, then in the portal. When scrolling in the portal I'm trying to replicate the smallest two movements you see me doing in the main document just before opening the portal. These small movements are really only a mm or so on my touchpad.
Then I scroll a larger amount in the main document, then in the portal.

https://github.com/ahrm/sioyek/assets/56606926/279d55de-3500-4854-85c6-4532bb30221b

## my system
```
Operating System: Kubuntu 23.10
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.0-10-generic (64-bit)
Graphics Platform: Wayland
Resolution: 2560 x 1600
Scaling: 125%
```

In `perfs_user.config` I have `vertical_move_amount` set to `1`
I am using sioyek 2.0.0

**Comment by jbirnick** [comment]
I have the same issue. Also @JoostScheffer it would be great if you could support [this issue](https://github.com/ahrm/sioyek/issues/867).

**Comment by ahrm** [comment]
We have a `scrollview_sensitivity` config option to configure sensitivity in overview window:

```
scrollview_sensitivity 0.1
```
