### ISSUE TITLE
Cannot search for arabic strings

### ISSUE THREAD

**Issue by llight3** [ahrm/sioyek#858]
I tried to search for the Arabic word "ترجمة" then while I am able to type the word into the search bar the search returns nothing even though other pdf readers can find multiple instances of it within my pdf, namely zotero.

**Comment by ahrm** [comment]
I think mupdf's default search does not properly support RTL languages. However, in the development branch RTL searches are working when `super_fast_search` is enabled (we use our own search algorithm then).
