### ISSUE TITLE
[Feature Request] set a "page offset"

### ISSUE THREAD

**Issue by kaiwizz** [ahrm/sioyek#86]
It would be nice to be able to set a page offset. That would mean to jump to the "book's page number" instead of the pdf's.

**Comment by MarcelRobitaille** [comment]
Shouldn't there be a way to detect this? [Zathura](https://git.pwmt.org/pwmt/zathura) is able to show the document page number as well as the PDF page number. It also shows roman numerals for the front pages. 

On frontpage ix, ix is shown as well as the true page number (9/135).
![image](https://user-images.githubusercontent.com/8503756/171553435-60795e98-6499-4d16-8b8d-cdff89059135.png)

On the first page after the front pages, a 1 is shown as well as the true page number (19/135).
![image](https://user-images.githubusercontent.com/8503756/171553501-697e5e5d-d4ec-4f01-b4ed-b52893c38776.png)

If it's possible to detect this, then maybe this should be taken into account when jumping to a page. Just an idea.
