### ISSUE TITLE
[Feature Request] Recolor MacOS Titlebar

### ISSUE THREAD

**Issue by ZakSingh** [ahrm/sioyek#860]
I use Sioyek as a previewer for latex next to my vim terminal. I've set up sioyek to match the color palette, but it would be incredible if the window title bar could be recolored to match as well. I think this must be possible, as some other apps like Chrome and the Kitty terminal provide the option.

<img width="1256" alt="Screen Shot 2023-11-10 at 9 24 15 AM" src="https://github.com/ahrm/sioyek/assets/18584287/68b103ec-f11c-457c-8b09-6509a04b8430">

**Comment by ahrm** [comment]
Added a `macos_titlebar_color` config option in https://github.com/ahrm/sioyek/commit/d9b1d2fdd4dbd4eeb25bcfd8265bf1ef230c33d2.

**Comment by FliiFe** [comment]
Could an option be added to control the text color as well ? The curreny behavior seems to be that the filename is rendered with the system colorscheme regardless of the statusbar background color, which is definitely the intended behavior when the background has not been modified, but leads to very low contrast during the day or at night depending on the custom background color chosen.

![CleanShot 2024-04-03 at 14 44 38@2x](https://github.com/ahrm/sioyek/assets/8740385/492315dd-71b4-4dfa-96f8-393cf0efa667)
