### ISSUE TITLE
[Feature] Add a Focus mode: hide the title bar when windowed

### ISSUE THREAD

**Issue by aleksmark98** [ahrm/sioyek#862]
It would be a great option to save the extra screen space. 
Currently most programs in my workflow have a mode that allows me to focus purely on the content of the window without any distractions (focusmode in windows terminal, navbar-less and tabless mode in Vieb). It would be great if sioyek could also do that on Windows.

**Comment by ahrm** [comment]
We do have a `toggle_titlebar` command but I think it was buggy in previous versions of Qt. I think this is fixed on development branch when built using qt 6.6 .
