### ISSUE TITLE
Page separator overlaps content

### ISSUE THREAD

**Issue by deusipse** [ahrm/sioyek#864]
**Description**
If there is no separator, then it looks like this: <img width="814" alt="image" src="https://github.com/ahrm/sioyek/assets/69350438/58b974ca-eec4-4bcd-b065-d1d7b387c9e1">
If `page_separator_width` is set to `10`, then it looks like this: 
<img width="808" alt="image" src="https://github.com/ahrm/sioyek/assets/69350438/e9300c8a-a29b-426b-9f9c-f23544774e08"> The page numbers are partially obscured.

**Expected behaviour**
The page separator should not obscure content.

Using version 2.0.0

**Comment by ahrm** [comment]
We added a `real_page_separation` config option in the development branch, which enables actual page separation instead of the virtual box that we draw normally. Note that the original non-separated pages are way faster, so this option is disabled by default.
