### ISSUE TITLE
Minimum window size

### ISSUE THREAD

**Issue by deusipse** [ahrm/sioyek#865]
Currently there seems to be a limit on the size of the window: 
<img width="593" alt="image" src="https://github.com/ahrm/sioyek/assets/69350438/005f3615-44be-4051-b7b2-7c586a3b4c08">
This seems to be around 500 pixels wide and 530 pixels tall.
Is it possible for this limit to be removed, or is it a limitation of the software used to render the window? Zathura does not have this problem for me.

**Comment by ahrm** [comment]
Removed the minimum size requirement is this commit in development branch: https://github.com/ahrm/sioyek/issues/865.
