### ISSUE TITLE
Inverse search without clicking

### ISSUE THREAD

**Issue by hajg-ijk** [ahrm/sioyek#868]
Hi! First of all, thank you for this brilliant software!

Secondly, since sioyek is very much keyboard-oriented, is there a good way of performing an inverse search with synctex without the need to use the mouse to click?
I initially thought of trying to define a custom command but then realized that there is no way to get a "y coordinate" for synctex from the available input parameters.
Ideally, it would be great to be able to jump to the line in the source file that corresponds to the line in focus selected through the `focus_text` command in sioyek (or something else along those lines, too, like with `keyboard_select`).

Is there any way to make something like this happen?

**Comment by ahrm** [comment]
In the next version of sioyek (not released yet) there will be a command to focus on the current focused line.

**Comment by ahrm** [comment]
The code for next version is released in the develpoment branch of this repository (no binaries yet though). You can see a demo here: https://github.com/ahrm/sioyek/issues/918#issuecomment-1899959646 .
