### ISSUE TITLE
Display bug when viewing reference by right clicking on cites and fastread is on

### ISSUE THREAD

**Issue by zz-f-g** [ahrm/sioyek#873]
It seems the order of display is wrong. The light-colored letters are on the top. Reference content is beyond the boundary and is displayed under light-colored letters.
![image](https://github.com/ahrm/sioyek/assets/80188984/06af9580-ccb8-476d-86dc-c6a916e75e0b)

**Comment by ahrm** [comment]
Should be fixed in this commit in development branch:

![fastread_overview](https://github.com/ahrm/sioyek/assets/6392321/da9afea8-df9a-4186-abd1-79a4c5cee136)
