### ISSUE TITLE
[Question] Can sioyek build with custom libmupdf？

### ISSUE THREAD

**Issue by SilverRainZ** [ahrm/sioyek#874]
Hello sioyek authors, thank for your awesome software.

I notice [v2.0.0](https://github.com/ahrm/sioyek/releases/tag/v2.0.0) can not run on Arch Linux because [its libmupdf](https://archlinux.org/packages/extra/x86_64/libmupdf/) too new (1.23.6), but sioyek 2.0.0 vendors 1.23.3 headers.

I am not sure why libmupdf has such strict version requirements, as it is hard to use the old version package on Arch Linux, I want to ask:
- whether we have any way to build sioyek with custom libmupdf
- or, can you upgrade libmupdf submodules and 
- if you have idea, please tell me

thanks again.

See also: https://github.com/archlinuxcn/repo/issues/3524

**Comment by ahrm** [comment]
Yes, in fact it is the default way that we build the appimage builds. We will update the mupdf submodule when the next sioyek version is released. The choice to use the system's mupdf was not mine, in fact I predicted this and complained about it prodigiously here for example: https://github.com/ahrm/sioyek/issues/302#issuecomment-1219673466 .
