### ISSUE TITLE
fit to content cuts of document

### ISSUE THREAD

**Issue by yashamon** [ahrm/sioyek#880]
Fit to content i.e. F10, cuts of parts of document, in my case the bottom. I think Sumatra solves this by fitting adaptively, measuring both top and side margins.

**Comment by jinjiaodawang** [comment]
You can try F5.

**Comment by yashamon** [comment]
F5 has nothing to do with my question.

**Comment by ahrm** [comment]
Also added a `fit_to_page_smart` command in https://github.com/ahrm/sioyek/commit/29772b6e218e76ade989350e9ddbf9d863aa5c59 which uses the minimum of width and height to fit the page.
