### ISSUE TITLE
Combine Full Screen with fit to page width

### ISSUE THREAD

**Issue by Bluey26** [ahrm/sioyek#885]
Hello.

First of all, thank you for this awesome program, i really like the annotation/highlights approach (only visible under the program) and the big possibilities to customize the keys/orders.

I was trying to do the following:
I have F11 binded to `toggle_fullscreen` but i would like it to work as:

`toggle_fullscreen;fit_to_page_width <f11>`

Tried that and it just toggles full screen, without changes in the width.

I was thinking in a way to 'press' the F9 key (default key for `fit_to_page_width`) after going/coming fullscreen. My idea is to make it fix the width in both cases, to make it readable when its fullscreen and when it is not.

Other commands were successfully linked (i.e. `goto_end;goto_bottom_of_page <end>` inside `keys_user.config` works properly)

Is this possible? How?

Thank you.

PS: I would also like to have some 'space' or black line to delimit the bottom border of the current page and the next one, i have found about `visual_mark` concept in the documentation but i am not sure on how to use it/how it works.

**Comment by ahrm** [comment]
This  should ideally work: `toggle_fullscreen;fit_to_page_width <f11>`, but I think it doesn't because qt handles fullscreen toggles asynchronously.

> PS: I would also like to have some 'space' or black line to delimit the bottom border of the current page and the next one, i have found about visual_mark concept in the documentation but i am not sure on how to use it/how it works.

We do have a `page_separator_width` config option which draws a line between pages.

**Comment by Bluey26** [comment]
Thanks for your answer, yes, the command does not work, i  have to manually press F9 to fit page width.

I just have tried to add to my `prefs_user.config` the following lines (as stated in the documentation):

```
page_separator_width 2
page_separator_color 0.5 0.5 0.5
```
I also have tried to change those color values and the width, but i do not see the separation between the lines(paper color is white and the background is black, i guess that the line should be a grayish color (0.5?))

I am using the `sioyek-appimage 2.0.0-2` package for Arch AUR. I have other options in the `prefs_user.config` and they seem to work.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/dd8c570f7f5df145931edaffb1c8abc7a5e4caea and using something like this:
```
toggle_fullscreen;wait_for_renders_to_finish;fit_to_page_width <f11>
```
