### ISSUE TITLE
[Feature Request]  Option for Centered Visual Mark During Navigation

### ISSUE THREAD

**Issue by ChuanyuXue** [ahrm/sioyek#889]
**Issue Description:**
Currently, when navigating after `enter_visual_mark_mode` with `j,k`, the visual mark does not remain centered on the screen. This requires frequent use of the ` `` ` key to re-center it. I tried to achieve this by combining some key binds, but it seems not possible to automatically execute ` `` ` after `j,k`.

**Feature requested:**
Is that possible to add a feature or a mode where the visual mark automatically stays centered on the screen while moving it up or down? Ideally, the screen would scroll one line at a time in sync with the visual mark movement, maintaining its central position.

**Comment by ahrm** [comment]
You can achieve this by setting:
```
visual_mark_next_page_fraction  0
visual_mark_next_page_threshold  1
```

**Comment by ChuanyuXue** [comment]
That works perfectly! Thank you for making this great project!
