### ISSUE TITLE
Disable left/right scroll when using the touchpad

### ISSUE THREAD

**Issue by A3EKV** [ahrm/sioyek#89]
Hello,
It seems that using the laptop touchpad to scroll using two fingers is not perfect because it causes a left/right scroll.
As shown below (In the recording I am using the touchpad to scrol up/down):

https://user-images.githubusercontent.com/90999345/139559006-41b50024-c583-4bb5-b1c4-07a409ccc97f.mp4

Is there a way to disable the left/right scrolling?

Thank you

**Comment by ahrm** [comment]
Added a command named `toggle_horizontal_scroll_lock` in 5d793478e33b16d7f0bffcbfece053f7253f2e30 which allows you to lock horizontal scroll.

**Comment by A3EKV** [comment]
> Added a command named `toggle_horizontal_scroll_lock` in [5d79347](https://github.com/ahrm/sioyek/commit/5d793478e33b16d7f0bffcbfece053f7253f2e30) which allows you to lock horizontal scroll.

Thank you very much for implementing that.
I have tested it and it works fine. 
Is there a way to make that as the default?

Thank you

**Comment by ahrm** [comment]
> > Added a command named `toggle_horizontal_scroll_lock` in [5d79347](https://github.com/ahrm/sioyek/commit/5d793478e33b16d7f0bffcbfece053f7253f2e30) which allows you to lock horizontal scroll.
> 
> Thank you very much for implementing that. I have tested it and it works fine. Is there a way to make that as the default?
> 
> Thank you

I added a `startup_commands` configuration which allows you to give a comma-separated list of commands to be executed when sioyek starts up. For example to achieve the desired effect, you can add the following to your `prefs_user.config`:
```
startup_commands		toggle_horizontal_scroll_lock
```

**Comment by nickdvlpr** [comment]
> ```
> startup_commands		toggle_horizontal_scroll_lock
> ```

The command "toggle_horizontal_scroll_lock" itself works when I enter it each time I open the app, but I copied this above line of yours into my prefs_user.config and it does not seem to remember my preference on startup. Do you have an idea why this is the case? It is the only line of code in that file for me - I'm on MacOS, so perhaps that is the issue.

**Comment by nickdvlpr** [comment]
Thank you. It appears my issue was I was editing my prefs_user.config by right-clicking the application and choosing "Show package contents" which does not appear to work. I found the correct file to edit within the app with ":" followed by "prefs_user"
