### ISSUE TITLE
bug report: hyperlink when no hyperlink

### ISSUE THREAD

**Issue by zhizhongpu** [ahrm/sioyek#890]
I hover over an entire page of text that does not have a hyperlink but the sioyek somehow detects a hyperlink (that sends me to the bibliography) 
![20231219_210451](https://github.com/ahrm/sioyek/assets/84325421/13be610f-e96a-4acd-af54-52d2043f3e92)

**Comment by ahrm** [comment]
Can you share the PDF here?

**Comment by ahrm** [comment]
I assume this was a malformed PDF which actually had an invisible link in that location. Feel free to reopen the issue if this is not the case.
