### ISSUE TITLE
Default selection of command and file selectors

### ISSUE THREAD

**Issue by tonyhu-x** [ahrm/sioyek#893]
Currently, when invoking the command selector (via ":") or the file selector (via "o"), the behaviour when pressing "return/enter" with no input is to select and apply the first item. However, I find this a bit unintuitive. It would be better if, instead of having "nothing" selected by default, the widget always selects the first item and highlights it. Example of a similar UI is the VSCode command palette:
<img width="605" alt="image" src="https://github.com/ahrm/sioyek/assets/54758881/396acdb8-feee-49cc-ba8f-d5054e7270ee">

I'm happy to work on this if people agree with the idea.

**Comment by ahrm** [comment]
Should be fixed in this commit in development branch: https://github.com/ahrm/sioyek/commit/d537c36f5af37355be1010c673a5a1d6a8a90260.
