### ISSUE TITLE
Scrolling inside a preview window is too fast

### ISSUE THREAD

**Issue by fofusa** [ahrm/sioyek#894]
When opening a preview (right click on a figure number or reference number) the scrolling inside the preview window is too fast.
It is noticeably faster than when scrolling the text in the main window.
With a trackpad, it is almost impossible to scroll down a tall figure without overshooting.
It might be related to my device (HP elitebook with stock Ubuntu) but I don't have any issue with other apps.

Cheers,

Fofusa.

**Comment by jinjiaodawang** [comment]
I encountered the same issue on macbook. I found the specific part of the code in Sioyek that controls the scroll speed in the preview window:
https://github.com/ahrm/sioyek/blob/779b52e36de9d596dc708ada045ea48af0c21c9d/pdf_viewer/main_widget.cpp#L2896
is set to scroll at half the speed of the main document, which is defined by:
`move_document(0.0f, 72.0f * amount * VERTICAL_MOVE_AMOUNT);`
If you, like me, find the preview scrolling too fast, a simple fix is to modify the value from 36.0f to a smaller number, such as 10.0f, which significantly reduces the scroll speed. After making this change, you'll need to compile the code locally to apply the modification.

**Comment by ahrm** [comment]
We have a `scrollview_sensitivity` config option which is used to adjust this sensitivity. For example you can add this to your `prefs_user.config`:
```
scrollview_sensitivity 0.1
```

**Comment by fofusa** [comment]
Thanks, that works like a charm!
Sadly, this seams to be undocumented as I did not find any mention of this on https://sioyek-documentation.readthedocs.io
Is this a stable feature?

Fofusa

**Comment by ahrm** [comment]
Yes it is stable, I have not had the time to update the documentation unfortunately.

**Comment by fofusa** [comment]
Hello again,
Weirdly enough, I tried to use the same setting on another computer but it does not work:
- adding `scrollview_sensitivity 0.1` to `prefs_user.config` does not change the speed of the scrolling in the preview
- when launched from the command line, sioyek reports an error:
`Error: scrollview_sensitivity is not a valid configuration name`

**Comment by ahrm** [comment]
Maybe you are using an older sioyek version?

**Comment by fofusa** [comment]
```
$ sioyek --version
     sioyek 2.0.0
```

**Comment by ahrm** [comment]
Did you use the same sioyek package for both computers?

**Comment by fofusa** [comment]
Yes, I think I installed them the same way, using the appimage.
I'll double check on Monday when I have both computers with me.

Fofusa

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/762e5a8aa195171f745149da32e11a671cd76aa5. Now scrolling speed in overview automatically matches normal scrolling speed, no further configuration should be necessary.
