### ISSUE TITLE
Required symbol pdf_parse_link_uri not found

### ISSUE THREAD

**Issue by clausecker** [ahrm/sioyek#897]
Sioyek uses the mupdf symbol `pdf_parse_link_uri` to parse a URI.  Unfortunately, this symbol has been dropped in mupdf 0.23, causing sioyek to no longer build.  Please redesign the code to no longer require this symbol.

See also this [Debian bug report](https://groups.google.com/g/linux.debian.bugs.dist/c/jbWpPKPjBXw).

As a temporary workaround, I'll go and apply this [Debian patch](https://salsa.debian.org/viccie30/sioyek/-/commit/3dd9671765b495812d3bcd4b629d51e5d50f0745) to the FreeBSD package.

**Comment by viccie30** [comment]
I'm the maintainer of Sioyek in Debian. I didn't write the patch myself. I took it from Alpine Linux at https://git.alpinelinux.org/aports/commit/?id=86e913eccf19b97a16f25d9b6cdf0f50232f1226.

**Comment by ahrm** [comment]
Fixed in this commit in development branch: https://github.com/ahrm/sioyek/tree/development. We use `fz_resolve_link_dest` now which I assume is not removed?
