### ISSUE TITLE
Add shortcut for sending a term as a simple search engine query (eg. google) instead of scholars/libgen

### ISSUE THREAD

**Issue by PurpleAzurite** [ahrm/sioyek#90]

**Comment by PurpleAzurite** [comment]
Or better yet, expose what URLs the application uses to perform searches in user config files. For instance, the libgen URL used in the current program version is inaccessible in my country. With the ability to change this in configs, this functionality can easily be restored.

**Comment by ahrm** [comment]
> Or better yet, expose what URLs the application uses to perform searches in user config files. For instance, the libgen URL used in the current program version is inaccessible in my country. With the ability to change this in configs, this functionality can easily be restored.

We already do this. The relevant part in `prefs.config` is:
```
google_scholar_address  https://scholar.google.com/scholar?q=
libgen_address          http://gen.lib.rus.ec/scimag/?q=
```

**Comment by ahrm** [comment]
Added the ability to configure more than those two search engines in e0b68e417c45dcfb7bffbafd19ff6f7a52420bf9.
See https://sioyek-documentation.readthedocs.io/en/latest/usage.html#external-search for more information.

**Comment by PurpleAzurite** [comment]
Thanks, the improvements work nicely.
