### ISSUE TITLE
option / command to enable (not toggle) synctex

### ISSUE THREAD

**Issue by pitkling** [ahrm/sioyek#900]
I'm using sioyek as my PDF viewer for vimtex (a vim plugin for LaTeX editing). In this mode, I'd like to have sioyek automatically activate synctex. Since I don't want to have synctex enabled if I start sioyek manually, I tried to activate it via the vimtex configuration, which allows me to give command line options to sioyek, e.g., via

```
vim.g.vimtex_view_sioyek_options = '--execute-command toggle_synctex'
```

in my (lua-based) Neovim config. But these options are executed each time I make a forward sync (syncing my cursor position from vimtex to sioyek), causing it to disable the synctex option each other forward sync. Would it be sensible to have a command line option that **enables** synctex instead of toggling it? Or is there a better way to achieve my goal I'm unaware of?

Thanks for the help (and the great program)!

**Comment by ahrm** [comment]
Unfortunately there is currently no way to do that but we'll probably have a command to do that in the next version.

**Comment by ahrm** [comment]
Okay I had forgotten that I already added a `turn_on_synctex` command in development branch here: https://github.com/ahrm/sioyek/tree/development .

**Comment by pitkling** [comment]
Cool, that'll be helpful until it gets merged into the main branch. Thanks! 🙂
