### ISSUE TITLE
[FR] Opening a file at a specific page

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#906]
I like to be able to link to locations inside PDF files in my notes. To do this, two things need to be implemented on the PDF viewer:
1. A command to copy the current location in the PDF file as a string (ideally including the page number, the exact location and zoom). E.g.,
```
/.../some.pdf::{page=12, zoom=150, x=0, y=120}
```
2. A way to open the PDF from the above string. (This should be usable from the command line so that external programs can do it.)

**Comment by NightMachinery** [comment]
Seeing the command `copy_link`, it seems most of the infrastructure for doing this already exists. It might even be possible already.

**Comment by ahrm** [comment]
Added the ability to access x and y offset in custom commands in https://github.com/ahrm/sioyek/commit/5121c9010e0c82f7cf41ae4d398e0748b5b3ba86. You can achieve what you specified by adding this to your prefs:
```
new_command _copy_location command_to_copy_to_clipboard "%{file_path}::{page=%{page_number}, zoom=%{zoom_level}, x=%{offset_x_document}, y=%{offset_y_document}}"
```
(replace command_to_copy_to_clipboard with the appropriate command for your OS).

It is already possible to open sioyek at a specific location:
```
sioyek <file path> --page <page> --xloc <offset_x> --yloc <offset_y> --zoom <zoom_level>
```

**Comment by NightMachinery** [comment]
Great!
