### ISSUE TITLE
Add ability to create notes in pdf files from Sioyek

### ISSUE THREAD

**Issue by PurpleAzurite** [ahrm/sioyek#91]
I have no idea how complicated or feasible this feature would be, but being able to jot down notes inside a pdf is very useful for a viewer aimed at scientific research work.

The mechanism should probably be implemented so the user can jot down notes on highlighted / marked text.

**Comment by ahrm** [comment]
Well we already have the bookmark feature which allows you to add notes. If you mean some feature where notes are drawn over the PDF page, it is pretty difficult to implement well and it is unlikely to be added anytime soon.

**Comment by PurpleAzurite** [comment]
The feature just makes a lot of sense for a pdf reader aimed at research papers. I currently use the app daily for my degree, and the feature would've been great. Regardless, if it's very hard to implement, then it's understandable.
