### ISSUE TITLE
Search bar not adjusting to font size (text too large for bar)

### ISSUE THREAD

**Issue by prosoitos** [ahrm/sioyek#916]
![2024-01-15_15-43](https://github.com/ahrm/sioyek/assets/4634851/0ea29ec1-df30-472b-b41a-1b151c833bdd)

Using version from the AUR: https://aur.archlinux.org/packages/sioyek-git
OS: Arch Linux 6.6.10

Thanks!!

**Comment by NightMachinery** [comment]
There are related issues, I have sent a PR for the command palette, for example. You should link them in a related section.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/445b76342ff792c17aff23c9dbfb9c3c70451284.

**Comment by prosoitos** [comment]
Thank you!!
