### ISSUE TITLE
Option to make SyncTeX box invisible

### ISSUE THREAD

**Issue by ravibrock** [ahrm/sioyek#918]
Hello - I wanted to submit a feature request for an option to make the SyncTeX box invisible/transparent. I really like that Sioyek automatically loads the correct file location when SyncTeX is enabled, but I find that the highlight box obscures the text. Ideally I would be able to use SyncTeX like usual, but make it so that the highlight box doesn't show up. I'll attach a picture of the highlight box below if what I'm referring to is unclear. Of course this is a fairly minor feature, as Sioyek is an amazing PDF viewer already, but it would be very convenient. Thank you!

Current behavior (though I have it highlighted in white to be more unobtrusive than the below image):
![Screenshot 2024-01-16 at 11 12 41](https://github.com/ahrm/sioyek/assets/66334356/5a478c74-020d-493e-8d25-0f49402d22f4)

Desired behavior:
![Screenshot 2024-01-16 at 11 13 04](https://github.com/ahrm/sioyek/assets/66334356/4d7c9ffb-12c2-4986-b008-f588bbeb3d2b)

**Comment by jinjiaodawang** [comment]
```
synctex_highlight_color    1.0 1.0 1.0
```
add this line to your configure file.

**Comment by ravibrock** [comment]
That highlights it in white–it's what I have it set to at the moment. It's better than the bright color, but still obscures the PDF (especially in certain cases, like images).

**Comment by jinjiaodawang** [comment]
Sorry about that, but it seems the `set_synctex_highlights` method is not conditioned on any configuration currently, it is mandatory by design.

**Comment by ravibrock** [comment]
That makes sense; it seemed that way from the docs as well. That's why I created this issue, since it would be nice to either have a way to disable it or to be able to set a transparency value in my Sioyek config file the way you can for, say, `visual_mark_color`.

**Comment by ahrm** [comment]
There are already multiple fixes for this in the development branch here: https://github.com/ahrm/sioyek/tree/development.
Now by default we only flash the synctex highlight and then hide it, there is also an option to use the ruler to highlight the synctex line which is useful because it can also be used to do a forward search from sioyek into the latex file. Video showing these features:


https://github.com/ahrm/sioyek/assets/6392321/6c8988e7-f1f7-4987-b453-e78f7eb934ed

**Comment by ravibrock** [comment]
Ah, that looks perfect. Thank you! Do you have any idea of when this will go into a binary? I can build from source if need be, but typically I try to keep everything consolidated in Homebrew installs.

**Comment by ahrm** [comment]
I don't have a timeline on when the next binaries will be released. Note  that the development branch is under heavy development and it might be buggy, so if you want to use them I recommend you backup your sioyek data (local.db and shared.db files) in case there is a corruption.

**Comment by ravibrock** [comment]
Ok, that all makes sense. Thanks for the help!

**Comment by DaitiDay** [comment]
Any updates on this?
