### ISSUE TITLE
`open_prev_doc` and `goto_toc` do not display text

### ISSUE THREAD

**Issue by Weznon** [ahrm/sioyek#92]
After updating to v1.0.0 through a clean rebuild from source (i.e. deleting the old build/binary/source), the `open_prev_doc` command's menu does not display any filenames or search text. The menu otherwise functions as normal, so the order of files gets updated properly as I open them and the correct file is opened. Additionally,  `open_documents_embedded` renders properly.

This image is the result of me running the `open_prev_doc` command.
![2021-11-03-1635975894](https://user-images.githubusercontent.com/14968011/140197693-f58e9065-669f-44d9-886c-8c3613ea4523.png)

A similar issue happens for `goto_toc`. It displays arrows for sections and the color of the highlights is as it was before, but no text is rendered. I do not use the other menus for marks or bookmarks so I am unsure whether it effects those as well.

I cannot remember which commit I had previously built sioyek from -- I can try to figure it out if needed. Please let me know if any system information is needed as well.

**Comment by ahrm** [comment]
Does this commit e4f00850c5081f9462c82a3a24e2c07174a96ea8 resolve the issue? (I was not able to reproduce the issue and I had to take a guess on what caused it, so I am not sure if it is fixed)

**Comment by Weznon** [comment]
It does! Thank you very much.
