### ISSUE TITLE
[Feature request]: classic Emacs-style kbd to edit typed words in the command line, bookmark list, toc, etc.

### ISSUE THREAD

**Issue by prosoitos** [ahrm/sioyek#921]
Thank you for the software ❤️ and my apologies if I missed something in the issues and/or documentation.

Would it be possible to have classic command line key-bindings to navigate and edit inputs in the command line, table of contents, bookmark list, etc.?

I am referring to the Emacs-style kbd that work by default in shells and most applications that use a command line:

```
- <C-a>: go to beginning of line
- <C-e>: go to end of line
- <C-k>: kill to end of line
- <C-f>: move forward one character
- <C-b>: move backward one character
- <A-f>: move forward one word
- <A-b>: move backward one word
- <C-h>: delete one character backward
- <C-d>: delete one character forward
```

`<C-u>` does clear the input, but all other keys I tried didn't work.

The functionalities to search toc, bookmarks, commands, etc. are really awesome in sioyek, and getting better as the fuzzy finding is improving, but editing the inputs remains a bit awkward.

Thank you so much!!!!

**Comment by ahrm** [comment]
We use the `qt`'s textbox for these functions, so I don't know how easy it would be to implement these though I agree it would be awesome if they were implemented.

**Comment by prosoitos** [comment]
OK. Thank you! 🙂

I have no idea whether that might be of any help, but I use [qutebrowser](https://github.com/qutebrowser/qutebrowser) as my web browser. It is also Qt based and all of the classic kbd are implemented when typing into the command/bookmark/etc. bar.

**Comment by prosoitos** [comment]
Note: I edited my initial post as I hadn't realized that GitHub Markdown had not rendered my kbd between `<>`.

**Comment by ahrm** [comment]
Added in this commit in development branch: https://github.com/ahrm/sioyek/commit/26bdde0b3dee71ce197a7d2d2e17e027049c53e2. We previously had an `emacs_mode_menus` config option but it did not support any of the shortcuts you requested. Now if `emacs_mode_menus` is set we use those shortcuts in menu line edits.

**Comment by prosoitos** [comment]
Amazing! Thank you so much ahrm!!! And thank you for implementing this so quickly!!!

**Comment by ahrm** [comment]
Removed `EMACS_MODE` in https://github.com/ahrm/sioyek/commit/208e0a8975fe373581c08ae49a7b0620fccf8709, because we now can bind custom commands even while in menus. For example, the previous `EMACS_MODE` can be achieved by adding this to `keys_user.config`:

```
[m]control_menu(move_to_begin) <C-a>
[m]control_menu(move_to_end) <C-e>
[m]control_menu(delete_to_end) <C-k>
[m]control_menu(cursor_forward) <C-f>
[m]control_menu(select_forward) <C-S-F>
[m]control_menu(cursor_backward) <C-b>
[m]control_menu(delete_prev_char) <C-h>
[m]control_menu(delete_prev_word) <C-w>
[m]control_menu(select_backward) <C-S-B>
[m]control_menu(delete_next_char) <C-d>
[m]control_menu(move_word_forward) <A-f>
[m]control_menu(select_word_forward) <A-S-F>
[m]control_menu(move_word_backward) <A-b>
[m]control_menu(select_word_backward) <A-S-B>
```

The `[m]` prefix means that this command is only active while we are in menus.

**Comment by prosoitos** [comment]
That's great! I like this even better as it gives full flexibility and control to the user.

Thank you ahrm!!!

**Comment by nikinbaidar** [comment]
> Removed `EMACS_MODE` in [208e0a8](https://github.com/ahrm/sioyek/commit/208e0a8975fe373581c08ae49a7b0620fccf8709), because we now can bind custom commands even while in menus. For example, the previous `EMACS_MODE` can be achieved by adding this to `keys_user.config`:
> 
> ```
> [m]control_menu(move_to_begin) <C-a>
> [m]control_menu(move_to_end) <C-e>
> [m]control_menu(delete_to_end) <C-k>
> [m]control_menu(cursor_forward) <C-f>
> [m]control_menu(select_forward) <C-S-F>
> [m]control_menu(cursor_backward) <C-b>
> [m]control_menu(delete_prev_char) <C-h>
> [m]control_menu(delete_prev_word) <C-w>
> [m]control_menu(select_backward) <C-S-B>
> [m]control_menu(delete_next_char) <C-d>
> [m]control_menu(move_word_forward) <A-f>
> [m]control_menu(select_word_forward) <A-S-F>
> [m]control_menu(move_word_backward) <A-b>
> [m]control_menu(select_word_backward) <A-S-B>
> ```
> 
> The `[m]` prefix means that this command is only active while we are in menus.

This fails when I open sioyek with no document. Meaning, when I run sioyek and it displays "no document" in red with a black background and I try to move to some file using the menu, these bindings don't work.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/6127c2abd59d0626aa39309b905d06f0a79ee00d.

**Comment by nikinbaidar** [comment]
Awesome.
