### ISSUE TITLE
Highlights disappeared after switching from Flatpak to AppImage.

### ISSUE THREAD

**Issue by adhiraj2001** [ahrm/sioyek#922]
Recently I decided to switch from Flatpak to AppImage as I found out that the Flatpak doesn't support custom configurations (?). Before the switch, I made sure the highlights were visible from both instances of the application. Even after uninstalling the Flatpak, the highlights were visible at first, but then disappeared on reboot.

I have tried searching for the highlight data in the directories related to the Flatpak installation but couldn't locate any relevant files. I suspect that the highlights may be stored in the Flatpak cache or a specific location that I'm not aware of.

Could someone provide guidance on how I can recover the highlights in this situation. 
Also, just want to thank the author for this wonderful open source project.

(Would also appreciate some suggestions in how I can prevent from similar situation from happening again since everything to be stored in common db seems a bit unsafe and would much prefer some kind of backup at the same location similar to Xournal++)

**Comment by ahrm** [comment]
You can find the database files for the flatpak (`local.db` and `shared.db`) and replace them in place of appimage database files (the location of these files should be printed when launching sioyek from command line).

**Comment by adhiraj2001** [comment]
Hey, thanks for the quick response !!
Following what you said, I was able to recover my highlights, but only from the time when I *just* had the Flatpak.
It seems like all the highlights since I started using the AppImage magically disappeared. 

Does changing the location of AppImage or replacing it with another version somehow overwrite these .db files ?
The only changes I seem to recall making to the AppImage is to update the version and recently change the location to create common AppImage directory to automate creating a desktop file using `appimaged`.

**Comment by ahrm** [comment]
Yes, the appimage and flatpak use different locations for database files.

**Comment by adhiraj2001** [comment]
> Yes, the appimage and flatpak use different locations for database files.

I understand that both of these applications have different location for database files, it's just that database file at `~/.local/share/Sioyek/` (which the AppImage uses) got overwritten for seemingly no reason, and I don't have these highlights anywhere. Initially I suspected that these highlights might be in the Flatpak Application cache, but this also doesn't seem to be the case.

Anyways, I am not sure if you'd be able to help me here without any specific details, so I will close the issue here.
At the end, I just want to know how can I prevent this from happening again and keep some kind of backup for these highlights as I mentioned before.

**Comment by adhiraj2001** [comment]
I think I understood the issue, it has to do with the portable version of the AppImage, and it stores the database files in a different location as compared to the normal version.

Is there any documentation as to how portable version works differently @ahrm ?

**Comment by ahrm** [comment]
I don't remember if I wrote a documentation on that. The portable version stores the database files in a directory inside the appimage if I remember correctly.
