### ISSUE TITLE
The label selection input bar obstructs the navigation links of slides

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#924]
<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/87cc5b8d-107b-4dd7-b8b5-fbd4db9b40cb">

<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/fff6405c-c919-4275-8843-7c4d82cc5962">

Possible solutions:
1. Show the input bar over the status bar instead (ala emacs minibuffer).
2. Make the input bar transparent. (not sure if this is enough)
3. Better yet, not show the bar at all. We can just change the color of the first key in labels that match, to show the user that they have pressed that key. If there are no labels with more characters, we can even get rid of the need to press enter. Vimium, Homerow, emacs avy, etc. use this approach.
In this screenshot (of Homerow), notice how `J` is highlighted as pressed:
<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/5cbea9ab-1aa7-4b1e-8189-6c8347d9821b">

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/6394761ab7f7fcb3c304a429d5d70a63b429c589. I used the following config options:
```
hide_overlapping_link_labels 0
alphabetic_link_tags 1
```

**Comment by NightMachinery** [comment]
Thanks, it's great.
