### ISSUE TITLE
can't build  the dev

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#926]
Cloned the dev branch with

```
git clone --recursive --branch development https://github.com/ahrm/sioyek.git
```

On Arch Linux, the `./build_linux.sh` produces following errors:

```
pdf_viewer/coordinates.h:283:16: error: there are no arguments to ‘sqrt’ that depend on a template parameter, so a declaration of ‘sqrt’ must be available [-fpermissive]
  283 |         return sqrt(norm_squared);


pdf_viewer/touchui/TouchSettings.cpp:226:17: error: invalid use of incomplete type ‘class QScreen’
  226 |     if (screen()->orientation() == Qt::PortraitOrientation) {
```

Adding  `#include <cmath>` and `#include <QScreen>` in the respective
files fixes these errors. However, I've been getting a qt error in the final
make in [L#21](https://github.com/ahrm/sioyek/blob/development/build_linux.sh#L21).

```
pdf_viewer/touchui/TouchDrawControls.cpp:149:30:   required from here
/usr/include/qt/QtCore/qobjectdefs.h:535:5: error: no type named ‘type’ in ‘struct std::enable_if<false, bool>’
```

I have installed all of the packages [specified here](https://github.com/ahrm/sioyek/tree/development#build-instructions).

```
$ qtplugininfo-qt5  -v
qplugininfo 5.15.12
```

I've set QMAKE to all '/usr/bin/qmake-qt5' + '/usr/bin/qmake' and
'qmake' but not this issue persists.

I don't know if this is an upstream issue with Qt. Do you have any insights on how to overcome this?

**Comment by ahrm** [comment]
We use qt 6.6 for the dev version.

**Comment by nikinbaidar** [comment]
> We use qt 6.6 for the dev version.

qmake6 produces
Project ERROR: Unknown module(s) in QT: 3dinput quickwidgets texttospeech

**Comment by NightMachinery** [comment]
> > We use qt 6.6 for the dev version.
> 
> qmake6 produces Project ERROR: Unknown module(s) in QT: 3dinput quickwidgets texttospeech

Try deleting the repo, and cloning again. I had some problems with `mupdf` not being updated to the version in the dev branch, and then not being compiled correctly due to its previous build artifacts.

Addressing these two and adding a missing import, I got the build branch working on macOS.

**Comment by nikinbaidar** [comment]
> Try deleting the repo, and cloning again

I still get 
make: Nothing to be done for 'default'.
Project ERROR: Unknown module(s) in QT: 3dinput quickwidgets texttospeech

**Comment by NightMachinery** [comment]
> > Try deleting the repo, and cloning again
> 
> I still get make: Nothing to be done for 'default'. Project ERROR: Unknown module(s) in QT: 3dinput quickwidgets texttospeech

On macOS, I had to add 
```
export INCLUDE_PATH=/opt/homebrew/include
export LIBRARY_PATH=/opt/homebrew/lib
```
these to the compiler flags. Maybe you also need something similar on Linux.

**Comment by nikinbaidar** [comment]
> > > Try deleting the repo, and cloning again
> > 
> > 
> > I still get make: Nothing to be done for 'default'. Project ERROR: Unknown module(s) in QT: 3dinput quickwidgets texttospeech
> 
> On macOS, I had to add
> 
> ```
> export INCLUDE_PATH=/opt/homebrew/include
> export LIBRARY_PATH=/opt/homebrew/lib
> ```
> 
> these to the compiler flags. Maybe you also need something similar on Linux.

I had to install the libraries. Turns out these aren't part of the qt6-base on Arch. 

Nevertheless, `build/sioyek --version` show 2.0.0.  Isn't the latest release 2.0.0? 

Is there any thread with all the latest features included in the dev?

**Comment by ahrm** [comment]
I have not updated the version yet. No.

**Comment by nikinbaidar** [comment]
> I have not updated the version yet. No.

Okay. Actually I see the new features. 


Guess I'll play around to figure things out.


Also should I file a PR with the missing imports I came across on Linux?

**Comment by ahrm** [comment]
No the development branch is currently under heavy development so they are likely to change soon :) .
