### ISSUE TITLE
Jump using table of contents causes blank screen in some documents

### ISSUE THREAD

**Issue by GenjiFujimoto** [ahrm/sioyek#927]
As the title says, if I use the table of documents of the following [document](https://github.com/ahrm/sioyek/files/13997840/Introduction.To.Commutative.Algebra.-.Atiyah.Macdonald.pdf), then the screen becomes blank and the application has to be restarted.

**Comment by ahrm** [comment]
Can't reproduce the issue. Which OS/sioyek package are you using? If you are on linux can you reproduce the issue on official appimage binaries in this repo?

**Comment by GenjiFujimoto** [comment]
I am on ArchLinux and was using the `sioyek` package from aur.archlinux.org. There is no issue using the appimage from this repo, so I guess you can then close this issue.

**Comment by Kratacoa** [comment]
Hello, I have this issue using the Guix version of sioyek. I can reproduce it on a wide variety of documents. Not sure what other info might be helpful, let me know if you get to it!
