### ISSUE TITLE
notes about  dev

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#930]
Some notes about the dev after one day of use:

1. The single problem that drives me crazy in the dev branch is not being able to prefix a number and then press `gg` or `G` to go to a page number. I don't know if you're adding this back or not. So I am asking it here.  I see `goto_page_with_pagenumber` command but I'd like to be able to prefix the page number with `gg` like 2.0.0

2. `embed_annotations` is great but keeps asking for confirmation/file path. I would like to be able to save them annotations without being prompted.

**Comment by HakonHarnes** [comment]
> Pressing a number followed by gg should be working.

Works for me on the latest dev branch on Arch Linux 6.6.10.

**Comment by nikinbaidar** [comment]
> Pressing a number followed by gg should be working.

It was my config. So sorry about that. 

Is there a way to skip prompt for `emmbed_annoatations`?

**Comment by ahrm** [comment]
Not currently.
