### ISSUE TITLE
Adding more options to dark mode customized options

### ISSUE THREAD

**Issue by langshangyuan** [ahrm/sioyek#931]
Currently, we can only configure the `dark_mode_background_color` option to set the color of empty space which is not occupied by the document. I hope the Sioyek can support dark mode customized options like `dark_mode_text_highlight_color`, `ui_text_color`, etc. (Achieve the logical symmetry between light mode and dark mode) These new options allows users to use two different themes under dark mode and light mode to improve the user experience.

**Comment by ahrm** [comment]
We have improved this in the development branch. Now we automatically translate the colors into appropriate colors for the current mode.
