### ISSUE TITLE
Provide a null command to unbind a keybinding from keys_user.config

### ISSUE THREAD

**Issue by langshangyuan** [ahrm/sioyek#932]
I think it is of equivalent importance to remove a keybinding and to add a user-customized keybinding. For example, I think the behavior of using the `q` key to quit the sioyek is quite annoying since I often occasionally hit the quit even when I don't want to end the reading. Another situation is that I hope I can unbind the `<space>` and then use a sequence of key starting with `<space>` for a specific command. I think this allows better mnemonics for shortcuts, such as, I want to map the `<space>ff` to open recently opened documents. Although I know it is possible to remove several keybinding is the global `keys.config` file, I think this is not an elegant way to handle such problem.

**Comment by ahrm** [comment]
We do have a `noop` command which you can use to unbind keys:
```
noop q
```

**Comment by langshangyuan** [comment]
Thank you for your valuable reply! Sorry, I just cannot find it on the documentation website! However, the remaining problem is that Sioyek will ignore the `<space>` key and recognize the following keystroke as a separate keystroke. For example, if I firstly unbind the `<space>` through the `noop <space>` configuration in the `keys_user.confg`, then I try to use the map `open_prev_doc <space>ff`, Sioyek will trigger the command `open_file` associated with `f` key and `f` appears in the input bar. If I want to directly remove the map `screen_down <space>` in the `keys.config` global configuration file, Sioyek can successfully recognize the `open_prev_doc <space>ff`. For the logical sanity, I guess the `noop` command should pass the key event directly to Sioyek for further processing, or it can remove the keybinding.

**Comment by langshangyuan** [comment]
By the way, I guess Sioyek won't report configuration error when it loads these files. Before I submitted this issue, I use the `<unbound> q` to unbind the keybinding as I think this word appears in the configuration multiple times. And this approach does work, even if Sioyek cannot recognize the `<unbound>` command. Maybe Sioyek can implement a mechanism to detect configuration errors like this. Anyway, I enjoy using Sioyek very very much! Thank you for your intelligent contribution, again!

**Comment by ahrm** [comment]
> Thank you for your valuable reply! Sorry, I just cannot find it on the documentation website! However, the remaining problem is that Sioyek will ignore the `<space>` key and recognize the following keystroke as a separate keystroke. For example, if I firstly unbind the `<space>` through the `noop <space>` configuration in the `keys_user.confg`, then I try to use the map `open_prev_doc <space>ff`, Sioyek will trigger the command `open_file` associated with `f` key and `f` appears in the input bar. If I want to directly remove the map `screen_down <space>` in the `keys.config` global configuration file, Sioyek can successfully recognize the `open_prev_doc <space>ff`. For the logical sanity, I guess the `noop` command should pass the key event directly to Sioyek for further processing, or it can remove the keybinding.

I think this is already fixed in development branch in this repo. We automatically unbind all commands that are the prefix of a new command so just adding:
```
open_prev_doc <space>ff
```
should work.

**Comment by langshangyuan** [comment]
Thank you! I am pretty excited about the coming version. Does it will be released several weeks or take longer time?

**Comment by ahrm** [comment]
It probably will take longer.
