### ISSUE TITLE
[BUG?] Citation links added using xelatex need sioyek to be restarted to register as links.

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#933]
<img width="1280" alt="image" src="https://github.com/ahrm/sioyek/assets/36224762/7fc83f22-74a1-457e-b4d0-37d08971c33d">

As you see, when I add new citations and re-compile my PDF using `xelatex`, sioyek doesn't register the new links as links until I manually restart sioyek. (See the green citation numbers that have no link hints above them.) Using the command `reload` has no effect. Clicking on the links also doesn't work. Basically, sioyek thinks the links aren't there.

**Comment by ahrm** [comment]
I think the `reload` command not working might already be fixed. Can you reproduce this on the latest commits?

**Comment by NightMachinery** [comment]
> I think the `reload` command not working might already be fixed. Can you reproduce this on the latest commits?

You're right, after rebasing again, the issue went away. Sorry, I didn't think you had committed anything of importance since the last pull. Your dev velocity is great!
