### ISSUE TITLE
Feature request: open PDF from URL

### ISSUE THREAD

**Issue by mawkler** [ahrm/sioyek#935]
I would love the ability to open a new PDF from the web from just its URL.

Let's call the command `open_from_url` for now. If a PDF's URL is `https://www.example.com/example.pdf`, I would then run `open_from_url https://www.example.com/example.pdf` in Sioyek, and Sioyek would then download the PDF to a temporary directory (for instance `/tmp/`) and open the PDF.

This would decrease a lot of friction when it comes to opening a PDF that you find online.

What say ye?

**Comment by ahrm** [comment]
We already have `download_paper_with_url` and `download_clipboard_url` commands in development branch here: https://github.com/ahrm/sioyek/tree/development.

**Comment by mawkler** [comment]
That's awesome, thank you! I must have missed it when searching through issues :)
