### ISSUE TITLE
different resize_commands depending on the resize

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#938]
I really like the concept of `resize_command` on one of the recent commits, but what would be better is if you could specify different resize commands depending on whether you're increasing or decreasing the size of the window containing the pdf viewer. This would be great for those on tiling window managers. For example, if I'm increasing the window size I like `fit_to_page_width_ratio` and when I'm tiling, I like the `fit_to_page_width_smart`.

**Comment by ahrm** [comment]
This can now be done using custom javascript commands:
`resize.js`:
```
let prev_width = sioyek_api.get_variable('width');
let current_width = sioyek_api.get_json_state()["window_width"];
sioyek_api.set_variable('width', current_width);

if (prev_width != undefined){
    if (current_width > prev_width){
        sioyek.fit_to_page_width();
    }
    else{
        sioyek.fit_to_page_height();
    }
}
```
`prefs_user.config`:
```
new_js_command _my_resize_command resize.js
resize_command _my_resize_command
```

**Comment by nikinbaidar** [comment]
What should be the path of resize.js?

**Comment by nikinbaidar** [comment]
> This can now be done using custom javascript commands: `resize.js`:


Awesome.  Where can I learn more about the API?

**Comment by ahrm** [comment]
It is not yet documented, you'll have to look at the code. Functions labeled with `Q_INVOKABLE` are callable from `sioyek_api` object and all normal sioyek commands are callable from `sioyek` object.
