### ISSUE TITLE
Sioyek opens links in Firefox

### ISSUE THREAD

**Issue by martenreeh** [ahrm/sioyek#939]
On Ubuntu 20.04.6 with Chrome set as my default browser somehow Sioyek opens links in firefox. Where can I change this? (And it would really be much nicer if it would just use the systems default browser.)

**Comment by ahrm** [comment]
We do use the default browser as far as I am aware.

**Comment by martenreeh** [comment]
Thanks ahrm, that was my bad. Chrome is set as my default browser but somehow firefox was set for some specific link things in `/usr/share/applications/defaults.list`. I wonder if some program did that since I never choose firefox as default myself. Anyway changed this and now opens with Chrome. Sorry for blaming Sioyek.
