### ISSUE TITLE
Wrong background color with custom color settings when using preview

### ISSUE THREAD

**Issue by BiliBraker** [ahrm/sioyek#940]
I'm using `custom_background_color` and `custom_text_color`, but when I open a reference with SmartJump, the gap between the pages is still white.
Video:

https://github.com/ahrm/sioyek/assets/51168364/f75e7023-02fc-4288-ac56-e7d3b4bf18ff

`prefs_user.config`:
```
startup_commands        toggle_custom_color

background_color 0.0 0.0 0.0
custom_background_color 0.1 0.1 0.1
custom_text_color 0.8 0.8 0.8
dark_mode_background_color 0.1 0.1 0.1
dark_mode_contrast 0.7

should_launch_new_window 0
super_fast_search 1

search_url_d https://duckduckgo.com/?q=
middle_click_search_engine d
```

Version: v2.0.0
OS: Ubuntu 20.04 LTS

**Comment by ahrm** [comment]
This is already fixed in the development branch.
