### ISSUE TITLE
[Enhancement] Draw unrendered page with current background color

### ISSUE THREAD

**Issue by char101** [ahrm/sioyek#947]
Hi,

When scrolling quickly and using the custom color or dark mode, there are flashing caused by unrendered page that is shown as a black page. Although there is the `should_draw_unrendered_pages` option, I think it would be more natural to draw the unrendered page using current background color. This will prevent flashing when the page has been rendered.

![black](https://github.com/ahrm/sioyek/assets/71255/c80bf0b5-9715-4ec9-acb8-57121e438aa7)

**Comment by ahrm** [comment]
Changed `should_draw_unrendered_pages` in https://github.com/ahrm/sioyek/commit/649fb2058fcdfa4a1b993dca7a70ddbac674e299 to show background color instead of checkerboard pattern.
