### ISSUE TITLE
get_file_path in input.cpp

### ISSUE THREAD

**Issue by nikinbaidar** [ahrm/sioyek#949]
Hi!

I am trying to change a few functions in the new version.  Specifically,  I am trying to change `std:wstring embedded_pdf_file_name` in the `class EmbedAnnotationsCommand` in the `input.cpp` file.

```
    void perform() {
        std::wstring embedded_pdf_file_name = <current_file_path>;
        if (embedded_pdf_file_name.size() > 0) {
            widget->main_document_view->get_document()->embed_annotations(embedded_pdf_file_name);
        }
    }
```

I see `    QString filename = QString::fromStdWString(path.filename().value());` in `document.cpp` returns the file path but I can't seem to set `embedded_pdf_file_name` to just that. Can you give me some insights on how I can get the current doc path inside input.cpp.

**Comment by ahrm** [comment]
You can use `widget->doc()->get_path()`.

**Comment by nikinbaidar** [comment]
> `widget->doc()->get_path()`.

Thank you so much.
