### ISSUE TITLE
Right clicking references / figures - bottom justify the preview?

### ISSUE THREAD

**Issue by py9mrg** [ahrm/sioyek#95]
Hello,

I've just come across this software and I love it - thank you. One quick idea. 

When you right click on a reference / figure reference you get a wonderful little preview. The preview is centre justified, which works perfectly for a reference, but I wonder if the preview ought to be bottom justified. The rationale being that the preview often crops off the top half of the figure (captions usually being at the bottom of a figure) so bottom justifying the preview would minimise that problem. Obviously that might then run the risk of cropping off the bottom of references, but references don't tend to be more than a couple of lines so I think - possibly - an almost bottom justified preview would rarely crop references and allow better previewing of figures.

Here's a couple of pics to show what I mean:

![image](https://user-images.githubusercontent.com/12600721/140305929-6a9888f0-0de7-4e54-93b4-b54b581b0f85.png)

Probably don't need as much space below the clicked reference.

![image](https://user-images.githubusercontent.com/12600721/140306005-eb5258a3-6ea7-47b3-8f5b-df0669cb1b98.png)

Bottom justifying would be nice to avoid cropping the top of the figure.

The one slight problem of this idea might be books where the reference is to a note rather than a reference - notes often spanning multiple lines.

**Comment by ahrm** [comment]
As you mentioned, this feature is not only used for figures but for references, definitions, theorems, etc. which are usually not bottom justified.
You can use the mouse wheel on this preview to quickly adjust it as you like.

**Comment by py9mrg** [comment]
Oh yeah! I could have sworn I tried that, sorry, but it worked fine now I tried it again. Good solution.
