### ISSUE TITLE
fit_to_page_width_smart fail to run on new window

### ISSUE THREAD

**Issue by char101** [ahrm/sioyek#955]
Hi,

If I have this config

```
should_launch_new_window 1
startup_commands toggle_custom_color;toggle_scrollbar;fit_to_page_width_smart
```

The startup commands will fail to run when opening a new document. If `fit_to_page_width_smart` is removed from the startup commands, then the startup commands will run.

**Comment by ahrm** [comment]
When sioyek launches, the pages sizes are still not computed which causes `fit_to_page_width_smart` to fail. You can do something like this:
```
startup_commands toggle_custom_color;toggle_scrollbar;wait_for_renders_to_finish;fit_to_page_width_smart
```

**Comment by char101** [comment]
Thanks you, adding `wait_for_renders_to_finish` works.
