### ISSUE TITLE
locking movement to verticle only in mouse drag mode while pdf is zoomed out

### ISSUE THREAD

**Issue by Aneeqasif** [ahrm/sioyek#957]
hy ahrm i hope you are enjoying good health
when pdf is zoomed out with some background on both side , using mouse drag mode is  very annoying as its very hard to do a vertical only movement with mouse and scrolling in vertical direction only is very hard. in many other pdf viewers like okular mouse drag only impact the vertical movement which is natural and wanted behavior. while pdf is zoomed way in it totally makes sense to have mouse drag working in both direction. which is also the default behavior in mentioned examples like okular , evince etc. please address this issue.

**Comment by ahrm** [comment]
Added this as the default behavior in https://github.com/ahrm/sioyek/commit/1bd072d50edf80f1b039262dea46aa38c55c4231. Also added a `allow_horizontal_drag_when_document_is_small` config option to disable this.

**Comment by Aneeqasif** [comment]
right. can you please tell when will all the new features and fixed from dev branch will be merged in main or new version. what you plan when to do it?

**Comment by ahrm** [comment]
This of course not available on the git package yet. I don't know when the next version will be released exactly, any time that I tell you will probably be wrong.

**Comment by Aneeqasif** [comment]
> This of course not available on the git package yet. I don't know when the next version will be released exactly, any time that I tell you will probably be wrong.

how can i get this fix . i tried building the dev branch but sioyek wont start if i do it like this .
the arch package also add some patches before installing ig thats the reason i cannot get the dev branch working properly can you please help me on this issue of building correctly the dev branch on arch

**Comment by ahrm** [comment]
The instructions for building the dev branch is pretty much the same as the normal branch, except we use Qt 6.6 instead of 5.12 .

**Comment by Aneeqasif** [comment]
OK ill try to bang my head again sometime i am pretty its me missing something dumb while building it. bdw there are alot of new features and fixes from dev branch that people are missing out. not every body spare the time to build manually from the repo

**Comment by ahrm** [comment]
I don't expect everyone to build manually from the repo. The development branch, as the name obviously suggests, is for developers and is under heavy development and is unstable. I might change the database format or other backward-incompatible things. I did not even plan to make the development branch public until it was done, but a lot of users requested to make it public so I did it.

**Comment by Aneeqasif** [comment]
right. i got your point
