### ISSUE TITLE
toggle_titlebar causing yabai to stop recognizing sioyek

### ISSUE THREAD

**Issue by hershkumar** [ahrm/sioyek#962]
After using the `toggle_titlebar` command, the titlebar disappears, but the sioyek window is no longer recognized as a window by yabai, and does not obey the proper positioning and sizing. Toggling the titlebar back on makes yabai recognize the window again.

<img width="1512" alt="Screenshot 2024-02-04 at 11 11 44 AM" src="https://github.com/ahrm/sioyek/assets/33847994/6c3c5665-73fd-4ad3-b926-2871b9e2456d">

<img width="1512" alt="Screenshot 2024-02-04 at 11 12 10 AM" src="https://github.com/ahrm/sioyek/assets/33847994/6470e6b3-f48b-499f-895e-332ff00aeae2">

**Comment by ahrm** [comment]
I think this is a Qt bug rather than a sioyek bug.

**Comment by jinjiaodawang** [comment]
Can confirm the issue as described, under the development branch. qutebrowser also faces the same Issue, you can see the issue was reopened after being upgraded to Qt6.
https://github.com/qutebrowser/qutebrowser/issues/4067

**Comment by jinjiaodawang** [comment]
Works fine for me. The mentioned issue provides the same workaround and has been closed. @ahrm, it seems we can close this issue too

**Comment by hpfmn** [comment]
> A workaround solution is to set the following rule to yabai:
> 
> ```
> yabai -m rule --add app="sioyek" role="AXWindow" subrole="AXDialog" manage=on
> ```

Something like `yabai -m rule --add app="^qutebrowser$" title!="^$" role="AXWindow" subrole="AXDialog" manage=on` does work for me for qutebrowser but not for sioyek. Which version do you use? Also if I query yabai for window the sioyek windows without the titlebar are not shown at all.

**Comment by hpfmn** [comment]
Ahh I found that I need to build the development branch
