### ISSUE TITLE
[Q] Is it possible to define a command that increases/decreases `epub_font_size`?

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#964]
Is it possible to define a command that increases/decreases `epub_font_size`, using something in `prefs_user` etc.?

**Comment by ahrm** [comment]
Added the ability to change numerical configs using `+=` and `-=` in https://github.com/ahrm/sioyek/commit/1de2f65f2f41c8c1d19922aac4d9f04e0093759a. Now you can do something like this in your keys file:
```
setconfig_epub_font_size(+=1) <keybind>
```

**Comment by miguel-celero** [comment]
Is it possible to set a default font size for epub in the config file?

**Comment by httpsrichard** [comment]
> Added the ability to change numerical configs using `+=` and `-=` in [1de2f65](https://github.com/ahrm/sioyek/commit/1de2f65f2f41c8c1d19922aac4d9f04e0093759a). Now you can do something like this in your keys file:
> 
> ```
> setconfig_epub_font_size(+=1) <keybind>
> ```

It doesn't adjust all text
<img width="932" height="485" alt="Image" src="https://github.com/user-attachments/assets/83a10658-a0e7-41e5-8682-f75af0bc3132" />

**Comment by ahrm** [comment]
I can't reproduce the issue. Can you share the epub?

**Comment by httpsrichard** [comment]
> I can't reproduce the issue. Can you share the epub?

https://filebin.net/cuwtzorz22hftvsc

**Comment by ahrm** [comment]
I think this might be a mupdf issue. For now, you can add something like this to your config which should make the document look better:

```
epub_css #sbo-rt-content p{font-size:1em!important}#sbo-rt-content h1{font-size:1.5em!important}#sbo-rt-content .H1---Chapter{font-size:1.65em!important}#sbo-rt-content h2{font-size:1.35em!important}#sbo-rt-content h3{font-size:1.2em!important}#sbo-rt-content h3.sub{font-size:1.1em!important}#sbo-rt-content h4{font-size:1em!important}#sbo-rt-content .callout-heading{font-size:1.1em!important}#sbo-rt-content .callout{font-size:.87em!important}#sbo-rt-content code,#sbo-rt-content kbd,#sbo-rt-content pre,#sbo-rt-content samp,#sbo-rt-content .source-code,#sbo-rt-content .source-inline,#sbo-rt-content .screen-inline{font-size:.85em!important}#sbo-rt-content pre{line-height:1.03em!important}
```
