### ISSUE TITLE
Can we set `epub_height` and `epub_width` to adjust to sioyek's size?

### ISSUE THREAD

**Issue by NightMachinery** [ahrm/sioyek#965]
When reading EPUBs, it's ideal to make each page exactly fit the current size of the app. This allows easy scrolling using `next_page` etc. As the page boundaries are meaningless in EPUBs anyway, this has no downsizes.

Can we set `epub_height` and `epub_width` to adjust to sioyek's size?

**Comment by ahrm** [comment]
You could achieve this using a script like this:
`fit_epub.js`:
```
let state = sioyek_api.get_json_state();

let width = state["window_width"];
let height = state["window_height"];
let zoom_level = state["zoom_level"];

sioyek.setconfig_epub_width(width / zoom_level);
sioyek.setconfig_epub_height(height / zoom_level);
```
`prefs_user`:
```
new_js_command _fit_epub fit_epub.js
```
`keys_user`:
```
_fit_epub <keybind>
```

But I also added a native `fit_epub_to_window` command in https://github.com/ahrm/sioyek/commit/1de2f65f2f41c8c1d19922aac4d9f04e0093759a because it seemed like a useful command.
