### ISSUE TITLE
Deleting highlight under cursor while having the highlight selected crashes sioyek

### ISSUE THREAD

**Issue by adriafarres** [ahrm/sioyek#968]
Create a highlight, select it, and run `delete_highlight_under_cursor` while having the cursor above the highlight. sioyek crashes. (development branch)

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/ff9512e6e1447f8ad1c737d7bd15e8a33f4f56e7.
