### ISSUE TITLE
Links don't jump to the correct page

### ISSUE THREAD

**Issue by adriafarres** [ahrm/sioyek#969]
Hello there,

Links don't always work. Take the pdf I attached. They jump to page 1 instead of the correct page. I have opened the pdf with Chrome and Zathura and they follow the link correctly. (development branch)

[Value Investing: From Graham to Buffett and Beyond.pdf](https://github.com/ahrm/sioyek/files/14232625/Value.Investing.From.Graham.to.Buffett.and.Beyond.pdf)

**Comment by ahrm** [comment]
Should be fixed in this commit in development branch: https://github.com/ahrm/sioyek/commit/651a876330de97c15016638eae0965703696272a.

**Comment by adriafarres** [comment]
Both this issue as well as the previous work perfectly. Thank you for your work! Love sioyek!

Are the development and main branches compatible as of now? Are the previous highlights still visible with the development branch?

**Comment by ahrm** [comment]
The development branch is compatible with the main branch (it will migrate the database). But once your database is migrated it no longer will be compatible with the main branch.

**Comment by adriafarres** [comment]
That makes a lot of sense. I guess what happened is I was originally on main, then switched to development to try it out, had some crashes (which seem to be fixed now), moved back to main, and upon going back to development again the migration was already done and the highlights didn't get migrated. Thanks again for everything.
