### ISSUE TITLE
Horizontal scroll lock option in prefs (feature request)

### ISSUE THREAD

**Issue by Sandybunting** [ahrm/sioyek#970]
I generally prefer to have horizontal scroll disabled, but the effects of the `toggle_horizontal_scroll_lock` command don't persist when I reopen Sioyek after closing it. It would be great if there was an entry in `prefs.config` to allow the horizontal scroll lock to default to being on, e.g. in `prefs.config`:
```
# Whether or not horizontal scroll lock is enabled by default (0 for off, 1 for on)
horizontal_scroll_lock_default 1
```

**Comment by ahrm** [comment]
You can do this:
```
startup_commands toggle_horizontal_scroll_lock
```

**Comment by Sandybunting** [comment]
Ahh perfect, thanks!
