### ISSUE TITLE
Omission of spaces in selected text

### ISSUE THREAD

**Issue by nickel8448** [ahrm/sioyek#974]
For some PDFs, sioyek is omitting spaces when any text is copied, I wrote a script to get selected_text variable and spaces are omitted for that too.
I am uncertain why this could be the case. As far as I know, nothing has changed in terms of the setup. I have attached a sample PDF to this issue.
[P4D.pdf](https://github.com/ahrm/sioyek/files/14268005/P4D.pdf)

**Comment by ahrm** [comment]
Can't reproduce the issue. Does this happen in all locations in the document for you or is it a specific location?

**Comment by nickel8448** [comment]
Apologies, I should have specified this. It happens for headings. Fro eg, page 30 of the PDF, try copying "Types of Nations: Advanced Economies"

**Comment by ahrm** [comment]
The issue seems to be with the document. It is using unicode 65039 (https://www.fileformat.info/info/unicode/char/fe0f/index.htm) instead of space in those locations.

**Comment by nickel8448** [comment]
Do you have any recommendation how I can fix it?

**Comment by nickel8448** [comment]
One more question, how did you figure how that it was using a unicode 65039 instead of a space?

**Comment by ahrm** [comment]
I don't know how to fix it. I ran sioyek in debug mode and inspected the value of the character.

**Comment by nickel8448** [comment]
Got it. I’ll try the same. Thank you!
