### ISSUE TITLE
Word selection boundaries are incorrect in combination with horizontal distances between glyphs

### ISSUE THREAD

**Issue by hrdl-github** [ahrm/sioyek#978]
Selecting e.g. "Basics" in `tutorial.pdf` when in word selection mode will also select "1.". This behaviour is a minor annoyance when highlighting section headlines or TOC entries.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/c7eb86d65658b636cef21ae3a8d40edd577f1ba2.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/bb0dd3ba5615c5358ffbcfb42d583887d813d879.
