### ISSUE TITLE
Where to put user config files for Ubuntu 20 AppImage ? 

### ISSUE THREAD

**Issue by damionx7** [ahrm/sioyek#98]
Thanks for this software. I am having trouble setting prefs for user. I used the dir `~/.config/sioyek` but sioyek doesn't change anything. How should I solve this ?

**Comment by ahrm** [comment]
When you launch `sioyek` from console, it prints a list of all places it considers for config files. Also you could open the user keys and preferences files by entering `:keys_user` and `:prefs_usr` respectively (if this command doesn't open the files, it usually means you don't have permission to open the files. Running `sioyek` as with higher privileges might help).

**Comment by damionx7** [comment]
Thanks. The directory was `~/.local/share/Sioyek`
