### ISSUE TITLE
"next_chapter"/"prev_chapter"

### ISSUE THREAD

**Issue by bragiato** [ahrm/sioyek#987]
First of all, I would like to note that sioyek is wonderful and that I am very grateful for you making the program available for free.
That said, I believe I've identified a problem with the "next_chapter" and "prev_chapter" commands.
Problem: the two commands only behave properly if they are activated on the first page of the current chapter. If they are used on any other page in the current chapter, the reader moves forward or backward one chapter further than expected.
I exemplify.
Imagine a PDF with 30 pages and 3 chapters. Each chapter has 10 pages.
Chapter 1: pages 1-10;
Chapter 2: pages 11-20;
Chapter 3: pages 21-30.
If I am on the first page of Chapter 1 and use the "next_chapter" command, I am correctly taken to the first page of Chapter 2, page 11. This is the expected behavior.
However, if I am on any of pages 2 to 10 of Chapter 1 and use the "next_chapter" command, I am directed to the first page of Chapter 3, page 21, which is unexpected behavior. I believe the command should take me to the first page of Chapter 2, page 11, regardless of which page of Chapter 1 I am on when I trigger it.
A similar situation occurs when using the "prev_chapter" command.
Could it be a bug or is it intentional behavior?
Thank you so much.

**Comment by ahrm** [comment]
Thanks :). Should be fixed in https://github.com/ahrm/sioyek/commit/5b0cd55c8a6e2596b5ce84dce8f75787ff6edb83.
