### ISSUE TITLE
Is it possible to change font family and font size ?

### ISSUE THREAD

**Issue by damionx7** [ahrm/sioyek#99]
Is it possible to change the font family and font size in sioyek window opened by typing `:` ?
![image](https://user-images.githubusercontent.com/6530843/140614545-e74d7a19-b48d-456e-946a-dfb7a85aec03.png)

**Comment by damionx7** [comment]
i found out about `ui_font` prefs. But can you also add `ui_font_size` prefs. As the text seems too small.

**Comment by ahrm** [comment]
Added a `font_size` preferences in d2e9be81ccb7af601f625dae7762b4d32adc14fe which allows you to customize font size.

**Comment by damionx7** [comment]
Thanks

**Comment by chaoyi** [comment]
`font_size` preference works but `ui_font` preference has no effect
