### ISSUE TITLE
`--new-window` option position

### ISSUE THREAD

**Issue by HuidaeCho** [ahrm/sioyek#992]
This command line opens a PDF in a new window:
```bash
sioyek file.pdf --new-window
```
But this one doesn't:
```bash
sioyek --new-window file.pdf
```

**Comment by ahrm** [comment]
I think this is fixed in the development version.

**Comment by HuidaeCho** [comment]
Thanks for the quick response. I cloned this repo yesterday. Actually, `sioyek --new-window file.pdf` doesn't open `file.pdf` at all either in an existing or new window.

**Comment by ahrm** [comment]
Which operating system are you using?

**Comment by HuidaeCho** [comment]
> Which operating system are you using?

I use Linux and xorg.

**Comment by ahrm** [comment]
Should be fixed in https://github.com/ahrm/sioyek/commit/86f7f097aefc7d7b5dbf430d98cbe3b42d37e724.
